import subprocess, time
from playwright.sync_api import sync_playwright
srv=subprocess.Popen(['python3','-m','http.server','8782','-d','www'],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL); time.sleep(1)
try:
  with sync_playwright() as p:
    b=p.chromium.launch(); ctx=b.new_context(viewport={'width':390,'height':844},service_workers='block')
    ctx.add_init_script("try{localStorage.setItem('drx.tour','1')}catch(e){}")
    ctx.route('**/config.js', lambda r: r.fulfill(body='window.DRX_CONFIG={adminEmail:"dhirajnisha804@gmail.com",firebase:{apiKey:"k",projectId:"p"}}', content_type='application/javascript'))
    ctx.route('**/vendor/firebase-app-compat.js', lambda r: r.fulfill(body=open('mockfb3.js').read(), content_type='application/javascript'))
    for f in ['auth','firestore']: ctx.route(f'**/vendor/firebase-{f}-compat.js', lambda r: r.fulfill(body='', content_type='application/javascript'))
    pg=ctx.new_page(); errs=[]; pg.on('pageerror',lambda e:errs.append(str(e)))
    pg.goto('http://localhost:8782/'); pg.wait_for_timeout(1800)
    print('1 sign-in screen shown:', pg.locator('#acctOv h2').inner_text())
    pg.click('#acNew'); pg.wait_for_timeout(200)
    pg.fill('#suN','Dr Test Kumar'); pg.fill('#suD','1995-05-05'); pg.select_option('#suS','Male'); pg.fill('#suPh','9876543210'); pg.fill('#suE','test@doc.in'); pg.fill('#suP','secret1')
    pg.click('#suGo'); pg.wait_for_timeout(300); print('   consent required msg:', pg.locator('#acMsg').inner_text())
    pg.check('#suC1'); pg.check('#suC2'); pg.click('#suGo'); pg.wait_for_timeout(800)
    print('2 verify-email screen:', pg.locator('#acctOv h2').inner_text())
    pg.click('#veOk'); pg.wait_for_timeout(500); print('   before verifying:', pg.locator('#acMsg').inner_text())
    pg.evaluate("__verify('test@doc.in')"); pg.click('#veOk'); pg.wait_for_timeout(800)
    print('3 profile form:', pg.locator('#acctOv h2').inner_text(), '| name prefilled:', pg.input_value('#pfN'))
    pg.fill('#pfReg','MMC 2020/12345'); pg.fill('#pfI','HBT Medical College'); pg.set_input_files('#pfGal','rx_sample.png'); pg.wait_for_timeout(800)
    pg.check('#pfOk'); pg.click('#pfGo'); pg.wait_for_timeout(1000)
    print('4 overlay closed:', pg.locator('#acctOv').count()==0, '| banner:', pg.locator('.acbar').first.inner_text() if pg.locator('.acbar').count() else 'NONE')
    print('   stored profile status:', pg.evaluate("__store.users.get(__accounts['test@doc.in'].uid).status"), '| proof stored:', pg.evaluate("__store.verifications.has(__accounts['test@doc.in'].uid)"))
    pg.click('[data-tab=templates]'); pg.wait_for_timeout(500)
    print('5 templates for pending user:', pg.locator('#tplCount').inner_text(), '| lock banner:', pg.locator('.lockban').count()==1)
    pg.click('[data-tab=meds]'); pg.wait_for_timeout(400); pg.click('[data-dtab=safety]'); pg.wait_for_timeout(300); print('   drugs locked:', pg.locator('.lockcard').count()==1)
    pg.screenshot(path='acct_locked.png')
    # admin approves
    pg.click('#btnMoreTop'); pg.wait_for_timeout(300); pg.click('[data-act=acct]'); pg.wait_for_timeout(300)
    pg.locator('#pfOut').click(); pg.wait_for_timeout(800)
    pg.fill('#acE','dhirajnisha804@gmail.com'); pg.fill('#acP','pw'); pg.click('#acGo'); pg.wait_for_timeout(1200)
    print('6 admin signed in, overlay closed:', pg.locator('#acctOv').count()==0)
    pg.click('#btnMoreTop'); pg.wait_for_timeout(400); print('   approvals row:', pg.locator('[data-act=approvals]').inner_text().replace('\n',' '))
    pg.click('[data-act=approvals]'); pg.wait_for_timeout(400); pg.locator('[data-apu]').first.click(); pg.wait_for_timeout(600)
    print('   proof image shown:', pg.locator('#apProof img').count()==1); pg.screenshot(path='acct_approve.png')
    pg.route('mailto:*', lambda r: r.abort())
    pg.evaluate("window.__oh=location.href"); pg.click('#apOk'); pg.wait_for_timeout(800)
    print('7 status now:', pg.evaluate("__store.users.get(__accounts['test@doc.in'].uid).status"), '| proof deleted:', not pg.evaluate("__store.verifications.has(__accounts['test@doc.in'].uid)"))
    pg.goto('http://localhost:8782/'); pg.wait_for_timeout(1500)
    pg.click('#btnMoreTop'); pg.wait_for_timeout(300); pg.click('[data-act=acct]'); pg.wait_for_timeout(300); pg.click('#amOut'); pg.wait_for_timeout(800)
    pg.fill('#acE','test@doc.in'); pg.fill('#acP','secret1'); pg.click('#acGo'); pg.wait_for_timeout(1500)
    pg.click('[data-tab=templates]'); pg.wait_for_timeout(600)
    print('8 verified user templates:', pg.locator('#tplCount').inner_text(), '| lock banner gone:', pg.locator('.lockban').count()==0)
    pg.click('[data-tab=cases]'); pg.wait_for_timeout(300); pg.click('[data-act=ixopen]'); pg.wait_for_timeout(300); print('   interactions open:', pg.locator('#ixQ').count()==1)
    print('errors', errs)
finally: srv.kill()
