# Exam drugs — slot 3: Injectables I–IX
W = "Wolverton 4e"; K = "Khopkar"
D = [
# ---------------- I LOCAL ANAESTHETICS ----------------
dict(name="Lignocaine (lidocaine) 2% injection", group="Injectables · I Local anaesthetics",
 cls="Amide local anaesthetic (intermediate duration)",
 moa=["The unionised form crosses the nerve membrane; inside, the ionised form blocks voltage-gated sodium channels from within",
      "No sodium influx → no depolarisation → no nerve conduction",
      "Small, unmyelinated fibres (pain, temperature, autonomic) are blocked first, then touch, pressure and motor"],
 pk=["pKa 7.9 — fast onset (1–2 min by infiltration); works poorly in acidic, infected tissue",
     "Duration about 30–120 min alone; 2–6 h with adrenaline (vasoconstriction slows absorption)",
     "Metabolised in the liver (CYP1A2, 3A4); reduce total dose in liver disease and heart failure",
     "2% = 20 mg/mL; 1% = 10 mg/mL"],
 uses=["Infiltration anaesthesia for biopsy, excision, electrosurgery, cryo, lasers, IL injections",
       "Nerve blocks (digital, ring, supraorbital, mental, etc.), field blocks",
       "Tumescent anaesthesia (very dilute, 0.05–0.1%) for liposuction and large procedures",
       "Topical forms (gel, EMLA with prilocaine — topicals slot)",
       "Antiarrhythmic (IV, ventricular arrhythmias)"],
 dose=["Maximum (Wolverton): plain 4.5 mg/kg (up to 300 mg); with adrenaline 7 mg/kg (up to 500 mg)",
       "Example: 300 mg = 15 mL of 2% plain lignocaine",
       "Formula: maximum volume (mL) = max dose (mg/kg) × weight (kg) ÷ 10 ÷ % concentration",
       "Tumescent: up to 35–55 mg/kg because of very slow absorption from fat",
       "Children: same mg/kg limits; dilute to 0.5–1% to give enough volume"],
 ae=["Pain and burning on injection (reduce by buffering with sodium bicarbonate 1 mL 8.4% per 10 mL, warming, slow injection, small needle)",
     "Systemic toxicity (overdose or intravascular injection) — CNS first: perioral numbness, metallic taste, tinnitus, light-headedness, slurred speech → muscle twitching → seizures → coma",
     "Then cardiovascular: bradycardia, hypotension, arrhythmia, cardiac arrest",
     "Vasovagal reaction (the commonest 'reaction' in practice)",
     "Adrenaline effects: palpitations, tremor, anxiety, tachycardia",
     "True allergy to amides is rare (preservative methylparaben may be the cause); esters (procaine, benzocaine — PABA) are more allergenic"],
 ci=["Known allergy to amide anaesthetics",
     "Caution: complete heart block, severe liver disease, heart failure",
     "With adrenaline — caution: uncontrolled hypertension, severe cardiovascular disease, hyperthyroidism, phaeochromocytoma, narrow-angle glaucoma; patients on non-selective β-blockers, MAOIs or tricyclics",
     "Adrenaline in digits/penis: traditionally avoided; Wolverton notes dilute adrenaline is now considered safe in healthy digits (avoid in vascular disease)"],
 ix=["β-blockers (propranolol) with adrenaline: unopposed α effect → hypertension and reflex bradycardia",
     "Cimetidine, propranolol, amiodarone reduce lignocaine clearance",
     "Other anti-arrhythmics: additive cardiac effects"],
 mon=["Calculate the maximum dose before starting; aspirate before injecting",
      "Watch for early CNS symptoms; have resuscitation equipment and 20% lipid emulsion available",
      "Treatment of toxicity: stop injecting, airway and oxygen, benzodiazepine for seizures, 20% lipid emulsion 1.5 mL/kg bolus then infusion"],
 preg="Safe in pregnancy (old FDA category B) and breastfeeding; defer elective procedures to the second trimester; adrenaline in small doses acceptable.",
 viva=["Amide vs ester: amides have two 'i's in the name (lIdocaIne); esters are metabolised by plasma cholinesterase and cause more allergy (PABA)",
       "Max dose: 4.5 mg/kg plain, 7 mg/kg with adrenaline",
       "Signs of toxicity progress from CNS to CVS",
       "Buffering with bicarbonate reduces pain",
       "Lipid emulsion is the antidote for systemic toxicity"],
 src=f"{W} ch.58 (Local anesthetics); {K} (Miscellaneous agents / Appendix)"),

# ---------------- II CORTICOSTEROIDS ----------------
dict(name="Hydrocortisone sodium succinate injection", group="Injectables · II Corticosteroids",
 cls="Short-acting natural glucocorticoid (cortisol) with mineralocorticoid action",
 moa=["Glucocorticoid receptor agonist — anti-inflammatory, immunosuppressive",
      "Significant mineralocorticoid effect (salt and water retention) — the right steroid for adrenal insufficiency"],
 pk=["Water-soluble succinate ester — rapid onset IV (within 1 h)",
     "Biological half-life 8–12 h (short-acting)",
     "Equivalence: 20 mg hydrocortisone = 5 mg prednisolone"],
 uses=["Anaphylaxis — adjunct after adrenaline (prevents late/biphasic reaction; not a first-line drug)",
       "Acute severe angioedema, severe acute urticaria, acute drug reactions",
       "Adrenal crisis and stress-dose cover in patients on long-term steroids (surgery, illness)",
       "Status asthmaticus"],
 dose=["Anaphylaxis: 200 mg IV or IM (adults); children 6–12 years 100 mg, 6 months–6 years 50 mg, under 6 months 25 mg",
       "Adrenal crisis: 100 mg IV bolus, then 50 mg every 6 h (or 200 mg/24 h infusion)",
       "Vials 100 mg (reconstitute with sterile water)"],
 ae=["Short courses: hyperglycaemia, fluid retention, hypokalaemia, hypertension, mood change",
     "Rapid IV bolus of large doses: hypotension, arrhythmia (rare)",
     "Long use: full range of steroid side effects"],
 ci=["No absolute contraindication in emergencies",
     "Caution: systemic fungal infection, uncontrolled diabetes, active peptic ulcer"],
 ix=["Enzyme inducers lower effect; diuretics add to hypokalaemia; NSAIDs increase GI risk"],
 mon=["BP, glucose, potassium with repeated doses"],
 preg="Safe for emergency use; mostly inactivated by the placenta.",
 viva=["Only injectable steroid with significant mineralocorticoid effect — drug of choice in adrenal crisis",
       "In anaphylaxis, steroids are adjuncts — adrenaline is the life-saving drug",
       "20 mg hydrocortisone = 5 mg prednisolone"],
 src=f"{W} ch.13; {K} ch.8 (Table 8.4, injectable steroids)"),

dict(name="Methylprednisolone (IV pulse)", group="Injectables · II Corticosteroids",
 cls="Intermediate-acting glucocorticoid; methylprednisolone sodium succinate for IV use",
 moa=["At pulse doses, genomic effects are saturated and rapid non-genomic effects on cell membranes add to immunosuppression",
      "Rapid lymphocyte depletion and suppression of inflammation — gives quick disease control with fewer long-term side effects than prolonged high oral doses"],
 pk=["Equivalence: 4 mg methylprednisolone = 5 mg prednisolone",
     "Minimal mineralocorticoid effect, so preferred for pulse therapy",
     "Methylprednisolone acetate (depot) is a different, long-acting IM/IL suspension — never give it IV"],
 uses=["Pemphigus vulgaris/foliaceus (severe, not responding), bullous pemphigoid (severe)",
       "SJS/TEN (early, short course — controversial), DRESS (severe), severe erythema multiforme",
       "Pyoderma gangrenosum, dermatomyositis (severe/with lung involvement), vasculitis, SLE",
       "Rapidly progressive alopecia areata (selected), severe type 1 lepra reaction or ENL with neuritis"],
 dose=["Pulse: 500 mg–1 g (about 10–15 mg/kg/day) in 250–500 mL of 5% dextrose or normal saline over 1–3 h, daily for 3 (to 5) consecutive days",
       "Never as a rapid IV bolus (risk of arrhythmia and sudden death)",
       "Follow with oral steroid or steroid-sparing drug",
       "Vials 40, 125, 500 mg, 1 g"],
 ae=["Acute: flushing, metallic taste, hyperglycaemia, hypertension, insomnia, mood change, psychosis",
     "Electrolyte shifts (hypokalaemia), fluid retention",
     "Cardiac arrhythmia and sudden death (especially with diuretics, low potassium, heart disease, fast infusion)",
     "Anaphylaxis (rare), seizures, infections; avascular necrosis with repeated pulses"],
 ci=["Active uncontrolled infection, systemic fungal infection",
     "Caution: heart disease, renal failure, electrolyte imbalance, uncontrolled diabetes or hypertension, psychiatric disease"],
 ix=["Diuretics and amphotericin B (hypokalaemia → arrhythmia)",
     "Enzyme inducers reduce effect; CYP3A4 inhibitors increase it"],
 mon=["Before each pulse: BP, pulse, ECG, electrolytes (K⁺), blood glucose, renal function, infection screen, pregnancy test",
      "During infusion: BP and cardiac monitoring; repeat glucose and K⁺ after"],
 preg="Partly inactivated by the placenta; use only for life-threatening disease in pregnancy.",
 viva=["Pulse = 500 mg–1 g over at least 1 h on 3 consecutive days",
       "Check K⁺ and ECG before each pulse",
       "Succinate (IV, soluble) vs acetate (depot, never IV)"],
 src=f"{W} ch.13 (pulse definition); {K} ch.8"),

dict(name="Dexamethasone sodium phosphate injection", group="Injectables · II Corticosteroids",
 cls="Long-acting fluorinated glucocorticoid (biological half-life 36–54 h)",
 moa=["Potent glucocorticoid receptor agonist (about 25–30 times hydrocortisone) with no mineralocorticoid effect"],
 pk=["Water-soluble phosphate ester — IV, IM, intralesional",
     "Equivalence: 0.75 mg dexamethasone = 5 mg prednisolone",
     "Crosses the placenta (not inactivated by 11β-HSD2)"],
 uses=["Dexamethasone–cyclophosphamide pulse (DCP) and dexamethasone pulse (DP) for pemphigus (Pasricha regimen; third line in the Derma Desk pemphigus ladder)",
       "Anaphylaxis/angioedema adjunct; acute severe allergic reactions",
       "SJS/TEN, DRESS (short courses, some centres)",
       "Cerebral oedema, fetal lung maturation (obstetrics)",
       "Intralesional/IM use in some Indian practice (less preferred than triamcinolone)"],
 dose=["DCP pulse: dexamethasone 100 mg in 500 mL 5% dextrose over 1–2 h on 3 consecutive days + cyclophosphamide 500 mg IV on day 1; repeated every 4 weeks; oral cyclophosphamide 50 mg daily between pulses",
       "Phases of DCP: I (pulses until complete remission), II (pulses continue for 9 months with daily oral cyclophosphamide), III (oral cyclophosphamide alone for 9 months), IV (off treatment, follow-up)",
       "Anaphylaxis adjunct: 4–8 mg IV",
       "Ampoules 4 mg/mL (2 mL); 8 mg/2 mL"],
 ae=["As for pulse steroids: hyperglycaemia, hypertension, hypokalaemia, arrhythmia, psychosis, infection",
     "Perineal burning/itching with rapid IV injection",
     "Long-acting — more HPA suppression if given daily"],
 ci=["As for systemic steroids; active serious infection, systemic fungal infection"],
 ix=["CYP3A4 inducer itself (may lower levels of some drugs); enzyme inducers lower its levels"],
 mon=["As for methylprednisolone pulse: ECG, electrolytes, glucose, BP before and during pulse"],
 preg="Crosses the placenta — used deliberately for fetal lung maturity; avoid for skin disease in pregnancy.",
 viva=["0.75 mg dexamethasone = 5 mg prednisolone",
       "DCP regimen: phases I–IV (Pasricha)",
       "No mineralocorticoid action"],
 src=f"{K} ch.8 (injectable steroids, DCP/DAP pulse); {W} ch.13"),

dict(name="Triamcinolone acetonide injection", group="Injectables · II Corticosteroids",
 cls="Intermediate-acting fluorinated glucocorticoid; insoluble depot suspension",
 moa=["Glucocorticoid receptor agonist (5 times hydrocortisone); the acetonide crystals dissolve slowly, giving a local depot lasting weeks",
      "In keloids: reduces fibroblast proliferation and collagen synthesis, increases collagenase"],
 pk=["Suspension — shake well; never give IV",
     "Local effect lasts 3–6 weeks; some systemic absorption (HPA suppression possible with large doses)",
     "Vials 10 mg/mL and 40 mg/mL"],
 uses=["Intralesional (IL): keloids and hypertrophic scars, alopecia areata (patchy), discoid lupus, lichen planus (hypertrophic), lichen simplex chronicus, prurigo nodularis, granuloma annulare, sarcoidosis, nodulocystic acne, psoriasis plaques and nail psoriasis, necrobiosis lipoidica, chalazion",
       "Intramuscular: short-term control of severe allergic or inflammatory dermatoses (used sparingly)"],
 dose=["IL concentrations: face and acne cysts 2.5 mg/mL; alopecia areata 2.5–10 mg/mL (5 mg/mL commonly); thick plaques 5–10 mg/mL; keloids 10–40 mg/mL",
       "Dilute with normal saline or lignocaine; inject 0.05–0.1 mL per site, about 1 cm apart, into the dermis (subcutaneous injection causes fat atrophy); keloids are injected into the body of the lesion",
       "Repeat every 3–6 weeks; keep the total per session modest (e.g. up to about 20–40 mg total for scalp)",
       "IM: 40–80 mg into the gluteus (deep), not more often than every 4–6 weeks"],
 ae=["Local: atrophy (dermal and fat), hypopigmentation (especially in dark skin), telangiectasia, injection-site infection, crystal deposits",
     "Rare but serious: blindness from retinal artery embolism after periocular/nasal/scalp injection — inject slowly with low pressure, aspirate",
     "Systemic (large doses/IM): HPA suppression, Cushingoid features, menstrual irregularity, hyperglycaemia",
     "IM: fat atrophy at gluteal site, abscess"],
 ci=["Infection at the injection site; known hypersensitivity",
     "IV injection",
     "Caution: on ritonavir/cobicistat (Cushing syndrome)"],
 ix=["Ritonavir, cobicistat, itraconazole (strong CYP3A4 inhibitors): iatrogenic Cushing and adrenal suppression even after IL/joint injection"],
 mon=["Photograph lesions; check for atrophy before repeat injections",
      "Glucose in diabetics after large doses"],
 preg="Small IL doses are acceptable; avoid large IM doses.",
 viva=["Concentrations by site: face 2.5, AA 5, keloid 10–40 mg/mL",
       "Inject into the dermis, not fat",
       "Atrophy and hypopigmentation are the commonest side effects; blindness the most feared",
       "Ritonavir interaction"],
 src=f"{W} ch.45 (Topical corticosteroids — IL use) and ch.13; {K} ch.22 (Topical and intralesional corticosteroids)"),

# ---------------- III ANTIBIOTICS ----------------
dict(name="Benzathine penicillin G", group="Injectables · III Antibiotics",
 cls="Long-acting depot form of penicillin G (natural β-lactam)",
 moa=["Binds penicillin-binding proteins and inhibits transpeptidation of the bacterial cell wall → bactericidal (needs actively dividing bacteria)",
      "Treponema pallidum divides slowly (every 30–33 h), so long, steady penicillin levels are needed — the benzathine salt gives low levels for 2–4 weeks"],
 pk=["IM depot slowly releases penicillin G over 3–4 weeks",
     "Does not reach treponemicidal levels in CSF — not suitable for neurosyphilis",
     "Excreted by the kidneys"],
 uses=["Syphilis: primary, secondary, early latent (first choice); late latent and tertiary (non-neuro)",
       "Syphilis in pregnancy (the only adequate treatment; desensitise if allergic)",
       "Contacts of early syphilis; NACO white kit (kit 3, genital ulcer disease)",
       "Rheumatic fever prophylaxis; streptococcal pharyngitis; yaws, pinta, bejel"],
 dose=["Early syphilis: 2.4 million units (MU) deep IM single dose (1.2 MU into each buttock)",
       "Late latent/unknown duration, tertiary (non-neuro): 2.4 MU IM once weekly × 3 weeks",
       "Congenital syphilis (asymptomatic infant, selected cases): 50,000 U/kg IM single dose",
       "Rheumatic fever prophylaxis: 1.2 MU every 3–4 weeks",
       "Reconstitute as per vial, inject deep IM with a wide-bore needle; observe for 30 min"],
 ae=["Jarisch–Herxheimer reaction (fever, chills, myalgia, worsening rash) within 2–24 h — from release of treponemal lipoproteins; commonest in secondary syphilis; manage with antipyretics; in pregnancy may cause preterm labour",
     "Anaphylaxis (rare; have adrenaline ready); urticaria, serum sickness",
     "Injection-site pain; accidental intravascular injection → Hoigné syndrome (with procaine penicillin) or Nicolau syndrome (embolia cutis medicamentosa — painful livedoid necrosis)"],
 ci=["Penicillin allergy (in pregnancy or neurosyphilis → desensitise, do not substitute)",
     "Not for IV use; not for neurosyphilis"],
 ix=["Probenecid raises penicillin levels",
     "Tetracyclines (bacteriostatic) may antagonise"],
 mon=["Non-treponemal titre (VDRL/RPR) at 3, 6, 12 (and 24) months; a four-fold fall (two dilutions) by 6–12 months shows adequate response",
      "Test for HIV and other STIs; trace and treat partners"],
 preg="Safe and essential in pregnancy (old FDA category B). Compatible with breastfeeding.",
 viva=["Drug of choice for all stages of syphilis except neurosyphilis (needs aqueous crystalline penicillin G IV)",
       "Jarisch–Herxheimer reaction vs drug allergy",
       "Nicolau syndrome — inadvertent intra-arterial injection",
       "Pregnant women with penicillin allergy must be desensitised",
       "Skin sensitivity testing is still commonly done in India before injection (keep adrenaline ready)"],
 src=f"{W} ch.9; {K} ch.1; NACO STI guidelines",
 note="Skin testing before benzathine penicillin is routine in many Indian hospitals; international guidelines (WHO/CDC) do not require it but stress readiness for anaphylaxis."),

dict(name="Ceftriaxone", group="Injectables · III Antibiotics",
 cls="Third-generation cephalosporin (β-lactam)",
 moa=["Binds penicillin-binding proteins and inhibits cell-wall synthesis → bactericidal",
      "Stable against many β-lactamases; good Gram-negative cover (Neisseria, Haemophilus ducreyi, Enterobacteriaceae) with streptococcal cover"],
 pk=["IM or IV; long half-life (6–9 h) → once-daily dosing",
     "Good CSF penetration with inflamed meninges",
     "Dual excretion (bile ~40% and urine) — no dose change in renal failure alone"],
 uses=["Gonorrhoea (uncomplicated: urethral, cervical, rectal, pharyngeal) and disseminated gonococcal infection",
       "Chancroid; PID (with doxycycline + metronidazole)",
       "Neurosyphilis (alternative when penicillin cannot be used); early syphilis alternative",
       "Lyme disease (late/neurological), cellulitis, severe skin and soft-tissue infections, meningococcaemia, typhoid"],
 dose=["Uncomplicated gonorrhoea: 500 mg IM single dose (1 g if over 150 kg) — CDC 2020; some guidelines (WHO 2024) use 1 g IM",
       "Chancroid: 250 mg IM single dose",
       "Disseminated gonococcal infection: 1 g IV/IM daily",
       "Neurosyphilis (alternative): 1–2 g IV/IM daily × 10–14 days",
       "Skin infections: 1–2 g IV daily",
       "Reconstitute IM dose with 1% lignocaine to reduce pain (never give lignocaine-mixed solution IV)"],
 ae=["Injection-site pain, phlebitis",
     "Hypersensitivity (rash, urticaria, anaphylaxis); cross-reactivity with penicillin is low (about 1–2%)",
     "Diarrhoea, C. difficile colitis",
     "Biliary pseudolithiasis (reversible sludge), especially in children with high doses",
     "Immune haemolytic anaemia (rare); SJS/TEN (rare)"],
 ci=["Severe immediate hypersensitivity (anaphylaxis) to penicillins or cephalosporins",
     "Neonates with hyperbilirubinaemia (displaces bilirubin → kernicterus)",
     "Neonates receiving IV calcium-containing solutions (fatal calcium–ceftriaxone precipitates)"],
 ix=["Calcium-containing IV fluids (Ringer lactate) — do not mix in the same line",
     "Warfarin effect may increase"],
 mon=["Test of cure for pharyngeal gonorrhoea (7–14 days); test for HIV, syphilis and chlamydia; treat partners"],
 preg="Safe in pregnancy (old FDA category B) — the gonorrhoea treatment of choice in pregnancy.",
 viva=["Drug of choice for gonorrhoea (single IM dose)",
       "Dual excretion — no renal dose adjustment",
       "Calcium precipitate risk in neonates",
       "Biliary sludge (pseudolithiasis)"],
 src=f"{W} ch.9; {K} ch.1; CDC STI Treatment Guidelines 2021",
 note="Gonorrhoea dose differs between guidelines (CDC 500 mg, older guidelines 250 mg, WHO 2024 1 g). Please use whatever dose your department or NACO follows."),

dict(name="Bleomycin (intralesional)", group="Injectables · III Antibiotics",
 cls="Glycopeptide cytotoxic antibiotic (from Streptomyces verticillus); antineoplastic",
 moa=["Binds DNA and iron; produces oxygen free radicals that cause single- and double-strand DNA breaks (G2 phase specific)",
      "In warts: kills HPV-infected keratinocytes and damages capillaries → haemorrhagic necrosis and eschar",
      "Skin and lung lack bleomycin hydrolase, the enzyme that inactivates it — hence toxicity in these organs"],
 pk=["Intralesional use gives very low systemic levels",
     "Systemic drug is excreted by the kidneys"],
 uses=["Recalcitrant viral warts (palmoplantar, periungual, common warts)",
       "Keloids and hypertrophic scars (alternative/adjunct)",
       "Vascular malformations (sclerotherapy), cystic lymphatic malformations",
       "Systemic (oncology): squamous cell carcinoma, lymphoma, Kaposi sarcoma (intralesional too), germ-cell tumours"],
 dose=["Warts: 1 U/mL (dissolve a 15 U vial in 15 mL normal saline or lignocaine); inject 0.1–0.2 mL into the base of each wart until it blanches",
       "Keep total dose low per session (usually 1–2 U, a few units at most); repeat every 2–4 weeks if needed",
       "Vascular malformations: weaker solution 0.2–0.4 mg/mL (Wolverton), every 2–4 weeks for 4–10 sessions",
       "Reconstituted solution is stable in the refrigerator for some weeks (check local pharmacy guidance)"],
 ae=["Pain during and after injection (use lignocaine as diluent or a digital block)",
     "Black eschar/haemorrhagic crust, then healing in 2–4 weeks",
     "Periungual/digital injection: nail dystrophy or loss, Raynaud phenomenon, digital necrosis (rare)",
     "Systemic use (not with IL warts): flagellate hyperpigmentation, pulmonary fibrosis (cumulative over 400 U), Raynaud, scleroderma-like changes, fever, alopecia"],
 ci=["Pregnancy and breastfeeding",
     "Peripheral vascular disease, Raynaud phenomenon (especially for digital warts)",
     "Immunosuppression with infection at site; children (relative)"],
 ix=["Cisplatin reduces bleomycin clearance (systemic)",
     "High oxygen concentration (anaesthesia) increases lung toxicity in patients who had systemic bleomycin"],
 mon=["Review at 2–4 weeks; watch digital circulation after periungual injection"],
 preg="Contraindicated (old FDA category D).",
 viva=["Works via DNA strand breaks from free radicals",
       "Flagellate pigmentation and lung fibrosis — systemic use only",
       "Skin and lungs lack bleomycin hydrolase",
       "IL warts: 1 U/mL, inject until blanching"],
 src=f"{W} ch.47 (Topical and intralesional chemotherapeutic agents); {K} (intralesional agents)"),

# ---------------- IV IMMUNOTHERAPY ----------------
dict(name="Histoglobulin (Histoglob PFS)", group="Injectables · IV Immunotherapy",
 cls="Human normal immunoglobulin + histamine dihydrochloride combination (non-specific immunotherapy / 'histaminopexy')",
 moa=["The histamine–immunoglobulin complex is thought to stimulate antibodies that bind histamine",
      "This raises the blood's capacity to bind and neutralise free histamine (histaminopexy) and lowers responsiveness to histamine",
      "May also reduce IgE levels and eosinophil counts and dampen mast-cell activation",
      "Exact mechanism is not fully established"],
 pk=["Given by subcutaneous injection; effect builds over the induction course"],
 uses=["Chronic spontaneous urticaria not controlled with antihistamines (adjunct)",
       "Allergic rhinitis, allergic asthma (adjunct)",
       "Atopic dermatitis (limited evidence)"],
 dose=["One prefilled syringe (PFS) subcutaneously per dose",
       "Induction: 6 injections at 4-day intervals (days 0, 5, 10, 15, 20, 25 as in the manufacturer's calendar); more injections may be given depending on response",
       "Maintenance: booster doses at 1, 3 and 6 months",
       "Continue the patient's antihistamine and taper it according to response"],
 ae=["Pain, redness or swelling at the injection site",
     "Fever, headache, transient flare of itch or urticaria",
     "Rare: hypersensitivity/anaphylaxis (contains human immunoglobulin) — observe after injection",
     "Blood-product precautions: very small theoretical risk of transmissible infection"],
 ci=["Known hypersensitivity to human immunoglobulin or histamine",
     "IgA deficiency with anti-IgA antibodies",
     "Acute febrile illness or infection (postpone), uncontrolled asthma attack",
     "Pregnancy and breastfeeding (insufficient data)"],
 ix=["Systemic corticosteroids may blunt the response (some prescribing information advises against simultaneous use)",
     "Live vaccines: immunoglobulin may reduce response — space as per immunoglobulin guidance"],
 mon=["Urticaria activity score (UAS7) at baseline and follow-up",
      "Observe 15–30 min after each injection"],
 preg="No adequate data — avoid.",
 viva=["Histamine + human immunoglobulin → histaminopexy",
       "Schedule: 6 SC injections every 4 days, then boosters at 1, 3 and 6 months",
       "Evidence is limited (small studies); guideline step-up for chronic urticaria is antihistamine updosing → omalizumab → cyclosporine"],
 src="Not covered in Wolverton or Khopkar; Histoglob PFS prescribing information (Bharat Serums and Vaccines) and dosing card shared by the user",
 note="Histoglobulin is in neither book. The dosing follows the Histoglob PFS card you shared (6 injections 4 days apart, then boosters at 1, 3 and 6 months)."),

# ---------------- V IMMUNOSUPPRESSANTS ----------------
dict(name="Cyclophosphamide injection", group="Injectables · V Immunosuppressants",
 cls="Nitrogen mustard alkylating agent (prodrug)",
 moa=["Activated in the liver (CYP2B6, 2C19) to phosphoramide mustard, which cross-links DNA strands (guanine N7) → cell death; cell-cycle non-specific",
      "Strongly suppresses B cells (antibody production) and T cells",
      "By-product acrolein causes bladder toxicity"],
 pk=["Oral and IV; metabolites excreted in urine — reduce dose in renal failure"],
 uses=["Pemphigus: DCP pulse (dexamethasone–cyclophosphamide; third line in the Derma Desk ladder); also refractory pemphigoid and mucous membrane pemphigoid (ocular)",
       "Systemic vasculitis (granulomatosis with polyangiitis, polyarteritis nodosa), lupus nephritis, dermatomyositis with lung disease, systemic sclerosis lung",
       "Lymphoma/mycosis fungoides (oncology), pyoderma gangrenosum (refractory)"],
 dose=["DCP: 500 mg IV on day 1 of each monthly dexamethasone pulse, plus 50 mg orally daily between pulses",
       "Vasculitis/lupus (IV pulse): 500–1000 mg/m² (or 15 mg/kg) monthly",
       "Oral: 1–2 mg/kg/day",
       "Give in the morning with plenty of fluid (2–3 L/day), frequent voiding; mesna with high IV doses"],
 ae=["Bone marrow suppression (nadir 8–14 days)",
     "Haemorrhagic cystitis (acrolein) and bladder cancer (long-term, cumulative) — prevent with hydration and mesna",
     "Infertility: premature ovarian failure, azoospermia (consider sperm/oocyte preservation)",
     "Nausea, vomiting, alopecia (anagen effluvium), nail and skin hyperpigmentation",
     "Infections (including PJP — consider co-trimoxazole prophylaxis), secondary malignancy (leukaemia, lymphoma, skin cancer)",
     "SIADH, pulmonary fibrosis, cardiotoxicity (high doses)"],
 ci=["Pregnancy and breastfeeding; active serious infection; bone marrow failure",
     "Urinary outflow obstruction"],
 ix=["Allopurinol: increases marrow toxicity",
     "Enzyme inducers (phenobarbital, rifampicin) increase toxic metabolites",
     "Succinylcholine: prolonged apnoea (cyclophosphamide inhibits pseudocholinesterase)"],
 mon=["CBC weekly to 2-weekly during therapy; urine for blood monthly and then for life (bladder cancer risk)",
      "Renal function, LFT; pregnancy test; fertility counselling"],
 preg="Contraindicated (old FDA category D) — teratogenic. Effective contraception during and for some months after treatment.",
 viva=["Prodrug activated in the liver; acrolein → haemorrhagic cystitis; mesna is the antidote for the bladder",
       "Lifelong urine checks for bladder cancer",
       "DCP regimen for pemphigus (Pasricha)",
       "Fertility counselling before starting"],
 src=f"{W} ch.19 (Cytotoxic agents); {K} (Non-steroidal immunosuppressive drugs; DCP pulse)"),

dict(name="5-Fluorouracil (5-FU) injection", group="Injectables · V Immunosuppressants",
 cls="Pyrimidine analogue antimetabolite (antineoplastic)",
 moa=["Converted to fluorodeoxyuridine monophosphate, which inhibits thymidylate synthase → no thymidine → no DNA synthesis",
      "Also incorporated into RNA",
      "In keloids: inhibits fibroblast proliferation and TGF-β-driven collagen production"],
 pk=["IL use gives minimal systemic levels; systemic drug is metabolised by dihydropyrimidine dehydrogenase (DPD)"],
 uses=["Intralesional: keloids and hypertrophic scars (alone or mixed with triamcinolone), warts, keratoacanthoma, small BCC (selected)",
       "Vitiligo (with microneedling/dermabrasion, off-label)",
       "Topical 5% cream for actinic keratosis, Bowen disease, superficial BCC (topicals slot)"],
 dose=["Supplied as 50 mg/mL injection",
       "Keloids: 50 mg/mL alone, or mixed with triamcinolone (e.g. 0.9 mL 5-FU + 0.1 mL triamcinolone 40 mg/mL); 0.2–0.5 mL per cm² of lesion; total usually under 2–3 mL per session; every 1–4 weeks",
       "Keratoacanthoma: 50 mg/mL, 0.1–1 mL weekly"],
 ae=["IL: pain, burning, ulceration, purpura, hyperpigmentation",
     "Systemic (rare with IL): myelosuppression, mucositis, diarrhoea; severe toxicity in DPD deficiency",
     "Systemic 5-FU skin effects: hand–foot syndrome, serpentine supravenous hyperpigmentation, photosensitivity"],
 ci=["Pregnancy and breastfeeding",
     "Known DPD deficiency; bone marrow suppression; infection at site"],
 ix=["Warfarin effect increases",
     "Sorivudine/brivudine (antivirals): fatal DPD inhibition"],
 mon=["CBC if large or frequent doses are used"],
 preg="Contraindicated (old FDA category D/X depending on form).",
 viva=["Thymidylate synthase inhibitor",
       "5-FU + TAC combination for keloids reduces atrophy and recurrence",
       "DPD deficiency → severe toxicity",
       "Supravenous serpentine hyperpigmentation with IV use"],
 src=f"{W} ch.47 (Topical and intralesional chemotherapeutic agents); {K} (Miscellaneous agents)"),

dict(name="Leucovorin calcium (folinic acid) injection", group="Injectables · V Immunosuppressants",
 cls="Reduced folate (5-formyl-tetrahydrofolate); antidote",
 moa=["Already in reduced form, so it bypasses the dihydrofolate reductase step blocked by methotrexate",
      "Restores purine and thymidine synthesis in normal cells ('leucovorin rescue')",
      "Also enhances 5-FU effect (stabilises thymidylate synthase binding) in oncology"],
 pk=["IV, IM or oral; rapidly converted to active folates"],
 uses=["Methotrexate toxicity/overdose (pancytopenia, mucositis, accidental daily dosing) — the antidote",
       "Planned rescue after high-dose methotrexate (oncology)",
       "Folate deficiency megaloblastic anaemia when oral folic acid cannot be used",
       "With 5-FU in colorectal cancer; pyrimethamine/trimethoprim toxicity"],
 dose=["MTX toxicity: give as early as possible (ideally within 24 h; effectiveness falls after 24–48 h)",
       "Typical: 10–15 mg/m² (or 15–25 mg) IV/IM/orally every 6 h until counts recover and MTX level is below safe threshold; larger doses for high levels",
       "Ampoules 15 mg/2 mL, 50 mg vials; tablets 15 mg",
       "Folic acid cannot replace leucovorin in acute toxicity (needs DHFR for activation)"],
 ae=["Rare: allergic reactions, fever",
     "Do not give intrathecally; do not give faster than 160 mg/min IV (calcium content)"],
 ci=["Pernicious anaemia/B12 deficiency (may correct anaemia while neurological damage progresses)"],
 ix=["Reduces efficacy of methotrexate (intended) and of co-trimoxazole for PJP",
     "Increases 5-FU toxicity",
     "Anticonvulsants (phenytoin, phenobarbital): levels may fall"],
 mon=["CBC daily in MTX toxicity; renal function; MTX level where available",
      "Supportive care: hydration, urine alkalinisation, mouth care, G-CSF if needed"],
 preg="Safe when needed.",
 viva=["Bypasses DHFR → antidote for methotrexate toxicity",
       "Give within 24 h",
       "Folic acid prevents side effects of low-dose MTX; leucovorin treats acute toxicity"],
 src=f"{W} ch.14 (Methotrexate — overdose management); {K} (Non-steroidal immunosuppressive drugs)"),

# ---------------- VI EMERGENCY DRUGS ----------------
dict(name="Adrenaline (epinephrine) injection", group="Injectables · VI Emergency drugs",
 cls="Endogenous catecholamine; α and β adrenergic agonist",
 moa=["α1: vasoconstriction → raises BP, reduces mucosal oedema",
      "β1: increases heart rate and contractility",
      "β2: bronchodilation; also stabilises mast cells (less mediator release)"],
 pk=["IM into the anterolateral thigh gives faster, higher peak levels than SC",
     "Onset within minutes; short action (5–10 min) — repeat dosing may be needed",
     "Concentrations: 1 mg/mL (1:1000) for IM; 0.1 mg/mL (1:10,000) for IV in cardiac arrest"],
 uses=["Anaphylaxis — the first-line, life-saving drug",
       "Cardiac arrest (IV/IO)",
       "Severe angioedema with airway involvement",
       "With local anaesthetics (1:100,000–1:200,000) to prolong action and reduce bleeding"],
 dose=["Anaphylaxis: 0.01 mg/kg of 1 mg/mL (1:1000) IM in the anterolateral thigh — adult and child over 12 years 0.5 mg (0.5 mL); 6–12 years 0.3 mg; under 6 years 0.15 mg",
       "Repeat every 5 min if no improvement",
       "Refractory anaphylaxis: IV infusion by experienced staff only (never give 1:1000 IV bolus)",
       "Cardiac arrest: 1 mg IV (1:10,000) every 3–5 min",
       "Autoinjectors: 0.3 mg (adult), 0.15 mg (child) — prescribe for patients with previous anaphylaxis"],
 ae=["Tremor, palpitations, anxiety, pallor, headache",
     "Tachyarrhythmias, hypertension, myocardial ischaemia (mainly with IV use or overdose)",
     "Tissue necrosis with accidental injection into digits (rare) or extravasation"],
 ci=["None in anaphylaxis — always give",
     "Caution with local anaesthetic use: uncontrolled hypertension, severe heart disease, hyperthyroidism, phaeochromocytoma"],
 ix=["β-blockers: anaphylaxis resistant to adrenaline → give glucagon 1–5 mg IV; non-selective β-blockers may cause severe hypertension",
     "Tricyclic antidepressants, MAO inhibitors, cocaine: exaggerated pressor effect",
     "Halothane: arrhythmias"],
 mon=["BP, pulse, SpO₂, ECG; observe for at least 6–12 h after anaphylaxis (biphasic reaction)"],
 preg="Use without hesitation in anaphylaxis in pregnancy.",
 viva=["Anaphylaxis: 0.5 mg (0.5 mL of 1:1000) IM in the thigh — repeat after 5 min",
       "Antihistamines and steroids are only add-ons",
       "Glucagon for patients on β-blockers",
       "Every dermatology procedure room should have adrenaline ready"],
 src=f"{W} ch.58 (local anaesthetics) and anaphylaxis sections; Resuscitation Council / WAO anaphylaxis guidance"),

dict(name="Pheniramine maleate injection", group="Injectables · VI Emergency drugs",
 cls="First-generation (sedating) H1 antihistamine; alkylamine group",
 moa=["H1 receptor inverse agonist — blocks histamine-mediated itch, wheal, flare and vascular leak",
      "Anticholinergic and sedative effects"],
 pk=["IM or slow IV; onset within 15–30 min; duration 4–6 h"],
 uses=["Adjunct in anaphylaxis (after adrenaline) — relieves itch and urticaria; does not treat airway or shock",
       "Acute urticaria, angioedema (non-airway), allergic drug reactions, insect bite reactions",
       "Pre-medication before contrast media or blood products in sensitised patients"],
 dose=["Adults: 22.75–45.5 mg (1–2 mL of 22.75 mg/mL) IM or slow IV; repeat up to 2–3 times a day if needed",
       "Children: about 0.5–1 mg/kg/day in divided doses (avoid in infants)",
       "Ampoule 22.75 mg/mL (2 mL)"],
 ae=["Sedation, dizziness; hypotension with fast IV injection",
     "Anticholinergic: dry mouth, urinary retention, blurred vision",
     "Paradoxical excitation in children, convulsions in overdose"],
 ci=["Neonates and premature infants; breastfeeding",
     "Caution: glaucoma, prostatic hypertrophy, epilepsy, elderly"],
 ix=["Alcohol, sedatives, opioids: additive CNS depression",
     "MAO inhibitors, other anticholinergics"],
 mon=["Watch BP and level of consciousness after IV use"],
 preg="Use only if needed; prefer second-generation oral antihistamines for routine use.",
 viva=["Commonly used injectable antihistamine in Indian practice (brand Avil)",
       "Second-line drug in anaphylaxis — never a substitute for adrenaline",
       "Inject IV slowly (hypotension)"],
 src=f"{K} (Antihistamines and mast cell stabilizers); {W} ch.32 (H1 antihistamines — class)"),

dict(name="Atropine sulphate injection", group="Injectables · VI Emergency drugs",
 cls="Antimuscarinic (anticholinergic) belladonna alkaloid",
 moa=["Competitively blocks muscarinic acetylcholine receptors",
      "Heart: blocks vagal tone → raises heart rate and AV conduction",
      "Also reduces secretions, relaxes smooth muscle, dilates pupils"],
 pk=["IV onset within 1 min; IM within 15 min; half-life about 2–4 h"],
 uses=["Symptomatic bradycardia — including severe vasovagal reaction during dermatological procedures",
       "Organophosphate/carbamate insecticide poisoning (large repeated doses)",
       "Pre-anaesthetic to dry secretions; reversal of neuromuscular block (with neostigmine)"],
 dose=["Bradycardia: 0.5–0.6 mg IV every 3–5 min, up to a total of 3 mg",
       "Organophosphate poisoning: 1.2–2.4 mg IV, doubled every 5 min until the chest is clear and the heart rate is over 80/min",
       "Children: 0.02 mg/kg (minimum 0.1 mg)",
       "Ampoule 0.6 mg/mL"],
 ae=["Dry mouth, flushing, hot dry skin, fever (especially children)",
     "Tachycardia, blurred vision, urinary retention, constipation",
     "Confusion, delirium in the elderly ('mad as a hatter, red as a beet, dry as a bone, blind as a bat, hot as a hare')",
     "Doses under 0.5 mg in adults can cause paradoxical bradycardia"],
 ci=["Angle-closure glaucoma, obstructive uropathy, paralytic ileus, myasthenia gravis (relative), tachyarrhythmias",
     "No absolute contraindication in life-threatening bradycardia or poisoning"],
 ix=["Other anticholinergics (TCAs, first-generation antihistamines, phenothiazines): additive effects"],
 mon=["Heart rate, BP, ECG"],
 preg="Crosses the placenta; use when needed in emergencies.",
 viva=["Vasovagal attack during a procedure: lie flat, legs up; atropine if bradycardia persists",
       "Minimum dose 0.5 mg in adults to avoid paradoxical bradycardia",
       "Signs of atropine toxicity (anticholinergic toxidrome)"],
 src=f"{W} ch.58 (vasovagal reactions); ACLS/resuscitation guidelines"),

dict(name="Sodium bicarbonate injection", group="Injectables · VI Emergency drugs",
 cls="Alkalinising agent (systemic buffer)",
 moa=["Bicarbonate combines with hydrogen ions → carbonic acid → CO₂ (breathed out) and water → raises blood pH",
      "Alkalinises urine; shifts potassium into cells",
      "In local anaesthesia: raises solution pH so more drug is unionised → faster onset and much less injection pain"],
 pk=["Available as 7.5% (≈0.9 mEq/mL) and 8.4% (1 mEq/mL) solutions; hypertonic"],
 uses=["Buffering lignocaine before injection (dermatology use): 1 mL 8.4% NaHCO₃ to 10 mL lignocaine (with or without adrenaline)",
       "Severe metabolic acidosis (e.g. pH below 7.1), hyperkalaemia (adjunct), tricyclic antidepressant overdose (QRS widening)",
       "Urinary alkalinisation in methotrexate toxicity and salicylate poisoning",
       "Not given routinely in cardiac arrest"],
 dose=["Buffering: 1 : 10 with lignocaine — use within about a week (adrenaline breaks down faster in alkaline solution); prepare fresh where possible",
       "Metabolic acidosis: 1 mEq/kg slow IV, then guided by blood gases",
       "Hyperkalaemia/TCA overdose: 50–100 mEq IV slowly"],
 ae=["Metabolic alkalosis, hypernatraemia, fluid overload",
     "Hypokalaemia, hypocalcaemia (tetany)",
     "Severe tissue necrosis if extravasated (hypertonic)",
     "Paradoxical CSF acidosis (CO₂ crosses BBB)"],
 ci=["Metabolic or respiratory alkalosis, hypocalcaemia, chloride loss from vomiting",
     "Caution: heart failure, renal failure, hypernatraemia"],
 ix=["Incompatible with calcium salts and catecholamines in the same line (precipitates/inactivates)",
     "Alkaline urine increases excretion of salicylates and methotrexate, decreases excretion of amphetamines"],
 mon=["Arterial blood gas, sodium, potassium, calcium during IV use"],
 preg="Use when indicated.",
 viva=["Buffered lignocaine (1:10) — less pain, faster onset",
       "Urine alkalinisation in MTX toxicity",
       "Not routine in CPR"],
 src=f"{W} ch.58 (buffering local anaesthetics) and ch.14 (MTX toxicity)"),

# ---------------- VII VACCINES ----------------
dict(name="MMR vaccine", group="Injectables · VII Vaccines",
 cls="Live attenuated viral vaccine (measles, mumps, rubella)",
 moa=["Attenuated viruses replicate briefly and induce long-lasting humoral and cell-mediated immunity",
      "Intralesional use in warts: the antigen triggers a delayed-type hypersensitivity (Th1) response with cytokines (IFN-γ, IL-2, TNF) that also clears distant, untreated warts"],
 pk=["0.5 mL subcutaneous (or IM); seroconversion over 2–3 weeks"],
 uses=["Prevention of measles, mumps and rubella (national schedule: MR at 9–12 months and 16–24 months; MMR in private schedule at 9 months, 15 months, 4–6 years)",
       "Rubella-susceptible women before pregnancy",
       "Dermatology: intralesional immunotherapy for multiple or recalcitrant warts (common, plantar, anogenital)"],
 dose=["Prophylaxis: 0.5 mL SC",
       "Warts: 0.3–0.5 mL injected into the largest (mother) wart, every 2–3 weeks, up to 3–5 sessions (pre-sensitisation not needed)"],
 ae=["Pain, swelling, fever, flu-like symptoms",
     "Transient measles-like rash, parotid swelling, arthralgia (rubella component, adult women)",
     "Febrile seizures (rare), thrombocytopenia (rare), anaphylaxis (gelatin/neomycin)"],
 ci=["Pregnancy (avoid pregnancy for 1 month after vaccination)",
     "Immunosuppression (high-dose steroids, chemotherapy, biologics, advanced HIV)",
     "Severe allergy to neomycin or gelatin; recent immunoglobulin or blood products (defer 3–11 months)",
     "Acute febrile illness"],
 ix=["Can temporarily suppress tuberculin skin test — do Mantoux on the same day or 4–6 weeks after",
     "Immunoglobulin products reduce response",
     "Give other live vaccines the same day or 4 weeks apart"],
 mon=["Observe 15–30 min after injection"],
 preg="Contraindicated (live vaccine); inadvertent vaccination is not a reason for termination.",
 viva=["Live vaccine — avoid in pregnancy and immunosuppression",
       "Immunotherapy for warts: induces Th1 response, clears distant warts",
       "Interferes with Mantoux reading"],
 src=f"{W} ch.43 (Topical and intralesional antiviral agents — IL immunotherapy for warts); national immunisation schedule",
 note="Wolverton discusses Candida antigen and HPV vaccine more than MMR; MMR wart protocol is from published Indian studies and IADVL practice."),

dict(name="BCG vaccine", group="Injectables · VII Vaccines",
 cls="Live attenuated Mycobacterium bovis (Bacille Calmette–Guérin) vaccine",
 moa=["Induces cell-mediated (Th1) immunity to mycobacteria",
      "Protects children against severe TB (miliary TB, TB meningitis); variable protection against pulmonary TB and some protection against leprosy",
      "Non-specific immune stimulation (trained immunity) — basis for use in warts and bladder cancer"],
 pk=["0.1 mL intradermal (0.05 mL in infants under 1 month) over the left deltoid insertion",
     "Papule → pustule → ulcer → scar over 6–12 weeks"],
 uses=["Routine at birth in India (national schedule; up to 1 year of age)",
       "Dermatology: immunotherapy for warts (intralesional or intradermal), leprosy contacts (some programmes)",
       "Intravesical BCG for superficial bladder cancer"],
 dose=["0.1 mL intradermal (0.05 mL under 1 month)",
       "Warts (off-label protocols): 0.1 mL intradermal/IL every 2–4 weeks for a few sessions"],
 ae=["Normal: local papule, ulcer, scar",
     "Complications: large ulcer, abscess, suppurative lymphadenitis (BCG adenitis), keloid",
     "Cutaneous TB at the site: lupus vulgaris, scrofuloderma; tuberculids (lichen scrofulosorum, papulonecrotic)",
     "Disseminated BCG infection (BCGosis) in immunodeficient children (SCID, chronic granulomatous disease, IFN-γ pathway defects, HIV)",
     "Flare (redness) of an old BCG scar in Kawasaki disease (a diagnostic clue)"],
 ci=["Immunosuppression (primary immunodeficiency, symptomatic HIV, steroids, biologics, chemotherapy)",
     "Pregnancy; generalised skin disease or infection at the site; active TB"],
 ix=["Antituberculous drugs inactivate the vaccine",
     "Immunosuppressants increase the risk of disseminated infection"],
 mon=["Check the site at follow-up; investigate persistent ulcer or adenitis"],
 preg="Contraindicated (live vaccine).",
 viva=["Live vaccine — intradermal, left deltoid",
       "Cutaneous complications include lupus vulgaris and scrofuloderma at the site",
       "BCGosis signals immunodeficiency",
       "BCG scar reactivation in Kawasaki disease"],
 src=f"{W} ch.43 (IL immunotherapy for warts — brief); national immunisation schedule; {K} (Immunobiologicals)"),

dict(name="Pneumococcal polysaccharide vaccine (PPSV23)", group="Injectables · VII Vaccines",
 cls="Inactivated polysaccharide vaccine — 23 serotypes of Streptococcus pneumoniae",
 moa=["Capsular polysaccharides induce antibodies by a T-cell-independent pathway",
      "Gives no immunological memory, no booster effect, and is poorly immunogenic in children under 2 years",
      "Conjugate vaccines (PCV13/15/20) link the polysaccharide to a protein → T-cell-dependent, better memory"],
 pk=["0.5 mL IM or SC; antibodies within 2–3 weeks; wane after about 5 years"],
 uses=["Adults 65 years and over",
       "People at high risk aged 2–64: asplenia, chronic heart/lung/liver/kidney disease, diabetes, HIV",
       "Dermatology: before or early in immunosuppressive therapy — rituximab, long-term systemic steroids, methotrexate, azathioprine, MMF, cyclophosphamide, JAK inhibitors, biologics",
       "Give at least 2 weeks before rituximab (rituximab blunts antibody response for 6+ months)"],
 dose=["0.5 mL IM or SC",
       "Usual sequence: conjugate vaccine (PCV) first, then PPSV23 at least 8 weeks later; one revaccination with PPSV23 after 5 years in high-risk patients",
       "If PCV20 or PCV21 is used, PPSV23 is usually not needed (current CDC advice)"],
 ae=["Injection-site pain and swelling (more after revaccination)",
     "Low-grade fever, myalgia",
     "Severe reactions rare"],
 ci=["Severe allergy to a previous dose or component",
     "Defer during acute illness"],
 ix=["Immunosuppressants and rituximab reduce response — vaccinate before starting where possible"],
 mon=["None"],
 preg="Not routinely given; may be given to high-risk women if needed (inactivated).",
 viva=["Polysaccharide = T-independent = no memory, poor in under-2s",
       "Vaccinate before rituximab and other immunosuppressants",
       "PCV first, then PPSV23 ≥8 weeks later"],
 src=f"{W} ch.30 (Rituximab — vaccination before therapy); CDC/ACIP adult schedule",
 note="Adult pneumococcal recommendations changed recently (PCV20/PCV21). Please confirm the current schedule."),

dict(name="HPV vaccine (quadrivalent)", group="Injectables · VII Vaccines",
 cls="Recombinant non-infectious virus-like particle (VLP) vaccine against HPV types 6, 11, 16 and 18",
 moa=["L1 capsid protein self-assembles into VLPs (no viral DNA) → strong neutralising antibody response",
      "Types 6 and 11 cause about 90% of anogenital warts; types 16 and 18 cause about 70% of cervical cancers",
      "Prophylactic — does not clear established infection (therapeutic use in warts is off-label)"],
 pk=["0.5 mL IM in the deltoid"],
 uses=["Prevention of cervical, vulvar, vaginal, anal, oropharyngeal cancers and anogenital warts in girls and boys",
       "Best given before sexual debut (9–14 years)",
       "Recurrent respiratory papillomatosis prevention",
       "Off-label: recalcitrant cutaneous and anogenital warts (case series; Wolverton notes some reports of benefit)",
       "India: indigenous qHPV vaccine (Cervavac) and introduction into the national programme for girls"],
 dose=["9–14 years: 2 doses (0 and 6–12 months)",
       "15–26 years: 3 doses (0, 2 and 6 months) — WHO now also accepts 1–2 doses in younger groups",
       "Immunocompromised (including HIV): 3 doses",
       "9-valent vaccine (Gardasil 9) adds types 31, 33, 45, 52, 58"],
 ae=["Injection-site pain, swelling",
     "Syncope (observe seated for 15 min), headache, fever",
     "Anaphylaxis very rare (yeast protein)"],
 ci=["Severe allergy to a previous dose or to yeast",
     "Pregnancy (defer remaining doses until after delivery; inadvertent dosing is not harmful)"],
 ix=["Immunosuppressants may reduce response"],
 mon=["Observe 15 min for syncope"],
 preg="Not recommended in pregnancy (precaution); safe in breastfeeding.",
 viva=["VLP vaccine — no DNA, cannot cause infection",
       "6 and 11 → warts; 16 and 18 → cancer",
       "2 doses if started before 15; 3 doses after 15 or if immunocompromised",
       "Prevents anogenital warts — relevant for STI clinic counselling"],
 src=f"{W} ch.43 (HPV vaccine in warts); WHO HPV position paper 2022"),

dict(name="Tuberculin PPD (Mantoux test)", group="Injectables · VII Vaccines",
 cls="Purified protein derivative of M. tuberculosis — diagnostic antigen for delayed-type hypersensitivity",
 moa=["In people previously sensitised to mycobacteria (infection or BCG), memory T cells react to intradermal PPD",
      "Type IV (delayed) hypersensitivity → induration peaks at 48–72 h"],
 pk=["Intradermal injection forms a 6–10 mm wheal (bleb)"],
 uses=["Screening for latent TB before biologics, JAK inhibitors, long-term steroids, methotrexate and other immunosuppressants (IGRA preferred after BCG)",
       "Supporting diagnosis of cutaneous TB (lupus vulgaris, TBVC, scrofuloderma usually strongly positive)",
       "Assessing cell-mediated immunity (anergy in sarcoidosis, HIV, lepromatous leprosy)",
       "Dermatology off-label: intralesional immunotherapy for warts (PPD 10 TU into the largest wart every 2 weeks)"],
 dose=["Mantoux: 0.1 mL (5 TU PPD-S or 2 TU PPD RT23 used in India) intradermal on the volar forearm",
       "Read at 48–72 h: measure induration (not redness) across the forearm",
       "Positive: ≥5 mm in HIV, immunosuppressed (including ≥15 mg prednisolone/day), recent contacts; ≥10 mm in others at risk (and in India generally); ≥15 mm in people with no risk factors"],
 ae=["Local itching, redness; rarely blistering or ulceration in highly sensitive people",
     "Lymphangitis (rare); anaphylaxis very rare"],
 ci=["Previous severe reaction to tuberculin (blistering, necrosis)",
     "Known active TB — not needed"],
 ix=["False negatives: recent live vaccine (MMR, varicella — do test the same day or 4–6 weeks later), immunosuppressants, HIV, sarcoidosis, malnutrition, overwhelming TB, measles, Hodgkin disease, very young or old",
     "False positives: BCG vaccination, non-tuberculous mycobacteria",
     "Booster phenomenon: repeat test may be positive because the first test re-awakens immunity (two-step testing)"],
 mon=["Read at 48–72 h by trained staff"],
 preg="Safe in pregnancy.",
 viva=["Measure induration, not erythema",
       "Lupus vulgaris — strongly positive",
       "Causes of false-negative and false-positive results",
       "IGRA is preferred in BCG-vaccinated people before biologics"],
 src=f"{W} ch.26 (TNF inhibitors — TB screening); {K} (Antituberculous agents)"),

# ---------------- VIII VITAMINS ----------------
dict(name="Vitamin D3 (cholecalciferol) 60,000 IU", group="Injectables · VIII Vitamins",
 cls="Fat-soluble vitamin (secosteroid prohormone)",
 moa=["Converted in the liver to 25-hydroxyvitamin D (storage form, measured in blood), then in the kidney to 1,25-dihydroxyvitamin D (calcitriol, active)",
      "Calcitriol acts on the vitamin D receptor: increases calcium and phosphate absorption, regulates bone",
      "Skin effects: regulates keratinocyte differentiation, boosts innate immunity (cathelicidin), dampens Th1/Th17 responses"],
 pk=["Stored in fat; long half-life of 25(OH)D (about 2–3 weeks) allows weekly or monthly dosing",
     "Oral 60,000 IU (sachet, capsule, chewable) is well absorbed and preferred",
     "IM injections (usually 300,000 or 600,000 IU) are absorbed slowly and unpredictably — reserve for malabsorption or poor compliance"],
 uses=["Vitamin D deficiency (common in India): especially patients on strict photoprotection (xeroderma pigmentosum, porphyria, lupus), long-term steroids, anticonvulsants, dark skin with little sun",
       "Bone protection with long-term systemic steroids (with calcium)",
       "Adjunct (evidence modest): atopic dermatitis, chronic urticaria, psoriasis, vitiligo, alopecia areata in deficient patients",
       "Rickets, osteomalacia"],
 dose=["Deficiency (adults): 60,000 IU once weekly orally for 8 weeks, then 60,000 IU monthly for maintenance",
       "Children: weight/age-based (e.g. 60,000 IU weekly for 6 weeks over 1 year of age; lower in infants)",
       "IM (if needed): 300,000–600,000 IU single dose ('stoss' therapy) — not repeated within 3 months",
       "Deficiency: 25(OH)D below 20 ng/mL; insufficiency 20–29 ng/mL; sufficient 30–100 ng/mL"],
 ae=["At usual doses — safe",
     "Toxicity (25(OH)D over about 150 ng/mL): hypercalcaemia → nausea, vomiting, constipation, polyuria, thirst, confusion, kidney stones, nephrocalcinosis, arrhythmia"],
 ci=["Hypercalcaemia, vitamin D toxicity",
     "Caution: granulomatous disease (sarcoidosis, TB — macrophages make calcitriol → hypercalcaemia), kidney stones, severe renal failure (needs active form)"],
 ix=["Thiazide diuretics: hypercalcaemia",
     "Digoxin: hypercalcaemia increases toxicity",
     "Anticonvulsants, rifampicin, long-term steroids increase vitamin D needs",
     "Orlistat and cholestyramine reduce absorption"],
 mon=["Serum 25(OH)D at baseline and 3 months after loading; serum calcium (especially with high doses or sarcoidosis)"],
 preg="Safe at recommended doses; deficiency should be corrected in pregnancy.",
 viva=["60,000 IU weekly × 8 weeks, then monthly",
       "Measure 25(OH)D, not 1,25(OH)₂D",
       "Sarcoidosis — risk of hypercalcaemia",
       "Patients on strict photoprotection need supplements"],
 src=f"{K} (Vitamins and trace elements); Endocrine Society and Indian vitamin D guidance",
 note="The exam list puts 60,000 IU under injectables, but 60,000 IU is mainly an oral dose in India (injections are 300,000/600,000 IU). Both are covered."),

# ---------------- IX MISCELLANEOUS ----------------
dict(name="Menadione (vitamin K3) injection", group="Injectables · IX Miscellaneous",
 cls="Synthetic water-soluble vitamin K analogue (provitamin; menadione sodium bisulfite)",
 moa=["Converted in the liver to active vitamin K2 (menaquinone-4)",
      "Vitamin K is a cofactor for γ-carboxylation of clotting factors II, VII, IX and X (and proteins C and S)",
      "Corrects bleeding from vitamin K deficiency, but acts slowly and weakly compared with vitamin K1"],
 pk=["Water-soluble — does not need bile for absorption (useful in obstructive jaundice)",
     "Onset slower than phytomenadione (vitamin K1); not reliable for reversing warfarin"],
 uses=["Hypoprothrombinaemia due to vitamin K deficiency: obstructive jaundice, malabsorption, long-term broad-spectrum antibiotics, prolonged parenteral nutrition",
       "Used as a haemostatic in some Indian practice",
       "Not the drug of choice for warfarin reversal or haemorrhagic disease of the newborn — phytomenadione (vitamin K1) is preferred"],
 dose=["Typically 10 mg IM/IV (menadione sodium bisulfite) as directed by the product",
       "Vitamin K1 (phytomenadione) for comparison: newborn prophylaxis 1 mg IM at birth; warfarin reversal 1–10 mg slow IV (no faster than 1 mg/min)"],
 ae=["Haemolytic anaemia in G6PD deficiency",
     "Neonates: haemolysis, hyperbilirubinaemia and kernicterus — contraindicated",
     "Vitamin K injection-site skin reactions (mostly with vitamin K1): itchy eczematous plaques at the injection site (early), and later sclerodermoid plaques with a 'cowboy belt' distribution on the buttocks and thighs (Texier disease)",
     "Rapid IV vitamin K1: anaphylactoid reactions (flushing, collapse)"],
 ci=["Neonates and infants; late pregnancy (risk to the newborn)",
     "G6PD deficiency",
     "Hypersensitivity"],
 ix=["Antagonises warfarin and other vitamin K antagonists",
     "Long-term antibiotics (cephalosporins) and cholestyramine increase vitamin K needs"],
 mon=["Prothrombin time/INR"],
 preg="Avoid menadione in late pregnancy (neonatal haemolysis and jaundice); vitamin K1 is safe.",
 viva=["Menadione (K3) vs phytomenadione (K1): K1 is preferred in neonates and for warfarin reversal",
       "Menadione causes haemolysis in G6PD deficiency and kernicterus in newborns",
       "Skin reactions to vitamin K injections: eczematous plaques; Texier disease (pseudo-scleroderma, cowboy-belt pattern)"],
 src=f"{K} (Vitamins and trace elements); pharmacology references; {W} (drug eruption sections)",
 note="Menadione is not covered in Wolverton. Khopkar and standard pharmacology texts were used; please check whether your examiners mean menadione (K3) or phytomenadione (K1)."),
]
