# More from Khopkar — slot 9: remaining topical agents, antiseptics, wart agents, scabicides, immunomodulators, pigmentary, wound care, peels
W = "Wolverton 4e"; K = "Khopkar"
G1 = "More from Khopkar · Topical antibacterials & antiseptics"
G2 = "More from Khopkar · Topical antifungals"
G3 = "More from Khopkar · Wart & antiviral agents"
G4 = "More from Khopkar · Scabicides & pediculicides"
G5 = "More from Khopkar · Topical immunomodulators & antipsoriatics"
G6 = "More from Khopkar · Pigmentary & cosmeceutical agents"
G7 = "More from Khopkar · Miscellaneous topicals & wound care"
G8 = "More from Khopkar · Chemical agents, peels & baths"
D = [
# ---------------- TOPICAL ANTIBACTERIALS & ANTISEPTICS ----------------
dict(name="Nadifloxacin 1% cream", group=G1,
 cls="Topical fluoroquinolone",
 moa=["Inhibits DNA gyrase and topoisomerase IV → bactericidal against C. acnes, S. aureus (including MRSA) and S. epidermidis; also anti-inflammatory (reduces cytokines)"],
 uses=["Inflammatory acne (with BPO), impetigo, folliculitis, infected dermatoses"],
 dose=["Twice daily; acne up to 8–12 weeks with BPO"],
 ae=["Itching, irritation, contact dermatitis (rare)"],
 ci=["Hypersensitivity to quinolones"],
 preg="Avoid (limited data).",
 viva=["Topical quinolone for acne in India/Japan; combine with BPO to prevent resistance"],
 src=f"{K} ch.18; {W} ch.41"),

dict(name="Neomycin, bacitracin & polymyxin B", group=G1,
 cls="Topical antibiotics often combined: neomycin (aminoglycoside), bacitracin (polypeptide), polymyxin B (cationic cyclic decapeptide)",
 moa=["Neomycin: 30S ribosome — Gram-negatives and staphylococci",
      "Bacitracin: blocks cell-wall synthesis (bactoprenol dephosphorylation) — Gram-positives",
      "Polymyxin B: disrupts Gram-negative outer membrane phospholipids (detergent-like); Pseudomonas"],
 uses=["Minor wounds, abrasions, superficial infections (triple antibiotic ointments)",
       "Not first choice for impetigo (mupirocin, fusidic acid, ozenoxacin better)"],
 dose=["1–3 times daily for up to 7 days"],
 ae=["Allergic contact dermatitis — neomycin is one of the commonest contact allergens (patch-test series); cross-reacts with framycetin, gentamicin",
     "Bacitracin: contact allergy and rare anaphylaxis/contact urticaria",
     "Ototoxicity/nephrotoxicity if absorbed from large wounds"],
 ci=["Known allergy; large raw areas; perforated ear drum (neomycin)"],
 preg="Small areas acceptable.",
 viva=["Neomycin — top contact allergen; avoid on stasis eczema/leg ulcers",
       "Bacitracin — contact allergy and anaphylaxis"],
 src=f"{K} ch.18 (Bacitracin, Polymyxin B); {W} ch.41 and ch.56"),

dict(name="Silver sulfadiazine 1% cream", group=G1,
 cls="Silver salt of a sulfonamide",
 moa=["Silver ions bind bacterial DNA and cell membranes; sulfadiazine adds antibacterial action — broad spectrum including Pseudomonas and Candida"],
 uses=["Burns (partial-thickness) — prevents infection", "Infected leg ulcers and wounds (short term)"],
 dose=["Apply 1–3 mm layer once or twice daily with sterile technique"],
 ae=["Transient leucopenia (in burns), argyria with prolonged large-area use, pseudoeschar, skin staining",
     "Sulfonamide hypersensitivity; haemolysis in G6PD deficiency; kernicterus (neonates)"],
 ci=["Sulfonamide allergy; pregnancy at term, newborns under 2 months; G6PD deficiency (large areas)"],
 preg="Avoid near term.",
 viva=["Burn wound antimicrobial; leucopenia; avoid in newborns and late pregnancy"],
 src=f"{K} ch.18 and ch.32 (Wound care products); {W} ch.54"),

dict(name="Gentian violet (crystal violet) 0.5–1%", group=G1,
 cls="Triphenylmethane (aniline) dye; antiseptic",
 moa=["Binds microbial DNA and disrupts cell walls → active against Gram-positive bacteria (including MRSA) and Candida; also anti-angiogenic"],
 uses=["Intertrigo, candidiasis (oral thrush — 0.5%), weeping eczema, chronic paronychia, MRSA colonised wounds, tinea pedis maceration"],
 dose=["Paint once or twice daily for a few days (0.5–1% aqueous)"],
 ae=["Purple staining of skin and clothes; irritation, ulceration on mucosa with strong solutions; contact dermatitis",
     "Tattooing if applied to granulation tissue; possible carcinogenicity in animals (restricted in some countries)"],
 ci=["Ulcerated or granulating areas; mucosa with high concentrations"],
 preg="Small areas acceptable.",
 viva=["Antiseptic dye — Gram-positive and Candida; stains purple"],
 src=f"{K} ch.30 (Eusol/Gentian violet)"),

dict(name="Povidone-iodine (5–10%)", group=G1,
 cls="Iodophor (iodine complexed with polyvinylpyrrolidone)",
 moa=["Slowly releases free iodine → oxidises microbial proteins and nucleic acids → broad-spectrum killing of bacteria, fungi, viruses, spores"],
 uses=["Skin antisepsis before procedures, wound cleansing, infected ulcers, mouth gargle, vaginal antisepsis"],
 dose=["10% solution/5% scrub; allow 2 min contact and to dry; ointment once or twice daily on wounds"],
 ae=["Irritant dermatitis (especially under occlusion), allergic contact dermatitis (rare), skin staining",
     "Systemic iodine absorption from large wounds/neonates → hypothyroidism, metabolic acidosis, renal toxicity"],
 ci=["Iodine allergy; thyroid disease (large areas); neonates and pregnancy (prolonged/large-area use)"],
 preg="Avoid prolonged or large-area use (fetal/neonatal hypothyroidism).",
 viva=["Needs contact time and drying; caution in neonates (hypothyroidism)"],
 src=f"{K} ch.30 (Povidone iodine); {W} ch.54"),

dict(name="Chlorhexidine (0.5–4%)", group=G1,
 cls="Bisbiguanide antiseptic",
 moa=["Cationic molecule binds and disrupts bacterial membranes; residual (persistent) activity on skin for hours"],
 uses=["Pre-operative skin preparation (with alcohol — preferred), hand hygiene, body washes for MRSA decolonisation and recurrent furunculosis, mouthwash (0.12–0.2%), umbilical cord care (7.1% gel)"],
 dose=["Body wash 4% daily for 5 days (with nasal mupirocin) for recurrent boils"],
 ae=["Irritation, contact dermatitis, contact urticaria and anaphylaxis (an increasingly recognised allergen)",
     "Ototoxicity if it enters the middle ear; keratitis (eyes); tooth staining (mouthwash)"],
 ci=["Eyes, ears (perforated drum), meninges"],
 preg="Safe.",
 viva=["Persistent activity — preferred pre-op antisepsis with alcohol",
       "Can cause anaphylaxis (chlorhexidine-coated catheters)"],
 src=f"{K} ch.30 (Chlorhexidine)"),

dict(name="Cetrimide", group=G1,
 cls="Quaternary ammonium cationic detergent antiseptic",
 moa=["Disrupts microbial membranes; detergent cleansing action (removes crusts and debris)"],
 uses=["Wound cleansing (often with chlorhexidine — e.g. Savlon), seborrhoeic dermatitis/dandruff shampoos, cleansing crusted lesions"],
 dose=["0.5–1% solution for cleansing; rinse off"],
 ae=["Irritation and burns with strong solutions; contact dermatitis"],
 ci=["Eyes and body cavities (strong solutions)"],
 preg="Safe for cleansing.",
 viva=["Cationic detergent — inactivated by soap (anionic)"],
 src=f"{K} ch.30 (Cetrimide)"),

dict(name="Hydrogen peroxide (1.5–6%)", group=G1,
 cls="Oxidising antiseptic",
 moa=["Releases oxygen on contact with tissue catalase → effervescence loosens debris; weak antibacterial (especially anaerobes)"],
 uses=["Cleansing of dirty wounds and crusts, ear wax; 40% solution for seborrhoeic keratoses (approved USA); cream 1% for impetigo (Europe)"],
 dose=["3% for cleansing (diluted); short contact"],
 ae=["Delays healing (toxic to fibroblasts) with repeated use; gas embolism if used in closed cavities under pressure; bleaching of hair and skin (transient white blanching)"],
 ci=["Closed body cavities, deep wounds under pressure"],
 preg="Safe.",
 viva=["Effervescence from catalase; harmful to granulation tissue with repeated use"],
 src=f"{K} ch.30 (Hydrogen peroxide)"),

dict(name="Acriflavine", group=G1,
 cls="Acridine dye antiseptic (yellow)",
 moa=["Intercalates DNA of bacteria — bacteriostatic against Gram-positive organisms"],
 uses=["Infected wounds, burns dressings (acriflavine emulsion/gauze), minor skin infections (largely historical)"],
 dose=["0.1% solution or emulsion on dressings"],
 ae=["Yellow staining, photosensitivity, contact dermatitis, delays healing"],
 ci=["Hypersensitivity"],
 preg="Minimal data.",
 viva=["Yellow acridine dye — historical wound antiseptic"],
 src=f"{K} ch.30 (Acriflavine)"),

dict(name="Hypochlorite solutions: EUSOL & Dakin's solution", group=G1,
 cls="Chlorine-releasing antiseptics (EUSOL = Edinburgh University Solution of Lime: chlorinated lime + boric acid; Dakin's = sodium hypochlorite 0.25–0.5%)",
 moa=["Release hypochlorous acid → oxidises proteins → kills bacteria, fungi, viruses; dissolves necrotic tissue (chemical debridement)"],
 uses=["Sloughy, infected, malodorous ulcers and wounds (short courses)",
       "Dilute bleach baths (0.005%) for atopic dermatitis with recurrent staphylococcal infection"],
 dose=["Soaked gauze changed once or twice daily for a few days; bleach bath: ½ cup 6% bleach in a full tub, 10 min, twice weekly"],
 ae=["Toxic to fibroblasts and granulation tissue — delays healing with prolonged use; irritation, pain"],
 ci=["Clean granulating wounds"],
 preg="Safe.",
 viva=["Chemical debridement of sloughy ulcers; stop once clean",
       "Dilute bleach baths in atopic dermatitis"],
 src=f"{K} ch.30 (EUSOL, 1% sodium hypochlorite — Dakin's solution) and ch.32"),

dict(name="Potassium permanganate (KMnO₄) 1:10,000", group=G1,
 cls="Oxidising agent; antiseptic and astringent",
 moa=["Releases oxygen → oxidises organic matter; antibacterial and antifungal; astringent (dries weeping lesions)"],
 uses=["Wet compresses and soaks for weeping/oozing dermatoses: acute eczema, pemphigus erosions, infected eczema, tinea pedis maceration, leg ulcers, bullous disorders",
       "Potassium permanganate baths"],
 dose=["1:10,000 solution (pale pink) — dissolve crystals fully; soak or compress for 10–15 min, once or twice daily for a few days"],
 ae=["Brown staining of skin and nails; burns and corrosive injury with concentrated solution or undissolved crystals; dryness",
     "Ingestion is toxic"],
 ci=["Concentrated solutions; mucosa"],
 preg="Safe.",
 viva=["1:10,000 pale pink solution — astringent for weeping lesions",
       "Undissolved crystals cause burns"],
 src=f"{K} ch.30 and ch.33 (Potassium permanganate bath)"),

dict(name="Silver nitrate (0.5% compress; 75% caustic stick)", group=G1,
 cls="Silver salt — antiseptic, astringent, caustic",
 moa=["Silver ions precipitate proteins → antiseptic and astringent at low concentration, caustic (chemical cautery) at high concentration"],
 uses=["Stick: haemostasis after shave/punch biopsy, excess granulation tissue (hypergranulation), pyogenic granuloma (small), umbilical granuloma, warts (adjunct)",
       "0.5% solution: wet dressings for burns and weeping lesions; ophthalmia neonatorum prophylaxis (historic, 1%)"],
 dose=["Touch the moistened stick to the area for a few seconds; protect surrounding skin"],
 ae=["Black/brown staining of skin (silver deposition), local pain, argyria with chronic use; hyponatraemia with large-area wet dressings"],
 ci=["Large areas; eyes (stick)"],
 preg="Safe.",
 viva=["Chemical haemostasis and hypergranulation; black staining"],
 src=f"{K} ch.30 (Silver nitrate) and ch.13 (Topical haemostatic agents)"),

dict(name="Burow's solution (aluminium acetate)", group=G1,
 cls="Astringent solution (aluminium subacetate/acetate, usually diluted 1:20–1:40)",
 moa=["Aluminium salts precipitate proteins → astringent (shrinks and dries weeping skin), mildly antibacterial; evaporation cools"],
 uses=["Wet compresses for acute weeping eczema, contact dermatitis (poison ivy), pompholyx, infected eczema, otitis externa",
       "Soaks for bullous and erosive lesions"],
 dose=["Dilute 1:20 to 1:40; apply compresses for 15–20 min 2–4 times daily for 2–3 days"],
 ae=["Over-drying with prolonged use; irritation"],
 ci=["Prolonged use on dry skin"],
 preg="Safe.",
 viva=["Wet compress for weeping dermatitis — 'if it's wet, dry it'"],
 src=f"{K} ch.30 (Burow's solution — aluminium subacetate solution)"),

# ---------------- TOPICAL ANTIFUNGALS ----------------
dict(name="Other topical azoles: econazole, sulconazole, bifonazole", group=G2,
 cls="Imidazole antifungals (topical)",
 moa=["Inhibit 14-α-demethylase → ergosterol depletion; econazole and sulconazole also antibacterial (Gram-positives)",
      "Bifonazole also inhibits HMG-CoA reductase — stays in skin long enough for once-daily use"],
 uses=["Tinea corporis, cruris, pedis; cutaneous candidiasis; pityriasis versicolor; erythrasma (econazole)",
       "Bifonazole 1% with 40% urea: onychomycosis (nail avulsion kit)"],
 dose=["Econazole 1% once or twice daily; sulconazole 1% once or twice daily; bifonazole 1% once daily — 2–4 weeks"],
 ae=["Burning, itching, contact dermatitis (imidazoles cross-react)"],
 ci=["Imidazole allergy"],
 preg="Minimal absorption; acceptable.",
 viva=["Bifonazole — once daily, long skin retention",
       "Econazole — also antibacterial (useful in infected toe webs)"],
 src=f"{K} ch.19; {W} ch.42"),

dict(name="Butenafine & naftifine", group=G2,
 cls="Benzylamine (butenafine) and allylamine (naftifine) antifungals",
 moa=["Inhibit squalene epoxidase → fungicidal against dermatophytes; anti-inflammatory (naftifine)"],
 uses=["Tinea pedis, corporis, cruris; pityriasis versicolor (butenafine)"],
 dose=["Butenafine 1% once daily for 2 weeks (corporis/cruris) or 4 weeks (pedis); naftifine 1–2% once daily for 2–4 weeks"],
 ae=["Burning, irritation, contact dermatitis (rare)"],
 ci=["Hypersensitivity"],
 preg="Acceptable.",
 viva=["Same target as terbinafine (squalene epoxidase) — fungicidal"],
 src=f"{K} ch.19; {W} ch.42"),

dict(name="Tolnaftate", group=G2,
 cls="Thiocarbamate antifungal",
 moa=["Inhibits squalene epoxidase (dermatophytes); inactive against Candida"],
 uses=["Tinea pedis, corporis, cruris, versicolor; prevention of tinea pedis (powder)"],
 dose=["1% cream/powder twice daily for 2–6 weeks"],
 ae=["Mild irritation"],
 ci=["Nail and scalp infections (ineffective)"],
 preg="Safe.",
 viva=["Inactive against Candida — wrong choice for intertrigo"],
 src=f"{K} ch.19; {W} ch.42"),

dict(name="Nystatin", group=G2,
 cls="Polyene antifungal (from Streptomyces noursei)",
 moa=["Binds ergosterol → membrane pores → leakage (fungicidal); not absorbed from gut or skin"],
 uses=["Candidiasis only: oral thrush (suspension), intertrigo, napkin candidiasis, candidal paronychia, vaginal candidiasis",
       "Combined with steroids/antibiotics in some creams"],
 dose=["Cream/ointment 100,000 U/g two to three times daily; oral suspension 100,000 U/mL, 1–4 mL four times daily (swish and swallow)"],
 ae=["Very safe; irritation, GI upset with large oral doses"],
 ci=["Dermatophyte infections (ineffective)"],
 preg="Safe (not absorbed).",
 viva=["Polyene — Candida only, not dermatophytes; not absorbed orally"],
 src=f"{K} ch.19; {W} ch.42"),

dict(name="Whitfield's ointment", group=G2,
 cls="Compound benzoic acid ointment (benzoic acid 6% + salicylic acid 3% in emulsifying base)",
 moa=["Benzoic acid: fungistatic; salicylic acid: keratolytic → sheds infected scale"],
 uses=["Tinea pedis (moccasin type), tinea corporis, tinea manuum, pityriasis versicolor — cheap, traditional ('half-strength' for children)"],
 dose=["Twice daily for several weeks (until 2 weeks after clearance)"],
 ae=["Irritation, peeling, burning (especially on inflamed/fissured skin)"],
 ci=["Acute inflamed skin, face, flexures (too irritating), large areas in children"],
 preg="Safe (small areas).",
 viva=["Benzoic 6% + salicylic 3% — classic traditional antifungal"],
 src=f"{K} ch.19 (Traditional antifungal remedies)"),

dict(name="Castellani's paint (carbol-fuchsin paint)", group=G2,
 cls="Magenta dye (basic fuchsin) + phenol + resorcinol + boric acid in acetone/alcohol",
 moa=["Antifungal, antibacterial, drying and mildly keratolytic"],
 uses=["Intertrigo, interdigital tinea pedis and candidiasis, weeping toe webs, chronic paronychia, napkin dermatitis (colourless versions)"],
 dose=["Paint once or twice daily; let dry"],
 ae=["Red-purple staining (colourless variant available), irritation; phenol toxicity if used on large areas in infants"],
 ci=["Large areas, infants (phenol absorption)"],
 preg="Small areas acceptable.",
 viva=["Traditional drying antifungal paint for macerated toe webs"],
 src=f"{K} ch.19 (Traditional antifungal remedies — Castellani's paint)"),

dict(name="Undecylenic acid", group=G2,
 cls="Unsaturated fatty acid antifungal (with zinc undecylenate)",
 moa=["Fungistatic — disrupts fungal membranes and morphogenesis (yeast-to-hyphae)"],
 uses=["Tinea pedis, tinea cruris (powders/creams), diaper candidiasis (weak)"],
 dose=["Twice daily for 2–4 weeks"],
 ae=["Irritation, rancid odour"],
 ci=["Hypersensitivity"],
 preg="Safe.",
 viva=["Fatty acid antifungal; weak, mainly OTC foot powders"],
 src=f"{K} ch.19 (Traditional antifungal remedies)"),

# ---------------- WART & ANTIVIRAL AGENTS ----------------
dict(name="Podophyllin & podophyllotoxin", group=G3,
 cls="Antimitotic plant resins — podophyllin (crude 10–25% resin in tincture of benzoin) and podophyllotoxin (purified active lignan, 0.5% solution / 0.15% cream)",
 moa=["Bind tubulin → arrest mitosis in metaphase → necrosis of wart tissue"],
 uses=["External anogenital warts (condylomata acuminata) — podophyllotoxin is the patient-applied form; podophyllin is clinic-applied"],
 dose=["Podophyllotoxin 0.5% solution/0.15% cream: twice daily for 3 days, then 4 days off; up to 4 cycles (patient-applied, ≤10 cm², ≤0.5 mL/day)",
       "Podophyllin 20–25%: applied by clinician to warts (≤10 cm², ≤0.5 mL), protect surrounding skin with petroleum jelly, wash off after 1–4 h; weekly"],
 ae=["Local burning, erosion, ulceration",
     "Podophyllin systemic toxicity if large amounts are applied or absorbed: nausea, vomiting, neuropathy, bone marrow suppression, coma, death",
     "Podophyllin causes histological changes that mimic dysplasia (podophyllin effect)"],
 ci=["Pregnancy (teratogenic, fetal death); mucosal (urethral, vaginal, cervical, anal canal) warts; bleeding or large wart areas"],
 preg="Contraindicated — use cryotherapy or TCA instead.",
 viva=["Contraindicated in pregnancy",
       "Podophyllotoxin is safer, patient-applied (3 days on, 4 off)",
       "Wash off podophyllin after 1–4 h"],
 src=f"{K} ch.20 (Podophyllin); {W} ch.43"),

dict(name="Trichloroacetic acid (TCA) — warts & peels", group=G3,
 cls="Caustic organic acid (protein coagulant)",
 moa=["Precipitates and coagulates proteins → chemical cautery; depth of injury depends on concentration (frosting)"],
 uses=["80–90% TCA: anogenital warts (safe in pregnancy), xanthelasma, small seborrhoeic keratoses",
       "CROSS technique (65–100%) for ice-pick acne scars",
       "Chemical peels: 10–20% superficial, 35% medium-depth (often after Jessner's or glycolic) for photoageing, actinic keratoses, pigmentation, scars"],
 dose=["Warts: apply tiny amount with a wooden stick until white frost appears; neutralise excess with talc/bicarbonate; weekly",
       "Peels: degree of frost guides depth (level I patchy, II white with pink, III solid white); does not need neutralisation"],
 ae=["Pain/burning, ulceration if overapplied, scarring",
     "Post-inflammatory hyperpigmentation (dark skin), hypopigmentation, infection, herpes reactivation after peels"],
 ci=["Active infection or herpes at site; keloid tendency, recent isotretinoin (deep peels — relative); unrealistic expectations"],
 preg="Safe for warts in pregnancy (not absorbed).",
 viva=["TCA is safe for warts in pregnancy",
       "Frosting indicates depth; TCA peels are self-neutralising",
       "CROSS technique for ice-pick scars"],
 src=f"{K} ch.20, ch.30 and ch.31 (TCA peels); {W} ch.53 (Chemical peels)"),

dict(name="Cantharidin (0.7%)", group=G3,
 cls="Vesicant terpenoid (from blister beetle, Cantharis vesicatoria)",
 moa=["Activates neutral serine proteases → breaks desmosomal plaques → intraepidermal acantholysis → blister lifts off the lesion; painless at application"],
 uses=["Molluscum contagiosum (0.7% topical solution approved in USA 2023 for age ≥2 years)",
       "Common and periungual warts (with podophyllin and salicylic acid in some formulations)"],
 dose=["Apply a small drop to each lesion in clinic; wash off after 4–6 h (molluscum: 24 h per label for the approved product); repeat every 3 weeks"],
 ae=["Blistering (expected), pain, burning, ring warts (annular recurrence), scarring, pigment change; toxic if ingested"],
 ci=["Face, genitals, mucosa; diabetes/peripheral vascular disease (feet)"],
 preg="Avoid.",
 viva=["Painless at application, blister in 24 h",
       "Ring warts after treatment",
       "Now approved for molluscum"],
 src=f"{K} ch.20 (Cantharidin); {W} ch.43"),

dict(name="Idoxuridine", group=G3,
 cls="Iodinated thymidine analogue (first antiviral drug)",
 moa=["Incorporated into viral (and host) DNA instead of thymidine → faulty DNA → inhibits replication of HSV and VZV; toxic systemically"],
 uses=["Historic: herpes simplex keratitis (eye drops), herpes labialis and zoster (5–40% in DMSO) — replaced by acyclovir"],
 dose=["Historic topical application several times daily"],
 ae=["Irritation, contact dermatitis; systemic toxicity (marrow) — topical only"],
 ci=["Systemic use"],
 preg="Avoid.",
 viva=["First antiviral (1962) — now obsolete"],
 src=f"{K} ch.20 (Idoxuridine)"),

dict(name="Formalin & glutaraldehyde", group=G3,
 cls="Aldehyde antiseptics/fixatives — formaldehyde (formalin 3–10% soaks) and glutaraldehyde (10–20%)",
 moa=["Cross-link proteins → kill virus-infected keratinocytes and dry the skin (anhidrotic and antiviral effects)"],
 uses=["Plantar and mosaic warts (soaks/paints)", "Plantar hyperhidrosis and bromhidrosis (soaks)", "Instrument disinfection (glutaraldehyde 2%)"],
 dose=["Formalin 3–5% foot soak for 10–15 min daily; glutaraldehyde 10% paint twice daily to warts"],
 ae=["Allergic contact dermatitis (formaldehyde is a major allergen), irritation, brown staining (glutaraldehyde), hardening of skin"],
 ci=["Formaldehyde allergy; broken skin"],
 preg="Avoid.",
 viva=["Formaldehyde — common contact allergen (cosmetics, textiles)"],
 src=f"{K} ch.20 and ch.30"),

dict(name="Intralesional vinblastine", group=G3,
 cls="Vinca alkaloid (antimitotic)",
 moa=["Binds tubulin → blocks microtubule assembly → mitotic arrest"],
 uses=["Kaposi sarcoma (localised lesions) — intralesional; warts (rarely)",
       "Systemic: lymphomas, Langerhans cell histiocytosis"],
 dose=["Intralesional 0.1–0.5 mg/mL (0.1 mL per 0.5 cm² lesion) every 2–3 weeks"],
 ae=["Pain at injection site, hyperpigmentation, ulceration; systemic: neuropathy, marrow suppression; extravasation necrosis"],
 ci=["Pregnancy; IV only for systemic use (intrathecal fatal)"],
 preg="Contraindicated.",
 viva=["Intralesional vinblastine for Kaposi sarcoma"],
 src=f"{W} ch.47; {K} (intralesional agents)"),

# ---------------- SCABICIDES & PEDICULICIDES ----------------
dict(name="Benzyl benzoate (25%)", group=G4,
 cls="Ester of benzyl alcohol and benzoic acid; scabicide",
 moa=["Neurotoxic to mites (kills mites; ovicidal partly)"],
 uses=["Scabies (cheap alternative where permethrin is unavailable), pediculosis"],
 dose=["Adults 25% emulsion; dilute to 12.5% for children (and 6% for infants, if used); apply neck down after bath, repeat next day without bathing, wash off 24 h after second application (regimens vary)"],
 ae=["Burning and irritation (common, especially on excoriated skin), irritant dermatitis; conjunctivitis if it reaches eyes"],
 ci=["Infants (irritation, benzyl alcohol toxicity), face and eyes"],
 preg="Has been used; permethrin preferred.",
 viva=["Burning sensation limits use; must be diluted for children"],
 src=f"{K} ch.21 (Benzyl benzoate); {W} ch.44"),

dict(name="Gamma benzene hexachloride (lindane, 1%)", group=G4,
 cls="Organochlorine insecticide",
 moa=["Blocks GABA-gated chloride channels in mite/louse nervous system → hyperexcitation, death; partly ovicidal"],
 uses=["Formerly scabies and lice — now second-line only (banned in many countries; withdrawn in India for human use in 2013)"],
 dose=["Historic: thin layer neck down, wash off after 8 h; single application"],
 ae=["Neurotoxicity: seizures, death (especially infants, elderly, malnourished, broken skin, repeated use); aplastic anaemia (rare); resistance"],
 ci=["Infants, children under 50 kg, elderly, pregnancy, breastfeeding, seizure disorders, crusted scabies, broken skin"],
 preg="Contraindicated.",
 viva=["Neurotoxic — seizures; banned/withdrawn in many countries"],
 src=f"{K} ch.21 (Gamma benzene hexachloride); {W} ch.44"),

dict(name="Crotamiton (10%)", group=G4,
 cls="Scabicide with antipruritic action",
 moa=["Mechanism unclear; weakly scabicidal; antipruritic (blocks TRPV4 itch channel)"],
 uses=["Scabies (second-line, less effective), post-scabetic itch, pruritus of other causes"],
 dose=["Scabies: apply neck down for 2–5 consecutive nights, wash off 48 h after last application"],
 ae=["Irritation, contact dermatitis; low efficacy (frequent failure)"],
 ci=["Raw/weeping skin, mucosa"],
 preg="Limited data; permethrin preferred.",
 viva=["Weak scabicide but good antipruritic — post-scabetic itch"],
 src=f"{K} ch.21 (Crotamiton); {W} ch.44"),

dict(name="Precipitated sulphur (5–10%)", group=G4,
 cls="Elemental sulphur in petrolatum (scabicide); also keratolytic and antimicrobial",
 moa=["Converted to hydrogen sulphide/pentathionic acid on skin → toxic to mites, fungi and bacteria; keratolytic"],
 uses=["Scabies in infants under 2 months and pregnancy (safe, cheap)",
       "Acne, rosacea, seborrhoeic dermatitis, pityriasis versicolor (with salicylic acid)"],
 dose=["Scabies: 5–10% ointment nightly for 3 nights (wash off before next application), repeat after a week"],
 ae=["Messy, malodorous, staining; irritant dermatitis with prolonged use"],
 ci=["Sulphur sensitivity"],
 preg="Safe — option in pregnancy and infancy.",
 viva=["Safest scabicide in infants and pregnancy (but messy)"],
 src=f"{K} ch.21 (Precipitated sulfur); {W} ch.44"),

dict(name="Malathion (0.5%)", group=G4,
 cls="Organophosphate (cholinesterase inhibitor) pediculicide",
 moa=["Irreversibly inhibits acetylcholinesterase in lice → paralysis; ovicidal; residual activity on hair"],
 uses=["Head lice resistant to permethrin (age ≥6 years); pubic lice; scabies (aqueous lotion, some countries)"],
 dose=["Apply 0.5% lotion to dry hair, leave 8–12 h, then wash; repeat after 7–9 days if lice still present"],
 ae=["Scalp irritation; alcohol-based lotion is flammable (no hairdryers/smoking); ingestion → cholinergic toxicity"],
 ci=["Children under 6 (USA label), neonates; flammable"],
 preg="Limited data.",
 viva=["Organophosphate — ovicidal; flammable lotion"],
 src=f"{K} ch.21 (Topical ivermectin/malathion); {W} ch.44"),

# ---------------- TOPICAL IMMUNOMODULATORS & ANTIPSORIATICS ----------------
dict(name="Pimecrolimus 1% cream", group=G5,
 cls="Topical calcineurin inhibitor (ascomycin macrolactam)",
 moa=["Binds macrophilin-12 (FKBP-12); complex inhibits calcineurin → blocks NFAT → reduces T-cell cytokines and mast cell mediator release",
      "More lipophilic and lower systemic absorption than tacrolimus; weaker effect (similar to low-potency steroid)"],
 uses=["Mild–moderate atopic dermatitis (≥2 years; approved) — face, eyelids, flexures",
       "Seborrhoeic dermatitis, vitiligo (face), intertriginous psoriasis, perioral dermatitis, steroid rosacea"],
 dose=["Twice daily; maintenance twice weekly"],
 ae=["Application-site burning/warmth (less than tacrolimus), skin infections (herpes, molluscum), alcohol flushing",
     "FDA boxed warning (theoretical malignancy) as for tacrolimus"],
 ci=["Under 2 years (label), immunosuppression, Netherton syndrome, active infection at site"],
 preg="Minimal absorption; limited areas acceptable.",
 viva=["Cream (pimecrolimus) vs ointment (tacrolimus); pimecrolimus is weaker and for mild disease"],
 src=f"{W} ch.48; {K} ch.23"),

dict(name="Contact sensitisers: DPCP, DNCB, SADBE", group=G5,
 cls="Topical immunotherapy with strong contact allergens — diphenylcyclopropenone (DPCP), dinitrochlorobenzene (DNCB), squaric acid dibutyl ester (SADBE)",
 moa=["Induce allergic contact dermatitis (type IV) at the site → 'antigenic competition': recruits suppressor T cells and cytokines that disrupt the autoimmune attack on hair follicles or the immune evasion of HPV",
      "DNCB is mutagenic (Ames test) — largely abandoned; DPCP and SADBE are preferred"],
 uses=["Extensive or chronic alopecia areata (DPCP — the most studied; response 30–60%)",
       "Recalcitrant viral warts, multiple warts in children (SADBE/DPCP)"],
 dose=["Sensitise with 2% DPCP to a small area (arm/scalp patch); after 2 weeks apply weekly starting at 0.001%, increasing concentration until a mild eczematous reaction (itch and erythema lasting 24–36 h) is achieved; leave 48 h, shield from light (DPCP is light-degraded)",
       "Regrowth after 8–12 weeks; continue for at least 6 months before calling failure",
       "Wear gloves; store in amber bottles"],
 ae=["Severe eczema, blistering, regional lymphadenopathy",
     "Pigmentary changes — dyschromia in confetti pattern, vitiligo (especially dark skin)",
     "Urticaria, erythema multiforme-like reactions; sensitisation of staff (gloves)"],
 ci=["Pregnancy and women planning pregnancy; DNCB (mutagenic) — not recommended"],
 preg="Contraindicated (DPCP not studied; DNCB mutagenic).",
 viva=["Antigenic competition mechanism",
       "DNCB mutagenic → DPCP preferred",
       "Shield DPCP from light; titrate to mild dermatitis"],
 src=f"{K} ch.23 (DNCB, DPCP, SADBE); {W} ch.57"),

dict(name="Topical vitamin D analogues: calcipotriol, tacalcitol, calcitriol", group=G5,
 cls="Vitamin D3 analogues for topical use",
 moa=["Bind the vitamin D receptor (VDR) → inhibit keratinocyte proliferation, promote normal differentiation; reduce Th17 cytokines (IL-17, IL-8)",
      "Do not cause skin atrophy"],
 uses=["Chronic plaque psoriasis (first-line, especially with steroid: calcipotriol + betamethasone dipropionate gel/ointment/foam), scalp psoriasis, nail psoriasis",
       "Off-label: vitiligo (with phototherapy), morphoea, disorders of keratinisation (ichthyoses, Darier), prurigo nodularis, seborrhoeic keratoses"],
 dose=["Calcipotriol 0.005% twice daily (maximum 100 g/week adults; 50 g/week for children 6–12, 75 g/week for 12+)",
       "Tacalcitol 4 µg/g once daily; calcitriol 3 µg/g twice daily (less irritating — face/flexures)",
       "Calcipotriol + betamethasone once daily for 4 weeks, then as needed/twice weekly"],
 ae=["Local irritation (lesional and perilesional), especially on face and flexures (calcipotriol)",
     "Hypercalcaemia and hypercalciuria if maximum weekly dose is exceeded or in renal disease",
     "Photosensitivity is not typical, but UVA degrades calcipotriol — apply after phototherapy, not before"],
 ci=["Disorders of calcium metabolism, severe renal/hepatic disease, generalised pustular/erythrodermic psoriasis (large areas)"],
 ix=["Salicylic acid inactivates calcipotriol — do not mix",
     "Thiazides/calcium supplements: hypercalcaemia risk"],
 mon=["Serum calcium if near maximum dose or with renal disease"],
 preg="Limited data — use small areas if needed.",
 viva=["Calcipotriol maximum 100 g/week",
       "Inactivated by salicylic acid and UVA",
       "Combination with betamethasone improves efficacy and reduces irritation"],
 src=f"{W} ch.49 (Topical vitamin D3); {K} ch.23 (Topical calcipotriol)"),

dict(name="Dithranol (anthralin)", group=G5,
 cls="Synthetic anthrone (derived from chrysarobin of Goa powder)",
 moa=["Generates free radicals (oxidation) → inhibits keratinocyte proliferation and mitochondrial function; also reduces neutrophil and T-cell activity"],
 uses=["Chronic plaque psoriasis (thick, stable plaques; especially in children or when steroids should be avoided) — inpatient Ingram regimen (with tar baths and UVB) or outpatient short-contact therapy",
       "Alopecia areata (irritant therapy — off-label)"],
 dose=["Short-contact therapy: start 0.1–0.5% for 10–30 min daily, increase to 1–3% as tolerated, then wash off",
       "Ingram regimen: tar bath → UVB → dithranol in Lassar's paste (with salicylic acid to stabilise) overnight",
       "Apply to plaques only; protect surrounding skin with petroleum jelly"],
 ae=["Irritation and burning of surrounding normal skin ('dithranol burn')",
     "Purple-brown staining of skin, nails, hair, clothes, bathtubs (oxidation products) — skin staining fades in 1–2 weeks",
     "Perilesional pigmentation as a sign of clearing"],
 ci=["Acute, erythrodermic, pustular or unstable psoriasis; face, flexures, genitals"],
 preg="Considered safe (not mutagenic in humans).",
 viva=["Short-contact therapy reduces staining and irritation",
       "Ingram regimen",
       "Salicylic acid stabilises dithranol (prevents oxidation)"],
 src=f"{K} ch.28 (Anthralin — dithranol, dithranol pomade); {W} ch.57"),

dict(name="Coal tar (crude coal tar, LCD)", group=G5,
 cls="Distillation product of coal (crude coal tar 1–5%; liquor carbonis detergens 5–20%)",
 moa=["Aryl hydrocarbon receptor agonist → normalises keratinocyte differentiation (restores filaggrin), antiproliferative, anti-inflammatory, antipruritic; photosensitises to UVA"],
 uses=["Chronic plaque and scalp psoriasis, palmoplantar psoriasis, atopic dermatitis (lichenified), lichen simplex, seborrhoeic dermatitis",
       "Goeckerman regimen (crude coal tar + UVB, inpatient)",
       "Tar baths (Ingram regimen)"],
 dose=["Crude coal tar 1–5% in petrolatum or zinc paste; LCD 5–20% in creams, shampoos and bath additives; apply at night"],
 ae=["Smell, staining, folliculitis (tar acne), irritant dermatitis, phototoxicity ('tar smarts'), keratoacanthomas/carcinogenicity (occupational, theoretical with therapy)"],
 ci=["Erythrodermic/pustular psoriasis, infected skin, pregnancy (relative)"],
 preg="Avoid (theoretical carcinogenicity).",
 viva=["AhR ligand; Goeckerman regimen (tar + UVB)",
       "Tar folliculitis and phototoxicity"],
 src=f"{K} ch.28 (Coal tar); {W} ch.57"),

# ---------------- PIGMENTARY & COSMECEUTICAL ----------------
dict(name="Monobenzone (monobenzyl ether of hydroquinone, 20%)", group=G6,
 cls="Melanocytotoxic depigmenting agent",
 moa=["Converted by tyrosinase to reactive quinones → haptens that trigger an immune (melanocyte-specific) response → permanent destruction of melanocytes, even at distant sites"],
 uses=["Permanent depigmentation of remaining normal skin in extensive (universal) vitiligo (>50–80% body surface)",
       "Never for melasma or cosmetic lightening"],
 dose=["20% cream once or twice daily to remaining pigmented areas; depigmentation over 4–12 months"],
 ae=["Irritant/allergic dermatitis, distant depigmentation (unintended), repigmentation in sun-exposed areas, permanent sun sensitivity",
     "Psychological impact — counsel carefully (irreversible)"],
 ci=["Melasma, freckles, PIH (causes irreversible confetti depigmentation), children"],
 preg="Avoid.",
 viva=["Only for universal vitiligo — permanent",
       "Different from hydroquinone (which is reversible)"],
 src=f"{K} ch.26 (Monobenzyl ether of hydroquinone); {W} ch.57"),

dict(name="Licorice extract (glabridin, liquiritin)", group=G6,
 cls="Botanical cosmeceutical (Glycyrrhiza glabra)",
 moa=["Glabridin inhibits tyrosinase and is anti-inflammatory; liquiritin disperses melanin"],
 uses=["Melasma, PIH, sensitive skin/rosacea (anti-inflammatory) — cosmeceutical creams"],
 dose=["Creams with licorice extract once or twice daily"],
 ae=["Rare irritation"],
 ci=["Allergy"],
 preg="Topical acceptable.",
 viva=["Glabridin — tyrosinase inhibitor; liquiritin — melanin dispersion"],
 src=f"{K} ch.26 and ch.29 (Cosmeceuticals)"),

# ---------------- MISCELLANEOUS TOPICALS & WOUND CARE ----------------
dict(name="Eflornithine 13.9% cream", group=G7,
 cls="Ornithine decarboxylase inhibitor",
 moa=["Irreversibly inhibits ornithine decarboxylase in hair follicle cells → slows hair growth (does not remove hair)"],
 uses=["Facial hirsutism in women (with laser or other hair removal)",
       "Systemic eflornithine: African trypanosomiasis"],
 dose=["Twice daily (at least 8 h apart); effect in 6–8 weeks; hair regrows within 8 weeks of stopping"],
 ae=["Acne, pseudofolliculitis, burning, stinging"],
 ci=["Under 12 years"],
 preg="Limited data — avoid.",
 viva=["ODC inhibitor; slows facial hair growth; combine with laser"],
 src=f"{K} ch.28 (Eflornithine); {W} ch.57"),

dict(name="Aluminium chloride hexahydrate (15–25%)", group=G7,
 cls="Antiperspirant metal salt",
 moa=["Forms aluminium hydroxide plugs in eccrine ducts → obstructs sweat outflow; long-term atrophy of secretory cells"],
 uses=["Focal hyperhidrosis — axillary (first-line), palmoplantar; bromhidrosis; haemostasis after biopsy (20–35% solution)"],
 dose=["Apply to completely dry skin at night (6–8 h), wash off in morning; nightly until controlled, then once or twice weekly"],
 ae=["Irritation, stinging, itching (apply on dry skin; use hydrocortisone if needed); staining of clothes"],
 ci=["Broken/shaved skin (wait 24 h after shaving)"],
 preg="Safe.",
 viva=["Apply to dry skin at night — first-line for axillary hyperhidrosis"],
 src=f"{K} ch.28 (Antiperspirants); {W} ch.57"),

dict(name="Topical 5-fluorouracil (5%, 0.5%)", merge_into="5-Fluorouracil (5-FU) injection", form_label="Topical form", group=G7,
 cls="Topical antimetabolite (5% cream; 0.5% cream; 4% cream)",
 moa=["Thymidylate synthase inhibition in rapidly proliferating dysplastic cells"],
 uses=["Actinic keratoses (field therapy), Bowen disease, superficial BCC (5%), warts (off-label, under occlusion), vitiligo (after dermabrasion — off-label), disseminated superficial actinic porokeratosis"],
 dose=["AK: 5% twice daily for 2–4 weeks (or 0.5% once daily); sBCC/Bowen: twice daily for 3–6 weeks"],
 ae=["Intense inflammation, erosion and crusting (expected), photosensitivity, pigmentary change; toxicity in DPD deficiency (rare)"],
 ci=["Pregnancy; DPD deficiency"],
 preg="Contraindicated.",
 viva=["Field therapy for AK; inflammation is expected; combine with calcipotriol for better effect"],
 src=f"{K} ch.28; {W} ch.47"),

dict(name="Topical niacinamide (2–5%)", merge_into="Nicotinamide (niacinamide, oral)", form_label="Topical form", group=G7,
 cls="Topical vitamin B3 (cosmeceutical/therapeutic)",
 moa=["Inhibits melanosome transfer, improves barrier (ceramide synthesis), reduces sebum and inflammation"],
 uses=["Acne (4% gel), rosacea, melasma/PIH (adjunct), atopic dermatitis barrier, photoageing"],
 dose=["Once or twice daily"],
 ae=["Mild irritation (rare)"],
 ci=["Hypersensitivity"],
 preg="Safe.",
 viva=["Blocks melanosome transfer (not tyrosinase)"],
 src=f"{K} ch.28 (Topical vitamin B3 — niacinamide)"),

dict(name="Topical zinc (zinc oxide, zinc sulfate)", merge_into="Zinc acetate (oral zinc)", form_label="Topical form", group=G7,
 cls="Topical zinc salts",
 moa=["Zinc oxide: physical barrier/sunscreen, astringent, mildly antiseptic; zinc sulfate: astringent, antiviral, anti-inflammatory"],
 uses=["Zinc oxide pastes: napkin dermatitis, intertrigo, protective barrier around ulcers/stomas; inorganic sunscreen",
       "Zinc sulfate 10–20% solution/lotion: warts (topical), herpes, acne, leishmaniasis (IL 2%) — limited evidence",
       "Zinc pyrithione: dandruff (separate post)"],
 dose=["Paste/ointment as needed; zinc sulfate solution 2–3 times daily"],
 ae=["Minimal; whitish cast"],
 ci=["Hypersensitivity"],
 preg="Safe.",
 viva=["Zinc oxide — barrier and broad-spectrum physical sunscreen"],
 src=f"{K} ch.24 (Topical zinc) and ch.28"),

dict(name="Topical hormones: testosterone & oestrogen", group=G7,
 cls="Topical sex steroids",
 moa=["Testosterone: stimulates collagen and epidermal growth in genital skin",
      "Oestrogen: increases epidermal thickness, collagen and hydration in oestrogen-deficient skin and mucosa"],
 uses=["Testosterone 2% ointment: lichen sclerosus (historical — inferior to clobetasol; no longer recommended)",
       "Oestrogen: atrophic vaginitis/vulvovaginal atrophy, labial adhesions in girls; photoaged skin in post-menopausal women (cosmeceutical, limited)"],
 dose=["Vaginal oestrogen cream as per gynaecological regimen"],
 ae=["Testosterone: virilisation (clitoral enlargement, hirsutism); oestrogen: breast tenderness, bleeding, systemic absorption"],
 ci=["Hormone-dependent cancers, pregnancy"],
 preg="Contraindicated.",
 viva=["Topical testosterone for lichen sclerosus is obsolete — clobetasol is first-line"],
 src=f"{K} ch.28 (Topical testosterone, oestrogen); {W} ch.45"),

dict(name="Dexpanthenol (provitamin B5)", group=G7,
 cls="Pantothenic acid precursor (topical)",
 moa=["Converted to pantothenic acid (part of coenzyme A) → supports epidermal regeneration and barrier lipid synthesis; humectant and anti-inflammatory"],
 uses=["Minor wounds, post-laser/peel care, radiation dermatitis, nipple fissures, napkin dermatitis, dry skin, cheilitis with isotretinoin"],
 dose=["5% cream/ointment once or several times daily"],
 ae=["Allergic contact dermatitis (occasional)"],
 ci=["Hypersensitivity"],
 preg="Safe.",
 viva=["Wound-healing moisturiser; occasional contact allergen"],
 src=f"{K} ch.28 (Topical pantothenic acid)"),

dict(name="Topical sucralfate", group=G7,
 cls="Aluminium salt of sucrose octasulfate (cytoprotective)",
 moa=["Forms a protective barrier over erosions, binds growth factors (EGF, bFGF) to the wound and stimulates healing"],
 uses=["Erosions and ulcers: oral and genital ulcers (Behçet), radiation dermatitis, perianal and peristomal dermatitis, diaper dermatitis, burns, epidermolysis bullosa wounds"],
 dose=["Paste/cream 4–7% or crushed tablet suspension applied 2–3 times daily"],
 ae=["Minimal"],
 ci=["Hypersensitivity"],
 preg="Safe.",
 viva=["Barrier + growth factor binding → wound healing"],
 src=f"{K} ch.28 (Sucralfate); {W} ch.54"),

dict(name="Growth factors (becaplermin, EGF)", group=G7,
 cls="Recombinant growth factors for wound healing — becaplermin (PDGF-BB) gel 0.01%, epidermal growth factor (rhEGF)",
 moa=["Stimulate chemotaxis and proliferation of fibroblasts, endothelial cells and keratinocytes → granulation tissue and re-epithelialisation"],
 uses=["Diabetic neuropathic foot ulcers (becaplermin — approved), pressure ulcers, chronic non-healing wounds (rhEGF — available in India)"],
 dose=["Becaplermin: amount calculated by ulcer size, once daily, covered with moist saline dressing; continue with offloading and debridement"],
 ae=["Local rash; possible increased cancer mortality with ≥3 tubes of becaplermin (boxed warning later removed)"],
 ci=["Malignancy at the application site; infected or ischaemic wounds"],
 preg="Avoid.",
 viva=["PDGF-BB gel for diabetic foot ulcers — only with good wound care and offloading"],
 src=f"{K} ch.32 (Growth factor preparations); {W} ch.54"),

dict(name="Wound dressings (films, hydrocolloids, hydrogels, alginates, foams)", group=G7,
 cls="Modern moist wound-healing dressings",
 moa=["Maintain a moist wound environment → faster epithelialisation, autolytic debridement, less pain; choice depends on exudate amount and wound depth"],
 uses=["Films (polyurethane, semi-permeable): clean superficial wounds, donor sites, IV sites — no absorption",
       "Hydrocolloids: light–moderate exudate, autolytic debridement of sloughy wounds, pressure ulcers (occlusive; not for infected wounds)",
       "Hydrogels: dry/necrotic wounds — donate moisture, rehydrate eschar; burns, radiation dermatitis",
       "Alginates (calcium alginate from seaweed): heavily exuding and bleeding wounds (haemostatic, forms gel); cavities",
       "Foams: moderate–heavy exudate, around tubes, under compression",
       "Others: silver/iodine antimicrobial dressings, honey, activated charcoal (odour), paraffin tulle (non-adherent), skin substitutes (Apligraf), negative pressure wound therapy"],
 dose=["Change according to exudate (hydrocolloids every 3–7 days; alginates/foams when saturated)"],
 ae=["Maceration of surrounding skin, allergy to adhesives (colophony), hydrocolloid odour/residue mistaken for infection"],
 ci=["Occlusive dressings on infected wounds (hydrocolloids); dry wounds for alginates"],
 preg="Not applicable.",
 viva=["Match the dressing to the exudate: dry → hydrogel; heavy → alginate/foam",
       "Hydrocolloid gel and odour can mimic infection"],
 src=f"{K} ch.32 (Wound care products — films, hydrocolloids, hydrogels, alginates, foams, artificial skin substitutes); {W} ch.54"),

dict(name="Collagenase ointment", group=G7,
 cls="Enzymatic debriding agent (clostridial collagenase from Clostridium histolyticum)",
 moa=["Digests native collagen in necrotic tissue → selective debridement without harming viable tissue"],
 uses=["Debridement of chronic dermal ulcers and severe burns (necrotic/sloughy tissue)",
       "Injectable collagenase: Dupuytren contracture, Peyronie disease (systemic forms)"],
 dose=["Once daily to the wound bed (2 mm layer), covered with moist dressing; stop when wound is clean"],
 ae=["Local erythema, burning"],
 ci=["Hypersensitivity"],
 ix=["Inactivated by silver, iodine, hexachlorophene, heavy metals and acidic solutions"],
 preg="Acceptable.",
 viva=["Selective enzymatic debridement; incompatible with silver/iodine"],
 src=f"{K} ch.32 (Collagenase); {W} ch.54"),

dict(name="Topical phenytoin", group=G7,
 cls="Anticonvulsant used topically for wound healing",
 moa=["Promotes fibroblast proliferation and collagen deposition, granulation tissue formation; reduces bacterial load and inflammation"],
 uses=["Chronic ulcers: diabetic foot ulcers, trophic ulcers of leprosy, venous and pressure ulcers, burns (Indian practice — supporting evidence from small studies)"],
 dose=["Phenytoin powder/suspension sprinkled on the ulcer bed after cleaning, daily, with dressing"],
 ae=["Local burning; systemic absorption from large ulcers (rare toxicity)"],
 ci=["Phenytoin hypersensitivity"],
 preg="Avoid large areas.",
 viva=["Cheap adjunct for trophic ulcers in leprosy"],
 src=f"{K} ch.32 (Phenytoin — wound healing)"),

dict(name="Aminolevulinic acid (ALA) — photodynamic therapy", group=G7,
 cls="Porphyrin precursor photosensitiser (5-ALA 20% solution/10% gel; methyl aminolevulinate 16% cream)",
 moa=["Taken up preferentially by dysplastic/neoplastic and sebaceous cells → converted to protoporphyrin IX",
      "Light activation (blue 417 nm or red 630 nm, daylight) → reactive oxygen species → selective cell death"],
 uses=["Approved: actinic keratoses (blue light/red light/daylight PDT), superficial BCC and Bowen disease (MAL red light, Europe)",
       "Off-label: acne, photoageing, sebaceous hyperplasia, warts, actinic cheilitis, field cancerisation in transplant patients"],
 dose=["Apply under occlusion for 1–3 h (incubation), then illuminate (blue 10 J/cm² or red 37 J/cm²); daylight PDT: 30 min incubation then 2 h daylight"],
 ae=["Pain/burning during illumination (main limitation), erythema, oedema, crusting, pigmentation; photosensitivity for 24–48 h (avoid sun)"],
 ci=["Porphyria, photosensitive disorders, allergy to ALA/MAL (peanut/almond oil in MAL cream)"],
 preg="Avoid.",
 viva=["ALA → protoporphyrin IX → light → ROS",
       "Blue 417 nm (superficial) vs red 630 nm (deeper)",
       "Pain during illumination"],
 src=f"{W} ch.25 (Photodynamic therapy); {K} (Photodynamic therapy — blue and red light)"),

# ---------------- CHEMICAL AGENTS, PEELS & BATHS ----------------
dict(name="Phenol (carbolic acid)", group=G8,
 cls="Aromatic alcohol — antiseptic, anaesthetic, keratocoagulant",
 moa=["Low concentration: antiseptic and topical anaesthetic (antipruritic in calamine with phenol)",
      "88% phenol: keratocoagulation — denatures proteins instantly (paradoxically less penetration than 50%)",
      "Baker–Gordon formula (phenol + croton oil + septisol + water): deep peel"],
 uses=["Chemical matricectomy for ingrown toenails (88% phenol, 3 × 30 s)",
       "Deep chemical peels for severe photoageing and wrinkles (Baker–Gordon — rarely now)",
       "Antipruritic in lotions (0.5–1%); cautery of small lesions"],
 dose=["Matricectomy: tourniquet, apply 88% phenol to matrix with cotton tip for 3 × 30 s, then irrigate with alcohol"],
 ae=["Systemic absorption (deep peels): cardiac arrhythmias — ECG monitoring, IV hydration, treat in segments over 60–90 min; renal and hepatic toxicity",
     "Permanent hypopigmentation ('alabaster' skin) after deep peels, scarring, laryngeal oedema"],
 ci=["Deep peels: cardiac, renal, hepatic disease; dark skin types"],
 preg="Avoid.",
 viva=["Deep phenol peel → arrhythmia (ECG monitoring)",
       "88% phenol for ingrown nail matricectomy"],
 src=f"{K} ch.30 (Phenol — carbolic acid) and ch.31 (Phenol peels); {W} ch.53"),

dict(name="Jessner's solution", group=G8,
 cls="Combination superficial peeling agent: resorcinol 14% + salicylic acid 14% + lactic acid 14% in ethanol",
 moa=["Keratolytic action of all three components → superficial exfoliation; resorcinol also weakens hydrogen bonds of keratin"],
 uses=["Superficial peel for acne, comedones, PIH, melasma, mild photoageing",
       "As a primer before 35% TCA (Monheit medium-depth peel)"],
 dose=["1–3 coats, depending on response (erythema → patchy frosting); no neutralisation needed"],
 ae=["Burning, erythema, peeling; salicylism (large areas); resorcinol — contact allergy, thyroid effects, ochronosis (rare)"],
 ci=["Resorcinol/salicylate allergy, pregnancy (salicylate), active infection"],
 preg="Avoid (salicylate).",
 viva=["Composition: resorcinol + salicylic + lactic acid 14% each",
       "Jessner + TCA 35% = Monheit peel"],
 src=f"{K} ch.31 (Combination peeling agents); {W} ch.53"),

dict(name="Resorcinol", group=G8,
 cls="Phenolic keratolytic, antiseptic and peeling agent",
 moa=["Keratolytic (breaks keratin hydrogen bonds), antibacterial and antifungal"],
 uses=["Acne (2% with sulphur), seborrhoeic dermatitis, component of Jessner's solution and Castellani's paint, Unna's paste (resorcinol paste peel)"],
 dose=["1–2% creams/lotions; 14% in Jessner's"],
 ae=["Contact dermatitis, brown-black discolouration of light hair, exogenous ochronosis; myxoedema with chronic large-area use (antithyroid), methaemoglobinaemia in infants"],
 ci=["Infants, large areas, broken skin"],
 preg="Avoid large areas.",
 viva=["Antithyroid effect with chronic absorption; component of Jessner's solution"],
 src=f"{K} ch.30 (Resorcinol)"),

dict(name="Therapeutic baths (oatmeal, oil, KMnO₄, bleach, tar, PUVA)", group=G8,
 cls="Bath additives used as adjunct therapy",
 moa=["Hydrate and soften scale, remove crusts and exudate, reduce bacterial load, soothe itch; allow treatment of large body surfaces"],
 uses=["Colloidal oatmeal bath: itch of atopic dermatitis, varicella, urticaria (anti-inflammatory avenanthramides)",
       "Oil baths (emollient bath oils): xerosis, ichthyosis, atopic dermatitis (slippery — fall risk)",
       "Potassium permanganate bath (1:10,000): weeping/infected eczema, pemphigus, bullous disorders",
       "Dilute bleach baths: atopic dermatitis with recurrent staphylococcal infections",
       "Tar baths (Ingram regimen), bath PUVA (trioxsalen/8-MOP), salt (Dead Sea) baths for psoriasis",
       "Cleansing baths for erosive and blistering diseases; wax bath (paraffin) for joint stiffness in scleroderma hands"],
 dose=["10–15 min, lukewarm water, followed by emollient within 3 min (soak and seal)"],
 ae=["Over-drying with prolonged hot baths; KMnO₄ staining/burns; slipping in oil baths"],
 ci=["Hot baths in rosacea/urticaria flares (heat aggravates)"],
 preg="Safe.",
 viva=["Soak-and-seal; KMnO₄ 1:10,000; bleach bath in AD; Ingram regimen tar baths"],
 src=f"{K} ch.33 (Baths — cleansing, oatmeal, oil, potassium permanganate, wax bath)"),

dict(name="Dermal fillers (hyaluronic acid and others)", group=G8,
 cls="Injectable soft-tissue fillers — temporary (hyaluronic acid, collagen), semi-permanent/biostimulatory (calcium hydroxylapatite, poly-L-lactic acid), permanent (PMMA, silicone)",
 moa=["Hyaluronic acid (cross-linked, non-animal stabilised): fills volume and binds water; reversible with hyaluronidase",
      "Biostimulators (PLLA, CaHA): stimulate neocollagenesis over months"],
 uses=["Nasolabial folds, lips, cheeks/midface volume loss, tear trough, chin and jawline contouring, acne scars (rolling), HIV facial lipoatrophy (PLLA — approved)"],
 dose=["Volume per region (0.5–2 mL typical); duration: HA 6–18 months, CaHA 12–18 months, PLLA ~2 years"],
 ae=["Bruising, swelling, lumps/nodules, Tyndall effect (blue hue — superficial HA), infection, biofilm, delayed hypersensitivity nodules",
     "Vascular occlusion (most serious): skin necrosis (glabella, nasal tip) and blindness (retinal artery embolism) — emergency high-dose hyaluronidase"],
 ci=["Active infection at site, autoimmune flare, pregnancy, allergy to components (lidocaine), unrealistic expectations"],
 preg="Avoid.",
 viva=["Hyaluronidase dissolves HA fillers — key in vascular occlusion",
       "Danger zones: glabella, nose, nasolabial (angular artery)",
       "Tyndall effect = superficial HA"],
 src=f"{W} ch.59 (Injectable dermal and subcutaneous fillers); {K} ch.34 (Dermal fillers)"),
]
