# More from Khopkar — slot 8: immunosuppressants, retinoids, photoprotection, biologics, antihistamines, vitamins, misc systemic
W = "Wolverton 4e"; K = "Khopkar"
D = [
# ---------------- IMMUNOSUPPRESSANTS / IMMUNOMODULATORS ----------------
dict(name="Antimalarials: hydroxychloroquine, chloroquine, quinacrine", group="More from Khopkar · Immunomodulators",
 cls="4-aminoquinolines (hydroxychloroquine, chloroquine) and acridine (quinacrine/mepacrine)",
 moa=["Weak bases that accumulate in lysosomes and raise their pH → impaired antigen processing and MHC-II presentation",
      "Inhibit endosomal Toll-like receptors (TLR7, TLR9) → less type I interferon (key in lupus)",
      "Absorb UV light, bind melanin, stabilise membranes; mild anti-platelet and lipid/glucose-lowering effects",
      "In porphyria cutanea tarda: form water-soluble complexes with porphyrins in the liver that are excreted in urine"],
 pk=["Well absorbed; huge volume of distribution; very long half-life (40–50 days) → takes 2–3 months to work",
     "Bound to melanin (skin, retina) — basis of retinopathy and pigmentation"],
 uses=["Cutaneous lupus (DLE, SCLE) and SLE (first-line; reduces flares and thrombosis)",
       "Dermatomyositis skin disease, Sjögren, rheumatoid arthritis",
       "Photodermatoses: polymorphous light eruption, solar urticaria (adjunct), lymphocytic infiltrate of Jessner",
       "Porphyria cutanea tarda — low dose (HCQ 100 mg or chloroquine 125 mg twice weekly)",
       "Others: lichen planopilaris and frontal fibrosing alopecia, morphoea, sarcoidosis, granuloma annulare, chronic urticaria (refractory), oral lichen planus",
       "Quinacrine: added to HCQ in refractory cutaneous lupus (no retinal toxicity)"],
 dose=["Hydroxychloroquine: ≤5 mg/kg real body weight/day (usually 200–400 mg/day)",
       "Chloroquine: ≤2.3 mg/kg real body weight/day (usually 250 mg/day)",
       "Quinacrine: 100 mg/day",
       "Never combine HCQ with chloroquine (additive retinal toxicity)"],
 ae=["Retinopathy ('bull's-eye' maculopathy) — related to daily dose per kg and duration; risk higher with chloroquine, renal disease, tamoxifen",
     "Skin: blue-grey/black pigmentation (shins, face, palate, nails), bleaching of hair (chloroquine), exacerbation of psoriasis, AGEP (HCQ is a classic cause), SJS/TEN, lichenoid eruptions",
     "Quinacrine: diffuse yellow skin discolouration, aplastic anaemia (rare)",
     "GI upset, headache; myopathy and cardiomyopathy (long-term); haemolysis in G6PD deficiency; hypoglycaemia; QT prolongation",
     "Accidental overdose in children is often fatal (chloroquine)"],
 ci=["Pre-existing maculopathy; hypersensitivity; caution in psoriasis, G6PD deficiency, porphyria (except low-dose regimen), epilepsy, long QT"],
 ix=["Tamoxifen (retinopathy risk), QT-prolonging drugs, digoxin (levels rise), antacids (separate by 4 h), cyclosporine levels rise, smoking reduces efficacy in lupus"],
 mon=["Baseline eye examination (fundus) within the first year; annual screening (OCT and visual fields) after 5 years on HCQ (earlier with risk factors)",
      "CBC and LFT periodically"],
 preg="Hydroxychloroquine is safe and recommended to continue in pregnancy (reduces lupus flares, congenital heart block risk in anti-Ro mothers); compatible with breastfeeding.",
 viva=["Mechanism: lysosomal pH, TLR7/9 inhibition",
       "Dose by real body weight: HCQ ≤5 mg/kg, chloroquine ≤2.3 mg/kg",
       "Bull's-eye maculopathy; AGEP; psoriasis flare",
       "Low-dose twice-weekly regimen in porphyria cutanea tarda",
       "Smoking reduces response in cutaneous lupus"],
 src=f"{W} ch.21 (Antimalarial agents); {K} (Antimalarials in LE and porphyria cutanea tarda)"),

dict(name="Hydroxyurea (hydroxycarbamide)", group="More from Khopkar · Immunomodulators",
 cls="Antimetabolite; ribonucleotide reductase inhibitor",
 moa=["Inhibits ribonucleotide reductase → no deoxyribonucleotides → blocks DNA synthesis (S-phase)",
      "Antiproliferative for keratinocytes; raises fetal haemoglobin (sickle cell)"],
 uses=["Psoriasis (refractory; older alternative to methotrexate), HIV (historical with didanosine)",
       "Hypereosinophilic syndrome, myeloproliferative disorders (polycythaemia vera, CML, essential thrombocythaemia), sickle cell disease"],
 dose=["Psoriasis: 500 mg–1.5 g/day (1–2 g in divided doses), adjusted to blood counts"],
 ae=["Bone marrow suppression (megaloblastic anaemia, leucopenia); macrocytosis is expected",
     "Skin: painful leg ulcers (malleolar), dermatomyositis-like eruption (hands — 'hydroxyurea dermopathy'), xerosis, hyperpigmentation (skin, nails — longitudinal melanonychia), lichenoid eruptions, alopecia",
     "Squamous cell carcinoma and actinic keratoses with long-term use (photo-exposed sites)",
     "GI upset, fever, hepatitis"],
 ci=["Marked marrow suppression, pregnancy, breastfeeding"],
 ix=["Other myelosuppressants; didanosine/stavudine (pancreatitis, neuropathy)"],
 mon=["CBC every 1–2 weeks initially, then monthly; LFT, renal function; skin examination"],
 preg="Contraindicated (teratogenic).",
 viva=["Ribonucleotide reductase inhibitor",
       "Leg ulcers and dermatomyositis-like eruption",
       "Melanonychia and SCC with long-term use"],
 src=f"{W} ch.19 (Cytotoxic agents); {K} (Non-steroidal immunosuppressive drugs)"),

dict(name="Leflunomide", group="More from Khopkar · Immunomodulators",
 cls="Pyrimidine synthesis inhibitor (isoxazole immunomodulator, prodrug of teriflunomide)",
 moa=["Inhibits dihydroorotate dehydrogenase → blocks de novo pyrimidine synthesis → activated lymphocytes arrested in G1 phase"],
 pk=["Active metabolite teriflunomide has a very long half-life (about 2 weeks) and enterohepatic recirculation — persists for up to 2 years without washout"],
 uses=["Psoriatic arthritis and rheumatoid arthritis (approved)",
       "Off-label: cutaneous/systemic lupus, Sjögren, dermatomyositis, vasculitis, sarcoidosis, BK/CMV infections in transplant"],
 dose=["10–20 mg/day (loading doses no longer routinely used)",
       "Washout: cholestyramine 8 g three times daily for 11 days (or activated charcoal) — before planned pregnancy or for toxicity"],
 ae=["Hepatotoxicity (boxed warning), diarrhoea, hypertension, weight loss, alopecia",
     "Cytopenias, infections, interstitial lung disease, peripheral neuropathy",
     "Skin: rash, SCLE induction, SJS/TEN, DRESS, cutaneous vasculitis"],
 ci=["Pregnancy (boxed warning — teratogenic) and women not using contraception; liver disease; severe immunodeficiency"],
 ix=["Methotrexate (more liver toxicity), rifampicin (raises teriflunomide), cholestyramine (lowers levels), warfarin"],
 mon=["LFT, CBC monthly for 6 months, then every 6–8 weeks; BP"],
 preg="Contraindicated; after stopping, washout and confirm plasma teriflunomide <0.02 mg/L on two tests before conception.",
 viva=["DHODH inhibitor",
       "Cholestyramine washout because of very long half-life"],
 src=f"{K} (Leflunomide); {W} ch.40 (Miscellaneous systemic drugs)"),

# ---------------- RETINOIDS ----------------
dict(name="Etretinate", group="More from Khopkar · Retinoids",
 cls="Second-generation (mono-aromatic) retinoid — ethyl ester prodrug of acitretin (withdrawn)",
 moa=["Converted to acitretin; acts on RAR/RXR like other retinoids"],
 pk=["Highly lipophilic, stored in fat; terminal half-life 80–160 days; detected in blood up to 2–3 years after stopping"],
 uses=["Formerly: psoriasis, disorders of keratinisation — replaced by acitretin (withdrawn from the US market in 1998)"],
 dose=["Historic: 0.5–1 mg/kg/day"],
 ae=["As for acitretin (mucocutaneous, lipids, liver, bone, teratogenicity) — prolonged teratogenic risk"],
 ci=["Pregnancy for years after stopping"],
 preg="Contraindicated; prolonged teratogenicity.",
 viva=["Acitretin + alcohol → etretinate (re-esterification) — the reason for 3-year contraception with acitretin"],
 src=f"{W} ch.22; {K} (Etretinate and acitretin)"),

dict(name="Bexarotene (oral + topical gel)", group="More from Khopkar · Retinoids",
 cls="Third-generation retinoid (rexinoid) — selective RXR agonist",
 moa=["Binds retinoid X receptors → induces apoptosis and inhibits proliferation of malignant T cells"],
 pk=["Take with a fatty meal; metabolised by CYP3A4"],
 uses=["Oral: cutaneous T-cell lymphoma (mycosis fungoides) refractory to at least one systemic therapy (approved)",
       "1% gel: early-stage (IA/IB) mycosis fungoides lesions (approved)",
       "Off-label gel: hand eczema, lymphomatoid papulosis, alopecia areata"],
 dose=["Oral: 300 mg/m²/day (start at 100–150 mg/m² and increase)",
       "Gel 1%: every other day at first, increasing up to 2–4 times daily as tolerated"],
 ae=["Central hypothyroidism (almost universal — suppresses TSH) → levothyroxine needed",
     "Severe hypertriglyceridaemia (risk of pancreatitis) → fibrate/statin often started with it (avoid gemfibrozil — raises bexarotene levels)",
     "Leucopenia, headache, mucocutaneous dryness, photosensitivity",
     "Gel: irritant dermatitis, pruritus"],
 ci=["Pregnancy (teratogenic); pancreatitis risk; uncontrolled lipids"],
 ix=["Gemfibrozil and CYP3A4 inhibitors raise levels; reduces efficacy of hormonal contraceptives"],
 mon=["Fasting lipids weekly at start, free T4 (not TSH), CBC, LFT"],
 preg="Contraindicated (category X); two contraceptive methods (one non-hormonal).",
 viva=["RXR-selective 'rexinoid'",
       "Central hypothyroidism — monitor free T4",
       "Hypertriglyceridaemia — avoid gemfibrozil"],
 src=f"{W} ch.22 and ch.37; {K} (Retinoids; topical retinoids)"),

dict(name="Isotretinoin topical (0.05%)", merge_into="Isotretinoin", form_label="Topical form", group="More from Khopkar · Retinoids",
 cls="Topical 13-cis-retinoic acid (gel 0.05%, combined with erythromycin in some products)",
 moa=["Comedolytic and anti-inflammatory; no effect on sebum when applied topically"],
 uses=["Mild–moderate comedonal and inflammatory acne (available in India/Europe, not USA)"],
 dose=["Thin layer once or twice daily at night"],
 ae=["Irritation, dryness, photosensitivity"],
 ci=["Pregnancy (precaution); eczema"],
 preg="Avoid (precaution).",
 viva=["Topical isotretinoin does not reduce sebum — only oral isotretinoin does"],
 src=f"{K} (Topical retinoids); {W} ch.46"),

# ---------------- PHOTOPROTECTION / PHOTOSENSITISERS ----------------
dict(name="Beta-carotene", group="More from Khopkar · Photoprotective agents",
 cls="Carotenoid (provitamin A); systemic photoprotective",
 moa=["Quenches singlet oxygen and free radicals generated by light-activated porphyrins",
      "Deposits in skin → carotenodermia (yellow-orange colour)"],
 uses=["Erythropoietic protoporphyria (classic indication; modest benefit — afamelanotide is newer)",
       "Polymorphous light eruption, solar urticaria, hydroa vacciniforme (limited evidence)"],
 dose=["Adults 60–180 mg/day (children 30–90 mg/day), aiming for blood carotene of 600–800 µg/dL; protection begins after 1–2 months"],
 ae=["Carotenodermia (palms, soles, nasolabial — sclera spared, unlike jaundice)",
     "Loose stools; increased lung cancer risk in smokers and asbestos workers at high doses"],
 ci=["Smokers (lung cancer risk)"],
 preg="Considered safe.",
 viva=["Carotenaemia spares the sclera",
       "Used in erythropoietic protoporphyria",
       "Avoid in smokers"],
 src=f"{K} (Systemic photoprotective agents); {W} ch.40"),

dict(name="Other psoralens: trioxsalen & 5-methoxypsoralen (5-MOP)", group="More from Khopkar · Photoprotective agents",
 cls="Furocoumarin photosensitisers used with UVA (PUVA)",
 moa=["Intercalate DNA; with UVA form monoadducts (and cross-links with 8-MOP/5-MOP) → antiproliferative, immunosuppressive and melanogenic effects",
      "Trioxsalen (4,5',8-trimethylpsoralen): more melanogenic, less phototoxic orally; very phototoxic topically and in bath PUVA",
      "5-MOP (bergapten): less nausea and less phototoxicity than 8-MOP; needs higher dose"],
 uses=["Vitiligo (trioxsalen orally with sunlight — PUVAsol; trioxsalen bath PUVA)",
       "Psoriasis and other PUVA indications (5-MOP — used in Europe)"],
 dose=["Trioxsalen 0.6 mg/kg orally 2 h before sunlight/UVA (Indian practice; tablets 5 mg)",
       "5-MOP 1.2–1.8 mg/kg orally 2 h before UVA",
       "Bath PUVA: trioxsalen or 8-MOP dissolved in bath water (e.g. 0.5–1 mg/L), UVA immediately after 15 min soak"],
 ae=["Phototoxic burns, PUVA itch, nausea (less with 5-MOP and trioxsalen)",
     "Long-term PUVA risks: SCC, lentigines, photoageing, cataract"],
 ci=["As for methoxsalen: photosensitive disorders, pregnancy, children <10–12, melanoma/skin cancer history"],
 ix=["Other photosensitisers"],
 preg="Avoid.",
 viva=["5-MOP — less nausea, needs 1.2 mg/kg",
       "Trioxsalen — popular in India for vitiligo (PUVAsol)",
       "Bath PUVA avoids systemic side effects"],
 src=f"{W} ch.23; {K} (Psoralens, PUVA and phototherapy)"),

dict(name="Khellin (oral + topical, KUVA)", group="More from Khopkar · Photoprotective agents",
 cls="Furochromone (from the plant Ammi visnaga); photosensitiser",
 moa=["Similar to psoralens but forms only monoadducts with DNA after UVA → stimulates melanocytes with minimal phototoxicity"],
 uses=["Vitiligo (KUVA — khellin + UVA/sunlight); topical khellin with UVA/NB-UVB or excimer"],
 dose=["Oral: 50–100 mg 2.5 h before UVA (historic); topical 2–5% gel/cream before UVA"],
 ae=["Oral: raised liver enzymes (hepatotoxicity limits oral use), nausea, orthostatic hypotension",
     "Topical: minimal phototoxicity"],
 ci=["Liver disease (oral); pregnancy"],
 preg="Avoid.",
 viva=["Low phototoxicity vs psoralens; oral use limited by hepatotoxicity"],
 src=f"{K} (Systemic photoprotective agents / PUVA); {W} ch.23"),

# ---------------- BIOLOGICS ----------------
dict(name="Etanercept", group="More from Khopkar · Biologicals",
 cls="TNF-α inhibitor — fusion protein of TNF receptor 2 (p75) with the Fc portion of IgG1",
 moa=["Acts as a soluble decoy receptor binding TNF-α (and lymphotoxin-α), preventing it from activating cell receptors",
      "Does not lyse TNF-bearing cells (unlike monoclonal antibodies) — less granulomatous infection risk"],
 uses=["Moderate–severe plaque psoriasis (adults and children ≥4 years), psoriatic arthritis",
       "Off-label: hidradenitis (weak), pyoderma gangrenosum, SJS/TEN (single dose in trials), sarcoidosis (ineffective)"],
 dose=["Psoriasis: 50 mg SC twice weekly for 12 weeks, then 50 mg once weekly; children 0.8 mg/kg weekly"],
 ae=["Injection-site reactions (common), upper respiratory infections",
     "Serious infections; TB reactivation (lower than monoclonals but still screen); hepatitis B reactivation",
     "Demyelinating disease, drug-induced lupus, worsening heart failure",
     "Paradoxical psoriasis (palmoplantar pustular), lymphoma risk (small)"],
 ci=["Active serious infection, untreated latent TB, multiple sclerosis/demyelination, NYHA III–IV heart failure, live vaccines"],
 ix=["Do not combine with other biologics or anakinra/abatacept (serious infections)"],
 mon=["TB screening (IGRA) before and yearly; hepatitis B/C, HIV; CBC/LFT periodically"],
 preg="Low placental transfer (Fc fusion protein) — can be used if needed; avoid live vaccines in infants for 6 months if exposed late.",
 viva=["Receptor fusion protein — decoy for TNF",
       "TNF inhibitors: screen for TB, avoid in demyelination and severe heart failure",
       "Paradoxical psoriasis with TNF inhibitors"],
 src=f"{W} ch.26 (TNF inhibitors); {K} (Immunobiologicals)"),

dict(name="Infliximab", group="More from Khopkar · Biologicals",
 cls="TNF-α inhibitor — chimeric (mouse–human) IgG1 monoclonal antibody",
 moa=["Binds soluble and membrane-bound TNF-α with high affinity; lyses TNF-expressing cells (complement and antibody-dependent cytotoxicity)"],
 uses=["Severe plaque psoriasis (fastest onset of TNF inhibitors), erythrodermic and generalised pustular psoriasis, psoriatic arthritis",
       "Pyoderma gangrenosum (especially with IBD), hidradenitis suppurativa (off-label), Behçet disease, sarcoidosis, SJS/TEN (case reports)",
       "Crohn disease, ulcerative colitis, rheumatoid arthritis"],
 dose=["5 mg/kg IV infusion at weeks 0, 2 and 6, then every 8 weeks (over 2 h)"],
 ae=["Infusion reactions (acute — fever, urticaria, hypotension; delayed serum-sickness-like)",
     "Antibodies against the drug (chimeric) → loss of response; methotrexate reduces this",
     "TB reactivation (highest risk among TNF inhibitors — often extrapulmonary/disseminated), opportunistic infections, hepatitis B reactivation",
     "Hepatotoxicity, demyelination, lupus-like syndrome, heart failure, hepatosplenic T-cell lymphoma (young men with azathioprine)",
     "Paradoxical psoriasis"],
 ci=["As for TNF inhibitors; murine protein hypersensitivity"],
 ix=["Other biologics; live vaccines"],
 mon=["TB, hepatitis, HIV screening; LFT; infusion monitoring"],
 preg="Crosses placenta in late pregnancy (IgG1) — stop by about 16–24 weeks if possible; avoid live vaccines (BCG, rotavirus) in exposed infants for 6–12 months.",
 viva=["Chimeric antibody — infusion reactions and antidrug antibodies",
       "Highest TB risk among anti-TNFs",
       "Fastest-acting TNF blocker in psoriasis"],
 src=f"{W} ch.26; {K} (Immunobiologicals)"),

dict(name="Efalizumab & alefacept (withdrawn T-cell biologics)", group="More from Khopkar · Biologicals",
 cls="T-cell targeted biologics for psoriasis — efalizumab (anti-CD11a monoclonal) and alefacept (LFA-3/IgG1 fusion protein)",
 moa=["Efalizumab: blocks CD11a (LFA-1) → prevents T-cell activation and migration into skin",
      "Alefacept: binds CD2 on memory T cells → blocks LFA-3/CD2 co-stimulation and causes NK-mediated apoptosis of CD45RO+ memory T cells"],
 uses=["Formerly: moderate–severe chronic plaque psoriasis",
       "Efalizumab withdrawn in 2009 (progressive multifocal leukoencephalopathy); alefacept withdrawn in 2011 (commercial reasons/low efficacy)"],
 dose=["Historic: efalizumab 1 mg/kg SC weekly; alefacept 15 mg IM weekly × 12 weeks (needed CD4 count monitoring)"],
 ae=["Efalizumab: PML (JC virus), rebound/flare of psoriasis on stopping, thrombocytopenia, aseptic meningitis",
     "Alefacept: CD4 lymphopenia, infections, malignancy concerns"],
 ci=["No longer marketed"],
 preg="Not applicable (withdrawn).",
 viva=["Efalizumab withdrawn due to PML",
       "Alefacept — first biologic approved for psoriasis (2003); depletes memory T cells; CD4 monitoring"],
 src=f"{K} (Immunobiologicals — efalizumab, alefacept); {W} ch.8 (Drugs taken off the market)"),

dict(name="Intravenous immunoglobulin (IVIG)", group="More from Khopkar · Biologicals",
 cls="Pooled polyclonal IgG from thousands of healthy donors",
 moa=["Saturates the neonatal Fc receptor (FcRn) → faster breakdown of pathogenic autoantibodies (key in pemphigus)",
      "Blocks Fas–FasL interaction → stops keratinocyte apoptosis (proposed in TEN)",
      "Neutralises autoantibodies (anti-idiotypes), blocks Fc receptors on macrophages, inhibits complement, modulates cytokines, expands regulatory T cells"],
 uses=["Kawasaki disease (with aspirin — prevents coronary aneurysms)",
       "Dermatomyositis (refractory; approved in USA), pemphigus vulgaris/foliaceus (refractory — 3rd line in the Derma Desk ladder), bullous pemphigoid, mucous membrane pemphigoid, EBA",
       "SJS/TEN (controversial benefit), scleromyxoedema (first line), pyoderma gangrenosum, chronic urticaria (refractory), vasculitis, primary immunodeficiency, ITP"],
 dose=["Immunomodulatory dose: 2 g/kg per cycle divided over 2–5 days, repeated every 4 weeks",
       "TEN: 1 g/kg/day for 3 days (total 3 g/kg) in studies",
       "Infuse slowly (start 0.5 mL/kg/h and increase)"],
 ae=["Infusion reactions (headache, chills, flushing, back pain) — slow rate, premedicate",
     "Aseptic meningitis, thrombosis (stroke, MI — hyperviscosity), acute kidney injury (sucrose-containing products), haemolysis (anti-A/B antibodies)",
     "Anaphylaxis in IgA-deficient patients with anti-IgA antibodies",
     "Eczematous/pompholyx-like eruptions after infusion"],
 ci=["IgA deficiency with anti-IgA antibodies (use IgA-depleted product); caution in renal failure, thrombosis risk, heart failure"],
 ix=["Live vaccines: response reduced (delay for months)"],
 mon=["Baseline IgA level, renal function, CBC; BP and vitals during infusion; hydration"],
 preg="Safe in pregnancy.",
 viva=["FcRn saturation increases IgG catabolism",
       "Check IgA levels before first infusion",
       "2 g/kg per cycle for autoimmune disease",
       "Scleromyxoedema — IVIG is first-line"],
 src=f"{W} ch.36 (Intravenous immunoglobulin); {K} (Intravenous immunoglobulins)"),

dict(name="Mycobacterium w vaccine (Mw / Immuvac / MIP)", group="More from Khopkar · Biologicals",
 cls="Heat-killed Mycobacterium indicus pranii (formerly Mycobacterium w) — Indian immunomodulatory vaccine",
 moa=["Shares antigens with M. leprae; boosts Th1 cell-mediated immunity and modulates cytokines",
      "Used as a non-specific immunostimulant"],
 uses=["Leprosy: adjunct to MDT in multibacillary leprosy (faster bacterial clearance, fewer reactions), immunoprophylaxis of contacts (trials)",
       "Off-label: recalcitrant warts (intralesional/intradermal), anogenital warts, molluscum, psoriasis, alopecia areata, vitiligo (limited data)",
       "Approved in India for gram-negative sepsis (adjunct)"],
 dose=["Intradermal 0.1 mL (first dose may be 0.2 mL split at two sites), repeated every 2–4 weeks for warts; leprosy schedules per protocol"],
 ae=["Injection-site papule, ulcer, abscess and scar; fever, flu-like symptoms; lymphadenopathy"],
 ci=["Immunosuppression; acute febrile illness; pregnancy (insufficient data)"],
 preg="Avoid.",
 viva=["Indian immunomodulator from M. indicus pranii — adjunct in MB leprosy and in warts"],
 src=f"{K} (Immunobiologicals — Immuvac / Mw vaccine)",
 note="Mw vaccine is described in Khopkar; Wolverton does not cover it."),

dict(name="Denileukin diftitox", group="More from Khopkar · Biologicals",
 cls="Fusion protein of interleukin-2 and diphtheria toxin",
 moa=["The IL-2 part binds CD25 (IL-2 receptor) on malignant and activated T cells; the diphtheria toxin part enters the cell and stops protein synthesis → cell death"],
 uses=["Persistent or recurrent CD25-positive cutaneous T-cell lymphoma (originally approved 1999, withdrawn 2014; a new formulation was re-approved in the USA in 2024)"],
 dose=["IV infusion daily for 5 days every 21 days (dose per product label)"],
 ae=["Capillary leak syndrome (oedema, hypoalbuminaemia, hypotension) — boxed warning",
     "Infusion reactions, visual loss (rare), hepatotoxicity, infections"],
 ci=["Hypersensitivity; low albumin"],
 preg="Avoid.",
 viva=["IL-2–diphtheria toxin fusion targeting CD25 in CTCL; capillary leak syndrome"],
 src=f"{K} (Immunobiologicals — denileukin diftitox); {W} ch.37"),

# ---------------- ANTIHISTAMINES & MAST CELL STABILISERS ----------------
dict(name="Chlorpheniramine maleate", group="More from Khopkar · Antihistamines",
 cls="First-generation (sedating) H1 antihistamine — alkylamine",
 moa=["H1 inverse agonist; crosses blood–brain barrier; anticholinergic"],
 uses=["Acute urticaria, allergic reactions, itch, insect bites; adjunct (IV/IM) in anaphylaxis"],
 dose=["Adults 4 mg every 4–6 h (max 24 mg/day); injection 10 mg IM/IV; children 0.35 mg/kg/day"],
 ae=["Sedation (milder than other first-generation drugs), anticholinergic effects, paradoxical excitation in children"],
 ci=["Neonates; caution in glaucoma, prostatism, epilepsy"],
 ix=["Alcohol and CNS depressants; MAO inhibitors; phenytoin levels may rise"],
 preg="Widely used in pregnancy (long safety record).",
 viva=["Alkylamine — least sedating first-generation antihistamine; long pregnancy safety record"],
 src=f"{K} (First generation H1 antihistamines); {W} ch.32"),

dict(name="Promethazine", group="More from Khopkar · Antihistamines",
 cls="First-generation H1 antihistamine — phenothiazine",
 moa=["H1 inverse agonist with strong anticholinergic, sedative, antiemetic and anti-dopaminergic effects"],
 uses=["Night-time itch and sedation, allergic reactions, motion sickness, nausea, pre-medication"],
 dose=["Adults 10–25 mg at night (up to 25 mg three times daily); injection 25 mg deep IM"],
 ae=["Marked sedation; respiratory depression in children under 2 (boxed warning — contraindicated)",
     "Photosensitivity and photoallergy (phenothiazine), contact dermatitis with topical use",
     "Extrapyramidal reactions, QT prolongation; severe tissue injury/gangrene with intra-arterial or perivascular injection"],
 ci=["Children under 2 years; intra-arterial or SC injection"],
 ix=["CNS depressants, other anticholinergics, QT drugs"],
 preg="Has been used; avoid near term (neonatal effects).",
 viva=["Phenothiazine antihistamine — photosensitivity; contraindicated under 2 years"],
 src=f"{K} (First generation H1 antihistamines); {W} ch.32"),

dict(name="Cyproheptadine", group="More from Khopkar · Antihistamines",
 cls="First-generation H1 antihistamine — piperidine; also serotonin (5-HT2) antagonist",
 moa=["Blocks H1 and 5-HT2 receptors; anticholinergic; appetite stimulant"],
 uses=["Cold urticaria (drug of choice among older agents), chronic urticaria, pruritus",
       "Serotonin syndrome (antidote), appetite stimulation, migraine prophylaxis in children"],
 dose=["4 mg three times daily (max 32 mg/day); children 0.25 mg/kg/day"],
 ae=["Sedation, increased appetite and weight gain, anticholinergic effects"],
 ci=["Glaucoma, urinary retention, neonates, elderly debilitated"],
 ix=["Reduces effect of SSRIs; CNS depressants"],
 preg="Avoid in late pregnancy.",
 viva=["Antiserotonergic — cold urticaria and serotonin syndrome; causes weight gain"],
 src=f"{K} (First generation H1 antihistamines); {W} ch.32"),

dict(name="Diphenhydramine", group="More from Khopkar · Antihistamines",
 cls="First-generation H1 antihistamine — ethanolamine",
 moa=["H1 inverse agonist; strongly sedative and anticholinergic; local anaesthetic effect"],
 uses=["Acute allergic reactions, urticaria, night-time itch, anaphylaxis adjunct",
       "1% injection as local anaesthetic in patients allergic to amides and esters"],
 dose=["25–50 mg every 4–6 h (max 300 mg/day); injection 10–50 mg IV/IM"],
 ae=["Marked sedation, impaired performance, anticholinergic delirium in elderly",
     "Topical diphenhydramine: frequent contact sensitiser and photosensitiser"],
 ci=["Neonates, breastfeeding; caution in elderly (Beers list)"],
 ix=["CNS depressants; CYP2D6 inhibitor (raises metoprolol, TCAs)"],
 preg="Has been used; avoid near term.",
 viva=["Can be used as an alternative local anaesthetic (1%) in 'caine' allergy",
       "Avoid topical antihistamines — sensitisation"],
 src=f"{K} (First generation H1 antihistamines); {W} ch.32 and ch.58"),

dict(name="Levocetirizine", group="More from Khopkar · Antihistamines",
 cls="Second-generation H1 antihistamine — active R-enantiomer of cetirizine",
 moa=["Selective peripheral H1 inverse agonist; twice the receptor affinity of cetirizine"],
 uses=["Chronic urticaria, allergic rhinitis, pruritus"],
 dose=["5 mg once daily in the evening (updosing up to 20 mg in urticaria); children 6–11 years 2.5 mg; 2–6 years 1.25 mg twice daily",
       "Halve or space doses in renal impairment"],
 ae=["Mild sedation (similar to cetirizine), dry mouth, fatigue"],
 ci=["End-stage renal disease; children under 6 months"],
 ix=["Alcohol, CNS depressants"],
 preg="Limited data — cetirizine/loratadine preferred.",
 viva=["5 mg levocetirizine = 10 mg cetirizine; renal dose adjustment"],
 src=f"{K} (Second generation H1 antihistamines); {W} ch.32"),

dict(name="Desloratadine", group="More from Khopkar · Antihistamines",
 cls="Second-generation H1 antihistamine — active metabolite of loratadine",
 moa=["Highly potent selective peripheral H1 inverse agonist; some anti-inflammatory effect"],
 uses=["Chronic urticaria, allergic rhinitis"],
 dose=["5 mg once daily (updosing up to 20 mg in urticaria); children 6–11 years 2.5 mg"],
 ae=["Headache, fatigue; non-sedating at standard dose"],
 ci=["Hypersensitivity to loratadine"],
 ix=["Minimal; erythromycin/ketoconazole raise levels without QT change"],
 preg="Limited data; loratadine preferred.",
 viva=["Active metabolite of loratadine; long half-life (~27 h)"],
 src=f"{K} (Second generation H1 antihistamines); {W} ch.32"),

dict(name="Ebastine", group="More from Khopkar · Antihistamines",
 cls="Second-generation H1 antihistamine — piperidine (prodrug of carebastine)",
 moa=["Converted in liver (CYP3A4) to carebastine — selective H1 inverse agonist"],
 uses=["Chronic urticaria, allergic rhinitis"],
 dose=["10–20 mg once daily"],
 ae=["Headache, dry mouth; QT prolongation possible at high doses or with CYP3A4 inhibitors"],
 ci=["Severe liver impairment; long QT"],
 ix=["Ketoconazole/erythromycin raise levels (QT caution)"],
 preg="Limited data — avoid.",
 viva=["Prodrug activated by CYP3A4; QT caution with azoles/macrolides"],
 src=f"{K} (Second generation H1 antihistamines)"),

dict(name="Mizolastine", group="More from Khopkar · Antihistamines",
 cls="Second-generation H1 antihistamine — benzimidazole derivative with anti-inflammatory activity",
 moa=["Selective H1 antagonist; also inhibits 5-lipoxygenase (leukotriene) production"],
 uses=["Chronic urticaria, allergic rhinitis"],
 dose=["10 mg once daily"],
 ae=["Drowsiness, dry mouth, weight gain; QT prolongation (cardiac caution)"],
 ci=["Long QT, significant heart disease, hypokalaemia; with macrolides or azoles"],
 ix=["CYP3A4 inhibitors (erythromycin, ketoconazole) — contraindicated together"],
 preg="Avoid.",
 viva=["Antihistamine + anti-leukotriene action; QT warning"],
 src=f"{K} (Second generation H1 antihistamines)"),

dict(name="Ketotifen", group="More from Khopkar · Antihistamines",
 cls="H1 antihistamine with mast cell–stabilising properties (benzocycloheptathiophene)",
 moa=["Stabilises mast cells (inhibits calcium influx and mediator release), blocks H1 receptors, inhibits eosinophil accumulation"],
 uses=["Chronic urticaria (adjunct), cholinergic and cold urticaria, physical urticarias",
       "Mastocytosis (symptom control), allergic conjunctivitis (eye drops), neurofibromatosis-associated itch (trials)"],
 dose=["1 mg twice daily (start 1 mg at night); children 0.5 mg twice daily (age >3)"],
 ae=["Sedation, weight gain (appetite), dry mouth; full effect takes 6–12 weeks"],
 ci=["Epilepsy (lowers seizure threshold — caution)"],
 ix=["Oral hypoglycaemics (reversible thrombocytopenia reported), CNS depressants"],
 preg="Limited data — avoid.",
 viva=["Mast cell stabiliser + antihistamine; slow onset; weight gain"],
 src=f"{K} (Mast cell stabilizers/ketotifen); {W} ch.32"),

dict(name="Doxepin (oral + topical)", group="More from Khopkar · Antihistamines",
 cls="Tricyclic antidepressant with very potent H1 and H2 receptor blocking activity",
 moa=["H1 affinity about 800 times diphenhydramine and 50 times hydroxyzine; also H2 blockade, anticholinergic, sedative and antidepressant (noradrenaline/serotonin reuptake inhibition)"],
 uses=["Chronic urticaria (especially with anxiety/depression, nocturnal itch), cold urticaria, dermographism",
       "Neuropathic itch and pain, psychogenic excoriation, lichen simplex chronicus",
       "Topical 5% cream: itch of atopic dermatitis and lichen simplex (short courses)"],
 dose=["Oral: 10–25 mg at bedtime (up to 75 mg/day); elderly 10 mg",
       "Topical 5% cream: four times daily for up to 8 days, maximum 10% body surface"],
 ae=["Sedation, dry mouth, constipation, weight gain, orthostatic hypotension",
     "Cardiac arrhythmia (QT prolongation), lethal in overdose",
     "Topical: drowsiness from absorption (about 20%), allergic contact dermatitis (common), burning"],
 ci=["Recent MI, heart block, narrow-angle glaucoma, urinary retention, MAO inhibitors within 14 days, mania"],
 ix=["CYP2D6 inhibitors (fluoxetine, terbinafine) raise levels; alcohol; other serotonergic drugs"],
 mon=["ECG in older patients or cardiac history"],
 preg="Avoid (neonatal withdrawal, limited data).",
 viva=["Most potent H1 blocker available",
       "Topical doxepin: absorbed enough to cause drowsiness; frequent contact allergy"],
 src=f"{W} ch.32 and ch.35; {K} (Antihistamines; topical doxepin)"),

dict(name="H2 antihistamines (cimetidine, ranitidine, famotidine)", group="More from Khopkar · Antihistamines",
 cls="H2 receptor antagonists",
 moa=["Block H2 receptors on gastric parietal cells and on skin blood vessels (part of wheal and flare)",
      "Cimetidine also has immunomodulatory (blocks suppressor T-cell H2 receptors) and anti-androgenic effects"],
 uses=["Add-on to H1 antihistamines in chronic urticaria (small extra benefit), anaphylaxis adjunct, mastocytosis",
       "Cimetidine: warts in children (immunomodulatory — evidence weak), hirsutism (anti-androgen), reduces dapsone methaemoglobinaemia"],
 dose=["Famotidine 20–40 mg twice daily; cimetidine 400 mg twice daily (warts 30–40 mg/kg/day)"],
 ae=["Generally safe; cimetidine — gynaecomastia, impotence, confusion in elderly, CYP inhibition",
     "Ranitidine withdrawn worldwide in 2020 (NDMA carcinogen contamination)"],
 ci=["Hypersensitivity"],
 ix=["Cimetidine inhibits CYP1A2, 2D6, 3A4 → raises warfarin, theophylline, phenytoin, lignocaine, doxepin levels"],
 preg="Famotidine considered safe.",
 viva=["H1 + H2 combination in refractory urticaria",
       "Cimetidine: interactions, gynaecomastia, warts (immunomodulation)",
       "Ranitidine withdrawn — NDMA"],
 src=f"{K} (Antihistamines); {W} ch.32"),

# ---------------- VITAMINS & TRACE ELEMENTS ----------------
dict(name="Vitamin A (retinol)", group="More from Khopkar · Vitamins & trace elements",
 cls="Fat-soluble vitamin (retinol and its esters)",
 moa=["Needed for epithelial differentiation, vision (rhodopsin), immunity; precursor of retinoic acid"],
 uses=["Vitamin A deficiency: phrynoderma (follicular hyperkeratosis), xerosis, night blindness, xerophthalmia, Bitot spots",
       "Measles in children (reduces mortality), prophylaxis in national programme (6–59 months)",
       "High-dose vitamin A was once used for acne, Darier disease and PRP (replaced by retinoids)"],
 dose=["National prophylaxis: 1 lakh IU at 9 months, then 2 lakh IU every 6 months up to 5 years",
       "Xerophthalmia/measles: 2 lakh IU on days 1, 2 and 14 (half dose under 1 year)"],
 ae=["Acute toxicity: raised intracranial pressure (bulging fontanelle, headache, vomiting), desquamation",
     "Chronic hypervitaminosis A: dry skin, cheilitis, alopecia, bone pain, hepatotoxicity, hypercalcaemia",
     "Teratogenic in high doses"],
 ci=["High doses in pregnancy (>10,000 IU/day); with oral retinoids"],
 ix=["Oral retinoids (additive toxicity); orlistat and mineral oil reduce absorption"],
 preg="Avoid doses above 10,000 IU/day (teratogenic).",
 viva=["Phrynoderma — toad skin of vitamin A deficiency",
       "Never give vitamin A supplements with isotretinoin/acitretin"],
 src=f"{K} (Vitamin A — retinol); {W} ch.40"),

dict(name="B-complex vitamins (riboflavin, niacin, pyridoxine, biotin, folic acid, B12)", group="More from Khopkar · Vitamins & trace elements",
 cls="Water-soluble vitamins",
 moa=["Coenzymes in energy metabolism (B2, B3), amino acid metabolism (B6), carboxylation (biotin), one-carbon and DNA synthesis (folate, B12)"],
 uses=["Riboflavin (B2) deficiency: angular cheilitis, glossitis (magenta tongue), seborrhoeic-like dermatitis, scrotal dermatitis",
       "Niacin (B3) deficiency — pellagra: photosensitive dermatitis (Casal necklace), diarrhoea, dementia; seen with alcoholism, isoniazid, carcinoid, Hartnup disease — treat with nicotinamide (see nicotinamide post)",
       "Pyridoxine (B6): prevent isoniazid neuropathy; deficiency causes seborrhoeic-like dermatitis, cheilitis",
       "Biotin: biotinidase/holocarboxylase deficiency (periorificial dermatitis, alopecia); popular for brittle nails (2.5 mg/day — limited evidence)",
       "Folic acid: with methotrexate; megaloblastic anaemia; pregnancy",
       "B12 (cyanocobalamin/methylcobalamin): pernicious anaemia, hyperpigmentation of knuckles and nails, glossitis; neuropathy"],
 dose=["Riboflavin 5–10 mg/day; nicotinamide 100 mg every 6 h for pellagra; pyridoxine 10–25 mg with INH; biotin 2.5–5 mg/day; folic acid 1–5 mg/day; B12 1000 µg IM daily × 1 week, then weekly, then monthly (deficiency)"],
 ae=["Nicotinic acid (not nicotinamide): flushing, pruritus, hepatotoxicity, acanthosis nigricans",
     "High-dose B6: sensory neuropathy; B12 injections: acneiform eruption, rosacea flare",
     "Biotin interferes with laboratory immunoassays (thyroid, troponin) — stop 2–3 days before tests"],
 ci=["Folic acid alone in B12 deficiency (corrects anaemia, neuropathy progresses)"],
 ix=["Isoniazid/penicillamine deplete B6; methotrexate/co-trimoxazole antagonise folate"],
 preg="Folic acid 400 µg–5 mg recommended in pregnancy.",
 viva=["Pellagra 4 Ds (dermatitis, diarrhoea, dementia, death); Casal necklace",
       "B12 deficiency → knuckle hyperpigmentation",
       "Biotin interferes with lab tests"],
 src=f"{K} (Water-soluble vitamins — riboflavin, niacin, biotin, folic acid); {W} ch.40"),

dict(name="Vitamin C (ascorbic acid) — oral + topical", group="More from Khopkar · Vitamins & trace elements",
 cls="Water-soluble antioxidant vitamin",
 moa=["Cofactor for prolyl and lysyl hydroxylase (collagen synthesis)",
      "Antioxidant (neutralises UV-generated free radicals); inhibits tyrosinase (depigmenting); regenerates vitamin E"],
 uses=["Scurvy: perifollicular haemorrhage, corkscrew hairs, gum bleeding, poor wound healing, woody oedema",
       "Adjunct in wound healing, iron absorption (with iron), Ehlers–Danlos (limited)",
       "Topical L-ascorbic acid 10–20% (pH <3.5) or stable derivatives (magnesium ascorbyl phosphate): photoageing, melasma and PIH (adjunct), photoprotection booster (with vitamin E and ferulic acid)"],
 dose=["Scurvy: 300–1000 mg/day for 1 month; supplement 500 mg/day",
       "Topical: once daily in the morning under sunscreen"],
 ae=["Oral high doses: GI upset, oxalate kidney stones, haemolysis in G6PD deficiency (IV)",
     "Topical: stinging, yellow staining as it oxidises (unstable in air/light)"],
 ci=["Recurrent oxalate stones (high dose); haemochromatosis"],
 ix=["Increases iron absorption; may interfere with glucose meters (IV)"],
 preg="Safe.",
 viva=["Scurvy: corkscrew hairs and perifollicular haemorrhage",
       "Topical vitamin C — antioxidant; must be acidic and fresh"],
 src=f"{K} (Ascorbic acid; topical vitamin C); {W} ch.57"),

dict(name="Vitamin E (tocopherol) — oral + topical", group="More from Khopkar · Vitamins & trace elements",
 cls="Fat-soluble antioxidant vitamin (α-tocopherol)",
 moa=["Lipid-phase antioxidant — protects cell membranes from lipid peroxidation; regenerated by vitamin C"],
 uses=["Adjunct in cutaneous lupus, yellow nail syndrome, epidermolysis bullosa, claudication (weak evidence)",
       "Reduces dapsone-induced haemolysis/methaemoglobinaemia (adjunct)",
       "Topical: moisturiser and antioxidant in cosmetics, scars (no proven benefit), photoprotection booster"],
 dose=["Oral 400–800 IU/day; topical in creams/oils"],
 ae=["High oral doses: bleeding tendency (antiplatelet), possible increased mortality with very high doses",
     "Topical: allergic contact dermatitis, contact urticaria, erythema multiforme-like reactions"],
 ci=["Bleeding disorders, anticoagulant therapy (high doses)"],
 ix=["Warfarin (increased bleeding)"],
 preg="Safe at dietary doses.",
 viva=["Topical vitamin E is a recognised contact allergen; no proof it improves scars"],
 src=f"{K} (Vitamin E — tocopherol; topical vitamins); {W} ch.57"),

dict(name="Iron", group="More from Khopkar · Vitamins & trace elements",
 cls="Mineral supplement (ferrous sulfate, fumarate, gluconate; IV iron sucrose, ferric carboxymaltose)",
 moa=["Restores haemoglobin and tissue iron; iron is a cofactor for ribonucleotide reductase in rapidly dividing hair matrix cells"],
 uses=["Iron deficiency in telogen effluvium and female pattern hair loss (many experts aim for ferritin >40–70 ng/mL)",
       "Koilonychia, angular cheilitis, glossitis, pruritus of iron deficiency, Plummer–Vinson syndrome",
       "Iron deficiency from chronic blood loss (e.g. dermatitis herpetiformis/coeliac, hereditary haemorrhagic telangiectasia)"],
 dose=["Oral elemental iron 60–120 mg once daily or on alternate days (better absorption), with vitamin C, away from tea/calcium; continue 3 months after Hb normalises",
       "IV iron for intolerance or malabsorption"],
 ae=["GI upset, constipation, black stools; IV — hypersensitivity, skin staining at infusion site (brown pigmentation from extravasation)"],
 ci=["Haemochromatosis, haemosiderosis, haemolytic anaemia without iron deficiency"],
 ix=["Reduces absorption of tetracyclines, fluoroquinolones, levothyroxine, dolutegravir, mycophenolate; PPIs/antacids reduce iron absorption"],
 mon=["Hb, ferritin, transferrin saturation"],
 preg="Recommended in pregnancy.",
 viva=["Check ferritin in diffuse hair loss",
       "Separate iron from tetracyclines and fluoroquinolones"],
 src=f"{K} (Trace elements — iron); {W} ch.40"),

dict(name="Copper", group="More from Khopkar · Vitamins & trace elements",
 cls="Trace element (oral copper salts; copper peptides topically)",
 moa=["Cofactor of tyrosinase (melanin), lysyl oxidase (collagen and elastin cross-linking), cytochrome oxidase, superoxide dismutase"],
 uses=["Copper deficiency (malnutrition, high-dose zinc, bariatric surgery): hypopigmentation of skin and hair, anaemia, neutropenia, neuropathy",
       "Menkes kinky hair disease (copper histidinate injections — early)",
       "Topical copper peptides (GHK-Cu): wound healing, cosmeceuticals"],
 dose=["Oral copper 2–4 mg/day elemental for deficiency (specialist guidance)"],
 ae=["Excess: GI upset, hepatic toxicity; Wilson disease (copper accumulation — Kayser–Fleischer rings, azure lunulae)"],
 ci=["Wilson disease"],
 ix=["Zinc reduces copper absorption (used therapeutically in Wilson disease)"],
 preg="Dietary amounts safe.",
 viva=["Menkes disease — pili torti, hypopigmentation; Wilson disease — azure lunulae",
       "Long-term zinc causes copper deficiency"],
 src=f"{K} (Trace elements — copper; copper peptides)"),

dict(name="Selenium (oral)", group="More from Khopkar · Vitamins & trace elements",
 cls="Trace element (antioxidant; component of glutathione peroxidase)",
 moa=["Part of selenoproteins (glutathione peroxidase, thioredoxin reductase) that protect against oxidative/UV damage"],
 uses=["Selenium deficiency (long-term parenteral nutrition, Keshan disease): leuconychia, hair and skin hypopigmentation, cardiomyopathy",
       "Adjunct antioxidant in vitiligo, psoriasis, polymorphous light eruption (limited evidence)",
       "Thyroid eye disease (mild — selenium 100 µg twice daily)"],
 dose=["50–200 µg/day (do not exceed 400 µg/day)"],
 ae=["Selenosis (excess): garlic breath, brittle nails and hair loss, skin rash, neuropathy; possible higher diabetes and skin cancer risk with long-term supplements"],
 ci=["Excess intake"],
 preg="Dietary amounts safe.",
 viva=["Selenosis — garlic breath, nail and hair loss",
       "Do not confuse with selenium sulfide shampoo"],
 src=f"{K} (Trace elements — selenium)"),

# ---------------- MISCELLANEOUS SYSTEMIC ----------------
dict(name="Spironolactone", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Aldosterone antagonist (potassium-sparing diuretic) with anti-androgenic activity",
 moa=["Blocks androgen receptors in sebaceous glands and hair follicles; reduces ovarian/adrenal androgen synthesis (inhibits 17α-hydroxylase); increases SHBG"],
 uses=["Acne in adult women (especially jawline/hormonal, PCOS) — 'off-label first-line hormonal therapy'",
       "Hirsutism, female pattern hair loss, hidradenitis suppurativa in women"],
 dose=["Acne: 50–100 mg/day (25–200 mg range); hirsutism/FPHL: 100–200 mg/day; results in 3 months",
       "Often combined with combined oral contraceptives (prevents menstrual irregularity, provides contraception)"],
 ae=["Menstrual irregularity, breast tenderness, diuresis, dizziness, postural hypotension",
     "Hyperkalaemia — rare in young healthy women (routine K⁺ checks not needed per recent guidance); check in renal disease, older patients, ACE inhibitor/ARB users",
     "Gynaecomastia in men (not used for men's acne)",
     "Animal tumour data (high doses) — not seen in humans"],
 ci=["Pregnancy (feminisation of male fetus), hyperkalaemia, renal failure, Addison disease; men (gynaecomastia)"],
 ix=["ACE inhibitors, ARBs, potassium supplements, trimethoprim, NSAIDs (hyperkalaemia); digoxin levels rise"],
 mon=["Potassium only if risk factors; BP"],
 preg="Contraindicated in pregnancy — use with contraception.",
 viva=["Anti-androgen for female acne and hirsutism",
       "Routine potassium monitoring not needed in healthy young women",
       "Pregnancy — feminisation risk"],
 src=f"{W} ch.34 (Antiandrogens); {K} (Antiandrogens)"),

dict(name="Cyproterone acetate (± ethinylestradiol)", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Progestogen with strong anti-androgenic activity (androgen receptor blocker)",
 moa=["Blocks androgen receptors; as a progestogen suppresses LH → lower ovarian androgen production",
      "With ethinylestradiol (2 mg + 35 µg) acts as a combined oral contraceptive"],
 uses=["Acne in women (moderate–severe, not responding to other therapy), hirsutism, PCOS, female pattern hair loss",
       "High-dose: prostate cancer, paraphilias (men)"],
 dose=["CPA 2 mg + ethinylestradiol 35 µg daily for 21 days, 7-day break",
       "Severe hirsutism: add CPA 25–100 mg on days 1–10 of cycle (reverse sequential regimen)"],
 ae=["Venous thromboembolism (higher than some other COCs)",
     "Meningioma with long-term high doses (EMA restriction 2020 — use lowest dose, MRI if symptoms)",
     "Hepatotoxicity at high doses, mood change, weight gain, breast tenderness, loss of libido"],
 ci=["Pregnancy, thrombosis history, liver disease, meningioma, smokers over 35, migraine with aura"],
 ix=["Enzyme inducers (rifampicin, carbamazepine) reduce efficacy"],
 mon=["BP, weight; LFT at high doses"],
 preg="Contraindicated (feminises male fetus).",
 viva=["Anti-androgen + contraceptive in one pill",
       "Meningioma risk with long-term high doses",
       "Stop 3 cycles after acne clears (VTE risk)"],
 src=f"{W} ch.34; {K} (Antiandrogens)"),

dict(name="Flutamide", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Non-steroidal pure anti-androgen (androgen receptor antagonist)",
 moa=["Competitively blocks androgen receptors in target tissues (hair follicle, sebaceous gland, prostate)"],
 uses=["Prostate cancer (approved)",
       "Off-label in women: hirsutism, acne, female pattern hair loss — limited by liver toxicity (bicalutamide is now preferred)"],
 dose=["Women (off-label): 62.5–250 mg/day with contraception"],
 ae=["Hepatotoxicity — may be fatal (boxed warning); dose-related",
     "Dry skin, GI upset, green-brown urine, photosensitivity"],
 ci=["Liver disease; pregnancy"],
 ix=["Warfarin (INR rises)"],
 mon=["LFT monthly for 4 months, then periodically"],
 preg="Contraindicated (feminisation of male fetus).",
 viva=["Pure anti-androgen; fatal hepatotoxicity limits use in women"],
 src=f"{W} ch.34; {K} (Antiandrogens)"),

dict(name="Combined oral contraceptives (in dermatology)", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Oestrogen (ethinylestradiol) + progestin combinations",
 moa=["Suppress ovarian androgen production (LH suppression), raise sex hormone-binding globulin (less free testosterone), reduce sebum",
      "Progestins with anti-androgenic action preferred: drospirenone, cyproterone, chlormadinone, dienogest; avoid androgenic progestins (levonorgestrel, norgestrel)"],
 uses=["Acne in women (FDA-approved COCs: drospirenone, norgestimate, norethindrone acetate/ferrous fumarate combinations)",
       "Hirsutism, PCOS, female pattern hair loss, hidradenitis suppurativa",
       "Contraception during teratogenic therapy (isotretinoin, acitretin, thalidomide, spironolactone)"],
 dose=["One tablet daily (21/7 or 24/4 regimens); acne improves after 3–6 cycles"],
 ae=["Venous thromboembolism (higher with drospirenone/cyproterone than levonorgestrel), stroke/MI (smokers >35)",
     "Nausea, breast tenderness, breakthrough bleeding, mood change, melasma (can worsen), erythema nodosum, photosensitivity, spider angiomas",
     "Hypertension"],
 ci=["Thrombosis history or thrombophilia, smokers over 35, migraine with aura, uncontrolled hypertension, liver disease, oestrogen-dependent cancer, breastfeeding <6 weeks"],
 ix=["Enzyme inducers (rifampicin, griseofulvin, carbamazepine, efavirenz) reduce efficacy",
     "Tetracyclines: no clinically significant reduction (except rifampicin) per current evidence"],
 mon=["BP, migraine history, smoking status"],
 preg="Stop if pregnant.",
 viva=["Choose anti-androgenic progestins for acne",
       "Melasma and erythema nodosum can be caused by COCs",
       "Rifampicin and griseofulvin reduce efficacy"],
 src=f"{W} ch.34; {K} (Antiandrogens — oral contraceptives)"),

dict(name="Glycopyrrolate & propantheline (oral + topical glycopyrronium)", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Quaternary ammonium antimuscarinics (anticholinergics) — poor CNS penetration",
 moa=["Block muscarinic (M3) receptors on eccrine sweat glands (sympathetic cholinergic innervation) → reduced sweating"],
 uses=["Hyperhidrosis (generalised, craniofacial, compensatory, palmoplantar) — oral glycopyrrolate or propantheline",
       "Topical glycopyrronium tosylate 2.4% cloth (axillary hyperhidrosis, approved USA), 1% cream (Europe), iontophoresis with glycopyrrolate solution for refractory palmar hyperhidrosis",
       "Drooling (sialorrhoea), anaesthetic premedication"],
 dose=["Glycopyrrolate 1–2 mg once or twice daily (titrate); propantheline 15 mg three times daily",
       "Topical cloth once daily to both axillae"],
 ae=["Dry mouth (most common), blurred vision (mydriasis), constipation, urinary retention, tachycardia, heat intolerance (risk of heat stroke)",
     "Topical: local irritation, transient mydriasis if touched to eyes"],
 ci=["Glaucoma, myasthenia gravis, obstructive uropathy, paralytic ileus, severe ulcerative colitis, tachyarrhythmia"],
 ix=["Other anticholinergics (TCAs, antihistamines); potassium chloride tablets (GI lesions)"],
 preg="Limited data — avoid.",
 viva=["Quaternary amine — fewer CNS effects than atropine",
       "Hyperhidrosis treatment ladder: topical aluminium chloride → iontophoresis → botulinum toxin → oral anticholinergics → sympathectomy"],
 src=f"{K} (Glycopyrrolate and propantheline bromide); {W} ch.57"),

dict(name="Stanozolol & danazol (attenuated androgens)", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Synthetic anabolic steroids with fibrinolytic activity",
 moa=["Increase hepatic synthesis of C1-esterase inhibitor (hereditary angioedema prophylaxis)",
      "Enhance fibrinolysis (stanozolol) — used in lipodermatosclerosis and cryofibrinogenaemia"],
 uses=["Hereditary angioedema long-term prophylaxis (older choice; now C1-INH, lanadelumab, berotralstat preferred)",
       "Lipodermatosclerosis, livedoid vasculopathy, cryofibrinogenaemia (stanozolol — off-label; withdrawn in many countries)",
       "Raynaud, chronic urticaria (danazol — limited)"],
 dose=["Stanozolol 2–5 mg twice daily (historic); danazol 200 mg/day (HAE, reduce to lowest effective)"],
 ae=["Virilisation in women (hirsutism, acne, voice change), menstrual irregularity",
     "Hepatotoxicity, peliosis hepatis, hepatic adenoma; dyslipidaemia; fluid retention, hypertension"],
 ci=["Pregnancy, children, liver disease, prostate/breast cancer"],
 ix=["Warfarin (INR rises), cyclosporine levels rise"],
 mon=["LFT, lipids, liver ultrasound (long-term)"],
 preg="Contraindicated.",
 viva=["Androgens raise C1-INH levels in hereditary angioedema",
       "Stanozolol in lipodermatosclerosis (fibrinolytic)"],
 src=f"{K} (Stanozolol); {W} ch.40"),

dict(name="Calcium dobesilate", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Vasoprotective (angioprotective) agent",
 moa=["Reduces capillary permeability and fragility, improves blood viscosity and lymphatic drainage; inhibits VEGF and FGF signalling (anti-angiogenic) — also studied topically in rosacea"],
 uses=["Chronic venous insufficiency, stasis dermatitis (adjunct), haemorrhoids, diabetic retinopathy (Europe)",
       "Pigmented purpuric dermatoses (limited evidence)"],
 dose=["500 mg two to three times daily"],
 ae=["GI upset, skin rash, arthralgia",
     "Agranulocytosis (rare but serious) — stop if fever, sore throat"],
 ci=["Hypersensitivity; history of agranulocytosis"],
 preg="Avoid (limited data).",
 viva=["Venotonic for capillary fragility; agranulocytosis is rare but important"],
 src=f"{K} (Calcium dobesilate)"),

dict(name="Low molecular weight dextran", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Plasma expander (dextran 40) with rheological (anti-sludging) effects",
 moa=["Reduces blood viscosity and red-cell aggregation, coats platelets and endothelium → improves microcirculation"],
 uses=["Historically in livedoid vasculopathy, Raynaud phenomenon/digital ischaemia, frostbite, necrotic ulcers due to microvascular occlusion, pyoderma gangrenosum (adjunct)"],
 dose=["500 mL of 10% dextran 40 IV infusion daily for a few days (historic regimens)"],
 ae=["Anaphylactoid reactions (dextran-reactive antibodies), fluid overload, renal failure, bleeding tendency (platelet coating)"],
 ci=["Heart failure, renal failure, bleeding disorders, dextran allergy"],
 preg="Avoid unless essential.",
 viva=["Improves microcirculation — historical use in livedoid vasculopathy and digital ischaemia"],
 src=f"{K} (Miscellaneous agents — low molecular weight dextran)"),

dict(name="Allopurinol", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Xanthine oxidase inhibitor",
 moa=["Inhibits xanthine oxidase → lowers uric acid; also inhibits Leishmania purine salvage (allopurinol riboside is toxic to parasite)"],
 uses=["Gout and tophi; prevention of tumour lysis",
       "Dermatology (off-label, historic): cutaneous leishmaniasis (with antimonials), sarcoidosis, reactive perforating collagenosis, granuloma annulare"],
 dose=["100–300 mg/day (start low, especially in renal impairment)"],
 ae=["Severe cutaneous adverse reactions: DRESS, SJS/TEN — allopurinol is the commonest cause of SJS/TEN in many countries; strongly linked to HLA-B*58:01 (screen in Han Chinese, Korean, Thai patients)",
     "Rash, hepatitis, interstitial nephritis, vasculitis"],
 ci=["Previous allopurinol hypersensitivity; HLA-B*58:01 positive (if tested)"],
 ix=["Azathioprine/6-mercaptopurine: severe myelosuppression — reduce azathioprine to 25% or avoid",
     "Ampicillin/amoxicillin: more rash; thiazides (hypersensitivity); cyclophosphamide (marrow toxicity)"],
 mon=["Renal function (start low), CBC, LFT; warn about rash in the first 8 weeks"],
 preg="Avoid unless essential.",
 viva=["Top cause of SJS/TEN and DRESS — HLA-B*58:01",
       "Allopurinol + azathioprine = severe marrow suppression"],
 src=f"{K} (Allopurinol); {W} ch.66 and ch.67"),

dict(name="Placental extract (injection + topical gel)", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Aqueous extract of human placenta (biogenic stimulator; e.g. Placentrex)",
 moa=["Contains nucleotides, peptides, enzymes and growth factors claimed to stimulate wound healing, melanogenesis and tissue regeneration (mechanism not well established)"],
 uses=["Indian practice: chronic non-healing ulcers, burns, post-procedure healing (gel); vitiligo (older topical preparations — weak evidence); periodontitis, pelvic inflammatory disease (injection — historic)"],
 dose=["Injection 2 mL IM daily or alternate days (as per product); gel applied once or twice daily to wounds"],
 ae=["Injection-site pain, allergic reactions; theoretical risk of transmissible infection (human-derived)"],
 ci=["Hypersensitivity"],
 preg="Avoid (insufficient data).",
 viva=["Indian biogenic product; evidence is weak — mention as an adjunct only"],
 src=f"{K} (Placental extract)"),

dict(name="Botulinum toxin type A", group="More from Khopkar · Miscellaneous systemic drugs",
 cls="Neurotoxin from Clostridium botulinum (onabotulinum-, abobotulinum-, incobotulinumtoxin A)",
 moa=["Heavy chain binds cholinergic nerve terminals; light chain (zinc protease) cleaves SNAP-25 → acetylcholine cannot be released",
      "Result: temporary chemodenervation of muscles (3–4 months) and eccrine sweat glands (6–9 months or longer)"],
 uses=["Hyperhidrosis: axillary (approved), palmar, plantar, craniofacial, compensatory",
       "Aesthetic: glabellar lines, crow's feet, forehead lines, platysmal bands, masseter hypertrophy, gummy smile",
       "Others: Hailey–Hailey and Darier disease (reduces sweating-triggered flares), rosacea flushing, keloids (adjunct), Raynaud phenomenon, Frey syndrome, anal fissure",
       "Microbotox/mesotherapy (intradermal dilute injections) for skin texture and sebum"],
 dose=["Axillary hyperhidrosis: 50 U onabotulinumtoxin A per axilla intradermally (after starch–iodine test)",
       "Glabellar lines: 20 U (5 sites × 4 U)",
       "Reconstitute with preservative-free (or preserved for less pain) saline; units are not interchangeable between brands (abobotulinum ~2.5–3 × onabotulinum units)"],
 ae=["Injection pain, bruising, headache",
     "Spread to adjacent muscles: ptosis (eyelid — use apraclonidine drops), brow ptosis, asymmetric smile, hand weakness (palmar injections)",
     "Antibody formation (non-response) with frequent high doses",
     "Distant spread (rare): dysphagia, breathing difficulty — boxed warning"],
 ci=["Neuromuscular disorders (myasthenia gravis, Lambert–Eaton, ALS), infection at site, pregnancy and breastfeeding, allergy to albumin"],
 ix=["Aminoglycosides, quinine, calcium-channel blockers, other neuromuscular blockers potentiate effect"],
 preg="Avoid (insufficient data).",
 viva=["Cleaves SNAP-25 → blocks acetylcholine release",
       "Sweat effect lasts longer than muscle effect",
       "Brand units are not interchangeable",
       "Ptosis — treat with apraclonidine eye drops"],
 src=f"{W} ch.60 (Botulinum toxin injections); {K} ch.35 (Botulinum toxin; mesotherapy)"),
]
