# Exam drugs — slot 1: Oral I–V (retinoids, antibiotics, antifungals, antivirals/ART, antiparasitic)
# Sources: Wolverton, Comprehensive Dermatologic Drug Therapy 4e (W) and Khopkar, Handbook of Dermatological Drug Therapy (K).
# Wolverton wins where they differ. Written in our own words.
W = "Wolverton 4e"; K = "Khopkar"
D = [
# ---------------- I RETINOIDS ----------------
dict(name="Isotretinoin", group="Oral · I Retinoids",
 cls="First-generation (non-aromatic) retinoid; 13-cis-retinoic acid",
 moa=["Acts mainly through its metabolites on nuclear retinoic acid receptors (RAR) to change gene transcription",
      "Shrinks sebaceous glands and cuts sebum output by up to ~90%; this is the only acne drug that does this",
      "Normalises follicular keratinisation, so fewer microcomedones",
      "Indirectly reduces C. acnes because the follicle becomes less favourable for it; also anti-inflammatory"],
 pk=["Bioavailability about 25%; roughly doubles when taken with a fatty meal (a lidose form, Absorica, is less food-dependent)",
     "99% bound to albumin; half-life 10–20 h; main metabolite 4-oxo-isotretinoin",
     "Metabolised in the liver, excreted in bile and urine; not stored in fat, so it clears in about 1 month"],
 uses=["Severe nodulocystic acne (approved use)",
       "Moderate acne that fails oral antibiotics, scarring acne, or acne causing marked distress",
       "Rosacea (papulopustular, phymatous; low dose), Gram-negative folliculitis",
       "Hidradenitis suppurativa and dissecting cellulitis (limited benefit)",
       "Sebaceous hyperplasia; chemoprevention of skin cancer in xeroderma pigmentosum (high dose)",
       "Disorders of keratinisation such as Darier disease and PRP (acitretin usually preferred)"],
 dose=["Acne: 0.5–1 mg/kg/day in 1–2 doses with food",
       "Aim for a total (cumulative) dose of 120–150 mg/kg; relapse is higher below 120 mg/kg",
       "Start low (e.g. 0.25–0.5 mg/kg) in severe or nodular acne to avoid an early flare",
       "Low-dose regimens (≈0.25–0.4 mg/kg/day) are used for moderate acne and rosacea",
       "Capsules 10, 20, 40 mg"],
 ae=["Mucocutaneous (almost universal): cheilitis — the earliest and most constant sign, often used as a marker of adherence; dry skin, dry nose with epistaxis, dry eyes and conjunctivitis, retinoid dermatitis",
     "Initial flare of acne; excess granulation tissue (pyogenic-granuloma-like) in nail folds or acne lesions",
     "Hair thinning, paronychia, photosensitivity",
     "Lipids: raised triglycerides (common); a rapid rise above 800–1000 mg/dL can cause pancreatitis",
     "Raised transaminases (usually mild and reversible)",
     "Musculoskeletal: myalgia and back pain; hyperostosis and premature epiphyseal closure with long, high-dose courses",
     "CNS: headache; pseudotumor cerebri (idiopathic intracranial hypertension), especially with tetracyclines",
     "Mood change and depression or suicide have been reported; a causal link is not proven, but screen and ask at each visit",
     "Inflammatory bowel disease: reported, but no causal link shown",
     "Night blindness (reduced dark adaptation)",
     "Teratogenic: retinoid embryopathy (CNS, craniofacial, cardiac and thymic defects)"],
 ci=["Pregnancy (absolute) and breastfeeding",
     "Women unable to follow reliable contraception",
     "Hypersensitivity, including to soy or paraben in some capsule fillers",
     "Relative: marked hyperlipidaemia, significant liver disease, hypervitaminosis A, concurrent tetracycline"],
 ix=["Tetracyclines raise the risk of pseudotumor cerebri — avoid together",
     "Vitamin A supplements: additive toxicity",
     "Methotrexate and alcohol: added liver toxicity",
     "Progestin-only 'mini-pill' is not reliable contraception during therapy",
     "Carbamazepine levels may fall"],
 mon=["Women: 2 negative pregnancy tests before starting, then monthly, and 1 month after stopping",
      "Fasting lipids and LFTs at baseline and after about 1–2 months on the target dose; repeat only if abnormal or the dose rises",
      "CBC is not routinely needed",
      "At every visit: mood, headache or visual change, back pain"],
 preg="Absolute contraindication (old FDA category X). Two methods of contraception from 1 month before, throughout, and for 1 month after stopping. No blood donation during treatment or for 1 month after. Avoid in breastfeeding.",
 viva=["Isotretinoin is the only acne drug that hits all four pathogenic factors: sebum, keratinisation, C. acnes and inflammation",
       "Cheilitis is the most common side effect; its absence suggests poor adherence",
       "Do not combine with tetracyclines (pseudotumor cerebri)",
       "Cumulative dose of 120–150 mg/kg reduces relapse",
       "Traditional advice was to delay waxing, dermabrasion and laser for 6 months; newer consensus says superficial procedures are probably acceptable — mention both"],
 src=f"{W} ch.22 (Systemic retinoids); {K} (Oral retinoids)"),

dict(name="Acitretin", group="Oral · I Retinoids",
 cls="Second-generation (mono-aromatic) retinoid; active metabolite of etretinate",
 moa=["Binds nuclear RAR and RXR receptors and changes gene transcription",
      "Normalises epidermal proliferation and differentiation",
      "Anti-inflammatory: reduces neutrophil migration (hence its good effect in pustular psoriasis)",
      "Not immunosuppressive — useful in HIV-associated psoriasis and in transplant recipients"],
 pk=["Bioavailability about 60%, better with food; 95% albumin bound; half-life about 50 h",
     "With alcohol it is re-esterified to etretinate, which is stored in fat and has a half-life of 80–160 days",
     "This is why contraception must continue for years after stopping"],
 uses=["Psoriasis: pustular (generalised and palmoplantar) and erythrodermic respond best to monotherapy",
       "Plaque psoriasis: modest alone; much better combined with phototherapy (Re-PUVA, Re-NB-UVB), which also lowers UV dose",
       "Disorders of keratinisation: ichthyoses (lamellar, epidermolytic), Darier disease, PRP, palmoplantar keratoderma",
       "Hypertrophic and palmoplantar lichen planus; hypertrophic lupus erythematosus",
       "Chemoprevention of squamous cell carcinoma in organ-transplant recipients"],
 dose=["Adults: 25–50 mg once daily with the main meal (start at 25 mg; avoid high starting doses)",
       "Lower doses (10–25 mg) are often enough when combined with phototherapy",
       "Children (keratinisation disorders): about 0.5–1 mg/kg/day, using the lowest dose that works",
       "Capsules 10, 25 mg; full response in psoriasis may take 3–6 months"],
 ae=["Mucocutaneous: cheilitis, xerosis, 'sticky' skin, peeling of palms and soles, retinoid dermatitis, paronychia, pyogenic granuloma",
     "Hair loss (telogen effluvium, dose-related) is commoner than with isotretinoin",
     "Raised triglycerides and cholesterol; raised transaminases (rarely toxic hepatitis)",
     "Bone: DISH-like hyperostosis, extraspinal calcification, premature epiphyseal closure in children on long courses",
     "Pseudotumor cerebri, night blindness, myalgia",
     "Teratogenic (long-lasting because of etretinate formation)"],
 ci=["Pregnancy, and women who may become pregnant within 3 years of stopping",
     "Breastfeeding; severe liver or kidney disease; chronic alcohol use; marked hyperlipidaemia",
     "Concurrent methotrexate (risk of hepatitis) or tetracyclines (pseudotumor cerebri)"],
 ix=["Alcohol → conversion to etretinate (long-lasting teratogenicity)",
     "Methotrexate: severe hepatotoxicity — avoid",
     "Tetracyclines: pseudotumor cerebri",
     "Progestin-only pill becomes unreliable",
     "Vitamin A: additive toxicity; phenytoin displaced from protein binding"],
 mon=["Pregnancy tests: before, monthly during treatment, and periodically for 3 years after stopping",
      "Lipids and LFTs at baseline, then every 1–2 weeks for the first 1–2 months, then every 3 months",
      "Children on long courses: watch growth; X-ray only if bone symptoms appear"],
 preg="Absolute contraindication (old FDA category X). Contraception from 1 month before, throughout, and for 3 years after stopping. No alcohol during treatment and for 2 months after. No blood donation for 3 years.",
 viva=["Best indications are pustular and erythrodermic psoriasis; for plaques, combine with UV (Re-PUVA)",
       "Alcohol turns acitretin into etretinate — hence 3 years of contraception",
       "It is not immunosuppressive, so it is safe in HIV and in transplant recipients",
       "Never combine with methotrexate"],
 src=f"{W} ch.22; {K} (Oral retinoids)",
 note="Some Indian and European texts give 2 years of contraception after acitretin; Wolverton (US label) gives 3 years, which we follow."),

# ---------------- II ANTIBIOTICS ----------------
dict(name="Doxycycline", group="Oral · II Antibiotics — a) Tetracyclines",
 cls="Second-generation semisynthetic tetracycline (lipophilic)",
 moa=["Antibacterial: binds the 30S ribosomal subunit and blocks aminoacyl-tRNA attachment → stops protein synthesis (bacteriostatic)",
      "Anti-inflammatory (independent of antibacterial action): inhibits matrix metalloproteinases, neutrophil chemotaxis, and pro-inflammatory cytokines",
      "This anti-inflammatory action is the basis of sub-antimicrobial dosing in rosacea"],
 pk=["Well absorbed (about 95%); food reduces absorption only slightly, but iron, calcium, magnesium, aluminium, zinc and bismuth chelate it",
     "Half-life 18–22 h → once- or twice-daily dosing",
     "Excreted mainly through the gut, so it is the safest tetracycline in renal failure"],
 uses=["Acne vulgaris (moderate–severe inflammatory) — always with topical benzoyl peroxide or retinoid; limit to 3–4 months",
       "Rosacea (papulopustular), perioral dermatitis",
       "Bullous pemphigoid (anti-inflammatory, often with nicotinamide)",
       "STIs: chlamydia/NGU, LGV, donovanosis, early and late syphilis when penicillin cannot be used",
       "Community MRSA skin infections, Lyme disease, rickettsial infections, Mycobacterium marinum",
       "Hidradenitis suppurativa; filariasis (kills Wolbachia); confluent and reticulated papillomatosis"],
 dose=["Acne/rosacea: 50–100 mg once or twice daily",
       "Sub-antimicrobial: 40 mg modified-release once daily, or 20 mg twice daily (rosacea)",
       "Chlamydia/NGU: 100 mg twice daily × 7 days; LGV: 100 mg twice daily × 21 days",
       "Early syphilis (penicillin allergy): 100 mg twice daily × 14 days; late latent: × 28 days",
       "Donovanosis: 100 mg twice daily for at least 3 weeks and until lesions heal",
       "Take with a full glass of water, sitting upright, not at bedtime"],
 ae=["GI upset; pill oesophagitis (take upright with water)",
     "Phototoxicity, including photo-onycholysis — the most phototoxic of the commonly used tetracyclines",
     "Tooth staining and enamel hypoplasia in children under 8 years (less than older tetracyclines)",
     "Pseudotumor cerebri; vaginal candidiasis",
     "Rare: hepatotoxicity, hypersensitivity"],
 ci=["Pregnancy (after about 15 weeks) and breastfeeding (long courses)",
     "Children under 8 years (except short courses for serious infections such as rickettsial disease)",
     "Concurrent isotretinoin or acitretin; known hypersensitivity"],
 ix=["Antacids, iron, calcium, zinc, magnesium, bismuth, milk: reduce absorption — separate by 2–3 h",
     "Isotretinoin/acitretin: pseudotumor cerebri",
     "Rifampicin, carbamazepine, phenytoin, barbiturates: lower doxycycline levels",
     "Warfarin: effect may increase"],
 mon=["No routine blood tests for courses used in acne",
      "Counsel about sun protection and correct swallowing"],
 preg="Avoid (old FDA category D): tooth discolouration and bone effects after about 15 weeks. Short courses in breastfeeding are generally acceptable; avoid long courses.",
 viva=["Safest tetracycline in renal failure (gut excretion)",
       "Most phototoxic of the common tetracyclines; photo-onycholysis",
       "Sub-antimicrobial 40 mg MR works by anti-inflammatory action and does not select resistance",
       "Never combine with isotretinoin"],
 src=f"{W} ch.9 (Systemic antibacterial agents); {K} ch.1",
 note="Khopkar says doxycycline lacks the anti-inflammatory effect of tetracycline. Wolverton describes clear anti-inflammatory actions (the basis of sub-antimicrobial dosing). We follow Wolverton."),

dict(name="Minocycline", group="Oral · II Antibiotics — a) Tetracyclines",
 cls="Second-generation semisynthetic tetracycline — the most lipophilic",
 moa=["Binds the 30S ribosome and blocks protein synthesis (bacteriostatic)",
      "Anti-inflammatory: inhibits MMPs, neutrophil chemotaxis and lymphocyte activity",
      "High lipophilicity → good penetration into the pilosebaceous unit, CNS and skin"],
 pk=["Almost completely absorbed; food has little effect; still chelated by metal ions",
     "Half-life 11–22 h; metabolised mainly in the liver"],
 uses=["Acne vulgaris (second choice after doxycycline because of its safety profile)",
       "Leprosy: part of the ROM regimen (rifampicin, ofloxacin, minocycline) and an alternative drug",
       "Atypical mycobacteria (especially M. marinum), Nocardia, community MRSA",
       "Rosacea; anti-inflammatory use in bullous pemphigoid, sarcoidosis, CARP"],
 dose=["Acne: 50–100 mg twice daily, or extended-release 1 mg/kg once daily",
       "Leprosy: 100 mg daily (alternative regimens); ROM monthly: 100 mg as part of the single monthly dose"],
 ae=["Vestibular toxicity (dizziness, vertigo, ataxia) — commoner in women",
     "Hyperpigmentation — Type I: blue-black in scars and inflamed sites (iron/haemosiderin stains); Type II: blue-grey on normal skin of shins and forearms (iron and melanin); Type III: muddy-brown diffuse in sun-exposed skin (melanin)",
     "Pigmentation can also affect teeth (even adult teeth), nails, sclera, oral mucosa, thyroid ('black thyroid') and bone",
     "Autoimmune: drug-induced lupus (often p-ANCA positive), autoimmune hepatitis, serum-sickness-like reaction, polyarteritis-like vasculitis",
     "Hypersensitivity syndrome (DRESS) in the first weeks, pneumonitis",
     "Less phototoxic than doxycycline; pseudotumor cerebri"],
 ci=["Pregnancy, breastfeeding, children under 8 years",
     "Lupus or autoimmune hepatitis history; concurrent oral retinoids"],
 ix=["Metal ions and antacids reduce absorption",
     "Isotretinoin/acitretin: pseudotumor cerebri",
     "Warfarin effect may increase"],
 mon=["No routine tests for short courses",
      "For courses beyond a few months: watch for pigmentation, joint pain, rash, and check LFT/ANA if symptoms"],
 preg="Avoid (old FDA category D). Avoid in breastfeeding.",
 viva=["Most lipophilic tetracycline → vestibular side effects and best CNS penetration",
       "Three types of pigmentation — be able to describe them",
       "Autoimmune side effects: drug-induced lupus and autoimmune hepatitis",
       "Least phototoxic of the commonly used tetracyclines",
       "Used in leprosy (ROM)"],
 src=f"{W} ch.9; {K} ch.1"),

dict(name="Lymecycline", group="Oral · II Antibiotics — a) Tetracyclines",
 cls="Second-generation tetracycline (tetracycline–lysine compound)",
 moa=["Same as other tetracyclines: binds the 30S ribosome and blocks protein synthesis",
      "Has anti-inflammatory effects useful in acne"],
 pk=["Much more water-soluble and better absorbed than tetracycline; food has less effect on absorption",
     "Allows once-daily dosing; half-life about 10 h; excreted mainly through the kidneys"],
 uses=["Acne vulgaris (moderate inflammatory) — with topical benzoyl peroxide or retinoid",
       "Rosacea (papulopustular)"],
 dose=["408 mg capsule (equivalent to 300 mg tetracycline base) once daily, usually for 8–12 weeks"],
 ae=["GI upset, headache",
     "Photosensitivity (less than doxycycline)",
     "Tooth staining in children; pseudotumor cerebri; vaginal candidiasis"],
 ci=["Pregnancy, breastfeeding, children under 12 (label in Europe/India)",
     "Significant renal impairment (renally excreted)",
     "Concurrent oral retinoids"],
 ix=["Metal ions and antacids reduce absorption",
     "Oral retinoids: pseudotumor cerebri",
     "Warfarin effect may increase"],
 mon=["No routine blood tests"],
 preg="Avoid in pregnancy and breastfeeding (tetracycline class effect).",
 viva=["Once-daily tetracycline widely used for acne in Europe and India",
       "Unlike doxycycline, it is renally excreted — avoid in renal failure"],
 src="Not covered separately in Wolverton or Khopkar; class information from Wolverton ch.9, details from product information",
 note="Neither book has a separate lymecycline section. Please check this one against your notes."),

dict(name="Azithromycin", group="Oral · II Antibiotics — b) Macrolide",
 cls="Azalide (15-membered macrolide)",
 moa=["Binds the 50S ribosomal subunit (23S rRNA) and blocks translocation → stops protein synthesis",
      "Bacteriostatic; can be bactericidal at high concentrations",
      "Also anti-inflammatory (reduces neutrophil activity and cytokines)"],
 pk=["Acid-stable; very high tissue and intracellular levels (concentrated in phagocytes, which carry it to infected sites)",
     "Very long tissue half-life (about 68 h) → single-dose or short-course regimens",
     "Mostly excreted unchanged in bile; little CYP3A4 inhibition (fewer interactions than erythromycin)"],
 uses=["STIs: chlamydia/NGU, chancroid, donovanosis, gonorrhoea (with ceftriaxone in some guidelines), early syphilis in special situations",
       "Skin and soft tissue infections; pyodermas in penicillin allergy",
       "Acne (pulse regimens) — used in India, but no better than doxycycline and promotes resistance",
       "Rosacea; trachoma; scrub typhus"],
 dose=["Chlamydia/NGU: 1 g single dose",
       "Chancroid: 1 g single dose",
       "Donovanosis: 1 g once weekly, or 500 mg daily, for at least 3 weeks and until healed",
       "Early syphilis: 2 g single dose (resistance is common — penicillin remains first choice)",
       "Skin infection: 500 mg on day 1, then 250 mg daily on days 2–5",
       "Children: 10 mg/kg/day"],
 ae=["GI upset (less than erythromycin), diarrhoea",
     "QT prolongation and arrhythmia (caution in heart disease or with other QT drugs)",
     "Cholestatic hepatitis (rare), hearing loss with long high-dose courses",
     "Rash, rarely SJS/TEN; C. difficile colitis"],
 ci=["Hypersensitivity to macrolides",
     "History of cholestatic jaundice with azithromycin",
     "Caution: long QT, hypokalaemia, severe liver disease"],
 ix=["Other QT-prolonging drugs (fluoroquinolones, antipsychotics, hydroxychloroquine)",
     "Antacids reduce peak levels",
     "Warfarin and digoxin levels may rise (less than with erythromycin or clarithromycin)"],
 mon=["None routinely; ECG if cardiac risk factors"],
 preg="Considered safe in pregnancy (old FDA category B); used for chlamydia in pregnancy. Compatible with breastfeeding.",
 viva=["Long tissue half-life makes single-dose STI treatment possible",
       "Least CYP3A4 inhibition among macrolides",
       "Part of the NACO STI kits (e.g. kit 1 with cefixime) — check the slot-2 STI kits post",
       "Azithromycin-resistant Treponema pallidum is widespread, so it is not first-line for syphilis"],
 src=f"{W} ch.9; {K} ch.1 (Macrolides)"),

dict(name="Metronidazole", group="Oral · II Antibiotics — c) Nitroimidazole",
 cls="5-nitroimidazole antimicrobial and antiprotozoal",
 moa=["Prodrug: its nitro group is reduced inside anaerobic bacteria and protozoa",
      "The reduced reactive intermediates damage DNA → cell death (bactericidal)",
      "Active against anaerobes, Trichomonas, Giardia and Entamoeba; inactive against aerobes"],
 pk=["Nearly 100% oral bioavailability; wide distribution including CSF, abscesses, vaginal secretions",
     "Half-life about 8 h; metabolised in the liver; excreted in urine (can turn urine dark)"],
 uses=["Trichomoniasis (patient and partner)",
       "Bacterial vaginosis; part of PID regimens; vaginal discharge syndrome kits",
       "Amoebiasis (including cutaneous amoebiasis), giardiasis",
       "Anaerobic skin infections, infected ulcers, fungating tumours (also topical for odour)",
       "Rosacea (mainly topical gel); perianal Crohn's disease; dracunculiasis"],
 dose=["Trichomoniasis: 2 g single dose (men); 500 mg twice daily × 7 days (women, preferred)",
       "Bacterial vaginosis: 500 mg twice daily × 7 days",
       "Amoebiasis: 750 mg three times daily × 7–10 days",
       "Anaerobic infections: 400–500 mg three times daily"],
 ae=["Metallic taste, nausea, anorexia, dry mouth",
     "Disulfiram-like reaction with alcohol (flushing, vomiting, headache, palpitations)",
     "Dark urine",
     "Peripheral neuropathy and seizures with high doses or long courses; aseptic meningitis; encephalopathy",
     "Fixed drug eruption; reversible neutropenia"],
 ci=["Alcohol during treatment and for 72 h after (some sources say 48 h)",
     "Recent disulfiram use (within 2 weeks): risk of psychosis",
     "First trimester: high-dose single-dose regimen best avoided; active neurological disease"],
 ix=["Alcohol: disulfiram-like reaction",
     "Warfarin: markedly increased INR",
     "Lithium, phenytoin, busulfan, 5-FU: levels may rise",
     "Phenobarbital, rifampicin: lower metronidazole levels"],
 mon=["CBC and neurological review if courses exceed 10 days"],
 preg="Old FDA category B; current guidelines allow use in all trimesters for trichomoniasis and BV. For the 2 g single dose in breastfeeding, pause breastfeeding for 12–24 h.",
 viva=["Prodrug activated only in anaerobes — hence selective toxicity",
       "Avoid alcohol for 72 h (disulfiram-like reaction)",
       "Trichomoniasis: always treat the partner",
       "Commonly causes fixed drug eruption"],
 src=f"{W} ch.9; {K} ch.1 and ch.5"),

# ---------------- III ANTIFUNGALS ----------------
dict(name="Griseofulvin", group="Oral · III Antifungals",
 cls="Benzofuran fungistatic antibiotic (from Penicillium griseofulvum)",
 moa=["Binds microtubule proteins (tubulin) and disrupts the mitotic spindle → arrests fungal cell division in metaphase",
      "Deposited in keratin precursor cells, so new keratin resists infection",
      "Active only against dermatophytes; no effect on Candida, Malassezia or deep fungi"],
 pk=["Poorly water-soluble; absorption improves with a fatty meal and with smaller particle size",
     "Microsize and ultramicrosize forms are not interchangeable mg-for-mg (ultramicrosize is better absorbed)",
     "Half-life 9–24 h; reaches the stratum corneum through sweat; washes out quickly after stopping",
     "Metabolised in the liver; a CYP inducer"],
 uses=["Tinea capitis — especially Microsporum infections (first choice), and children",
       "Extensive tinea corporis/cruris when other drugs are unavailable",
       "Not suitable for onychomycosis (needs 12–18 months, poor cure)",
       "Rarely used for anti-inflammatory purposes (lichen planus, etc.)"],
 dose=["Children (tinea capitis): microsize 20–25 mg/kg/day, or ultramicrosize 10–15 mg/kg/day, with fatty food, for at least 6–8 weeks",
       "Adults: microsize 500 mg–1 g/day (ultramicrosize 375–750 mg/day)",
       "Tinea corporis: 2–4 weeks; tinea pedis: 4–8 weeks"],
 ae=["Headache (most common; often settles)",
     "GI upset, taste disturbance",
     "Photosensitivity; can precipitate or worsen lupus erythematosus and acute porphyria",
     "Urticaria, morbilliform rash, fixed drug eruption, rarely SJS/TEN",
     "Hepatotoxicity, leukopenia, proteinuria (rare)",
     "Disulfiram-like reaction with alcohol"],
 ci=["Pregnancy; men should not father children during treatment and for 6 months after",
     "Porphyria, hepatic failure, systemic lupus"],
 ix=["Enzyme inducer: reduces efficacy of oral contraceptives, warfarin, cyclosporine",
     "Phenobarbital reduces griseofulvin absorption",
     "Alcohol: disulfiram-like reaction"],
 mon=["CBC and LFT only for prolonged courses",
      "Advise extra contraception"],
 preg="Contraindicated (old FDA category X) — teratogenic and embryotoxic.",
 viva=["Fungistatic; acts on the mitotic spindle",
       "Drug of choice for Microsporum tinea capitis; terbinafine is better for Trichophyton tonsurans",
       "Give with a fatty meal (e.g. milk)",
       "Ineffective against Candida and Malassezia",
       "Enzyme inducer — reduces oral contraceptive efficacy"],
 src=f"{W} ch.10 (Systemic antifungal agents), Table 10.5; {K} ch.2"),

dict(name="Terbinafine", group="Oral · III Antifungals",
 cls="Allylamine antifungal",
 moa=["Inhibits squalene epoxidase, an early step in ergosterol synthesis",
      "Toxic build-up of squalene inside the cell → fungicidal against dermatophytes",
      "Ergosterol deficiency adds a fungistatic effect (mainly against yeasts)"],
 pk=["70–80% absorbed; food does not matter",
     "Highly lipophilic and keratophilic; reaches the stratum corneum via sebum and the nail via the matrix",
     "Persists in nails for weeks to months after stopping; long terminal half-life",
     "Metabolised in the liver; inhibits CYP2D6"],
 uses=["Dermatophytosis: tinea corporis, cruris, pedis and manuum",
       "Onychomycosis caused by dermatophytes (drug of choice)",
       "Tinea capitis — especially Trichophyton tonsurans (less effective for Microsporum)",
       "Some activity in sporotrichosis, chromoblastomycosis; poor against Candida and Malassezia orally"],
 dose=["Adults: 250 mg once daily",
       "Tinea corporis/cruris: 2–4 weeks (often longer in India due to resistance — follow current national consensus)",
       "Onychomycosis: fingernails 6 weeks, toenails 12 weeks",
       "Tinea capitis (children): 10–20 kg 62.5 mg; 21–40 kg 125 mg; over 40 kg 250 mg daily, for 2–6 weeks (T. tonsurans)"],
 ae=["GI upset, headache",
     "Taste disturbance (can last weeks), loss of smell",
     "Rash, urticaria; rarely SJS/TEN, AGEP, DRESS",
     "Induction or worsening of subacute cutaneous lupus; worsening of psoriasis",
     "Hepatotoxicity — rare but can be severe (cholestatic or hepatitic; liver failure reported)",
     "Neutropenia, depression (rare)"],
 ci=["Chronic or active liver disease",
     "Severe renal impairment (clearance under 50 mL/min — avoid or reduce dose)",
     "Lupus erythematosus (relative)"],
 ix=["CYP2D6 inhibition: raises levels of tricyclic antidepressants, some SSRIs, beta-blockers (metoprolol), codeine activation reduced",
     "Rifampicin lowers terbinafine levels; cimetidine raises them"],
 mon=["Baseline LFT (as advised by the label); repeat if courses exceed 6 weeks or symptoms of liver injury",
      "CBC if course exceeds 6 weeks"],
 preg="Old FDA category B, but because it is not urgent, treatment of onychomycosis is postponed until after pregnancy and breastfeeding.",
 viva=["The only commonly used oral antifungal that is fungicidal",
       "Squalene epoxidase inhibition — not CYP450 dependent",
       "Inhibits CYP2D6, not CYP3A4 (unlike azoles)",
       "Squalene epoxidase gene mutations explain terbinafine resistance in T. indotineae seen in India"],
 src=f"{W} ch.10, Table 10.5; {K} ch.2"),

dict(name="Fluconazole", group="Oral · III Antifungals",
 cls="Triazole antifungal (first generation)",
 moa=["Inhibits fungal lanosterol 14-α-demethylase (CYP51), blocking ergosterol synthesis",
      "Fungistatic; membrane damage from accumulated toxic methylated sterols"],
 pk=["Water-soluble; about 90% bioavailable; absorption not affected by food or gastric acid",
     "Low protein binding; excellent CSF, eye and urine penetration",
     "Half-life about 30 h → weekly dosing possible",
     "Excreted unchanged in urine — reduce dose in renal failure"],
 uses=["Vulvovaginal, oropharyngeal and oesophageal candidiasis; candidal intertrigo and paronychia",
       "Pityriasis versicolor, Malassezia folliculitis",
       "Dermatophytosis and onychomycosis (alternative)",
       "Cryptococcosis (including meningitis, with amphotericin B first), coccidioidomycosis",
       "Prophylaxis in immunocompromised patients"],
 dose=["Vulvovaginal candidiasis: 150 mg single dose; recurrent: 150 mg every 72 h × 3 doses, then weekly for 6 months",
       "Oropharyngeal candidiasis: 100–200 mg/day × 7–14 days",
       "Tinea corporis: 150–300 mg once weekly × 2–4 weeks",
       "Pityriasis versicolor: 300 mg weekly × 2 weeks (or 400 mg single dose)",
       "Onychomycosis: 150–450 mg once weekly for 6–12 months",
       "Children: 3–6 mg/kg/day (tinea capitis 6 mg/kg/day)"],
 ae=["GI upset, headache",
     "Hepatotoxicity (usually mild)",
     "QT prolongation and torsades de pointes",
     "Alopecia with prolonged high doses",
     "Rash; fixed drug eruption (common in Indian practice); rarely SJS/TEN"],
 ci=["Hypersensitivity to azoles",
     "With QT-prolonging drugs metabolised by CYP3A4 (e.g. cisapride, pimozide, quinidine, erythromycin)",
     "Pregnancy (high-dose or prolonged use)"],
 ix=["Inhibits CYP2C9, CYP2C19 and (moderately) CYP3A4",
     "Raises levels of warfarin, phenytoin, sulfonylureas, cyclosporine, tacrolimus, some statins, benzodiazepines",
     "Rifampicin lowers fluconazole levels"],
 mon=["LFT for courses longer than a few weeks; ECG if other QT risks; renal function for dosing"],
 preg="Avoid. High-dose or prolonged use in the first trimester is linked to birth defects (old FDA category D); a single 150 mg dose was category C. Compatible with breastfeeding in usual doses.",
 viva=["Water-soluble azole — best CSF penetration, renal excretion",
       "Absorption is not acid-dependent (unlike itraconazole)",
       "Main enzyme inhibited for interactions: CYP2C9 (warfarin, phenytoin)",
       "Weekly dosing is possible because of the long half-life"],
 src=f"{W} ch.10; {K} ch.2"),

dict(name="Itraconazole", group="Oral · III Antifungals",
 cls="Triazole antifungal (first generation; lipophilic)",
 moa=["Inhibits fungal lanosterol 14-α-demethylase → ergosterol depletion",
      "Fungistatic; broad spectrum: dermatophytes, Candida, Malassezia, Aspergillus and dimorphic fungi"],
 pk=["Capsules need gastric acid and food — take with a full meal; avoid antacids and PPIs (or take with a cola drink)",
     "Oral solution is better absorbed on an empty stomach; super-bioavailable (SUBA) forms are less food-dependent",
     "Highly lipophilic and keratophilic; reaches skin via sebum and sweat and stays in nails for 6–9 months after stopping",
     "Half-life 24–42 h; metabolised by CYP3A4 (active metabolite hydroxy-itraconazole)"],
 uses=["Dermatophytosis (tinea corporis, cruris, pedis), onychomycosis (pulse therapy)",
       "Pityriasis versicolor, Malassezia folliculitis, seborrhoeic dermatitis",
       "Candidiasis (mucocutaneous, candida onychomycosis)",
       "Sporotrichosis (drug of choice for cutaneous forms), chromoblastomycosis, histoplasmosis, blastomycosis, paracoccidioidomycosis",
       "Aspergillosis (alternative)"],
 dose=["Tinea corporis/cruris: 100–200 mg/day × 2–4 weeks (longer courses at 200 mg/day are often needed in India)",
       "Onychomycosis pulse: 200 mg twice daily for 1 week each month — 2 pulses for fingernails, 3 for toenails",
       "Onychomycosis continuous: 200 mg/day × 12 weeks (toenails)",
       "Pityriasis versicolor: 200 mg/day × 5–7 days",
       "Sporotrichosis: 100–200 mg/day for 3–6 months",
       "Children: about 5 mg/kg/day"],
 ae=["GI upset, headache, rash",
     "Hepatotoxicity (rare but can be severe)",
     "Negative inotropic effect: can cause or worsen congestive heart failure (boxed warning)",
     "Hypokalaemia, hypertension, oedema (mineralocorticoid-like effect at high doses)",
     "QT prolongation; peripheral neuropathy (rare)"],
 ci=["Congestive heart failure or ventricular dysfunction (for nail infections)",
     "Pregnancy",
     "Concurrent CYP3A4 substrates with dangerous toxicity: simvastatin, lovastatin, midazolam/triazolam, cisapride, pimozide, quinidine, dofetilide, ergot alkaloids"],
 ix=["Potent CYP3A4 inhibitor (and P-glycoprotein inhibitor)",
     "Raises cyclosporine, tacrolimus, digoxin, warfarin, calcium-channel blockers, some benzodiazepines, colchicine",
     "Rifampicin, phenytoin, carbamazepine lower itraconazole levels; PPIs/H2 blockers/antacids reduce capsule absorption"],
 mon=["LFT at baseline and monthly if continuous therapy beyond 1 month",
      "Ask about heart failure symptoms"],
 preg="Avoid (old FDA category C); women should use contraception during treatment and for 2 months after. Avoid in breastfeeding.",
 viva=["Capsule absorption needs acid and food; solution on an empty stomach",
       "Pulse therapy works because the drug persists in the nail for months",
       "Contraindicated in congestive heart failure",
       "Potent CYP3A4 inhibitor — statin interaction (rhabdomyolysis)",
       "Drug of choice for cutaneous sporotrichosis"],
 src=f"{W} ch.10; {K} ch.2"),

dict(name="Voriconazole", group="Oral · III Antifungals",
 cls="Second-generation triazole (fluconazole derivative)",
 moa=["Inhibits fungal 14-α-demethylase → ergosterol depletion",
      "Broad spectrum: Aspergillus (fungicidal), Fusarium, Scedosporium, Candida (including fluconazole-resistant C. krusei and C. glabrata), dimorphic fungi",
      "No activity against Mucorales (mucormycosis)"],
 pk=["About 96% bioavailable — take 1 h before or after meals",
     "Non-linear (saturable) kinetics; metabolised by CYP2C19, 2C9 and 3A4",
     "CYP2C19 poor metabolisers (more common in Asians) have higher levels and more toxicity",
     "Good CNS penetration"],
 uses=["Invasive aspergillosis (drug of choice)",
       "Fusarium and Scedosporium infections; candidaemia and resistant oesophageal candidiasis",
       "Rarely in dermatology: refractory chromoblastomycosis or deep fungal infections in the immunocompromised"],
 dose=["Oral: 200 mg every 12 h (100 mg every 12 h if under 40 kg)",
       "IV: 6 mg/kg every 12 h × 2 doses (loading), then 4 mg/kg every 12 h",
       "Adjust by trough level (target about 1–5.5 µg/mL)"],
 ae=["Visual disturbance (blurring, colour change, photophobia) in about 30% — transient",
     "Phototoxicity (skin-related highlight): exaggerated sunburn, cheilitis, pseudoporphyria, lentigines and accelerated photoageing",
     "Cutaneous squamous cell carcinoma (and melanoma) with long-term use, especially in transplant recipients",
     "Periostitis and fluorosis (fluoride content) with long courses — bone pain, raised alkaline phosphatase",
     "Hepatotoxicity, QT prolongation, hallucinations and encephalopathy"],
 ci=["Concurrent rifampicin, rifabutin, carbamazepine, long-acting barbiturates, efavirenz (standard dose), high-dose ritonavir, sirolimus, ergot alkaloids, pimozide, quinidine",
     "Pregnancy"],
 ix=["Raises tacrolimus, cyclosporine, sirolimus, warfarin, statins, benzodiazepines",
     "Enzyme inducers drastically lower voriconazole levels"],
 mon=["Trough levels, LFT, electrolytes, ECG",
      "Regular full-skin examination and strict sun protection on long courses; eye review if visual symptoms persist",
      "Fluoride level or bone scan if bone pain"],
 preg="Avoid (old FDA category D — teratogenic in animals). Effective contraception during treatment.",
 viva=["Drug of choice for invasive aspergillosis; inactive against Mucor",
       "Phototoxicity and skin cancer (SCC) with long-term use — key dermatology point",
       "Periostitis due to fluoride",
       "CYP2C19 polymorphism affects levels"],
 src=f"{W} ch.10; {K} ch.2"),

# ---------------- IV ANTIVIRALS ----------------
dict(name="Acyclovir", group="Oral · IV Antivirals — Anti-herpes",
 cls="Synthetic acyclic guanosine (nucleoside) analogue",
 moa=["Phosphorylated first by viral thymidine kinase (so it is activated only in infected cells), then by host kinases to acyclovir triphosphate",
      "Acyclovir triphosphate competitively inhibits viral DNA polymerase and is incorporated into viral DNA → chain termination",
      "Active against HSV-1 and HSV-2 (most), VZV (needs higher doses); weak against EBV and CMV"],
 pk=["Oral bioavailability only 15–30% → frequent dosing",
     "Half-life about 2.5–3 h; excreted unchanged by the kidneys (glomerular filtration and tubular secretion)",
     "Reduce dose in renal impairment"],
 uses=["Genital herpes: first episode, recurrences, suppression",
       "Herpes labialis (severe or frequent), eczema herpeticum, herpetic whitlow",
       "Herpes zoster (start within 72 h) and varicella in adolescents/adults or complicated cases",
       "HSV-associated recurrent erythema multiforme (suppression)",
       "Severe or disseminated infection, encephalitis, neonatal herpes (IV)"],
 dose=["First-episode genital herpes: 400 mg three times daily (or 200 mg five times daily) × 7–10 days",
       "Recurrent genital herpes: 400 mg three times daily × 5 days, or 800 mg twice daily × 5 days, or 800 mg three times daily × 2 days",
       "Suppression: 400 mg twice daily",
       "Herpes zoster: 800 mg five times daily × 7 days",
       "Varicella: 20 mg/kg (max 800 mg) four times daily × 5 days",
       "Severe/disseminated HSV or VZV: 10 mg/kg IV every 8 h (neonatal herpes 20 mg/kg every 8 h)"],
 ae=["Oral: nausea, diarrhoea, headache (generally very safe)",
     "IV: crystalline nephropathy (keep well hydrated, infuse slowly), phlebitis at the drip site",
     "Neurotoxicity (confusion, tremor, hallucinations) in elderly or renally impaired patients"],
 ci=["Hypersensitivity to acyclovir or valacyclovir",
     "Dose reduction (not contraindication) in renal impairment"],
 ix=["Probenecid and cimetidine reduce renal clearance",
     "Mycophenolate: both drugs' levels rise",
     "Other nephrotoxic drugs (with IV acyclovir)"],
 mon=["Renal function with IV use or in the elderly"],
 preg="Considered safe (old FDA category B); used for first-episode and late-pregnancy suppression of genital herpes. Compatible with breastfeeding.",
 viva=["Needs viral thymidine kinase for activation → selective for infected cells",
       "Resistance (TK-deficient mutants) occurs in the immunocompromised → foscarnet or cidofovir",
       "Zoster needs about 4 times the HSV dose",
       "Hydrate patients on IV acyclovir"],
 src=f"{W} ch.11 (Systemic antiviral agents); {K} ch.3"),

dict(name="Valacyclovir", group="Oral · IV Antivirals — Anti-herpes",
 cls="L-valyl ester prodrug of acyclovir",
 moa=["Rapidly converted to acyclovir by first-pass intestinal and hepatic metabolism",
      "Then acts like acyclovir: viral thymidine kinase → triphosphate → inhibits viral DNA polymerase"],
 pk=["Bioavailability about 55% (3–5 times that of acyclovir) → fewer daily doses",
     "Gives plasma acyclovir levels similar to IV acyclovir at high doses",
     "Renal excretion as acyclovir — reduce dose in renal impairment"],
 uses=["Herpes zoster (start within 72 h)",
       "Genital herpes: first episode, recurrences, suppression (also reduces transmission to partner)",
       "Herpes labialis (single-day treatment)",
       "HSV-associated erythema multiforme suppression"],
 dose=["Herpes zoster: 1 g three times daily × 7 days",
       "First-episode genital herpes: 1 g twice daily × 7–10 days",
       "Recurrent genital herpes: 500 mg twice daily × 3 days, or 1 g once daily × 5 days",
       "Suppression: 500 mg–1 g once daily",
       "Herpes labialis: 2 g twice daily for 1 day (12 h apart)"],
 ae=["Headache, nausea, abdominal pain",
     "CNS toxicity (confusion, hallucinations) in elderly or renally impaired patients",
     "Very high doses (8 g/day) in advanced HIV/transplant: thrombotic microangiopathy (TTP/HUS)"],
 ci=["Hypersensitivity to valacyclovir or acyclovir"],
 ix=["As for acyclovir: probenecid, cimetidine, mycophenolate, nephrotoxic drugs"],
 mon=["Renal function in the elderly or those with kidney disease"],
 preg="Considered safe (old FDA category B). Compatible with breastfeeding.",
 viva=["A prodrug with 3–5 times better bioavailability than acyclovir",
       "Once-daily suppression; reduces genital herpes transmission",
       "TTP/HUS reported at very high doses in immunocompromised patients"],
 src=f"{W} ch.11; {K} ch.3"),

dict(name="Famciclovir", group="Oral · IV Antivirals — Anti-herpes",
 cls="Diacetyl ester prodrug of penciclovir (guanosine analogue)",
 moa=["Converted to penciclovir in the gut wall and liver",
      "Penciclovir is phosphorylated by viral thymidine kinase, then by host kinases, to penciclovir triphosphate, which inhibits viral DNA polymerase",
      "Not an obligate chain terminator (unlike acyclovir), but stays inside infected cells much longer (intracellular half-life 7–20 h)"],
 pk=["Bioavailability about 77%",
     "Plasma half-life about 2 h, but long intracellular half-life → less frequent dosing",
     "Renal excretion — reduce dose in renal impairment"],
 uses=["Herpes zoster (start within 72 h)",
       "Genital herpes: first episode, recurrences, suppression",
       "Herpes labialis (single dose)",
       "Recurrent HSV in HIV"],
 dose=["Herpes zoster: 500 mg three times daily × 7 days",
       "First-episode genital herpes: 250 mg three times daily × 7–10 days",
       "Recurrent genital herpes: 1 g twice daily for 1 day (or 125 mg twice daily × 5 days)",
       "Suppression: 250 mg twice daily",
       "Herpes labialis: 1500 mg single dose",
       "HIV, recurrent HSV: 500 mg twice daily × 7 days"],
 ae=["Headache, nausea, diarrhoea",
     "Confusion in the elderly (rare)"],
 ci=["Hypersensitivity to famciclovir or penciclovir"],
 ix=["Probenecid may raise penciclovir levels",
     "Few clinically important interactions"],
 mon=["Renal function for dose adjustment"],
 preg="Old FDA category B; limited human data — acyclovir and valacyclovir are preferred in pregnancy.",
 viva=["Prodrug of penciclovir; long intracellular half-life",
       "Cross-resistance with acyclovir (both need viral thymidine kinase)",
       "Single-day treatment options for herpes labialis and recurrent genital herpes"],
 src=f"{W} ch.11; {K} ch.3"),

# ---------------- IV ANTIVIRALS — ART ----------------
dict(name="Abacavir + Lamivudine", group="Oral · IV Antivirals — Antiretroviral (ART)",
 cls="Fixed-dose combination of two NRTIs (nucleoside reverse transcriptase inhibitors)",
 moa=["Both are nucleoside analogues, phosphorylated inside cells to active triphosphates",
      "They compete with natural nucleotides for HIV reverse transcriptase and cause chain termination of viral DNA",
      "Abacavir is a guanosine analogue (active form carbovir triphosphate); lamivudine is a cytidine analogue that is also active against hepatitis B"],
 pk=["Both are well absorbed with or without food",
     "Abacavir: metabolised by alcohol dehydrogenase and glucuronidation (no CYP); lamivudine: excreted by the kidneys",
     "Long intracellular half-lives allow once-daily dosing"],
 uses=["Backbone of first-line ART in children (with dolutegravir) under the national (NACO) programme",
       "Adults when tenofovir cannot be used (e.g. renal disease, osteoporosis)"],
 dose=["Adults: abacavir 600 mg + lamivudine 300 mg once daily",
       "Children: weight-band dosing with dispersible tablets (abacavir 120 mg + lamivudine 60 mg) as per NACO tables"],
 ae=["Abacavir hypersensitivity syndrome (about 5–8%, usually in the first 6 weeks): fever, rash, GI symptoms, malaise, cough or breathlessness",
     "It is strongly linked to HLA-B*57:01. Rechallenge after a reaction can be fatal, so never restart",
     "Abacavir: possible increase in myocardial infarction risk",
     "Lamivudine: very well tolerated; pancreatitis in children; flare of hepatitis B when stopped",
     "NRTI class: lactic acidosis and hepatic steatosis (rare with these two)"],
 ci=["HLA-B*57:01 positive (test before use where available)",
     "Previous abacavir hypersensitivity (lifelong contraindication)",
     "Moderate–severe liver impairment (abacavir)"],
 ix=["Alcohol raises abacavir levels",
     "Lamivudine: co-trimoxazole raises levels slightly; do not combine with emtricitabine (same drug class and target)"],
 mon=["CD4 count and viral load as per programme schedule",
      "Hepatitis B status before starting (lamivudine stopping can cause a flare)",
      "LFT; lipids; cardiovascular risk"],
 preg="Both can be used in pregnancy; the national programme prefers TLD (tenofovir + lamivudine + dolutegravir) for pregnant women.",
 viva=["Abacavir hypersensitivity = HLA-B*57:01 — never rechallenge",
       "Lamivudine also treats hepatitis B; stopping it can cause a hepatitis flare",
       "Current NACO preferred first-line for adults is TLD; ABC + 3TC + DTG is used in children"],
 src=f"{K} ch.4 (Antiretroviral drugs); {W} ch.3 (HLA-B*57:01 pharmacogenetics) and ch.11; check against current NACO guidelines",
 note="Wolverton covers ART only briefly (HLA associations and a list of drugs), so Khopkar and NACO were the main guides here. Regimens change often — please confirm with the latest NACO guidelines."),

dict(name="Lamivudine + Zidovudine", group="Oral · IV Antivirals — Antiretroviral (ART)",
 cls="Fixed-dose combination of two NRTIs",
 moa=["Zidovudine (AZT) is a thymidine analogue; lamivudine (3TC) is a cytidine analogue",
      "Both are phosphorylated to triphosphates that inhibit HIV reverse transcriptase and terminate viral DNA chains"],
 pk=["Well absorbed with or without food",
     "Zidovudine is glucuronidated in the liver (short half-life, twice-daily dosing); lamivudine is excreted by the kidneys"],
 uses=["Alternative NRTI backbone in ART when tenofovir or abacavir cannot be used",
       "Older first-line regimens (with nevirapine or efavirenz)",
       "Zidovudine alone: infant prophylaxis in PMTCT (prevention of mother-to-child transmission) programmes"],
 dose=["Adults: lamivudine 150 mg + zidovudine 300 mg twice daily",
       "Children: weight-band dosing as per NACO tables"],
 ae=["Zidovudine: bone marrow suppression — macrocytic anaemia and neutropenia (avoid if Hb below about 8 g/dL)",
     "Zidovudine: nausea, headache, myopathy, lactic acidosis with hepatic steatosis, lipoatrophy",
     "Skin and mucosal signs of zidovudine: longitudinal melanonychia, nail and mucocutaneous hyperpigmentation",
     "Lamivudine: generally well tolerated; hepatitis B flare on stopping"],
 ci=["Severe anaemia (Hb under about 7–8 g/dL) or neutropenia",
     "Hypersensitivity"],
 ix=["Other bone marrow suppressants raise anaemia risk: ganciclovir, co-trimoxazole (high dose), pyrimethamine, interferon, chemotherapy",
     "Stavudine is antagonistic — never combine with zidovudine",
     "Probenecid and fluconazole raise zidovudine levels"],
 mon=["Hb and CBC at baseline, then monthly for the first 3 months, then periodically",
      "CD4 and viral load per programme; LFT"],
 preg="Zidovudine has the longest safety record in pregnancy; currently TLD is preferred, with zidovudine kept for infant prophylaxis and special cases.",
 viva=["Zidovudine → anaemia (macrocytic) and neutropenia",
       "Zidovudine causes longitudinal melanonychia — a common viva photo",
       "Never combine zidovudine with stavudine (antagonism)"],
 src=f"{K} ch.4; {W} ch.11; check current NACO guidelines",
 note="Wolverton gives little detail on ART; Khopkar and NACO used."),

dict(name="Lamivudine + Nevirapine + Zidovudine", group="Oral · IV Antivirals — Antiretroviral (ART)",
 cls="Fixed-dose triple combination: 2 NRTIs (lamivudine, zidovudine) + 1 NNRTI (nevirapine)",
 moa=["NRTIs: chain-terminating nucleoside analogues of HIV reverse transcriptase",
      "Nevirapine: non-competitive inhibitor that binds a pocket near the reverse transcriptase active site"],
 pk=["Nevirapine induces its own metabolism (CYP3A4 and 2B6 autoinduction) over the first 2 weeks",
     "So the full triple combination is used only after a 2-week lead-in with once-daily nevirapine"],
 uses=["Former first-line ART regimen (the 'ZLN' regimen), now largely replaced by dolutegravir-based TLD",
       "May still be met in patients started long ago"],
 dose=["Lead-in (14 days): lamivudine 150 mg + zidovudine 300 mg twice daily, with nevirapine 200 mg once daily only",
       "Then: fixed-dose lamivudine 150 mg + nevirapine 200 mg + zidovudine 300 mg twice daily",
       "If rash appears during lead-in: do not increase the dose until it resolves; do not extend lead-in beyond 28 days"],
 ae=["Nevirapine rash (about 15–20%), mostly in the first 6 weeks; SJS/TEN and DRESS",
     "Nevirapine hepatotoxicity — higher in women with CD4 above 250 and men with CD4 above 400",
     "Zidovudine anaemia and neutropenia; melanonychia",
     "Lamivudine: hepatitis B flare on stopping"],
 ci=["Previous severe nevirapine rash or hepatitis",
     "Moderate–severe liver disease",
     "Severe anaemia (zidovudine)"],
 ix=["Nevirapine induces CYP3A4: lowers oral contraceptives, ketoconazole, methadone, protease inhibitors",
     "Rifampicin lowers nevirapine — avoid together",
     "Zidovudine: other marrow suppressants"],
 mon=["LFT at baseline, 2, 4, 8 and 12 weeks (nevirapine)",
      "Hb/CBC (zidovudine)",
      "Check skin and mucosa at each visit in the first 6–8 weeks"],
 preg="Used widely in the past; nevirapine-related liver toxicity is higher in women with higher CD4 counts. TLD is now preferred.",
 viva=["Why the lead-in? Autoinduction — the 2-week once-daily dose lowers the risk of rash and hepatitis",
       "Nevirapine is one of the commonest causes of SJS/TEN in Indian studies",
       "Stop permanently if rash comes with fever, blisters, mucosal involvement or hepatitis"],
 src=f"{K} ch.4 (Table 4.2); {W} ch.3 and ch.67; check current NACO guidelines",
 note="Wolverton gives little detail on ART; Khopkar and NACO used."),

dict(name="Ritonavir", group="Oral · IV Antivirals — Antiretroviral (ART)",
 cls="HIV protease inhibitor (PI); used today mainly as a pharmacokinetic booster",
 moa=["Inhibits HIV protease, which cleaves the gag-pol polyprotein → immature, non-infectious virus particles",
      "At low dose (100 mg) it strongly inhibits CYP3A4 (and P-gp), so it is used to 'boost' levels of other PIs (lopinavir, atazanavir, darunavir)"],
 pk=["Take with food; metabolised by CYP3A4 (and also induces some enzymes such as glucuronidation, CYP1A2, 2C9 and 2C19)",
     "Highly protein bound"],
 uses=["Booster in second-line ART: lopinavir/ritonavir 400/100 mg twice daily, atazanavir/ritonavir 300/100 mg once daily, darunavir/ritonavir",
       "Full-dose ritonavir as the only PI is no longer used because of poor tolerance"],
 dose=["Booster dose: 100 mg once or twice daily with the partner PI",
       "Heat-stable tablet formulations; take with food"],
 ae=["GI: nausea, vomiting, diarrhoea; altered taste; perioral and peripheral paraesthesia",
     "Metabolic: hypertriglyceridaemia, hypercholesterolaemia, insulin resistance",
     "Lipodystrophy: central fat gain (buffalo hump, increased abdominal fat) with peripheral lipoatrophy",
     "Hepatitis, pancreatitis; PR/QT prolongation"],
 ci=["Co-administration with CYP3A4 substrates that are dangerous at high levels: simvastatin, lovastatin, midazolam (oral), pimozide, ergot alkaloids, amiodarone, sildenafil for pulmonary hypertension, colchicine in renal/liver impairment"],
 ix=["Dermatology-relevant: inhaled, intranasal or injected corticosteroids (fluticasone, budesonide, intralesional or intra-articular triamcinolone) → iatrogenic Cushing syndrome and adrenal suppression",
     "Raises cyclosporine, tacrolimus, colchicine (fatal toxicity reported), itraconazole and some antihistamines",
     "Lowers oral contraceptive (ethinylestradiol) levels and voriconazole levels",
     "Rifampicin lowers PI levels — avoid"],
 mon=["Lipids and glucose; LFT",
      "Review all co-prescribed drugs, including steroid injections and creams over large areas"],
 preg="Boosted PIs (e.g. atazanavir/ritonavir, lopinavir/ritonavir) are used in pregnancy when needed.",
 viva=["Ritonavir is mostly a 'booster' through CYP3A4 inhibition",
       "Triamcinolone injection or inhaled fluticasone with ritonavir → Cushing syndrome",
       "PI-related lipodystrophy and dyslipidaemia"],
 src=f"{K} ch.4; {W} ch.11 and ch.66 (Drug interactions); check current NACO guidelines",
 note="Wolverton gives little detail on ART; Khopkar and NACO used."),

dict(name="Dolutegravir", group="Oral · IV Antivirals — Antiretroviral (ART)",
 cls="Integrase strand transfer inhibitor (INSTI), second generation",
 moa=["Binds the HIV integrase active site and blocks the strand-transfer step",
      "So viral DNA cannot integrate into the host chromosome",
      "High genetic barrier to resistance"],
 pk=["Taken once daily with or without food; half-life about 14 h",
     "Metabolised by UGT1A1 (and CYP3A4 to a lesser extent)"],
 uses=["Part of the preferred first-line ART regimen in India (TLD: tenofovir 300 mg + lamivudine 300 mg + dolutegravir 50 mg once daily) for adults, adolescents and pregnant women",
       "Children: with abacavir + lamivudine (weight-band dosing)",
       "Second-line regimens and post-exposure prophylaxis (PEP)"],
 dose=["50 mg once daily (usually within the TLD tablet)",
       "50 mg twice daily if taken with rifampicin or when INSTI resistance is suspected"],
 ae=["Insomnia, headache, abnormal dreams, depression (uncommon)",
     "Weight gain",
     "Small rise in serum creatinine (blocks tubular creatinine secretion; true kidney function is not reduced)",
     "Hypersensitivity reactions and hepatotoxicity (rare)",
     "Early concern about neural tube defects with use at conception; later data show the risk is very small — it is now recommended in pregnancy"],
 ci=["Dofetilide (raised levels)",
     "Previous hypersensitivity"],
 ix=["Polyvalent cations (antacids with Mg/Al, calcium, iron, zinc supplements) chelate it — take dolutegravir 2 h before or 6 h after",
     "Rifampicin, carbamazepine, phenytoin lower levels (double the dose with rifampicin; avoid the others)",
     "Raises metformin levels — limit the metformin dose (about 1 g/day) and monitor"],
 mon=["CD4 and viral load per programme",
      "Weight, mood, renal function (expect a small, stable creatinine rise)"],
 preg="Recommended in pregnancy as part of TLD; give folic acid. Compatible with national breastfeeding guidance for women on ART.",
 viva=["INSTI — blocks integration of viral DNA",
       "TLD is the preferred first-line regimen in India",
       "Separate from zinc, iron, calcium or antacids — relevant when we prescribe zinc",
       "Creatinine rise without real kidney damage"],
 src=f"{K} ch.4 (older edition, before dolutegravir); {W} ch.11 (lists the drug); current NACO guidelines",
 note="Khopkar's edition predates dolutegravir, and Wolverton only lists it, so this post follows current NACO/WHO guidance. Please check."),

dict(name="Nevirapine", group="Oral · IV Antivirals — Antiretroviral (ART)",
 cls="Non-nucleoside reverse transcriptase inhibitor (NNRTI)",
 moa=["Binds directly to a hydrophobic pocket close to the active site of HIV-1 reverse transcriptase",
      "Non-competitive inhibition of the enzyme; no phosphorylation needed",
      "Not active against HIV-2"],
 pk=["Over 90% absorbed; crosses the placenta and enters breast milk",
     "Metabolised by CYP3A4 and 2B6 and induces these enzymes (autoinduction), so the half-life falls from about 45 h to 25–30 h after 2–4 weeks"],
 uses=["Former first-line ART (with zidovudine + lamivudine), now replaced by dolutegravir-based regimens",
       "Infant prophylaxis in PMTCT (nevirapine syrup) under national programmes"],
 dose=["200 mg once daily for 14 days (lead-in), then 200 mg twice daily",
       "Infant prophylaxis: weight-based syrup for 6–12 weeks as per NACO"],
 ae=["Rash in about 15–20%, mostly in the first 6 weeks; SJS/TEN and DRESS (hypersensitivity syndrome)",
     "Hepatotoxicity: can be fulminant; risk higher in women with CD4 above 250 and men with CD4 above 400",
     "Fever, myalgia, nausea"],
 ci=["Women with CD4 above 250 and men with CD4 above 400 (when starting)",
     "Moderate or severe liver disease (Child–Pugh B/C)",
     "Previous severe rash or hepatitis with nevirapine — never restart"],
 ix=["Lowers levels of oral contraceptives, ketoconazole, methadone, protease inhibitors",
     "Rifampicin lowers nevirapine levels — avoid",
     "Fluconazole raises nevirapine levels"],
 mon=["LFT at baseline, 2, 4, 8 and 12 weeks, then periodically",
      "Skin examination in the first 6–8 weeks; stop if rash with fever, blisters, mucosal involvement, or hepatitis"],
 preg="Has been used in pregnancy, but liver toxicity is higher in women with high CD4 counts. Dolutegravir-based regimens are now preferred.",
 viva=["Lead-in dosing because of autoinduction",
       "Rash in the first 6 weeks; one of the commonest causes of SJS/TEN in India",
       "CD4 thresholds for hepatotoxicity: women above 250, men above 400",
       "HLA associations with nevirapine hypersensitivity are described (Wolverton ch.3)"],
 src=f"{K} ch.4; {W} ch.3, ch.11 and ch.67; check current NACO guidelines"),

# ---------------- V ANTIPARASITIC ----------------
dict(name="Ivermectin", group="Oral · V Antiparasitic",
 cls="Macrocyclic lactone (semisynthetic avermectin from Streptomyces avermitilis)",
 moa=["Binds glutamate-gated chloride channels in invertebrate nerve and muscle cells (also GABA-gated channels)",
      "Increases chloride entry → hyperpolarisation → paralysis and death of the parasite",
      "In mammals these channels are only in the CNS, and P-glycoprotein at the blood–brain barrier keeps ivermectin out — hence its safety"],
 pk=["Absorption increases with a fatty meal (often given with food for scabies; the label advises water on an empty stomach)",
     "Highly lipophilic, widely distributed; half-life about 18 h",
     "Metabolised in the liver (CYP3A4); excreted in faeces",
     "Kills mites and lice but not eggs — so a second dose is needed"],
 uses=["Scabies — classic (alternative to permethrin, and for mass treatment, institutions, poor compliance) and crusted (Norwegian) scabies with topical therapy",
       "Head lice resistant to topical treatment",
       "Strongyloidiasis (drug of choice), cutaneous larva migrans, larva currens",
       "Onchocerciasis, lymphatic filariasis (mass drug administration with albendazole/DEC)",
       "Demodicosis and rosacea (topical 1% cream mainly)"],
 dose=["Usual dose: 200 µg/kg as a single dose; tablets 3, 6 and 12 mg",
       "Scabies: 200 µg/kg, repeated after 7–14 days",
       "Crusted scabies: 200 µg/kg on days 1, 2, 8, 9 and 15 (plus days 22 and 29 in severe cases), with topical permethrin",
       "Head lice: 400 µg/kg on days 1 and 8 (some use 200 µg/kg)",
       "Strongyloidiasis: 200 µg/kg for 1–2 days; cutaneous larva migrans: 200 µg/kg for 1–2 days",
       "Onchocerciasis: 150 µg/kg once (repeat every 6–12 months)"],
 ae=["Generally very well tolerated: dizziness, nausea, transient worsening of itch",
     "Mazzotti reaction in onchocerciasis (fever, itch, lymphadenopathy, hypotension from dying microfilariae)",
     "Severe encephalopathy in people with very high Loa loa microfilaraemia",
     "Neurotoxicity in people with P-glycoprotein defects or with P-gp inhibitors"],
 ci=["Children under 15 kg",
     "Pregnancy and breastfeeding (avoid, though accidental exposure has not shown clear harm)",
     "High Loa loa microfilaraemia (endemic areas); conditions with a damaged blood–brain barrier (e.g. meningitis)"],
 ix=["Warfarin: INR may rise",
     "P-gp/CYP3A4 inhibitors (ketoconazole, cyclosporine, verapamil) may raise CNS exposure"],
 mon=["No routine blood tests"],
 preg="Not recommended in pregnancy (old FDA category C) or breastfeeding; use permethrin instead.",
 viva=["Acts on glutamate-gated chloride channels; P-glycoprotein keeps it out of the human brain",
       "Not ovicidal — repeat the dose after 7–14 days",
       "Drug of choice for crusted scabies (with topical) and strongyloidiasis",
       "Avoid in children under 15 kg and in pregnancy"],
 src=f"{W} ch.12 (Systemic antiparasitic agents); {K} ch.5",
 note="Wolverton says to repeat the scabies dose in 1 week to 10 days; other guides say 7–14 days. Both fit — 7–14 days is used here."),
]
