# More from Khopkar — slot 6: antileprosy drugs & MDT, antituberculous drugs
W = "Wolverton 4e"; K = "Khopkar"
D = [
# ---------------- ANTILEPROSY ----------------
dict(name="Dapsone (oral + topical gel)", group="More from Khopkar · Antileprosy drugs",
 cls="Sulfone (4,4'-diaminodiphenyl sulfone); antibacterial and anti-inflammatory",
 moa=["Antibacterial: like sulfonamides, competes with PABA and inhibits dihydropteroate synthase → no folate synthesis in M. leprae (bacteriostatic)",
      "Anti-inflammatory: inhibits neutrophil myeloperoxidase and the halide–peroxide system → less oxidative tissue damage",
      "Also inhibits neutrophil adherence (integrin-mediated) and chemotaxis, and eosinophil peroxidase",
      "Hence its value in neutrophil-predominant dermatoses"],
 pk=["Well absorbed; half-life about 24–30 h (once daily)",
     "Metabolised by N-acetylation (fast/slow acetylators) and N-hydroxylation (CYP2C9, 3A4) → hydroxylamine metabolite causes haemolysis and methaemoglobinaemia",
     "Enterohepatic circulation; excreted in urine"],
 uses=["Leprosy (part of MDT)",
       "Dermatitis herpetiformis (drug of choice — itch improves within 48–72 h)",
       "Linear IgA disease, bullous SLE, subcorneal pustular dermatosis, erythema elevatum diutinum, mucous membrane pemphigoid, bullous pemphigoid (adjunct), IgA pemphigus",
       "Neutrophilic and vasculitic: urticarial vasculitis, leukocytoclastic vasculitis, Sweet syndrome, pyoderma gangrenosum, Behçet disease",
       "Others: chronic urticaria (refractory), granuloma faciale, actinomycetoma (Welsh regimen with co-trimoxazole), loxoscelism, relapsing polychondritis, acne (topical)"],
 dose=["Leprosy: 100 mg daily (adults), 1–2 mg/kg in children",
       "Dermatoses: start 25–50 mg/day, increase by 25–50 mg weekly to 100–200 mg/day (max usually 300 mg); taper to the lowest effective dose",
       "Check G6PD before starting",
       "Tablets 25, 50, 100 mg"],
 ae=["Dose-related haemolysis (in everyone; Hb falls 1–2 g/dL) — severe in G6PD deficiency",
     "Methaemoglobinaemia (dose-related): grey-blue lips, breathlessness, headache; usually tolerated below 10–12%; cimetidine or vitamin E may reduce it; methylene blue for severe cases (not in G6PD deficiency)",
     "Agranulocytosis (idiosyncratic, usually in the first 3 months) — sore throat, fever",
     "Dapsone hypersensitivity syndrome (DRESS-like): 2–8 weeks after starting — fever, rash, lymphadenopathy, hepatitis; linked to HLA-B*13:01 (common in Asians); can be fatal",
     "Hepatitis, cholestatic jaundice; peripheral motor neuropathy (distal weakness); psychosis",
     "Exfoliative dermatitis, TEN, fixed drug eruption"],
 ci=["Severe G6PD deficiency; previous dapsone hypersensitivity",
     "Caution: anaemia, cardiopulmonary disease (cannot tolerate methaemoglobinaemia), sulfonamide allergy (cross-reactivity uncommon)"],
 ix=["Trimethoprim raises dapsone levels (and vice versa) → more methaemoglobinaemia",
     "Rifampicin lowers dapsone levels (about 7–10 times) — not clinically important in MDT",
     "Probenecid raises levels; other oxidant drugs (primaquine, nitrates, EMLA/prilocaine) add to methaemoglobinaemia",
     "Cimetidine reduces hydroxylamine formation (used to lower methaemoglobin)"],
 mon=["Baseline: G6PD, CBC, LFT, renal function, urine; HLA-B*13:01 where available",
      "CBC weekly for 4 weeks, every 2 weeks until 12 weeks, then every 3–4 months; LFT periodically; methaemoglobin if symptomatic",
      "Ask about fever, rash, sore throat and weakness at each visit"],
 preg="Used in pregnancy for leprosy (WHO); risk of neonatal haemolysis and hyperbilirubinaemia near term. Excreted in milk — watch for haemolysis in G6PD-deficient infants.",
 viva=["Drug of choice for dermatitis herpetiformis",
       "Haemolysis and methaemoglobinaemia are dose-related; agranulocytosis and hypersensitivity syndrome are idiosyncratic",
       "Check G6PD first; HLA-B*13:01 for dapsone hypersensitivity",
       "Mechanism in skin: inhibits neutrophil myeloperoxidase"],
 src=f"{W} ch.20 (Dapsone); {K} ch.6 (Antileprosy drugs)"),

dict(name="Dapsone gel (5%, 7.5%)", merge_into="Dapsone (oral + topical gel)", form_label="Topical form", group="More from Khopkar · Antileprosy drugs",
 cls="Topical sulfone in a gel vehicle",
 moa=["Anti-inflammatory (neutrophil myeloperoxidase inhibition) and antibacterial against C. acnes"],
 uses=["Acne vulgaris (inflammatory, especially in adult women); rosacea (off-label)"],
 dose=["5% gel twice daily or 7.5% gel once daily"],
 ae=["Dryness, redness; temporary orange-brown discolouration if used with benzoyl peroxide",
     "Blood levels are about 100 times lower than with oral dapsone — no routine G6PD test needed"],
 ci=["Hypersensitivity"],
 preg="Limited data; minimal absorption.",
 viva=["Topical dapsone + BPO → orange skin staining"],
 src=f"{W} ch.20 and ch.46 (topical dapsone)"),

dict(name="Clofazimine", group="More from Khopkar · Antileprosy drugs",
 cls="Riminophenazine dye; antimycobacterial and anti-inflammatory",
 moa=["Binds guanine bases of mycobacterial DNA → inhibits replication; generates reactive oxygen species (weakly bactericidal)",
      "Anti-inflammatory: inhibits neutrophil motility and lymphocyte proliferation; stimulates phagocyte activity",
      "Very lipophilic — accumulates in fat and macrophages (crystals in tissues)"],
 pk=["Variable absorption, better with food; very long half-life (about 70 days); stored in fat and reticuloendothelial system"],
 uses=["Leprosy — part of MB-MDT (and now 3-drug PB regimen)",
       "Erythema nodosum leprosum (steroid-sparing for chronic/recurrent ENL)",
       "Off-label: discoid lupus, pyoderma gangrenosum, granulomatous cheilitis (Melkersson–Rosenthal), granuloma annulare, Sweet syndrome",
       "MDR-TB (newer regimens) and Mycobacterium avium complex"],
 dose=["MDT adult: 300 mg once a month (supervised) + 50 mg daily",
       "ENL: 100 mg three times daily (300 mg/day) for no more than 12 weeks, then taper to 100 mg/day; takes 4–6 weeks to act — combine with steroids initially",
       "Capsules 50 and 100 mg, with food"],
 ae=["Reddish-brown to purple-black skin pigmentation (dose-related; most marked in lesions; fades over months to years after stopping) — may cause social stigma and depression",
     "Red-brown discolouration of conjunctiva, tears, sweat, urine, sputum, breast milk",
     "Ichthyosis/xerosis (especially legs)",
     "GI: abdominal pain, diarrhoea; crystal-deposition enteropathy with high doses (can mimic acute abdomen — splenic infarction rare)",
     "QT prolongation"],
 ci=["Hypersensitivity; caution in pre-existing GI disease and long QT"],
 ix=["QT-prolonging drugs (bedaquiline, fluoroquinolones, macrolides)",
     "May reduce the effect of rifampicin slightly (not significant clinically)"],
 mon=["Weight, abdominal symptoms on high doses; ECG if other QT drugs"],
 preg="Used in pregnancy within MDT (WHO); infants may be born with pigmentation (reversible).",
 viva=["Pigmentation is the main side effect — counsel before starting",
       "Anti-inflammatory action used in ENL (300 mg/day max 3 months)",
       "Crystal enteropathy with high-dose use"],
 src=f"{K} ch.6; {W} ch.40 (Miscellaneous systemic drugs — clofazimine)"),

dict(name="Rifampicin", group="More from Khopkar · Antileprosy drugs",
 cls="Rifamycin (semisynthetic antibiotic); antileprosy and antituberculous",
 moa=["Inhibits bacterial DNA-dependent RNA polymerase (β-subunit, rpoB gene) → no RNA synthesis → bactericidal",
      "Most potent bactericidal drug against M. leprae — a single 600 mg dose kills over 99.9% of viable bacilli",
      "Resistance from rpoB mutations — never used as monotherapy"],
 pk=["Well absorbed on an empty stomach; widely distributed (CSF, tissues, secretions)",
     "Metabolised in the liver; excreted in bile (enterohepatic circulation)",
     "Potent inducer of CYP3A4, 2C9, 2C19 and P-gp — induces its own metabolism"],
 uses=["Leprosy: part of MDT (monthly supervised dose); single-dose rifampicin post-exposure prophylaxis for contacts",
       "Tuberculosis including cutaneous TB (HRZE regimen)",
       "Atypical mycobacteria (M. marinum, M. ulcerans), rhinoscleroma, cutaneous leishmaniasis (limited)",
       "Hidradenitis suppurativa: clindamycin 300 mg + rifampicin 300 mg twice daily for 10–12 weeks",
       "Recurrent staphylococcal furunculosis (decolonisation, with another antibiotic)",
       "Pruritus of cholestasis (pregnancy excluded), brucellosis"],
 dose=["Leprosy MDT: 600 mg once a month (supervised); children 10–14 years 450 mg; under 10 years 10 mg/kg",
       "TB: 10 mg/kg/day (max 600 mg) in fixed-dose combinations",
       "Take on an empty stomach (1 h before or 2 h after food)"],
 ae=["Orange-red discolouration of urine, sweat, tears (stains soft contact lenses)",
     "Hepatotoxicity (more with isoniazid and in alcoholics)",
     "Intermittent dosing: 'flu-like syndrome', thrombocytopenia, haemolytic anaemia, acute renal failure (immune-mediated)",
     "Rash, pruritus, flushing; rarely SJS/TEN, DRESS"],
 ci=["Jaundice; hypersensitivity",
     "Concurrent protease inhibitors (except with rifabutin substitution) and some other ART"],
 ix=["Powerful enzyme inducer — reduces levels of: oral contraceptives (use another method), corticosteroids (double steroid dose in lepra reactions/ENL), cyclosporine, tacrolimus, azoles (itraconazole, voriconazole), warfarin, sulfonylureas, methadone, digoxin, dapsone, PIs, nevirapine, dolutegravir (needs 50 mg twice daily)",
     "Hepatotoxicity increased with isoniazid, pyrazinamide, alcohol"],
 mon=["LFT at baseline and if symptoms; CBC on intermittent dosing",
      "Review all co-prescribed drugs"],
 preg="Used in pregnancy for leprosy and TB; vitamin K to the newborn (risk of haemorrhagic disease) when given in late pregnancy.",
 viva=["Single monthly dose kills >99.9% of M. leprae",
       "Enzyme inducer — OCP failure and need to double steroid dose",
       "Orange-red body fluids",
       "Flu-like syndrome with intermittent dosing"],
 src=f"{K} ch.6 and ch.7; {W} ch.9 (rifamycins) and ch.66 (Drug interactions)"),

dict(name="Multidrug therapy (MDT) for leprosy", group="More from Khopkar · Antileprosy drugs",
 cls="WHO multidrug therapy regimens (blister-pack combinations of rifampicin, clofazimine, dapsone)",
 moa=["Combining a bactericidal drug (rifampicin) with bacteriostatic drugs (dapsone, clofazimine) prevents resistance and kills persisters",
      "Monthly supervised doses ensure the key drug (rifampicin) is taken"],
 uses=["Classification for treatment (WHO): paucibacillary (PB) = 1–5 skin lesions, no nerve or only one nerve involved, skin smear negative; multibacillary (MB) = more than 5 lesions, or more than one nerve, or smear positive",
       "MB adult (12 months — 12 blister packs within 18 months): rifampicin 600 mg + clofazimine 300 mg once monthly (supervised); clofazimine 50 mg + dapsone 100 mg daily",
       "PB adult (older WHO/NLEP): rifampicin 600 mg monthly + dapsone 100 mg daily for 6 months (6 packs within 9 months)",
       "WHO 2018: the same 3 drugs for PB as well (6 months) — 'uniform' approach; India's NLEP has moved to 3-drug PB treatment (confirm current NLEP guidance)",
       "Children 10–14 years: rifampicin 450 mg + clofazimine 150 mg monthly; clofazimine 50 mg alternate days + dapsone 50 mg daily",
       "Children under 10 years: rifampicin 10 mg/kg monthly, clofazimine 100 mg monthly + 50 mg twice weekly, dapsone 2 mg/kg daily",
       "U-MDT (uniform MDT, trials): MB regimen for 6 months for all patients",
       "A-MDT (accompanied MDT): full course given at diagnosis to patients who cannot attend monthly",
       "ROM (rifampicin 600 mg + ofloxacin 400 mg + minocycline 100 mg) single dose — formerly for single-lesion PB; monthly ROM is an alternative regimen",
       "Rifampicin-resistant leprosy: clofazimine + two second-line drugs (ofloxacin/moxifloxacin, minocycline, clarithromycin) — WHO 2018",
       "Post-exposure prophylaxis: single-dose rifampicin (10 mg/kg, 600 mg adults) to contacts (SDR-PEP)"],
 dose=["Blister packs: MB-adult (red), PB-adult (green), MB-child and PB-child packs",
       "Instructions to patients: take the monthly dose in front of the health worker; urine may turn red; skin will darken (clofazimine) and fade after treatment; report reactions, nerve pain, weakness early; MDT is free"],
 ae=["See individual drugs",
     "Leprosy reactions may occur during or after treatment (not a reason to stop MDT): type 1 (reversal) — prednisolone 40 mg/day tapering over 12–20 weeks; type 2 (ENL) — prednisolone, thalidomide, clofazimine"],
 ci=["Rifampicin hypersensitivity → use alternative regimens (clofazimine + ofloxacin + minocycline)",
     "Dapsone allergy → MB: rifampicin + clofazimine; PB: clofazimine replaces dapsone"],
 mon=["Monthly review: compliance, reactions, nerve function (VMT/ST), drug side effects",
      "Release from treatment after the fixed duration; surveillance for relapse (PB 2 years, MB 5 years per older NLEP advice)"],
 preg="MDT is safe and should be continued in pregnancy and breastfeeding; reactions may flare after delivery.",
 viva=["PB vs MB definitions and regimens (adult and child doses)",
       "Fixed-duration therapy: MB 12 months, PB 6 months",
       "U-MDT, A-MDT, ROM, SDR-PEP — know what each means",
       "Leprosy reactions are treated without stopping MDT"],
 src=f"{K} ch.6 (WHO-MDT, U-MDT, A-MDT, ROM, instructions to patients); WHO Guidelines for leprosy 2018; NLEP",
 note="Leprosy regimens have changed (WHO 2018 3-drug PB; India NLEP updates). Please check the latest NLEP circular before the exam."),

dict(name="Newer antileprosy drugs (ofloxacin, moxifloxacin, minocycline, clarithromycin, rifapentine, ethionamide)", group="More from Khopkar · Antileprosy drugs",
 cls="Second-line bactericidal drugs used for resistance, intolerance and alternative regimens",
 moa=["Fluoroquinolones (ofloxacin, moxifloxacin): inhibit DNA gyrase — strongly bactericidal against M. leprae (moxifloxacin is the most potent)",
      "Minocycline: 30S ribosome inhibitor; the only tetracycline with significant activity against M. leprae",
      "Clarithromycin: 50S ribosome inhibitor; bactericidal against M. leprae",
      "Rifapentine: long-acting rifamycin, more potent than rifampicin in mice",
      "Ethionamide/prothionamide: inhibit mycolic acid synthesis; hepatotoxic — rarely used now"],
 uses=["Rifampicin-resistant leprosy (with clofazimine)",
       "Patients intolerant of standard MDT drugs",
       "ROM regimens and trial regimens (e.g. rifapentine–moxifloxacin–minocycline, PEP studies)"],
 dose=["Ofloxacin 400 mg daily; moxifloxacin 400 mg daily; minocycline 100 mg daily; clarithromycin 500 mg daily",
       "Rifapentine 900 mg monthly (in trial regimens)"],
 ae=["Fluoroquinolones: GI upset, tendinopathy, QT prolongation, CNS effects, photosensitivity (sparfloxacin)",
     "Minocycline: vestibular effects, pigmentation, autoimmune reactions",
     "Clarithromycin: GI upset, taste change, CYP3A4 interactions",
     "Ethionamide: severe hepatotoxicity, GI upset"],
 ci=["Fluoroquinolones in pregnancy and children (cartilage effects — relative)",
     "Minocycline in pregnancy and children under 8"],
 preg="Avoid fluoroquinolones and minocycline in pregnancy; clarithromycin with caution.",
 viva=["Most bactericidal second-line drugs: moxifloxacin, rifapentine",
       "ROM = rifampicin + ofloxacin + minocycline",
       "Rifampicin-resistant leprosy = clofazimine + 2 of (FQ, minocycline, clarithromycin)"],
 src=f"{K} ch.6 (Newer drugs in leprosy); {W} ch.9; WHO 2018 leprosy guidelines"),

# ---------------- ANTITUBERCULOUS ----------------
dict(name="Isoniazid (INH)", group="More from Khopkar · Antituberculous drugs",
 cls="Isonicotinic acid hydrazide; first-line antituberculous drug",
 moa=["Prodrug activated by mycobacterial catalase-peroxidase (KatG)",
      "Inhibits InhA (enoyl-ACP reductase) → blocks mycolic acid synthesis in the cell wall",
      "Bactericidal for rapidly dividing bacilli; bacteriostatic for resting ones"],
 pk=["Well absorbed; penetrates all tissues and caseous material",
     "Metabolised by N-acetylation (NAT2) — slow acetylators (about half of Indians) have more neuropathy; fast acetylators more hepatitis (debated)"],
 uses=["All forms of TB including cutaneous TB (lupus vulgaris, scrofuloderma, TBVC, tuberculids)",
       "Latent TB infection before biologics/JAK inhibitors (6–9 months alone, or with rifapentine/rifampicin in short regimens)"],
 dose=["5 mg/kg/day (max 300 mg) in fixed-dose combinations (India NTEP weight bands)",
       "Pyridoxine 10–25 mg/day to prevent neuropathy (higher in HIV, diabetes, malnutrition, pregnancy, alcoholism)"],
 ae=["Hepatitis (age-related; higher with rifampicin, alcohol)",
     "Peripheral neuropathy (pyridoxine deficiency) — prevented by pyridoxine",
     "Pellagra (niacin deficiency) — photosensitive dermatitis, diarrhoea, dementia",
     "Drug-induced lupus (ANA, antihistone antibodies)",
     "Acneiform eruption, exfoliative dermatitis, DRESS; optic neuritis, seizures, psychosis (rare)"],
 ci=["Previous INH-induced hepatitis; acute liver disease"],
 ix=["Inhibits CYP2C19/3A4 → raises phenytoin and carbamazepine levels",
     "Antacids reduce absorption; alcohol adds hepatotoxicity"],
 mon=["LFT at baseline and if symptoms (routine in high-risk); ask about neuropathy"],
 preg="Safe in pregnancy with pyridoxine.",
 viva=["Give pyridoxine with INH",
       "Cutaneous side effects: pellagra, acneiform eruption, drug-induced lupus",
       "Slow acetylators → neuropathy"],
 src=f"{K} ch.7 (Antituberculous agents); {W} ch.9 and ch.26 (TB screening before biologics)"),

dict(name="Pyrazinamide (PZA)", group="More from Khopkar · Antituberculous drugs",
 cls="Nicotinamide analogue; first-line antituberculous drug",
 moa=["Prodrug converted by mycobacterial pyrazinamidase to pyrazinoic acid, which is active in acidic environments (inside macrophages and caseous lesions)",
      "Disrupts membrane energy and trans-translation → kills semi-dormant bacilli — key to the 6-month short-course regimen"],
 uses=["Intensive phase of TB treatment (first 2 months), including cutaneous TB",
       "Not effective against M. bovis (naturally resistant) — relevant for BCG complications"],
 dose=["25 mg/kg/day (range 20–30) in fixed-dose combinations"],
 ae=["Hepatotoxicity (dose-related) — the most hepatotoxic first-line drug at high doses",
     "Hyperuricaemia and gout (inhibits urate excretion); arthralgia",
     "Photosensitivity, rash, pruritus; GI upset"],
 ci=["Severe liver disease; acute gout"],
 ix=["Antagonises probenecid and allopurinol (raises uric acid)"],
 mon=["LFT; uric acid if joint symptoms"],
 preg="WHO recommends its use in pregnancy (US guidance more cautious).",
 viva=["Works in acid pH — kills intracellular, semi-dormant bacilli",
       "Hyperuricaemia; M. bovis/BCG is naturally resistant"],
 src=f"{K} ch.7; {W} ch.9"),

dict(name="Ethambutol (E)", group="More from Khopkar · Antituberculous drugs",
 cls="Ethylenediamine derivative; first-line antituberculous drug",
 moa=["Inhibits arabinosyl transferase → blocks arabinogalactan synthesis in the mycobacterial cell wall (bacteriostatic)",
      "Mainly prevents resistance to other drugs"],
 uses=["TB (intensive and continuation phases in India's daily regimen), cutaneous TB",
       "Atypical mycobacteria (M. marinum with clarithromycin; MAC)"],
 dose=["15 mg/kg/day (range 15–25) in fixed-dose combinations",
       "Reduce dose/interval in renal impairment"],
 ae=["Optic (retrobulbar) neuritis: reduced visual acuity and red–green colour blindness (dose-related, usually reversible if stopped early)",
     "Hyperuricaemia, peripheral neuropathy, rash (rare)"],
 ci=["Pre-existing optic neuritis; young children who cannot report visual symptoms (relative)"],
 ix=["Aluminium antacids reduce absorption"],
 mon=["Visual acuity and colour vision (Ishihara) at baseline and monthly"],
 preg="Safe in pregnancy.",
 viva=["Optic neuritis — red–green colour vision test",
       "Used with clarithromycin for M. marinum"],
 src=f"{K} ch.7; {W} ch.9"),

dict(name="Streptomycin", group="More from Khopkar · Antituberculous drugs",
 cls="Aminoglycoside antibiotic (first aminoglycoside); injectable antituberculous drug",
 moa=["Binds the 30S ribosomal subunit → misreading of mRNA → bactericidal for extracellular bacilli"],
 uses=["TB (now rarely; previously in retreatment regimens)",
       "Plague, tularaemia, brucellosis (with doxycycline)",
       "Donovanosis and mycetoma (historical/alternative regimens)"],
 dose=["15 mg/kg IM daily (max 1 g; 0.75 g in older patients)"],
 ae=["Ototoxicity — mainly vestibular (vertigo, ataxia), also hearing loss",
     "Nephrotoxicity (less than other aminoglycosides), neuromuscular blockade",
     "Hypersensitivity rashes, contact dermatitis in health workers handling it"],
 ci=["Pregnancy (fetal deafness), myasthenia gravis, pre-existing hearing/vestibular disease"],
 ix=["Other ototoxic/nephrotoxic drugs (loop diuretics, vancomycin, amphotericin B)"],
 mon=["Hearing, balance, renal function"],
 preg="Contraindicated (old FDA category D — congenital deafness).",
 viva=["Vestibular toxicity — the classic streptomycin side effect",
       "Contraindicated in pregnancy"],
 src=f"{K} ch.7; {W} ch.9 (aminoglycosides)"),

dict(name="TB regimens for cutaneous tuberculosis", group="More from Khopkar · Antituberculous drugs",
 cls="Standard short-course antituberculous chemotherapy (India NTEP)",
 moa=["Combination of bactericidal (H, R, Z) and resistance-preventing (E) drugs",
      "Intensive phase kills the bulk of bacilli; continuation phase kills persisters"],
 uses=["All forms of cutaneous TB: lupus vulgaris, scrofuloderma, tuberculosis verrucosa cutis, orificial TB, metastatic tuberculous abscess, miliary TB of skin",
       "Tuberculids (papulonecrotic tuberculid, lichen scrofulosorum, erythema induratum) — when an active TB focus is found or empirically",
       "Therapeutic trial in suspected cutaneous TB (response in 4–6 weeks supports the diagnosis)"],
 dose=["India NTEP (daily regimen, new patients): intensive phase 2 months HRZE, continuation phase 4 months HRE (ethambutol continued) — total 6 months, fixed-dose combinations by weight band",
       "Extend continuation phase for extensive/scrofuloderma or slow responders (total 9–12 months, by physician decision)",
       "Drug-resistant TB: per NTEP drug-resistant guidelines (rapid molecular testing, bedaquiline-based regimens)"],
 ae=["Hepatotoxicity (H, R, Z) — commonest reason to interrupt",
     "Cutaneous drug reactions to ATT are common: morbilliform rash, lichenoid eruptions, DRESS, SJS/TEN — reintroduce drugs one by one after recovery"],
 ci=["See individual drugs"],
 mon=["Monthly clinical review; LFT if symptoms or risk; notification to NTEP (Nikshay); HIV test"],
 preg="First-line drugs (HRZE) are used in pregnancy; avoid streptomycin.",
 viva=["2HRZE + 4HRE daily (NTEP)",
       "Therapeutic trial — response by 4–6 weeks",
       "Reintroduction of ATT after cutaneous reactions"],
 src=f"{K} ch.7 (Regimens, DOTS); NTEP guidelines; {W} ch.9",
 note="Khopkar describes the older DOTS (thrice-weekly) regimen; India now uses daily fixed-dose combinations (NTEP). The current regimen is given here."),

dict(name="Second-line & newer antituberculous agents", group="More from Khopkar · Antituberculous drugs",
 cls="Drugs for drug-resistant TB and intolerance (ethionamide, cycloserine, PAS, injectable agents, fluoroquinolones, thiacetazone, newer drugs)",
 moa=["Ethionamide/prothionamide: inhibit InhA (mycolic acid synthesis)",
      "Cycloserine: inhibits cell-wall peptidoglycan synthesis (D-alanine analogue)",
      "Para-aminosalicylic acid (PAS): folate antagonist",
      "Injectables (kanamycin, amikacin, capreomycin): protein synthesis inhibitors",
      "Fluoroquinolones (levofloxacin, moxifloxacin): DNA gyrase inhibitors — backbone of MDR regimens",
      "Thiacetazone: older cheap drug, now abandoned",
      "Newer drugs (bedaquiline, delamanid, pretomanid, linezolid) now replace injectables in MDR-TB"],
 uses=["MDR/RR-TB and XDR-TB (including cutaneous forms) under the national programme",
       "Atypical mycobacterial infections (amikacin, clarithromycin, fluoroquinolones)"],
 dose=["As per NTEP drug-resistant TB guidelines (e.g. bedaquiline-pretomanid-linezolid-moxifloxacin, BPaLM, 6 months)"],
 ae=["Ethionamide: GI upset, hepatitis, hypothyroidism, gynaecomastia, alopecia, acne",
     "Cycloserine: psychosis, depression, seizures",
     "PAS: GI upset, hypothyroidism, lichenoid rash",
     "Injectables: ototoxicity, nephrotoxicity",
     "Thiacetazone: severe SJS/TEN, especially in HIV — the reason it was abandoned",
     "Bedaquiline/clofazimine/fluoroquinolones: QT prolongation; linezolid: myelosuppression, neuropathy"],
 ci=["Thiacetazone in HIV (never use)"],
 mon=["ECG (QT), CBC, LFT, thyroid, audiometry (injectables), psychiatric review (cycloserine)"],
 preg="Specialist decision; avoid injectables (ototoxic).",
 viva=["Thiacetazone → SJS/TEN in HIV",
       "Ethionamide → hypothyroidism, gynaecomastia",
       "MDR-TB now treated with all-oral bedaquiline-based regimens"],
 src=f"{K} ch.7 (Second-line and newer antituberculous agents); NTEP/WHO drug-resistant TB guidelines"),

dict(name="Regimens for atypical (non-tuberculous) mycobacterial infections", group="More from Khopkar · Antituberculous drugs",
 cls="Treatment of cutaneous infections by non-tuberculous mycobacteria (NTM)",
 moa=["NTM are naturally resistant to many first-line TB drugs; therapy is based on species and, for rapid growers, on sensitivity testing"],
 uses=["M. marinum (fish tank/swimming pool granuloma): clarithromycin + ethambutol (or rifampicin), or minocycline/doxycycline or co-trimoxazole alone for limited disease — continue 1–2 months after lesions resolve (usually 3–4 months total)",
       "Rapid growers (M. fortuitum, M. chelonae, M. abscessus — post-injection/post-procedure abscesses): clarithromycin plus another drug by sensitivity (amikacin, ciprofloxacin/levofloxacin, linezolid, cefoxitin, imipenem) for 4–6 months; surgical debridement",
       "M. ulcerans (Buruli ulcer): rifampicin + clarithromycin for 8 weeks (WHO), surgery/grafting as needed",
       "M. avium complex: clarithromycin/azithromycin + ethambutol + rifampicin",
       "M. kansasii: rifampicin + ethambutol + isoniazid/macrolide"],
 dose=["Clarithromycin 500 mg twice daily; ethambutol 15 mg/kg/day; rifampicin 10 mg/kg/day; minocycline/doxycycline 100 mg twice daily; co-trimoxazole 160/800 mg twice daily"],
 ae=["See component drugs; long courses need monitoring of liver, blood counts, vision (ethambutol), hearing (amikacin)"],
 ci=["See component drugs"],
 mon=["Culture and sensitivity for rapid growers; clinical response; drug toxicity monitoring"],
 preg="Avoid tetracyclines and aminoglycosides; macrolides with care.",
 viva=["M. marinum — sporotrichoid spread on the hand; clarithromycin + ethambutol",
       "Rapid growers after injections/cosmetic procedures — clarithromycin-based combination by sensitivity",
       "Buruli ulcer — rifampicin + clarithromycin 8 weeks"],
 src=f"{K} ch.7 (Table 7.2, regimens for atypical mycobacterial infections); {W} ch.9"),
]
