# Exam drugs — slot 4 (part A): Topicals I–V (antifungals, antibacterials, antiparasitics, corticosteroids, steroid combinations)
W = "Wolverton 4e"; K = "Khopkar"
D = [
# ---------------- I ANTIFUNGALS ----------------
dict(name="Ketoconazole (cream, lotion, shampoo)", group="Topicals · I Antifungals — Azoles",
 cls="Imidazole antifungal",
 moa=["Inhibits lanosterol 14-α-demethylase (CYP51) → ergosterol deficiency and toxic sterol build-up → fungistatic",
      "Strong activity against Malassezia; also mild anti-inflammatory and anti-androgenic effects"],
 uses=["Seborrhoeic dermatitis (face, scalp), dandruff",
       "Pityriasis versicolor (shampoo as a body wash), Malassezia folliculitis",
       "Tinea corporis/cruris/pedis, cutaneous candidiasis",
       "Androgenetic alopecia (adjunct shampoo)"],
 dose=["Cream 2%: once or twice daily for 2–4 weeks (tinea), longer for seborrhoeic dermatitis",
       "Shampoo 2%: seborrhoeic dermatitis/dandruff — lather, leave 3–5 min, rinse; twice weekly for 2–4 weeks, then weekly to prevent relapse",
       "Pityriasis versicolor: shampoo on affected skin for 5 min daily for 1–3 days (single-application regimens also used)",
       "Lotion 2% for scalp/hairy areas"],
 ae=["Local irritation, burning, dryness of hair; rare contact dermatitis",
     "Shampoo may change hair texture or colour (permanent-waved/grey hair)"],
 ci=["Hypersensitivity (including sulfite allergy for some formulations)"],
 preg="Topical use is safe (negligible absorption).",
 viva=["Drug of choice topically for seborrhoeic dermatitis and pityriasis versicolor",
       "Oral ketoconazole is no longer used for skin infections (hepatotoxicity, adrenal suppression) — topical is safe",
       "Shampoo needs contact time of 3–5 min"],
 src=f"{W} ch.42 (Topical antifungals) and ch.51 (Therapeutic shampoos); {K} ch.19"),

dict(name="Clotrimazole (cream, solution, dusting powder, paint, soap)", group="Topicals · I Antifungals — Azoles",
 cls="Imidazole antifungal",
 moa=["Inhibits fungal 14-α-demethylase → ergosterol depletion; fungistatic (fungicidal at high concentration)",
      "Broad spectrum: dermatophytes, Candida, Malassezia; some Gram-positive bacteria"],
 uses=["Cutaneous candidiasis (intertrigo, napkin candidiasis, paronychia), tinea corporis/cruris/pedis, pityriasis versicolor",
       "Dusting powder: prevention in moist areas (groin, toe webs, folds) after the cream clears infection",
       "Mouth paint 1%: oral thrush; vaginal tablets/cream: vulvovaginal candidiasis",
       "Solution: hairy areas, nails folds, ear (otomycosis)",
       "Soap: adjunct only (short contact time)"],
 dose=["Cream 1%: twice daily, continue 2 weeks after clinical cure (usually 2–4 weeks)",
       "Powder 1%: once or twice daily on dry skin",
       "Mouth paint 1%: 3–4 times daily for 1–2 weeks"],
 ae=["Burning, irritation, rare contact dermatitis"],
 ci=["Hypersensitivity"],
 preg="Safe — preferred topical azole for vaginal candidiasis in pregnancy.",
 viva=["Workhorse imidazole for candidiasis",
       "Powders are for prevention, not treatment of active infection",
       "Clotrimazole + steroid combinations are widely misused (see the combination post)"],
 src=f"{W} ch.42; {K} ch.19"),

dict(name="Sertaconazole 2% (cream, lotion)", group="Topicals · I Antifungals — Azoles",
 cls="Imidazole with a benzothiophene ring",
 moa=["Inhibits 14-α-demethylase (fungistatic)",
      "The benzothiophene ring mimics tryptophan and is inserted into the fungal membrane, making pores → direct fungicidal effect",
      "Also antibacterial (Gram-positive), anti-inflammatory and antipruritic (inhibits cytokines, activates p38–COX-2–PGE2 pathway)"],
 uses=["Tinea pedis (interdigital) — approved in the USA; tinea corporis/cruris",
       "Cutaneous candidiasis, pityriasis versicolor, seborrhoeic dermatitis",
       "Lotion for hairy areas, scalp and large areas"],
 dose=["Twice daily for 4 weeks"],
 ae=["Contact dermatitis, burning, dryness (uncommon)"],
 ci=["Hypersensitivity to imidazoles"],
 preg="Minimal absorption; use if needed.",
 viva=["Fungistatic + fungicidal (benzothiophene ring)",
       "Antipruritic and anti-inflammatory — useful in itchy tinea"],
 src=f"{W} ch.42 (azoles — sertaconazole); {K} ch.19"),

dict(name="Miconazole 2% cream", group="Topicals · I Antifungals — Azoles",
 cls="Imidazole antifungal",
 moa=["Inhibits 14-α-demethylase; at higher concentrations directly damages membranes",
      "Also active against Gram-positive bacteria"],
 uses=["Cutaneous and mucosal candidiasis (cream, oral gel, vaginal)",
       "Tinea corporis/cruris/pedis, pityriasis versicolor, angular cheilitis (Candida/staph)",
       "Napkin candidiasis"],
 dose=["Cream 2%: twice daily, continue 10–14 days after lesions clear",
       "Oral gel: 4 times daily after food (oral thrush)"],
 ae=["Local irritation, contact dermatitis"],
 ci=["Oral gel in infants under 4–6 months (choking risk)",
     "Oral gel with warfarin (see interactions)"],
 ix=["Miconazole oral gel (and even vaginal/topical use in large amounts) is absorbed and inhibits CYP2C9 → markedly raised INR with warfarin; also raises sulfonylurea and phenytoin levels"],
 preg="Topical use safe.",
 viva=["Miconazole oral gel + warfarin → bleeding (classic interaction)",
       "Useful in angular cheilitis (antifungal + antibacterial)"],
 src=f"{W} ch.42 and ch.66 (Drug interactions); {K} ch.19"),

dict(name="Oxiconazole nitrate 1% cream", group="Topicals · I Antifungals — Azoles",
 cls="Imidazole antifungal",
 moa=["Inhibits ergosterol synthesis; good stratum corneum retention allows once-daily use"],
 uses=["Tinea pedis, corporis, cruris", "Pityriasis versicolor"],
 dose=["Once or twice daily: 2 weeks (corporis/cruris, versicolor), 4 weeks (pedis)"],
 ae=["Itching, burning, irritation (uncommon)"],
 ci=["Hypersensitivity"],
 preg="Limited data; minimal absorption.",
 viva=["Once-daily imidazole for dermatophytosis and PV"],
 src=f"{W} ch.42; {K} ch.19"),

dict(name="Luliconazole 1% cream", group="Topicals · I Antifungals — Azoles",
 cls="Imidazole (ketene dithioacetal structure) — newest topical azole",
 moa=["Inhibits 14-α-demethylase; very low MICs against dermatophytes (among the most potent topical azoles)",
      "High stratum corneum retention → short, once-daily courses"],
 uses=["Tinea corporis, cruris and pedis (approved)",
       "Cutaneous candidiasis, pityriasis versicolor",
       "Onychomycosis (10% solution in Japan)"],
 dose=["Once daily: tinea corporis/cruris for 1 week, interdigital tinea pedis for 2 weeks (FDA label)",
       "In Indian practice with chronic/recurrent tinea, courses of 2–4 weeks are common"],
 ae=["Application-site irritation, contact dermatitis (rare)"],
 ci=["Hypersensitivity"],
 preg="Minimal absorption; animal data reassuring; use if needed.",
 viva=["Most potent topical azole against dermatophytes",
       "Once daily, short course",
       "Widely used in India — rising resistance concerns with misuse"],
 src=f"{W} ch.42 (luliconazole); {K} edition predates it"),

dict(name="Ciclopirox olamine (1% cream, 8% nail lacquer)", group="Topicals · I Antifungals — Other",
 cls="Hydroxypyridone antifungal",
 moa=["Chelates trivalent metal ions (Fe³⁺, Al³⁺) → inhibits metal-dependent enzymes (catalase, peroxidase, cytochromes) needed for fungal metabolism",
      "Different from azoles and allylamines — no cross-resistance",
      "Broad spectrum: dermatophytes, Candida, Malassezia, non-dermatophyte moulds, Gram-positive and Gram-negative bacteria; anti-inflammatory"],
 uses=["1% cream/gel: tinea, candidiasis, pityriasis versicolor, seborrhoeic dermatitis",
       "1% shampoo: seborrhoeic dermatitis of scalp",
       "8% nail lacquer: mild–moderate onychomycosis without matrix involvement (also in children), and as adjunct to oral therapy"],
 dose=["Cream: twice daily for 2–4 weeks",
       "Lacquer: apply daily to the nail and 5 mm of surrounding skin; apply new layers over old; remove all layers weekly with alcohol; trim/file the nail; continue up to 48 weeks"],
 ae=["Cream: mild burning, itching",
     "Lacquer: periungual redness, nail discolouration, ingrown nail (rare)"],
 ci=["Hypersensitivity"],
 preg="Minimal absorption; avoid unless needed.",
 viva=["Metal chelator — unique mechanism",
       "8% lacquer daily; remove weekly with alcohol; 48 weeks",
       "Antifungal + antibacterial + anti-inflammatory"],
 src=f"{W} ch.42; {K} ch.19"),

dict(name="Amorolfine (0.25% cream, 5% nail lacquer)", group="Topicals · I Antifungals — Other",
 cls="Morpholine antifungal",
 moa=["Inhibits two steps of ergosterol synthesis: Δ14-reductase and Δ7–Δ8 isomerase → ergosterol depletion and toxic sterol build-up",
      "Fungicidal against dermatophytes; also active against Candida and some moulds"],
 uses=["0.25% cream: tinea corporis, cruris, pedis; cutaneous candidiasis; pityriasis versicolor",
       "5% lacquer: distal and lateral onychomycosis without matrix involvement (up to 2 nails / under 80% nail area), and with oral antifungals for more severe disease"],
 dose=["Cream: once daily (evening) for at least 2–3 weeks, continue 3–5 days after cure",
       "Lacquer: file the nail, clean with alcohol swab, apply once or twice weekly — 6 months for fingernails, 9–12 months for toenails"],
 ae=["Mild burning, itching, erythema",
     "Lacquer: nail discolouration, brittleness"],
 ci=["Hypersensitivity; children (limited data for lacquer)"],
 preg="Avoid (limited data).",
 viva=["Morpholine — two enzymes in ergosterol pathway",
       "Lacquer once weekly (vs ciclopirox daily)",
       "Not available in the USA; used in India and Europe"],
 src=f"{K} ch.19; {W} ch.42 (brief)"),

dict(name="Coal tar + Ketoconazole scalp lotion/shampoo", group="Topicals · I Antifungals — Other",
 cls="Combination: keratoplastic/antiproliferative tar + imidazole antifungal",
 moa=["Coal tar: antiproliferative (activates aryl hydrocarbon receptor → normalises keratinocyte differentiation), antipruritic, anti-inflammatory",
      "Ketoconazole: reduces Malassezia load",
      "Together they treat scaling, inflammation and the yeast driver in scalp disease"],
 uses=["Seborrhoeic dermatitis and dandruff of scalp, especially thick scaling",
       "Scalp psoriasis (mild) and sebopsoriasis"],
 dose=["Lotion: apply to scalp at night, wash next morning (or as directed) 2–3 times weekly",
       "Shampoo: lather, leave 3–5 min, rinse; 2–3 times weekly, then weekly for maintenance"],
 ae=["Tar: odour, staining of hair (especially grey/blonde) and fabrics, folliculitis, irritation, photosensitivity",
     "Ketoconazole: irritation, dry hair"],
 ci=["Acutely inflamed or broken scalp skin; infected scalp",
     "Avoid tar in pustular or erythrodermic psoriasis"],
 preg="Coal tar: avoid in pregnancy (theoretical carcinogenicity); ketoconazole topical safe.",
 viva=["Tar = AhR agonist (normalises differentiation), ketoconazole = anti-Malassezia",
       "Tar shampoos may stain grey hair yellow"],
 src=f"{W} ch.51 (Therapeutic shampoos) and ch.57 (Miscellaneous topicals — tar); {K} ch.28"),

# ---------------- II ANTIBACTERIALS ----------------
dict(name="Ozenoxacin 1% cream", group="Topicals · II Antibacterials",
 cls="Non-fluorinated quinolone (topical only)",
 moa=["Inhibits both bacterial DNA gyrase and topoisomerase IV → bactericidal",
      "Dual-target binding means a lower chance of resistance; active against MRSA and quinolone-resistant strains, and Streptococcus pyogenes"],
 uses=["Impetigo (non-bullous and bullous, localised) in adults and children 2 months and older"],
 dose=["Thin layer twice daily for 5 days (up to 100 cm² in adults; 2% BSA in children)"],
 ae=["Rare: application-site itching, rosacea flare, seborrhoeic dermatitis"],
 ci=["Hypersensitivity; not for eyes, mouth or mucosa"],
 preg="Negligible absorption — acceptable.",
 viva=["Newer impetigo treatment; works against MRSA and mupirocin-resistant staph",
       "5-day course, twice daily"],
 src=f"{W} ch.41 (Topical antibacterial agents — ozenoxacin)"),

dict(name="Clindamycin phosphate 1% gel", group="Topicals · II Antibacterials",
 cls="Lincosamide antibiotic (topical)",
 moa=["Binds the 50S ribosomal subunit → inhibits bacterial protein synthesis (bacteriostatic)",
      "Reduces C. acnes and the free fatty acids it produces; anti-inflammatory (reduces neutrophil chemotaxis)",
      "Phosphate ester is inactive until hydrolysed in the skin"],
 uses=["Inflammatory acne vulgaris (papules, pustules) — always combined with benzoyl peroxide (BPO) to prevent resistance",
       "Folliculitis, hidradenitis suppurativa (mild, Hurley I), rosacea (alternative), pitted keratolysis, erythrasma",
       "Also in the anti-acne list (group VII)"],
 dose=["Thin layer once or twice daily",
       "Fixed combinations: clindamycin 1% + BPO 2.5–5%; clindamycin 1.2% + tretinoin 0.025%; clindamycin + adapalene; clindamycin + nicotinamide",
       "Do not use as monotherapy and limit to about 12 weeks"],
 ae=["Dryness, peeling, irritation",
     "C. acnes and staphylococcal resistance with monotherapy",
     "C. difficile colitis is very rare (case reports)"],
 ci=["History of inflammatory bowel disease or antibiotic-associated colitis",
     "Hypersensitivity to lincomycin/clindamycin"],
 ix=["Erythromycin topical — antagonism (both act at 50S)"],
 preg="Safe in pregnancy (preferred topical antibiotic with BPO).",
 viva=["Never use topical antibiotics alone for acne — always with BPO (resistance)",
       "Safe in pregnancy",
       "Rare pseudomembranous colitis — ask about bowel disease"],
 src=f"{W} ch.41 (Topical antibacterials); {K} ch.18"),

dict(name="Clindamycin + Nicotinamide gel", group="Topicals · II Antibacterials",
 cls="Combination: lincosamide antibiotic + vitamin B3 (anti-inflammatory)",
 moa=["Clindamycin: 50S protein-synthesis inhibitor (anti-C. acnes)",
      "Nicotinamide 4%: anti-inflammatory (inhibits neutrophil chemotaxis, IL-8, mast cells), reduces sebum, improves barrier",
      "Nicotinamide is non-antibiotic, so the combination may reduce reliance on the antibiotic"],
 uses=["Mild–moderate inflammatory acne"],
 dose=["Usually clindamycin 1% + nicotinamide 4% gel once or twice daily; combine with BPO or a retinoid; limit antibiotic use to about 12 weeks"],
 ae=["Dryness, irritation, burning"],
 ci=["As for clindamycin"],
 preg="Acceptable.",
 viva=["Nicotinamide 4% gel alone is comparable to clindamycin 1% in some trials",
       "Combination still needs BPO to prevent resistance"],
 src=f"{W} ch.41 and ch.57 (nicotinamide); {K} ch.28 (topical niacinamide)"),

dict(name="Mupirocin 2% cream/ointment", group="Topicals · II Antibacterials",
 cls="Monoxycarbolic acid antibiotic (pseudomonic acid A, from Pseudomonas fluorescens)",
 moa=["Reversibly binds bacterial isoleucyl-tRNA synthetase → stops protein synthesis",
      "Unique target — no cross-resistance with other antibiotics",
      "Bacteriostatic at low concentration, bactericidal at the high concentrations reached on skin",
      "Active against Staphylococcus aureus (including MRSA) and Streptococcus pyogenes"],
 uses=["Impetigo (localised), secondarily infected eczema, folliculitis, small infected wounds",
       "Nasal decolonisation of S. aureus/MRSA carriers (recurrent furunculosis, before surgery)"],
 dose=["Apply 2–3 times daily for 5–10 days",
       "Nasal ointment: twice daily into both nostrils for 5 days (with chlorhexidine body washes for recurrent boils)"],
 ae=["Burning, itching",
     "Polyethylene glycol (ointment base) can be absorbed from large wounds → nephrotoxicity (avoid in renal impairment on extensive raw areas)",
     "Resistance with prolonged or repeated use (low-level and high-level mupA-mediated)"],
 ci=["Hypersensitivity; large burns or open wounds in renal impairment (PEG base)"],
 preg="Safe.",
 viva=["Target: isoleucyl-tRNA synthetase",
       "Nasal decolonisation for recurrent furunculosis",
       "Limit course to under 10 days to prevent resistance"],
 src=f"{W} ch.41; {K} ch.18"),

dict(name="Framycetin sulphate 1% cream", group="Topicals · II Antibacterials",
 cls="Aminoglycoside antibiotic (closely related to neomycin; neomycin B)",
 moa=["Binds the 30S ribosomal subunit → misreading of mRNA → bactericidal",
      "Active against staphylococci and many Gram-negative bacilli; weak against streptococci"],
 uses=["Superficial bacterial skin infections, infected wounds, burns, ulcers (also as impregnated gauze — tulle dressings)",
       "Commonly used in India; limited by sensitisation"],
 dose=["Apply 2–3 times daily for up to 7 days; gauze dressings changed daily"],
 ae=["Allergic contact dermatitis (common; cross-reacts with neomycin, gentamicin)",
     "Ototoxicity and nephrotoxicity if absorbed from large raw areas, especially in renal impairment"],
 ci=["Large raw areas/burns in renal impairment; perforated ear drum (ototoxic)",
     "Known aminoglycoside allergy"],
 preg="Avoid on large areas (fetal ototoxicity in theory).",
 viva=["Aminoglycoside — contact sensitiser (neomycin group) and ototoxic if absorbed",
       "Suspect allergy if a wound worsens on framycetin tulle"],
 src=f"{K} ch.18; {W} ch.41 (neomycin/aminoglycosides) and ch.56 (Irritants and allergens)"),

dict(name="Fusidic acid 2% cream", group="Topicals · II Antibacterials",
 cls="Fusidane (steroid-like) antibiotic",
 moa=["Inhibits elongation factor G → stops bacterial protein synthesis",
      "Excellent penetration through intact skin and crusts; active against S. aureus (including many MRSA) and streptococci"],
 uses=["Impetigo, folliculitis, infected eczema, erythrasma, paronychia",
       "Combinations with steroid (fusidic acid + betamethasone/hydrocortisone) for infected eczema"],
 dose=["Apply 3 times daily for up to 7–10 days (short courses limit resistance)"],
 ae=["Local irritation; rare contact dermatitis",
     "Rapid emergence of resistance with prolonged or widespread use"],
 ci=["Hypersensitivity"],
 preg="Safe.",
 viva=["EF-G inhibitor; steroid-like structure",
       "Resistance is a major problem — keep courses short",
       "Good penetration through crusts"],
 src=f"{W} ch.41; {K} ch.18"),

dict(name="Minocycline 4% topical foam", merge_into="Minocycline", form_label="Topical form", group="Topicals · II Antibacterials",
 cls="Tetracycline antibiotic in a hydrophobic foam base (topical minocycline foam)",
 moa=["Binds the 30S ribosome; anti-inflammatory (MMP inhibition, neutrophil effects)",
      "Topical delivery gives high follicular levels with negligible blood levels — avoids systemic minocycline side effects"],
 uses=["Moderate–severe inflammatory acne (4% foam, age 9 and over)",
       "Papulopustular rosacea (1.5% foam)"],
 dose=["Apply once daily at about the same time, at least 1 h before bathing/sleep; avoid fire (flammable)"],
 ae=["Mild irritation; possible hyperpigmentation (rare)",
     "Theoretically tooth discolouration in children under 8 — not used in that age group"],
 ci=["Hypersensitivity to tetracyclines; children under 9"],
 preg="Avoid in pregnancy (tetracycline class).",
 viva=["Topical tetracycline that avoids vestibular and autoimmune side effects of oral minocycline",
       "Foam is flammable"],
 src="Not covered in Wolverton 4e or Khopkar (newer product); product information (Amzeeq/Zilxi)",
 note="The exam list says 4% gel; the approved product is minocycline 4% foam (acne) and 1.5% foam (rosacea), so it is listed as a foam. Topical minocycline is not described in Wolverton 4e or Khopkar; added at your request."),

# ---------------- III ANTIPARASITICS ----------------
dict(name="Permethrin (5% cream, 1% creme rinse)", group="Topicals · III Antiparasitics",
 cls="Synthetic pyrethroid",
 moa=["Blocks sodium channels in the parasite's nerve membranes (delays repolarisation) → paralysis and death of mites and lice",
      "Poorly absorbed (under 2%) and rapidly inactivated by esterases in humans → very safe",
      "Partly ovicidal"],
 uses=["5% cream: scabies (first line), including children over 2 months and pregnant/breastfeeding women",
       "1% creme rinse: head lice (pediculosis capitis) and pubic lice",
       "Crusted scabies (with oral ivermectin)"],
 dose=["Scabies: apply 5% cream to the whole body from the neck down (include scalp, face and ears in infants, elderly and immunocompromised), especially between fingers, wrists, genitals and under nails; wash off after 8–14 h; repeat after 7 days",
       "Treat all close contacts at the same time; wash clothes and bedding in hot water or store in a sealed bag for 72 h",
       "Head lice: apply 1% rinse to washed, towel-dried hair for 10 min, rinse; repeat on day 9–10; wet-comb to remove nits"],
 ae=["Burning, stinging, itch (post-scabetic itch may last 2–4 weeks — not treatment failure)",
     "Contact dermatitis (rare; cross-reaction with chrysanthemum/ragweed)"],
 ci=["Hypersensitivity to pyrethrins/chrysanthemums; infants under 2 months (5% cream)"],
 preg="Safe — first choice in pregnancy and breastfeeding.",
 viva=["Drug of choice for scabies",
       "Apply neck down (whole body in infants and elderly), 8–14 h, repeat after 1 week",
       "Treat contacts simultaneously",
       "Itch persisting 2–4 weeks is expected"],
 src=f"{W} ch.44 (Topical antiparasitic agents); {K} ch.21"),

dict(name="Ivermectin 1% cream (and 0.5% lotion)", merge_into="Ivermectin", form_label="Topical form", group="Topicals · III Antiparasitics",
 cls="Macrocyclic lactone (avermectin) — topical",
 moa=["Binds glutamate-gated chloride channels in invertebrates → paralysis of Demodex mites and lice",
      "Anti-inflammatory effects (reduces neutrophil activity and cytokines)"],
 uses=["1% cream: papulopustular rosacea (more effective than metronidazole gel), demodicosis",
       "0.5% lotion: head lice (age 6 months and older) — single 10-min application, no nit combing needed",
       "Scabies (off-label, compounded 1% lotion/cream)"],
 dose=["Rosacea: 1% cream once daily for up to 16 weeks, then maintenance",
       "Head lice: 0.5% lotion to dry hair and scalp, leave 10 min, rinse — single use"],
 ae=["Burning, irritation, dry skin; transient rosacea flare at start"],
 ci=["Hypersensitivity"],
 preg="Minimal absorption; limited data — avoid unless needed.",
 viva=["Targets Demodex in rosacea",
       "Single-application head lice treatment"],
 src=f"{W} ch.44; {K} ch.21"),

dict(name="Spinosad 0.9% lotion", group="Topicals · III Antiparasitics",
 cls="Spinosyn insecticide (from fermentation of the soil bacterium Saccharopolyspora spinosa)",
 moa=["Activates nicotinic acetylcholine receptors in the insect nervous system → hyperexcitation, paralysis and death",
      "Pediculicidal and ovicidal (contains benzyl alcohol) — often one application is enough"],
 uses=["Head lice in patients 6 months and older (FDA)",
       "Scabies (approved in the USA for age 4 years and older)"],
 dose=["Head lice: cover dry scalp and hair, leave 10 min, rinse; repeat after 7 days only if live lice are seen",
       "Scabies: apply to the whole body, leave 10 min (label) — check current label"],
 ae=["Redness and irritation of scalp and eyes"],
 ci=["Infants under 6 months (benzyl alcohol — gasping syndrome)"],
 preg="Minimal absorption; considered acceptable.",
 viva=["Ovicidal — nit combing not mandatory",
       "Benzyl alcohol content — avoid under 6 months"],
 src=f"{W} ch.44 (spinosad, head lice); not in {K}"),

# ---------------- IV TOPICAL CORTICOSTEROIDS ----------------
dict(name="Topical corticosteroids — overview & potency", group="Topicals · IV Topical corticosteroids",
 cls="Glucocorticoids for skin use; classified by potency (vasoconstrictor assay)",
 moa=["Anti-inflammatory: switch off NF-κB/AP-1-driven cytokines; induce lipocortin → less arachidonic acid → fewer prostaglandins and leukotrienes",
      "Immunosuppressive: reduce Langerhans cells, T-cell activation",
      "Antiproliferative (epidermis and fibroblasts) — useful in psoriasis, harmful as atrophy",
      "Vasoconstrictive — basis of the McKenzie–Stoughton potency assay"],
 pk=["Absorption increases with: higher potency, ointment base, occlusion, thin skin (face, eyelids, genitals, flexures — up to 30–40 times forearm), inflamed skin, infants and elderly, large area",
     "Halogenation (fluorination) increases potency and side effects"],
 uses=["US 7-class system (most to least potent):",
       "Class 1 (super-potent): clobetasol propionate 0.05%, halobetasol propionate 0.05%, augmented betamethasone dipropionate 0.05% ointment",
       "Class 2 (high): mometasone furoate 0.1% ointment, fluocinonide 0.05%, desoximetasone 0.25%",
       "Class 3 (high): betamethasone valerate 0.1% ointment, fluticasone propionate 0.005% ointment",
       "Class 4 (medium): mometasone furoate 0.1% cream, triamcinolone acetonide 0.1% ointment, fluocinolone 0.025% ointment",
       "Class 5 (medium–low): triamcinolone 0.1% cream/lotion, fluticasone 0.05% cream, betamethasone valerate 0.1% cream, hydrocortisone valerate/butyrate",
       "Class 6 (low): desonide 0.05%, fluocinolone 0.01%, alclometasone 0.05%",
       "Class 7 (least potent): hydrocortisone 1–2.5% (acetate or base)",
       "UK/India often use a 4-class system: very potent (clobetasol), potent (betamethasone valerate, mometasone), moderate (clobetasone butyrate), mild (hydrocortisone)"],
 dose=["Fingertip unit (FTU): ribbon from the tip of an adult index finger to the first crease ≈ 0.5 g, covers about 2 adult palms (2% BSA)",
       "Once or twice daily; once daily is usually enough for potent steroids (reservoir effect)",
       "Super-potent: no more than 50 g/week and usually 2 weeks continuous use, then taper or switch to pulsed weekend therapy",
       "Face, flexures, genitals, children: low/medium potency, short courses",
       "Weekend (proactive) therapy twice weekly prevents eczema flares",
       "Tachyphylaxis — loss of effect with continuous use; use intermittent schedules"],
 ae=["Local: atrophy, striae (irreversible), telangiectasia, purpura, hypopigmentation, hypertrichosis",
     "Steroid acne, rosacea-like and perioral dermatitis",
     "Masking of infection: tinea incognito (steroid-modified tinea — a major problem in India), scabies incognito, worsening of herpes/molluscum/demodex",
     "Topical steroid withdrawal/dependence ('red skin'); topical steroid-damaged face (TSDF) from misuse of creams as fairness products",
     "Allergic contact dermatitis to the steroid (suspect when eczema does not improve; budesonide, tixocortol are markers)",
     "Periocular use: glaucoma, cataract",
     "Systemic: HPA suppression, iatrogenic Cushing, growth retardation in children (large area, potent, occlusion, infants)"],
 ci=["Untreated skin infections (bacterial, fungal, viral, scabies), rosacea, perioral dermatitis, acne vulgaris, ulcerated skin",
     "Potent steroids on face, flexures, genitals and in infants (except under specialist guidance)"],
 preg="Mild–moderate steroids are safe; potent/super-potent steroids over large areas are linked to low birth weight — use the lowest potency for the shortest time.",
 viva=["Know 1–2 examples for each class",
       "FTU = 0.5 g; 1 FTU covers 2 palms",
       "Clobetasol: max 50 g/week, 2 weeks",
       "Tinea incognito and TSDF — the Indian steroid misuse problem; irrational antifungal–steroid FDCs",
       "Contact allergy to steroids — suspect when eczema fails to respond"],
 src=f"{W} ch.45 (Topical corticosteroids); {K} ch.22 (Topical and intralesional corticosteroids)"),

dict(name="Hydrocortisone acetate 1% lotion/cream", merge_into="Hydrocortisone sodium succinate injection", form_label="Topical form", group="Topicals · IV Topical corticosteroids",
 cls="Least potent topical steroid (US class 7; UK 'mild'); non-fluorinated",
 moa=["Glucocorticoid receptor agonist — mild anti-inflammatory action with very little atrophy"],
 uses=["Face, eyelids, flexures, genitals and nappy area",
       "Infants and children: mild eczema, seborrhoeic dermatitis, intertrigo",
       "Maintenance after stronger steroids"],
 dose=["Apply thinly once or twice daily; can be used for longer periods than potent steroids"],
 ae=["Very low risk; prolonged use on the face can still cause perioral dermatitis/rosacea",
     "Contact allergy (tixocortol pivalate group — class A)"],
 ci=["Untreated infection, rosacea, perioral dermatitis"],
 preg="Safe.",
 viva=["Safest steroid for face and infants",
       "Hydrocortisone is the marker of class A (Coopman) contact allergy"],
 src=f"{W} ch.45; {K} ch.22"),

dict(name="Desonide 0.05% cream/lotion", group="Topicals · IV Topical corticosteroids",
 cls="Low-potency non-fluorinated topical steroid (US class 6)",
 moa=["Glucocorticoid receptor agonist; low atrophy risk"],
 uses=["Atopic dermatitis and seborrhoeic dermatitis of face and flexures, children (approved from 3 months)",
       "Mild eczema in sensitive areas"],
 dose=["Thin layer twice daily; usually up to 4 weeks"],
 ae=["Burning, mild atrophy with long use; perioral dermatitis"],
 ci=["Untreated infections, rosacea, perioral dermatitis"],
 preg="Acceptable (low potency).",
 viva=["Low potency, non-fluorinated — suitable for face and children",
       "Belongs to the acetonide group (class B contact allergy)"],
 src=f"{W} ch.45; {K} ch.22"),

dict(name="Mometasone furoate 0.1% (cream, ointment, lotion)", group="Topicals · IV Topical corticosteroids",
 cls="Medium (cream, US class 4) to high (ointment, class 2) potency non-fluorinated (chlorinated) steroid; 'soft steroid'",
 moa=["Potent glucocorticoid receptor agonist with high skin activity but low systemic bioavailability (rapid hepatic breakdown)",
      "Favourable ratio of benefit to atrophy"],
 uses=["Atopic dermatitis, psoriasis (including scalp — lotion), lichen planus, discoid lupus, seborrhoeic dermatitis",
       "Children over 2 years (short courses), and limited face use under supervision",
       "Proactive twice-weekly maintenance in atopic dermatitis"],
 dose=["Once daily (its long skin activity allows single daily application)",
       "Children: avoid long courses, large areas and occlusion"],
 ae=["Atrophy, striae, perioral dermatitis with misuse (lower than other potent steroids)",
     "Widely misused in India in fairness/combination creams"],
 ci=["As for topical steroids; avoid in nappy area under occlusion"],
 preg="Use on limited areas for short periods.",
 viva=["Once-daily 'soft' steroid with low systemic absorption",
       "Cream class 4 vs ointment class 2 — vehicle changes potency"],
 src=f"{W} ch.45; {K} ch.22"),

dict(name="Triamcinolone acetonide (cream, lotion, paste)", merge_into="Triamcinolone acetonide injection", form_label="Topical form", group="Topicals · IV Topical corticosteroids",
 cls="Medium-potency fluorinated steroid (0.1% cream/lotion US class 5; ointment class 4)",
 moa=["Glucocorticoid receptor agonist (acetonide group)"],
 uses=["Cream/lotion 0.1%: eczema, psoriasis, lichen planus, insect bite reactions, body and scalp (lotion)",
       "Dental/oral paste 0.1% (in Orabase — adheres to wet mucosa): oral lichen planus, aphthous ulcers, mucous membrane pemphigoid and other erosive oral lesions",
       "Also used intralesionally (injectables slot)"],
 dose=["Cream/lotion: 2–3 times daily (or once daily for maintenance)",
       "Oral paste: dab (do not rub) a small amount onto the dried lesion 2–4 times daily, preferably after meals and at bedtime"],
 ae=["Skin: as for medium-potency steroids",
     "Oral paste: oral candidiasis (thrush) with prolonged use — add an antifungal if needed"],
 ci=["Skin infections; oral paste — oral herpes, candidiasis, untreated infection"],
 preg="Acceptable on limited areas.",
 viva=["Orabase paste sticks to wet mucosa — main topical steroid for oral lesions",
       "Watch for oral candidiasis"],
 src=f"{W} ch.45 and ch.61 (Oral mucosal therapeutics); {K} ch.22"),

dict(name="Fluticasone propionate + Mupirocin cream", group="Topicals · IV Topical corticosteroids",
 cls="Combination: medium-potency fluorinated steroid (fluticasone 0.05%, US class 5) + mupirocin 2%",
 moa=["Fluticasone: potent glucocorticoid receptor agonist with rapid hepatic inactivation (low systemic effect)",
      "Mupirocin: isoleucyl-tRNA synthetase inhibitor — kills S. aureus and Streptococcus that colonise and worsen eczema"],
 uses=["Secondarily infected (impetiginised) eczema and dermatitis — short term",
       "Infected insect bite reactions, infected lichen simplex"],
 dose=["Twice daily for 7–10 days, then switch to plain steroid"],
 ae=["Steroid side effects with misuse; mupirocin resistance with long use; burning"],
 ci=["Primary bacterial, fungal or viral infections without dermatitis; rosacea, acne",
     "Not for long-term use"],
 preg="Acceptable on limited areas.",
 viva=["Rational combination only for short-term infected eczema",
       "Fluticasone is safe in children (approved from 3 months) as plain cream"],
 src=f"{W} ch.45 and ch.41; {K} ch.22"),

dict(name="Clobetasol propionate 0.05% (ointment, lotion, solution)", group="Topicals · IV Topical corticosteroids",
 cls="Super-potent fluorinated steroid (US class 1; UK 'very potent')",
 moa=["Most potent glucocorticoid receptor agonist used on skin — strong anti-inflammatory and antiproliferative effects"],
 uses=["Chronic plaque psoriasis (body; scalp — lotion/solution/shampoo), palmoplantar psoriasis and eczema",
       "Lichen planus (hypertrophic), lichen simplex chronicus, discoid lupus",
       "Lichen sclerosus (first-line, including genital — even in children under specialist care)",
       "Localised bullous pemphigoid (whole-body clobetasol is as effective as oral steroids)",
       "Alopecia areata (under occlusion), vitiligo (limited areas, short pulses)"],
 dose=["Once or twice daily; maximum 50 g per week; usually no more than 2 weeks continuously, then taper or use pulsed/weekend therapy",
       "Bullous pemphigoid: 10–40 g/day initially over the whole body (except face), then taper over months",
       "Lichen sclerosus: once daily for 1 month, alternate days for 1 month, twice weekly for 1 month, then as needed"],
 ae=["All topical steroid side effects — most likely with this agent: atrophy, striae, purpura, telangiectasia, steroid rosacea, tinea incognito, HPA suppression with large areas, Cushing syndrome",
     "Commonly misused in India in fairness and 'itch' creams — leading cause of topical steroid-damaged face"],
 ci=["Face, flexures, genitals (except lichen sclerosus), children under 12 (except specialist use)",
     "Rosacea, acne, perioral dermatitis, untreated infection"],
 preg="Avoid large areas/long courses (association with low birth weight).",
 viva=["Most potent topical steroid: max 50 g/week, 2 weeks",
       "First-line for lichen sclerosus and localised bullous pemphigoid",
       "Ointment more potent than cream; lotion/solution for scalp"],
 src=f"{W} ch.45; {K} ch.22"),

dict(name="Halobetasol propionate (0.05% / 0.01% lotion)", group="Topicals · IV Topical corticosteroids",
 cls="Super-potent fluorinated steroid (US class 1); 0.01% lotion in a newer vehicle remains high/super-high potency",
 moa=["Glucocorticoid receptor agonist with very high potency (similar to clobetasol)",
      "The 0.01% lotion (polymeric emulsion) delivers drug efficiently, allowing a lower concentration with less HPA suppression and longer use (up to 8 weeks)"],
 uses=["Plaque psoriasis (adults)",
       "Other steroid-responsive thick dermatoses (lichen simplex, hypertrophic lichen planus)"],
 dose=["0.05% cream/ointment: once or twice daily, max 50 g/week, up to 2 weeks",
       "0.01% lotion: once daily for up to 8 weeks, max 50 g/week",
       "Halobetasol 0.01% + tazarotene 0.045% lotion is also available for psoriasis"],
 ae=["As for super-potent steroids: atrophy, striae, folliculitis, HPA suppression"],
 ci=["Face, flexures, groin; children under 12–18 (label); untreated infection, rosacea"],
 preg="Avoid large areas.",
 viva=["Class 1 steroid; 0.01% lotion allows 8-week use",
       "Fixed combination with tazarotene reduces retinoid irritation and steroid atrophy"],
 src=f"{W} ch.45; product information for 0.01% lotion (Bryhali)"),

dict(name="Halobetasol + Salicylic acid", group="Topicals · IV Topical corticosteroids",
 cls="Combination: super-potent steroid + keratolytic",
 moa=["Salicylic acid (usually 3%) dissolves the cement between corneocytes (desmolytic) → removes scale",
      "This increases penetration of the steroid into thick plaques"],
 uses=["Thick, scaly plaque psoriasis, hyperkeratotic eczema, lichen simplex chronicus, palmoplantar psoriasis/eczema"],
 dose=["Once or twice daily for up to 2 weeks (max 50 g/week), then taper"],
 ae=["Steroid side effects; irritation and stinging from salicylic acid",
     "Salicylism if used over large areas (especially with renal impairment, children)"],
 ci=["Face, flexures, children; large body areas; aspirin allergy (relative); untreated infection"],
 preg="Avoid large areas.",
 viva=["Salicylic acid improves steroid penetration in thick plaques",
       "Salicylate toxicity if large areas are treated"],
 src=f"{W} ch.45 and ch.55 (Agents for hyperkeratosis); {K} ch.22 and ch.27"),

dict(name="Clobetasol + Salicylic acid", group="Topicals · IV Topical corticosteroids",
 cls="Combination: super-potent steroid (clobetasol 0.05%) + keratolytic (salicylic acid 3–6%)",
 moa=["Salicylic acid removes scale (desmolytic), allowing better steroid penetration"],
 uses=["Thick plaque and scalp psoriasis (lotion/ointment), palmoplantar psoriasis, hyperkeratotic hand eczema, lichen simplex chronicus"],
 dose=["Once or twice daily for up to 2 weeks; maximum 50 g/week; then switch to a maintenance regimen"],
 ae=["Steroid atrophy, striae, HPA suppression; salicylic acid irritation; salicylism over large areas"],
 ci=["Face, flexures, genitals, children; large areas; infection"],
 preg="Avoid large areas.",
 viva=["Same principle as halobetasol + SA",
       "Avoid on more than about 20% of body surface (salicylism and steroid absorption)"],
 src=f"{W} ch.45 and ch.55; {K} ch.22"),

# ---------------- V STEROID COMBINATIONS ----------------
dict(name="Clotrimazole + Beclomethasone cream", group="Topicals · V Steroid combinations",
 cls="Combination: imidazole antifungal (clotrimazole 1%) + potent fluorinated steroid (beclomethasone dipropionate 0.025%)",
 moa=["Clotrimazole: ergosterol synthesis inhibitor",
      "Beclomethasone: rapid relief of itch and inflammation"],
 uses=["Limited valid use: short-term (under 1–2 weeks) for highly inflamed candidal intertrigo or dermatophyte infection, under a doctor's supervision",
       "In practice it is heavily misused (OTC) in India for any itchy rash"],
 dose=["Twice daily for a maximum of about 1–2 weeks; then continue plain antifungal"],
 ae=["Steroid-modified tinea (tinea incognito) — extensive, atypical, chronic, recurrent dermatophytosis",
     "Atrophy, striae (especially groin and thighs), telangiectasia, topical steroid dependence",
     "Majocchi granuloma (deep fungal folliculitis), treatment failure, increasing antifungal resistance"],
 ci=["Tinea when used for more than a short period; children, face, flexures (steroid absorption)",
     "Not for self-medication"],
 preg="Avoid.",
 viva=["Irrational/misused FDC — a key driver of India's chronic dermatophytosis epidemic",
       "Many steroid–antifungal–antibiotic FDCs were banned by the Indian government in 2018; IADVL campaigns against steroid misuse",
       "Treat tinea with antifungal alone"],
 src=f"{W} ch.42 and ch.45 (misuse of combinations); {K} ch.19 and ch.22; IADVL taskforce on steroid abuse"),

dict(name="Ketoconazole + Clobetasone butyrate cream", group="Topicals · V Steroid combinations",
 cls="Combination: imidazole antifungal (ketoconazole 2%) + moderate-potency steroid (clobetasone butyrate 0.05%, UK 'moderate')",
 moa=["Ketoconazole: anti-Malassezia, anti-dermatophyte, mild anti-inflammatory",
      "Clobetasone butyrate: moderate steroid (much weaker than clobetasol — do not confuse the names)"],
 uses=["Short-term for inflamed seborrhoeic dermatitis (face, flexures) and inflamed intertrigo",
       "Not recommended for tinea"],
 dose=["Once or twice daily for up to 1–2 weeks, then plain ketoconazole for maintenance"],
 ae=["Steroid side effects with prolonged use: perioral dermatitis, rosacea, atrophy; tinea incognito"],
 ci=["Tinea, rosacea, acne, perioral dermatitis; long-term use on face"],
 preg="Avoid prolonged use.",
 viva=["Clobetasone (moderate) ≠ clobetasol (super-potent) — classic confusion",
       "Rationale is seborrhoeic dermatitis, not tinea"],
 src=f"{W} ch.45; {K} ch.22"),
]
