# More from Khopkar — slot 7: other antibacterials, antifungals, antivirals & ART, antiparasitics
W = "Wolverton 4e"; K = "Khopkar"
D = [
# ---------------- ANTIBACTERIALS ----------------
dict(name="Penicillins (penicillin G, amoxicillin, ampicillin, cloxacillin)", group="More from Khopkar · Other antibacterials",
 cls="β-lactam antibiotics — natural penicillins, aminopenicillins and penicillinase-resistant penicillins",
 moa=["Bind penicillin-binding proteins → block transpeptidation (cross-linking) of the peptidoglycan cell wall → lysis of dividing bacteria (bactericidal)",
      "Natural penicillin G: streptococci, Treponema, Neisseria (sensitive strains)",
      "Aminopenicillins (amoxicillin, ampicillin): add some Gram-negatives; destroyed by β-lactamase — clavulanic acid protects them",
      "Cloxacillin/flucloxacillin: resist staphylococcal penicillinase → anti-staphylococcal (not MRSA)"],
 pk=["Amoxicillin is better absorbed than ampicillin and unaffected by food; cloxacillin best on an empty stomach",
     "Renal excretion (probenecid prolongs levels)"],
 uses=["Aqueous crystalline penicillin G: neurosyphilis, ocular and otic syphilis — 18–24 million U/day IV (3–4 MU every 4 h) for 10–14 days",
       "Procaine penicillin 2.4 MU IM daily + probenecid 500 mg four times daily × 10–14 days: alternative for neurosyphilis",
       "Benzathine penicillin: see exam-list post",
       "Amoxicillin (± clavulanate): impetigo/cellulitis (step-down), infected eczema, bites (co-amoxiclav), early Lyme disease in children, actinomycosis",
       "Cloxacillin/flucloxacillin: staphylococcal impetigo, furunculosis, cellulitis, SSSS (with IV forms)",
       "Erysipelas/streptococcal cellulitis: penicillin V or amoxicillin"],
 dose=["Amoxicillin 500 mg three times daily (co-amoxiclav 625 mg three times daily)",
       "Cloxacillin 500 mg four times daily, 1 h before food",
       "Children: amoxicillin 25–45 mg/kg/day; cloxacillin 50–100 mg/kg/day in divided doses"],
 ae=["Hypersensitivity: urticaria, angioedema, anaphylaxis (1–4 per 10,000 courses)",
     "Ampicillin/amoxicillin maculopapular rash in infectious mononucleosis (EBV) — up to 80–100%, not true allergy",
     "Serum-sickness-like reaction (amoxicillin, children), AGEP, SJS/TEN, DRESS (rare)",
     "Jarisch–Herxheimer reaction in syphilis; Hoigné syndrome (procaine penicillin: acute anxiety, hallucinations from procaine embolism)",
     "Diarrhoea, C. difficile colitis; cholestatic hepatitis (co-amoxiclav, flucloxacillin)"],
 ci=["Penicillin allergy (immediate type) — avoid; desensitise when penicillin is essential (syphilis in pregnancy, neurosyphilis)",
     "Amoxicillin in suspected infectious mononucleosis"],
 ix=["Probenecid raises levels; allopurinol increases ampicillin rash",
     "Methotrexate: reduced renal clearance → toxicity",
     "Warfarin: INR may rise"],
 mon=["Watch for allergy; LFT on long co-amoxiclav/flucloxacillin courses"],
 preg="Safe in pregnancy and breastfeeding (old FDA category B).",
 viva=["Neurosyphilis needs aqueous crystalline penicillin G IV — benzathine does not reach CSF",
       "Ampicillin rash in EBV infection",
       "Cloxacillin = penicillinase-resistant, for staph (not MRSA)",
       "Hoigné syndrome vs anaphylaxis vs Jarisch–Herxheimer"],
 src=f"{K} ch.1 (Penicillins); {W} ch.9 (β-lactams)"),

dict(name="Oral cephalosporins (cephalexin, cefadroxil, cefuroxime, cefixime, cefpodoxime)", group="More from Khopkar · Other antibacterials",
 cls="β-lactam antibiotics — 1st (cephalexin, cefadroxil), 2nd (cefuroxime) and 3rd generation (cefixime, cefpodoxime) oral cephalosporins",
 moa=["Inhibit cell-wall synthesis (PBP binding) → bactericidal",
      "Moving from 1st to 3rd generation: less Gram-positive (staph) activity, more Gram-negative activity and β-lactamase stability"],
 uses=["1st generation (cephalexin, cefadroxil): staphylococcal and streptococcal skin infections — impetigo, cellulitis, furunculosis, infected eczema, wound infection",
       "2nd generation (cefuroxime axetil): early Lyme disease (alternative to doxycycline), skin infections",
       "3rd generation: cefixime 400 mg single dose (NACO grey and yellow kits — gonorrhoea/cervicitis, PID); cefpodoxime for skin and soft-tissue infections",
       "Injectable 3rd generation (ceftriaxone): see exam-list post"],
 dose=["Cephalexin 500 mg four times daily (25–50 mg/kg/day in children)",
       "Cefadroxil 500 mg–1 g twice daily",
       "Cefuroxime axetil 500 mg twice daily (Lyme 14–21 days)",
       "Cefixime 400 mg single dose (gonorrhoea, as per NACO kit); 200 mg twice daily for other infections",
       "Cefpodoxime 200 mg twice daily"],
 ae=["Diarrhoea, C. difficile colitis",
     "Hypersensitivity — cross-reactivity with penicillin is low (about 1–2%), mainly with similar side chains (cephalexin/cefadroxil share amoxicillin's side chain)",
     "Serum-sickness-like reaction (classically cefaclor in children)",
     "Positive Coombs test, rarely haemolytic anaemia"],
 ci=["Previous anaphylaxis to a cephalosporin; caution in immediate penicillin allergy"],
 ix=["Probenecid raises levels; alcohol (some injectables with MTT side chain — disulfiram-like)"],
 preg="Safe in pregnancy and breastfeeding.",
 viva=["Generations and their spectrum shift",
       "Cefixime is the oral drug in NACO kits",
       "Low cross-reactivity with penicillin — related to side chains"],
 src=f"{K} ch.1 (Cephalosporins); {W} ch.9; NACO STI guidelines"),

dict(name="Co-trimoxazole (trimethoprim–sulfamethoxazole)", group="More from Khopkar · Other antibacterials",
 cls="Fixed combination of a dihydrofolate reductase inhibitor (trimethoprim) and a sulfonamide (sulfamethoxazole) in 1:5 ratio",
 moa=["Sequential blockade of bacterial folate synthesis: sulfamethoxazole inhibits dihydropteroate synthase; trimethoprim inhibits dihydrofolate reductase",
      "Together they are bactericidal and slow resistance"],
 uses=["Community MRSA skin infections (abscess, furunculosis — after drainage)",
       "Actinomycetoma (Nocardia): with dapsone or amikacin (two-step and Welsh regimens) — long courses",
       "Nocardiosis, M. marinum (limited disease), donovanosis (alternative), chancroid (older regimen)",
       "Pneumocystis pneumonia prophylaxis: HIV (CD4 under 200) and patients on high-dose steroids, rituximab, cyclophosphamide",
       "Toxoplasmosis prophylaxis, UTI, Whipple disease"],
 dose=["Double-strength tablet (160/800 mg) twice daily for skin infections",
       "Actinomycetoma: 160/800 mg twice daily (or 8–10 mg/kg/day trimethoprim component) for many months",
       "PCP prophylaxis: one double-strength tablet daily or three times weekly"],
 ae=["Skin reactions are frequent: morbilliform rash, fixed drug eruption (a classic cause), SJS/TEN (sulfonamides are among the highest-risk drugs; much higher in HIV), DRESS, photosensitivity",
     "Bone marrow suppression (folate antagonism), megaloblastic anaemia; haemolysis in G6PD deficiency",
     "Hyperkalaemia (trimethoprim blocks ENaC), raised creatinine; hepatitis; aseptic meningitis",
     "Kernicterus in newborns (sulfonamide displaces bilirubin)"],
 ci=["Sulfonamide allergy; severe liver/kidney disease; megaloblastic anaemia",
     "Late pregnancy and neonates under 6 weeks; G6PD deficiency (caution)"],
 ix=["Methotrexate: severe, sometimes fatal pancytopenia — avoid",
     "Warfarin (INR rises), phenytoin, sulfonylureas (hypoglycaemia)",
     "ACE inhibitors, spironolactone: hyperkalaemia; dapsone: more methaemoglobinaemia"],
 mon=["CBC and potassium on long courses (mycetoma); stop at first sign of rash with mucosal involvement"],
 preg="Avoid in first trimester (folate antagonist) and near term (kernicterus) unless essential (e.g. PCP prophylaxis in HIV).",
 viva=["Sequential block of folate pathway",
       "Never combine with methotrexate",
       "Common cause of FDE and SJS/TEN, especially in HIV",
       "Drug of choice backbone for actinomycetoma"],
 src=f"{K} ch.1 (Cotrimoxazole, Sulfonamides); {W} ch.9"),

dict(name="Erythromycin (oral + topical)", group="More from Khopkar · Other antibacterials",
 cls="Macrolide antibiotic (14-membered lactone ring; prototype macrolide)",
 moa=["Binds 23S rRNA of the 50S ribosomal subunit → blocks translocation → bacteriostatic (bactericidal at high concentration)",
      "Anti-inflammatory effects (reduces neutrophil chemotaxis) — used in some inflammatory dermatoses",
      "Motilin receptor agonist → GI cramps"],
 pk=["Destroyed by gastric acid — given as enteric-coated base, stearate or estolate (estolate best absorbed)",
     "Metabolised by CYP3A4 (and inhibits it strongly); poor CSF penetration"],
 uses=["Penicillin-allergic patients: streptococcal and staphylococcal skin infections, erysipelas",
       "STIs in pregnancy or penicillin/tetracycline allergy: chlamydia, chancroid, LGV, donovanosis",
       "Erythrasma, pitted keratolysis, acne in pregnancy and children under 8",
       "Bullous pemphigoid (with nicotinamide), pityriasis rosea (controversial, early use)",
       "Topical 2% gel/solution: acne (always with BPO — resistance very high), erythrasma"],
 dose=["500 mg four times daily (30–50 mg/kg/day in children)",
       "Chlamydia: 500 mg four times daily × 7 days; chancroid: 500 mg three times daily × 7 days; LGV: 500 mg four times daily × 21 days",
       "Topical 2–4% once or twice daily with BPO"],
 ae=["GI cramps, nausea, diarrhoea (motilin effect) — the main problem",
     "Cholestatic hepatitis (mainly estolate; more in pregnancy)",
     "QT prolongation, transient hearing loss with high IV doses",
     "Infantile hypertrophic pyloric stenosis when given to young infants",
     "Topical: dryness; resistant C. acnes and staphylococci"],
 ci=["Liver disease (estolate); long QT",
     "Concurrent CYP3A4 substrates with serious toxicity: simvastatin/lovastatin, pimozide, ergotamine, terfenadine/astemizole"],
 ix=["Strong CYP3A4 inhibitor: raises cyclosporine, tacrolimus, carbamazepine, warfarin, theophylline, statins, colchicine, benzodiazepines",
     "Topical erythromycin and clindamycin antagonise each other (same 50S site)"],
 preg="Base and stearate are safe in pregnancy; avoid estolate (hepatotoxicity). Note: erythromycin does not adequately treat fetal syphilis.",
 viva=["Estolate → cholestatic hepatitis",
       "CYP3A4 inhibitor — cyclosporine and statin interactions",
       "Safe acne antibiotic in pregnancy/children (oral)",
       "Topical erythromycin — high resistance; always add BPO"],
 src=f"{K} ch.1 (Macrolides — erythromycin; Table 1.6) and ch.18; {W} ch.9 and ch.41"),

dict(name="Roxithromycin", group="More from Khopkar · Other antibacterials",
 cls="Semisynthetic 14-membered macrolide",
 moa=["50S ribosomal inhibitor (like erythromycin); acid-stable"],
 pk=["Better absorbed and longer acting than erythromycin (half-life about 12 h); less CYP3A4 inhibition"],
 uses=["Skin and soft-tissue infections, impetigo, folliculitis in penicillin allergy",
       "Acne (alternative), NGU/chlamydia (older regimens)"],
 dose=["150 mg twice daily or 300 mg once daily before food; children 5–8 mg/kg/day"],
 ae=["GI upset (less than erythromycin), rash, raised LFT, QT prolongation (rare)"],
 ci=["Macrolide allergy; with ergot alkaloids"],
 ix=["Weaker CYP3A4 inhibition than erythromycin; caution with QT drugs, theophylline, warfarin"],
 preg="Limited data; erythromycin or azithromycin preferred.",
 viva=["Acid-stable erythromycin analogue with twice-daily dosing and fewer GI effects"],
 src=f"{K} ch.1 (Roxithromycin, Table 1.7); {W} ch.9"),

dict(name="Clarithromycin", group="More from Khopkar · Other antibacterials",
 cls="Semisynthetic 14-membered macrolide",
 moa=["50S ribosomal inhibitor; bactericidal against M. leprae; active against many atypical mycobacteria"],
 pk=["Acid-stable; active 14-hydroxy metabolite; potent CYP3A4 inhibitor"],
 uses=["Atypical mycobacterial infections (backbone drug): M. marinum, M. chelonae/abscessus/fortuitum, MAC, M. ulcerans (with rifampicin)",
       "Leprosy (second-line, rifampicin-resistant regimens)",
       "Skin infections in penicillin allergy, acne (alternative), H. pylori (associated urticaria)",
       "Bacillary angiomatosis"],
 dose=["250–500 mg twice daily (NTM: 500 mg twice daily for months)"],
 ae=["Taste disturbance (metallic), GI upset",
     "QT prolongation, hepatotoxicity",
     "Possible increase in long-term cardiac mortality in heart disease patients (FDA advisory)"],
 ci=["With colchicine in renal/hepatic impairment (fatal toxicity), simvastatin/lovastatin, ergot, pimozide; long QT"],
 ix=["Strong CYP3A4 inhibitor: colchicine, statins, cyclosporine, tacrolimus, carbamazepine, warfarin, rifampicin (reduces clarithromycin; rifabutin uveitis)"],
 preg="Avoid unless necessary (animal teratogenicity; old FDA category C).",
 viva=["Key drug for NTM skin infections",
       "Colchicine + clarithromycin = fatal toxicity"],
 src=f"{K} ch.1 and ch.6; {W} ch.9"),

dict(name="Clindamycin oral", merge_into="Clindamycin phosphate 1% gel", form_label="Oral form", group="More from Khopkar · Other antibacterials",
 cls="Lincosamide (oral/IV)",
 moa=["50S ribosomal inhibitor; also suppresses toxin production by staphylococci and streptococci (useful in necrotising infections)"],
 uses=["Hidradenitis suppurativa: clindamycin 300 mg + rifampicin 300 mg twice daily for 10–12 weeks",
       "Staphylococcal/streptococcal skin infections in penicillin allergy; community MRSA (if sensitive)",
       "Necrotising fasciitis and toxic shock syndrome (with penicillin — antitoxin effect); anaerobic infections; BV (oral/vaginal)"],
 dose=["150–450 mg four times daily (adults); children 10–25 mg/kg/day"],
 ae=["Diarrhoea and C. difficile pseudomembranous colitis (classic association)",
     "Rash, metallic taste, hepatitis (rare)"],
 ci=["History of antibiotic-associated colitis"],
 ix=["Neuromuscular blockers (potentiated); erythromycin (antagonism)"],
 preg="Acceptable in pregnancy.",
 viva=["Clindamycin + rifampicin for hidradenitis",
       "Antitoxin effect in toxic shock",
       "Classic cause of C. difficile colitis"],
 src=f"{K} ch.1; {W} ch.9 and ch.41"),

dict(name="Metronidazole gel/cream (0.75–1%)", merge_into="Metronidazole", form_label="Topical form", group="More from Khopkar · Other antibacterials",
 cls="Topical nitroimidazole",
 moa=["Anti-inflammatory (reduces reactive oxygen species from neutrophils) and antimicrobial — benefit in rosacea is mainly anti-inflammatory"],
 uses=["Papulopustular rosacea (first-line topical), perioral dermatitis",
       "Malodorous fungating wounds and ulcers (reduces anaerobic odour)",
       "Vaginal gel 0.75%: bacterial vaginosis"],
 dose=["0.75% twice daily or 1% once daily; maintenance after oral therapy in rosacea"],
 ae=["Mild irritation, dryness; no disulfiram reaction (negligible absorption)"],
 ci=["Hypersensitivity"],
 preg="Safe.",
 viva=["Topical metronidazole for rosacea; ivermectin cream is more effective"],
 src=f"{K} ch.18; {W} ch.41 and ch.57"),

dict(name="Fluoroquinolones (ciprofloxacin, ofloxacin, levofloxacin, moxifloxacin, sparfloxacin, norfloxacin)", group="More from Khopkar · Other antibacterials",
 cls="Synthetic fluorinated quinolone antibiotics",
 moa=["Inhibit bacterial DNA gyrase (topoisomerase II — main target in Gram-negatives) and topoisomerase IV (Gram-positives) → DNA breaks → bactericidal",
      "Concentration-dependent killing"],
 pk=["Well absorbed but chelated by antacids, iron, calcium, zinc, dairy",
     "Good tissue and intracellular penetration; ciprofloxacin/levofloxacin/ofloxacin renally excreted; moxifloxacin hepatic"],
 uses=["Gram-negative skin and soft-tissue infections (Pseudomonas — ciprofloxacin), diabetic foot, osteomyelitis",
       "Chancroid (ciprofloxacin 500 mg twice daily × 3 days), donovanosis (ciprofloxacin 750 mg twice daily ≥3 weeks)",
       "Gonorrhoea — no longer recommended (high resistance)",
       "Leprosy (ofloxacin, moxifloxacin — second-line), TB (MDR regimens), rapid-growing NTM (sensitivity-guided)",
       "Typhoid, anthrax, rickettsial infections (alternative)"],
 dose=["Ciprofloxacin 500–750 mg twice daily; ofloxacin 200–400 mg twice daily; levofloxacin 500–750 mg once daily; moxifloxacin 400 mg once daily"],
 ae=["Tendinopathy and tendon rupture (Achilles; risk higher with age >60, steroids, renal transplant) — FDA boxed warning, also peripheral neuropathy, CNS effects, myasthenia exacerbation",
     "QT prolongation, dysglycaemia, aortic aneurysm/dissection",
     "Phototoxicity (sparfloxacin highest — withdrawn in many countries; ofloxacin least); photo-onycholysis",
     "Fixed drug eruption, SJS/TEN, vasculitis",
     "Arthropathy in growing animals → avoided in children and pregnancy (relative)",
     "C. difficile diarrhoea, seizures (especially with NSAIDs)"],
 ci=["Children and adolescents (relative), pregnancy and breastfeeding (relative)",
     "History of tendon disorder with fluoroquinolones; myasthenia gravis; long QT"],
 ix=["Antacids/iron/calcium/zinc: separate by 2–6 h",
     "Ciprofloxacin inhibits CYP1A2 → theophylline, caffeine, tizanidine toxicity",
     "Warfarin (INR rises), NSAIDs (seizures), steroids (tendon rupture), QT drugs"],
 preg="Avoid (use only when no alternative).",
 viva=["DNA gyrase/topoisomerase IV",
       "Tendon rupture — boxed warning; worse with steroids",
       "Sparfloxacin most phototoxic, ofloxacin least",
       "Ciprofloxacin–theophylline interaction"],
 src=f"{K} ch.1 (Fluoroquinolones, Table 1.8); {W} ch.9"),

dict(name="Aminoglycosides: gentamicin (systemic + topical) & amikacin", group="More from Khopkar · Other antibacterials",
 cls="Aminoglycoside antibiotics",
 moa=["Bind 30S ribosomal subunit → mRNA misreading → bactericidal (concentration-dependent; oxygen-dependent uptake, so inactive against anaerobes)",
      "Amikacin is resistant to most aminoglycoside-inactivating enzymes — the most broad-spectrum"],
 pk=["Not absorbed orally; IV/IM; renal excretion — dose by renal function; once-daily dosing exploits post-antibiotic effect"],
 uses=["Gentamicin IV/IM: serious Gram-negative infections (Pseudomonas), with β-lactams in endocarditis; donovanosis (adjunct); plague, tularaemia",
       "Gentamicin topical 0.1% cream/ointment: impetigo, infected wounds, Pseudomonas-infected toe webs/nails (resistance and sensitisation limit use)",
       "Amikacin: actinomycetoma (Welsh regimen — amikacin 15 mg/kg/day in cycles with co-trimoxazole), rapid-growing NTM, MDR-TB (older regimens), Nocardia"],
 dose=["Gentamicin 5–7 mg/kg IV once daily (adjust to levels)",
       "Amikacin 15 mg/kg/day (e.g. 500 mg twice daily) IM/IV; Welsh regimen: 3-week cycles with 2-week gaps, up to 3–4 cycles, with co-trimoxazole",
       "Topical gentamicin 3–4 times daily, short courses"],
 ae=["Nephrotoxicity (acute tubular necrosis, reversible)",
     "Ototoxicity — cochlear (amikacin) and vestibular (gentamicin, streptomycin); often irreversible; mitochondrial gene variant increases risk",
     "Neuromuscular blockade (avoid in myasthenia)",
     "Topical: contact allergy (cross-reacts with neomycin/framycetin)"],
 ci=["Pregnancy (fetal ototoxicity); myasthenia gravis; pre-existing hearing loss",
     "Topical on large raw areas or perforated tympanic membrane"],
 ix=["Loop diuretics, vancomycin, amphotericin B, cisplatin, cyclosporine: additive oto/nephrotoxicity",
     "Neuromuscular blockers potentiated"],
 mon=["Renal function, trough levels, audiometry (baseline and during long amikacin courses — mycetoma)"],
 preg="Avoid (old FDA category D).",
 viva=["Welsh regimen for actinomycetoma — amikacin + co-trimoxazole",
       "Ototoxicity: amikacin cochlear, gentamicin/streptomycin vestibular",
       "Topical gentamicin sensitises and cross-reacts with neomycin"],
 src=f"{K} ch.1 (Aminoglycosides, Amikacin) and ch.18 (topical gentamicin); {W} ch.9 and ch.41"),

dict(name="Spectinomycin", group="More from Khopkar · Other antibacterials",
 cls="Aminocyclitol antibiotic (related to aminoglycosides)",
 moa=["Binds 30S ribosomal subunit → inhibits protein synthesis (bacteriostatic)"],
 uses=["Gonorrhoea (urogenital/anorectal) in patients allergic to cephalosporins or in pregnancy — not effective for pharyngeal gonorrhoea",
       "Disseminated gonococcal infection (older regimens)"],
 dose=["2 g IM single dose; DGI 2 g IM daily (older regimens)"],
 ae=["Injection-site pain, urticaria, fever, nausea (uncommon)"],
 ci=["Hypersensitivity"],
 preg="Considered safe (old FDA category B).",
 viva=["Gonorrhoea alternative — poor pharyngeal activity; largely unavailable now"],
 src=f"{K} ch.1 (Spectinomycin)"),

dict(name="Vancomycin", group="More from Khopkar · Other antibacterials",
 cls="Glycopeptide antibiotic",
 moa=["Binds D-alanyl-D-alanine terminus of cell-wall precursors → blocks peptidoglycan polymerisation → bactericidal (Gram-positives only)"],
 pk=["Not absorbed orally (oral form only for C. difficile colitis); IV; renal excretion"],
 uses=["Serious MRSA infections: complicated skin and soft-tissue infection, bacteraemia, osteomyelitis",
       "Severe staphylococcal/streptococcal infections in β-lactam allergy",
       "Oral vancomycin: C. difficile colitis"],
 dose=["15–20 mg/kg IV every 8–12 h, infused slowly (at least 60 min); dosing guided by AUC/trough levels"],
 ae=["Vancomycin infusion reaction ('red man' / flushing syndrome): flushing, itch, hypotension of upper body from direct histamine release with fast infusion — slow the infusion, give antihistamine (not true allergy)",
     "Drug-induced linear IgA bullous dermatosis — vancomycin is the commonest cause",
     "DRESS (HLA-A*32:01), SJS/TEN",
     "Nephrotoxicity (especially with piperacillin–tazobactam, aminoglycosides), ototoxicity, neutropenia"],
 ci=["Hypersensitivity"],
 ix=["Aminoglycosides, loop diuretics, cyclosporine: additive toxicity"],
 mon=["Serum levels (AUC/trough), renal function, CBC on long courses"],
 preg="Use if needed (monitor levels).",
 viva=["Red man syndrome = infusion-rate reaction, not allergy",
       "Commonest cause of drug-induced linear IgA disease",
       "DRESS linked to HLA-A*32:01"],
 src=f"{K} ch.1 (Vancomycin); {W} ch.9 and ch.67 (Cutaneous drug reactions)"),

# ---------------- ANTIFUNGALS ----------------
dict(name="Amphotericin B", group="More from Khopkar · Other antifungals",
 cls="Polyene macrolide antifungal (from Streptomyces nodosus); also antileishmanial",
 moa=["Binds ergosterol in fungal (and Leishmania) membranes → forms pores → leakage of ions → cell death (fungicidal)",
      "Some binding to human cholesterol → toxicity",
      "Lipid formulations (liposomal, lipid complex) deliver drug to tissues with much less nephrotoxicity"],
 pk=["Not absorbed orally; IV only; long tissue half-life; poor CSF penetration but effective in cryptococcal meningitis"],
 uses=["Life-threatening deep fungal infections: mucormycosis (drug of choice, liposomal), cryptococcal meningitis (with flucytosine), disseminated histoplasmosis, blastomycosis, coccidioidomycosis, disseminated sporotrichosis, invasive candidiasis/aspergillosis, penicilliosis (talaromycosis)",
       "Leishmaniasis: visceral (kala-azar — India's programme uses single-dose liposomal amphotericin B 10 mg/kg), post-kala-azar dermal leishmaniasis (alternative to miltefosine), mucosal and refractory cutaneous leishmaniasis"],
 dose=["Conventional (deoxycholate): 0.5–1 mg/kg/day IV in 5% dextrose over 4–6 h (test dose 1 mg historically)",
       "Liposomal: 3–5 mg/kg/day (mucormycosis 5–10 mg/kg/day)",
       "Kala-azar (India): liposomal 10 mg/kg single infusion"],
 ae=["Infusion reactions: fever, chills, rigors, hypotension (premedicate with paracetamol, antihistamine, hydrocortisone)",
     "Nephrotoxicity (dose-limiting with conventional form) — saline loading helps",
     "Hypokalaemia, hypomagnesaemia, renal tubular acidosis",
     "Normocytic anaemia (reduced erythropoietin), thrombophlebitis"],
 ci=["Hypersensitivity; caution with renal impairment (prefer liposomal)"],
 ix=["Nephrotoxic drugs (aminoglycosides, cyclosporine, vancomycin); corticosteroids and diuretics worsen hypokalaemia (digoxin toxicity)"],
 mon=["Daily renal function, K⁺ and Mg²⁺ initially; CBC; LFT"],
 preg="Drug of choice for serious fungal infections in pregnancy.",
 viva=["Binds ergosterol → pores",
       "Liposomal form for mucormycosis and single-dose kala-azar",
       "Nephrotoxicity and hypokalaemia"],
 src=f"{K} ch.2 and ch.5 (antileishmanial); {W} ch.10 and ch.12"),

dict(name="Flucytosine (5-FC)", group="More from Khopkar · Other antifungals",
 cls="Fluorinated pyrimidine antifungal",
 moa=["Taken up by fungal cytosine permease and converted by cytosine deaminase (absent in human cells) to 5-fluorouracil",
      "5-FU inhibits thymidylate synthase and is incorporated into fungal RNA",
      "Rapid resistance when used alone — always combined"],
 pk=["Well absorbed; excellent CSF penetration; renal excretion (adjust dose)"],
 uses=["Cryptococcal meningitis (induction with amphotericin B or fluconazole)",
       "Chromoblastomycosis (with itraconazole/amphotericin B)",
       "Severe candidiasis (with amphotericin B)"],
 dose=["100 mg/kg/day orally in 4 divided doses (adjust to renal function and serum levels)"],
 ae=["Bone marrow suppression (leucopenia, thrombocytopenia), especially with renal failure",
     "Hepatotoxicity, GI upset (enterocolitis)"],
 ci=["Pregnancy; severe marrow suppression"],
 ix=["Amphotericin B reduces its renal clearance (synergy but toxicity); cytosine arabinoside antagonises"],
 mon=["CBC, LFT, renal function; drug levels where available"],
 preg="Contraindicated (teratogenic in animals; converted to 5-FU).",
 viva=["Prodrug converted to 5-FU only in fungi (cytosine deaminase)",
       "Never used alone — resistance",
       "Chromoblastomycosis and cryptococcal meningitis"],
 src=f"{K} ch.2; {W} ch.10"),

dict(name="Ketoconazole oral", merge_into="Ketoconazole (cream, lotion, shampoo)", form_label="Oral form", group="More from Khopkar · Other antifungals",
 cls="Imidazole antifungal (oral)",
 moa=["Inhibits fungal 14-α-demethylase; also inhibits human steroid-synthesising CYP enzymes (17,20-lyase, 11β-hydroxylase) → lowers cortisol and testosterone"],
 pk=["Needs gastric acid for absorption; potent CYP3A4 inhibitor"],
 uses=["Formerly used for dermatophytosis, PV, candidiasis, seborrhoeic dermatitis",
       "No longer recommended for skin and nail infections — withdrawn/restricted in Europe and the USA (2013) because of serious liver injury and adrenal suppression",
       "Still used by endocrinologists for Cushing syndrome (anti-steroidogenic)"],
 dose=["200–400 mg/day (historic dermatology dose)"],
 ae=["Serious hepatotoxicity (including fulminant hepatitis, deaths)",
     "Adrenal insufficiency; gynaecomastia, reduced libido, oligospermia (anti-androgenic)",
     "QT prolongation"],
 ci=["Liver disease; with CYP3A4 substrates (simvastatin, cisapride, midazolam, ergot)"],
 ix=["Strong CYP3A4 inhibitor (cyclosporine, statins, warfarin); antacids/PPIs reduce absorption"],
 preg="Avoid.",
 viva=["Oral ketoconazole is obsolete for skin infections — hepatotoxicity and adrenal suppression",
       "Topical ketoconazole remains safe and useful"],
 src=f"{K} ch.2; {W} ch.10"),

dict(name="Terbinafine 1% cream", merge_into="Terbinafine", form_label="Topical form", group="More from Khopkar · Other antifungals",
 cls="Allylamine (topical)",
 moa=["Squalene epoxidase inhibitor — fungicidal against dermatophytes; persists in stratum corneum"],
 uses=["Tinea corporis, cruris, pedis (including interdigital), pityriasis versicolor (solution/spray)",
       "Less effective for cutaneous candidiasis than azoles"],
 dose=["Once or twice daily for 1–2 weeks (tinea pedis 1 week interdigital; continue 1–2 weeks after clearing in recurrent disease)"],
 ae=["Burning, itching, irritation; rare contact dermatitis"],
 ci=["Hypersensitivity"],
 preg="Safe (minimal absorption).",
 viva=["Fungicidal topical — shorter courses than azoles for dermatophytes"],
 src=f"{K} ch.19; {W} ch.42"),

# ---------------- ANTIVIRALS ----------------
dict(name="Acyclovir 5% cream", merge_into="Acyclovir", form_label="Topical form", group="More from Khopkar · Antivirals & ART",
 cls="Topical guanosine analogue",
 moa=["Same as oral acyclovir; limited penetration through intact skin"],
 uses=["Recurrent herpes labialis (start at prodrome) — modest benefit (shortens episode by about half a day)",
       "Not useful for genital herpes, zoster or primary infections — use oral drugs"],
 dose=["5 times daily for 4–5 days"],
 ae=["Burning, stinging, contact dermatitis (propylene glycol)"],
 ci=["Hypersensitivity; not for eyes/mucosa (ophthalmic ointment is separate)"],
 preg="Safe.",
 viva=["Topical acyclovir has minimal benefit — oral therapy is preferred"],
 src=f"{K} ch.20 (Topical antivirals); {W} ch.43"),

dict(name="Penciclovir 1% cream", group="More from Khopkar · Antivirals & ART",
 cls="Topical guanosine analogue (active metabolite of famciclovir)",
 moa=["Phosphorylated by viral thymidine kinase → inhibits viral DNA polymerase; long intracellular half-life"],
 uses=["Recurrent herpes labialis in adults and children over 12 (slightly better than topical acyclovir)"],
 dose=["Every 2 h while awake for 4 days, starting at the first sign"],
 ae=["Local irritation, numbness"],
 ci=["Hypersensitivity; mucous membranes"],
 preg="Minimal absorption — acceptable.",
 viva=["Topical form of famciclovir's active drug; frequent application needed"],
 src=f"{K} ch.20 (Penciclovir); {W} ch.43"),

dict(name="Ganciclovir & valganciclovir", group="More from Khopkar · Antivirals & ART",
 cls="Guanosine analogue (ganciclovir) and its oral L-valyl ester prodrug (valganciclovir)",
 moa=["In CMV-infected cells, phosphorylated by the viral UL97 kinase, then by host kinases → triphosphate inhibits viral DNA polymerase",
      "Much more active against CMV than acyclovir"],
 uses=["CMV infections in immunocompromised patients (retinitis, colitis, pneumonitis, CMV cutaneous ulcers in HIV/transplant)",
       "Prevention of CMV in transplant recipients",
       "HHV-6/CMV reactivation in severe DRESS (selected cases)"],
 dose=["Ganciclovir 5 mg/kg IV every 12 h (induction), then 5 mg/kg daily",
       "Valganciclovir 900 mg twice daily (induction), then 900 mg daily; adjust for renal function"],
 ae=["Bone marrow suppression (neutropenia, thrombocytopenia) — dose-limiting",
     "Renal impairment, CNS effects, fever, rash",
     "Carcinogenic, teratogenic and aspermatogenic in animals"],
 ci=["Severe neutropenia (<500/mm³) or thrombocytopenia; pregnancy"],
 ix=["Zidovudine, MMF, other marrow suppressants: more myelosuppression; imipenem (seizures)"],
 mon=["CBC 2–3 times a week during induction; renal function"],
 preg="Avoid (teratogenic); contraception during and after treatment (men 90 days).",
 viva=["Activated by CMV UL97 kinase",
       "Neutropenia is dose-limiting",
       "Valganciclovir is the oral prodrug"],
 src=f"{K} ch.3; {W} ch.11"),

dict(name="Foscarnet", group="More from Khopkar · Antivirals & ART",
 cls="Pyrophosphate (phosphonoformic acid) analogue",
 moa=["Directly blocks the pyrophosphate-binding site of viral DNA polymerase — does not need activation by viral thymidine kinase",
      "So it works against acyclovir-resistant (TK-deficient) HSV and VZV and ganciclovir-resistant CMV"],
 uses=["Acyclovir-resistant mucocutaneous HSV and VZV in immunocompromised patients (HIV, transplant)",
       "Ganciclovir-resistant CMV"],
 dose=["40 mg/kg IV every 8 h (or 60 mg/kg every 12 h) for HSV/VZV; with pre-hydration; adjust to creatinine clearance"],
 ae=["Nephrotoxicity (acute tubular necrosis, nephrogenic diabetes insipidus)",
     "Electrolyte disturbances: hypocalcaemia (ionised — chelation), hypomagnesaemia, hypokalaemia, hypo/hyperphosphataemia → paraesthesia, seizures, arrhythmia",
     "Painful genital (penile/vulval) ulcers from high drug concentration in urine — good hygiene after voiding",
     "Anaemia, nausea"],
 ci=["Severe renal impairment (relative); hypersensitivity"],
 ix=["Other nephrotoxic drugs; pentamidine IV (severe hypocalcaemia); QT drugs"],
 mon=["Creatinine, Ca²⁺ (ionised), Mg²⁺, K⁺, PO₄ 2–3 times weekly; ECG"],
 preg="Avoid unless life-threatening.",
 viva=["TK-independent — used for acyclovir-resistant HSV",
       "Genital ulceration from urinary excretion",
       "Electrolyte chaos — especially low ionised calcium"],
 src=f"{K} ch.3 (Foscarnet); {W} ch.11"),

dict(name="Cidofovir (systemic + topical/intralesional)", group="More from Khopkar · Antivirals & ART",
 cls="Acyclic nucleoside phosphonate (cytosine nucleotide analogue)",
 moa=["Already carries a phosphonate group, so needs only host kinases (no viral TK) → cidofovir diphosphate inhibits viral DNA polymerase",
      "Broad DNA virus activity: CMV, HSV (including acyclovir-resistant), VZV, HPV, poxviruses (molluscum, orf), adenovirus",
      "Very long intracellular half-life → weekly/fortnightly dosing"],
 uses=["IV: CMV retinitis in AIDS; acyclovir- and foscarnet-resistant HSV",
       "Topical 1–3% (compounded gel/cream): acyclovir-resistant HSV ulcers, recalcitrant warts (anogenital, periungual) and molluscum in immunocompromised patients (HIV, transplant), recurrent respiratory papillomatosis",
       "Intralesional: recalcitrant warts (case series)"],
 dose=["IV: 5 mg/kg once weekly × 2, then every 2 weeks — always with probenecid (2 g 3 h before, 1 g at 2 and 8 h after) and 1 L normal saline",
       "Topical 1–3% once daily, 5 days a week, for several cycles"],
 ae=["IV: dose-limiting nephrotoxicity (proximal tubule — Fanconi syndrome), neutropenia, ocular hypotony/uveitis, metabolic acidosis",
     "Topical: local erosion, ulceration, burning (inflammation is common); absorption from large areas can cause renal toxicity"],
 ci=["Renal impairment (creatinine >1.5 mg/dL or proteinuria), concurrent nephrotoxic drugs, probenecid/sulfa allergy (for IV)",
     "Pregnancy"],
 ix=["Nephrotoxic drugs (aminoglycosides, amphotericin B, foscarnet, NSAIDs, tenofovir)"],
 mon=["Creatinine and urine protein before each IV dose; CBC; eye exams"],
 preg="Avoid (carcinogenic/teratogenic in animals).",
 viva=["Nucleotide analogue — TK-independent",
       "Topical cidofovir for warts/molluscum in HIV and acyclovir-resistant HSV",
       "IV always with probenecid and saline (nephrotoxicity)"],
 src=f"{K} ch.3 and ch.20 (Cidofovir); {W} ch.11 and ch.43"),

dict(name="Interferons (systemic, intralesional, topical)", group="More from Khopkar · Antivirals & ART",
 cls="Cytokine immunomodulators — IFN-α (2a, 2b, pegylated), IFN-β, IFN-γ (1b); recombinant proteins",
 moa=["Bind interferon receptors → JAK-STAT signalling → hundreds of interferon-stimulated genes",
      "Antiviral: inhibit viral replication (2',5'-oligoadenylate synthetase, protein kinase R)",
      "Antiproliferative and immunomodulatory: activate NK cells, cytotoxic T cells and macrophages, increase MHC expression; IFN-γ activates macrophage killing"],
 uses=["Intralesional IFN-α2b: condylomata acuminata (refractory), keloids (after excision), BCC and SCC (selected), keratoacanthoma, common warts",
       "Systemic IFN-α: cutaneous T-cell lymphoma (mycosis fungoides, Sézary — often with PUVA/retinoids), Kaposi sarcoma, melanoma (adjuvant — historical), Behçet disease, chronic hepatitis B/C (historical), life-threatening infantile haemangioma (historical — spastic diplegia risk)",
       "IFN-γ-1b: chronic granulomatous disease (reduces infections — approved), severe atopic dermatitis (limited), osteopetrosis",
       "Topical IFN gel/cream: genital warts, herpes (limited)"],
 dose=["Intralesional IFN-α2b for genital warts: 1 million IU into each wart (up to 5 warts) three times a week for 3 weeks",
       "Systemic IFN-α for CTCL: 3–9 million IU SC three times weekly",
       "IFN-γ-1b (CGD): 50 µg/m² SC three times weekly"],
 ae=["Flu-like syndrome (fever, chills, myalgia, headache) — premedicate with paracetamol; tachyphylaxis over weeks",
     "Fatigue, depression and suicidal ideation, cognitive changes",
     "Cytopenias, raised LFT, thyroid dysfunction (hypo/hyper), autoimmunity",
     "Skin: injection-site reactions/necrosis, alopecia, induction or flare of psoriasis, sarcoidosis, lichen planus, vitiligo, lupus"],
 ci=["Severe depression or suicidal history; autoimmune hepatitis; decompensated liver disease; uncontrolled thyroid disease; pregnancy (relative)"],
 ix=["Theophylline levels rise; additive marrow suppression with zidovudine and other myelosuppressives"],
 mon=["CBC, LFT, TSH, mood assessment during systemic use"],
 preg="Avoid (abortifacient in animals at high doses).",
 viva=["IL IFN-α2b for genital warts — 1 MIU per wart thrice weekly × 3 weeks",
       "IFN-γ for chronic granulomatous disease",
       "IFN therapy can induce psoriasis and sarcoidosis",
       "Flu-like illness and depression are the key side effects"],
 src=f"{K} ch.3, ch.13 (Immunobiologicals — interferons) and ch.20 (topical/intralesional IFN); {W} ch.43 and ch.37"),

dict(name="Tenofovir & emtricitabine (NRTIs)", group="More from Khopkar · Antivirals & ART",
 cls="Tenofovir: nucleotide reverse transcriptase inhibitor (TDF / TAF); emtricitabine: cytidine NRTI (like lamivudine)",
 moa=["Tenofovir (adenosine nucleotide analogue) needs only two phosphorylation steps → tenofovir diphosphate terminates HIV DNA chains; also active against hepatitis B",
      "Emtricitabine (FTC) is a fluorinated lamivudine analogue — interchangeable with lamivudine in regimens (never together)"],
 pk=["TDF (disoproxil fumarate) gives high plasma tenofovir; TAF (alafenamide) concentrates inside cells → lower plasma levels, less kidney and bone toxicity",
     "Renal excretion"],
 uses=["Backbone of preferred first-line ART in India: TLD = tenofovir 300 mg + lamivudine 300 mg + dolutegravir 50 mg once daily",
       "Post-exposure prophylaxis (TLD for 28 days)",
       "Pre-exposure prophylaxis (PrEP): TDF + FTC (or TDF + 3TC) daily for people at high risk",
       "Chronic hepatitis B (TDF/TAF), including HIV–HBV co-infection"],
 dose=["TDF 300 mg once daily (in FDC); TAF 25 mg; emtricitabine 200 mg once daily"],
 ae=["TDF: nephrotoxicity (proximal tubulopathy — Fanconi syndrome, falling GFR), reduced bone mineral density",
     "GI upset, headache; lactic acidosis (class, rare)",
     "Hepatitis B flare on stopping",
     "Emtricitabine: palmoplantar hyperpigmentation (especially in dark skin)"],
 ci=["TDF: creatinine clearance below 50 mL/min (avoid/adjust) — use abacavir or TAF"],
 ix=["Other nephrotoxic drugs (aminoglycosides, amphotericin B, cidofovir, high-dose NSAIDs)",
     "Didanosine levels rise (avoid)"],
 mon=["Creatinine/eGFR, urine dipstick (protein, glucose) at baseline and periodically; HBsAg before starting"],
 preg="TDF-based TLD is the recommended regimen in pregnancy and breastfeeding.",
 viva=["TLD = preferred first-line in India",
       "TDF → kidney and bone; TAF is safer",
       "Emtricitabine → palmoplantar hyperpigmentation",
       "Also treats hepatitis B — stopping can cause a flare"],
 src=f"{K} ch.4 (Tenofovir, Emtricitabine); {W} ch.11; current NACO ART guidelines"),

dict(name="Efavirenz", group="More from Khopkar · Antivirals & ART",
 cls="Non-nucleoside reverse transcriptase inhibitor (NNRTI)",
 moa=["Non-competitive inhibitor binding the allosteric pocket of HIV-1 reverse transcriptase; inactive against HIV-2"],
 pk=["Long half-life (40–55 h); take at bedtime on an empty stomach (food raises levels and CNS effects); CYP2B6 metabolism (slow-metaboliser genotype → high levels); CYP3A4 inducer"],
 uses=["Formerly the preferred NNRTI in first-line ART (TLE — tenofovir + lamivudine + efavirenz); now alternative to dolutegravir (TLD)",
       "Women who cannot take dolutegravir, or with rifampicin-based TB treatment"],
 dose=["600 mg once daily at bedtime (400 mg in some regimens)"],
 ae=["CNS: vivid dreams, insomnia, dizziness, poor concentration, depression, psychosis — usually settle in 2–4 weeks",
     "Rash in about 15–25% (usually mild, in first 2 weeks; SJS rare) — less severe than nevirapine",
     "Hyperlipidaemia, gynaecomastia, raised LFT, false-positive cannabinoid tests"],
 ci=["Significant psychiatric illness (relative); hypersensitivity"],
 ix=["CYP3A4 inducer: lowers levels of voriconazole (avoid standard doses), itraconazole, protease inhibitors, oral contraceptives (use additional method), methadone, artemether-lumefantrine",
     "Rifampicin: can be used together (dose unchanged in most guidelines)"],
 mon=["LFT, lipids; mood and sleep"],
 preg="Earlier concern about neural tube defects is not confirmed; can be used, though dolutegravir regimens are preferred.",
 viva=["Bedtime dosing because of CNS effects",
       "Rash milder and less frequent than nevirapine",
       "Gynaecomastia and dyslipidaemia"],
 src=f"{K} ch.4 (Efavirenz); {W} ch.11 and ch.66; current NACO ART guidelines"),

dict(name="Stavudine & didanosine (older NRTIs)", group="More from Khopkar · Antivirals & ART",
 cls="Nucleoside reverse transcriptase inhibitors — stavudine (d4T, thymidine analogue) and didanosine (ddI, adenosine analogue)",
 moa=["Phosphorylated to triphosphates that terminate HIV DNA chains (mitochondrial DNA polymerase-γ inhibition explains toxicity)"],
 uses=["Historical: stavudine-based first-line regimens (D4T/3TC/NVP, D4T/3TC/EFV) were widely used in India; phased out by WHO/NACO because of toxicity",
       "Important for exams because of their adverse effects"],
 dose=["Stavudine 30 mg twice daily (historic); didanosine 400 mg once daily on an empty stomach (historic)"],
 ae=["Stavudine: lipoatrophy (facial and limb fat loss — the classic cause), painful peripheral neuropathy, lactic acidosis with hepatic steatosis, pancreatitis",
     "Didanosine: pancreatitis (can be fatal), peripheral neuropathy, lactic acidosis, non-cirrhotic portal hypertension",
     "Stavudine + didanosine together: fatal lactic acidosis in pregnancy — never combined"],
 ci=["Never combine stavudine with zidovudine (antagonism) or with didanosine (toxicity)"],
 ix=["Hydroxyurea, ribavirin increase didanosine toxicity; tenofovir raises didanosine levels"],
 preg="Not used now.",
 viva=["Stavudine → lipoatrophy (facial wasting) and neuropathy — reason for its withdrawal",
       "Mitochondrial toxicity of 'd-drugs' (d4T, ddI, ddC)"],
 src=f"{K} ch.4 (Stavudine, Didanosine; D4T/3TC/NVP regimens); {W} ch.11"),

dict(name="Other protease inhibitors (lopinavir, atazanavir, indinavir, nelfinavir, saquinavir)", group="More from Khopkar · Antivirals & ART",
 cls="HIV protease inhibitors (PIs), usually boosted with ritonavir",
 moa=["Block HIV protease → gag-pol polyproteins not cleaved → immature non-infectious virions"],
 pk=["CYP3A4 substrates; ritonavir boosting raises levels (see ritonavir post)"],
 uses=["Second-line ART in India: lopinavir/ritonavir (LPV/r) or atazanavir/ritonavir (ATV/r) with 2 NRTIs (and dolutegravir in some regimens)",
       "Children: LPV/r formulations (older guidance)",
       "Indinavir, nelfinavir, saquinavir: historical, now rarely used"],
 dose=["LPV/r 400/100 mg twice daily; ATV/r 300/100 mg once daily with food"],
 ae=["Class: lipodystrophy (central fat accumulation, buffalo hump), dyslipidaemia, insulin resistance, GI upset",
     "Atazanavir: unconjugated hyperbilirubinaemia (jaundice, yellow eyes — benign, UGT1A1 inhibition), nephrolithiasis",
     "Indinavir: retinoid-like effects — paronychia, ingrown toenails, pyogenic granulomas, xerosis, cheilitis, alopecia; nephrolithiasis (drink plenty)",
     "Lopinavir: diarrhoea, PR/QT prolongation; nelfinavir: diarrhoea"],
 ci=["With rifampicin (use rifabutin), simvastatin/lovastatin, ergot, oral midazolam, pimozide; PPIs with atazanavir"],
 ix=["As for ritonavir: inhaled/injected corticosteroids → Cushing syndrome; colchicine, cyclosporine, azoles"],
 mon=["Lipids, glucose, LFT, bilirubin (atazanavir), renal function"],
 preg="LPV/r and ATV/r can be used in pregnancy.",
 viva=["Indinavir → retinoid-like nail fold changes and pyogenic granuloma",
       "Atazanavir → benign jaundice",
       "PI lipodystrophy"],
 src=f"{K} ch.4 (Protease inhibitors); {W} ch.11 and ch.67; current NACO ART guidelines"),

dict(name="Enfuvirtide", group="More from Khopkar · Antivirals & ART",
 cls="HIV fusion inhibitor (36-amino-acid synthetic peptide)",
 moa=["Binds the HR1 region of HIV gp41 → prevents the conformational change needed for fusion of virus and cell membranes → virus cannot enter CD4 cells"],
 uses=["Salvage therapy in heavily treatment-experienced patients with multidrug-resistant HIV (rarely used now)"],
 dose=["90 mg subcutaneously twice daily"],
 ae=["Injection-site reactions in almost all patients: painful erythematous nodules, induration, cysts (dermatology viva point)",
     "Increased bacterial pneumonia; hypersensitivity (rare)"],
 ci=["Hypersensitivity"],
 preg="Limited data.",
 viva=["The only injectable fusion inhibitor — injection-site nodules in ~98%"],
 src=f"{K} ch.4 (Enfuvirtide); {W} ch.11"),

dict(name="HIV post-exposure prophylaxis (PEP) & prevention of parent-to-child transmission (PPTCT)", group="More from Khopkar · Antivirals & ART",
 cls="Antiretroviral prophylaxis regimens (current NACO guidance)",
 moa=["ART given soon after exposure prevents establishment of infection in local dendritic cells and lymph nodes",
      "In pregnancy, maternal viral suppression plus infant prophylaxis prevents transmission"],
 uses=["Occupational PEP (needle-stick in dermatology procedures, splash on mucosa) and non-occupational PEP (sexual exposure, sexual assault)",
       "Risk assessment: exposure type (percutaneous, mucous membrane, broken skin) and source status",
       "PPTCT: all HIV-positive pregnant and breastfeeding women start lifelong ART irrespective of CD4 count"],
 dose=["PEP: start as early as possible (ideally within 2 h, not beyond 72 h); preferred regimen TLD (tenofovir + lamivudine + dolutegravir) once daily for 28 days",
       "Baseline HIV test of exposed person; follow-up HIV tests at 6 weeks, 3 months (and 6 months as per programme)",
       "Immediate care: wash wound with soap and water, do not squeeze or use bleach; flush mucous membranes with water",
       "PPTCT: mother on TLD lifelong; infant prophylaxis with nevirapine syrup for 6 weeks (low risk), or zidovudine + nevirapine (dual prophylaxis) for 12 weeks if high risk (mother not virally suppressed/late diagnosis), with early infant diagnosis (DNA-PCR at 6 weeks)",
       "Hepatitis B: check vaccination status after needle-stick; give vaccine ± HBIG"],
 ae=["See component drugs; PEP side effects are usually mild with TLD"],
 ci=["PEP not indicated if the exposed person is already HIV-positive or exposure is beyond 72 h"],
 mon=["HIV test at baseline and follow-up; LFT/renal function if indicated; counsel safe sex/blood donation avoidance until follow-up negative"],
 preg="TLD is used in pregnancy for PEP and PPTCT.",
 viva=["PEP within 72 h (ideally 2 h) for 28 days — TLD",
       "Infant prophylaxis: NVP 6 weeks or AZT+NVP 12 weeks (high risk)",
       "Lifelong ART for all pregnant women with HIV"],
 src="Current NACO PEP and PPTCT guidance; " + f"{K} ch.4 (Postexposure prophylaxis, perinatal transmission regimens — older regimens superseded)",
 note="Khopkar's PEP and perinatal regimens (zidovudine-based, single-dose nevirapine) are outdated; only current NACO regimens are given here. Please confirm with the latest NACO technical guidelines."),

# ---------------- ANTIPARASITICS ----------------
dict(name="Albendazole", group="More from Khopkar · Other antiparasitics",
 cls="Benzimidazole anthelmintic (broad spectrum)",
 moa=["Binds parasite β-tubulin → inhibits microtubule polymerisation → impaired glucose uptake and energy depletion → death of worms (larvicidal, some ovicidal action)"],
 pk=["Poorly absorbed; a fatty meal increases absorption (needed for tissue infections); active metabolite albendazole sulfoxide"],
 uses=["Cutaneous larva migrans (drug of choice with ivermectin): 400 mg daily for 3–7 days",
       "Cysticercosis (including cysticercosis cutis and neurocysticercosis — with steroids and anticonvulsants)",
       "Gnathostomiasis, larva currens (strongyloidiasis — ivermectin preferred), hookworm, ascariasis, hydatid disease",
       "Lymphatic filariasis mass drug administration (with DEC ± ivermectin)",
       "Deworming before starting long-term systemic steroids/immunosuppressants in endemic areas"],
 dose=["Single dose 400 mg (worms; 200 mg in children 1–2 years)",
       "CLM: 400 mg daily × 3–7 days",
       "Neurocysticercosis: 15 mg/kg/day (max 800 mg) in 2 doses for 8–30 days, with steroids",
       "Gnathostomiasis: 400 mg twice daily for 21 days"],
 ae=["Single dose: GI upset, headache",
     "Long courses: raised transaminases, reversible alopecia, bone marrow suppression (rare)",
     "Neurocysticercosis: seizures/raised ICP from dying cysts (cover with steroids)"],
 ci=["Pregnancy (first trimester) — teratogenic in animals; ocular cysticercosis (treat surgically first)"],
 ix=["Dexamethasone and praziquantel raise albendazole levels; carbamazepine/phenytoin lower them"],
 mon=["CBC and LFT every 2 weeks on long courses"],
 preg="Avoid in the first trimester; single doses in 2nd/3rd trimester allowed in deworming programmes.",
 viva=["Drug of choice for CLM (with ivermectin)",
       "Take with fatty food for tissue parasites",
       "Steroid cover in neurocysticercosis"],
 src=f"{K} ch.5 (Table 5.1); {W} ch.12"),

dict(name="Mebendazole", group="More from Khopkar · Other antiparasitics",
 cls="Benzimidazole anthelmintic",
 moa=["Inhibits parasite microtubule (β-tubulin) polymerisation → impaired glucose uptake → worm death"],
 pk=["Very poorly absorbed (<10%) — mainly acts in the gut lumen"],
 uses=["Intestinal worms (pinworm, roundworm, hookworm, whipworm)",
       "Cutaneous larva migrans (less effective than albendazole — poor absorption)",
       "Trichinosis (with steroids), hydatid disease (high doses, historical)"],
 dose=["100 mg twice daily × 3 days, or 500 mg single dose; pinworm 100 mg single, repeat after 2 weeks"],
 ae=["Abdominal pain, diarrhoea; with high doses — neutropenia, hepatitis, alopecia",
     "SJS/TEN reported when combined with metronidazole"],
 ci=["Pregnancy (first trimester); children under 1 year"],
 ix=["Metronidazole: SJS/TEN reports; cimetidine raises levels; carbamazepine lowers them"],
 preg="Avoid in the first trimester.",
 viva=["Poorly absorbed — luminal worms; albendazole preferred for tissue parasites like CLM"],
 src=f"{K} ch.5; {W} ch.12"),

dict(name="Thiabendazole (oral + topical)", group="More from Khopkar · Other antiparasitics",
 cls="Benzimidazole anthelmintic (first of its class)",
 moa=["Inhibits helminth fumarate reductase and microtubule function; also anti-inflammatory and antipyretic"],
 uses=["Topical 10–15% (suspension/cream, compounded, or crushed tablets in petrolatum): cutaneous larva migrans — applied to the track and 2 cm beyond",
       "Oral: strongyloidiasis, CLM, visceral larva migrans (now replaced by ivermectin/albendazole; oral form withdrawn in many countries)"],
 dose=["Topical: 10–15% three times daily for 5 days (or until track stops progressing)",
       "Oral (historic): 25 mg/kg twice daily for 2–5 days (max 3 g/day)"],
 ae=["Oral: frequent nausea, vomiting, dizziness, foul-smelling urine, hepatotoxicity, SJS/TEN, hallucinations",
     "Topical: minimal irritation"],
 ci=["Oral: liver disease, pregnancy"],
 ix=["Oral: raises theophylline levels"],
 preg="Topical acceptable; avoid oral.",
 viva=["Topical thiabendazole for localised CLM (useful in children and pregnancy)",
       "Oral form largely abandoned because of side effects"],
 src=f"{K} ch.5 and ch.21; {W} ch.12 and ch.44"),

dict(name="Diethylcarbamazine (DEC)", group="More from Khopkar · Other antiparasitics",
 cls="Piperazine derivative; antifilarial",
 moa=["Makes microfilariae more susceptible to host immune attack (alters arachidonic acid metabolism and surface membranes); some macrofilaricidal effect on adult worms"],
 uses=["Lymphatic filariasis (Wuchereria bancrofti, Brugia malayi) — individual treatment and mass drug administration (MDA with albendazole ± ivermectin in India's elimination programme)",
       "Loiasis (Loa loa) — drug of choice (with caution)",
       "Tropical pulmonary eosinophilia; toxocariasis (alternative)",
       "Not for onchocerciasis (severe Mazzotti reaction, eye damage)"],
 dose=["Treatment: 6 mg/kg/day for 12 days (tropical pulmonary eosinophilia: 21 days)",
       "MDA: 6 mg/kg single annual dose (with albendazole 400 mg)",
       "Loiasis: start low and increase (to avoid encephalopathy), with steroids/antihistamines"],
 ae=["Mazzotti-like reaction from dying microfilariae: fever, headache, itch, rash, lymphadenitis, hypotension — worse with heavy infection",
     "Encephalopathy and death in heavy Loa loa microfilaraemia",
     "GI upset, dizziness"],
 ci=["Onchocerciasis (eye damage); heavy Loa loa microfilaraemia (>2500/mL without pre-treatment); pregnancy"],
 ix=["Few significant interactions"],
 preg="Avoid (excluded from MDA).",
 viva=["Drug of choice for lymphatic filariasis and loiasis",
       "Contraindicated in onchocerciasis",
       "Mazzotti reaction"],
 src=f"{K} ch.5 (Diethylcarbamazine); {W} ch.12"),

dict(name="Praziquantel", group="More from Khopkar · Other antiparasitics",
 cls="Pyrazinoisoquinoline anthelmintic (anti-trematode, anti-cestode)",
 moa=["Increases calcium permeability of the worm's tegument → spastic paralysis and tegument damage → exposure to host immunity"],
 uses=["Schistosomiasis (including cercarial dermatitis sequelae and cutaneous schistosomiasis)",
       "Cysticercosis (cysticercosis cutis, neurocysticercosis — with or after albendazole), taeniasis",
       "Liver and lung flukes (clonorchiasis, paragonimiasis)"],
 dose=["Schistosomiasis: 40 mg/kg single dose or 20 mg/kg twice in one day",
       "Taeniasis: 5–10 mg/kg single dose",
       "Neurocysticercosis: 50 mg/kg/day in 3 doses for 15 days (with steroids)",
       "Cysticercosis cutis (Khopkar): single or short courses; excision is often curative"],
 ae=["Headache, dizziness, abdominal pain, malaise; inflammatory reactions from dying cysts (seizures in neurocysticercosis)"],
 ci=["Ocular cysticercosis (inflammation can destroy the eye — remove surgically)",
     "With strong CYP3A4 inducers (rifampicin)"],
 ix=["Rifampicin, carbamazepine, phenytoin, dexamethasone lower levels; cimetidine raises them"],
 preg="May be used for schistosomiasis in pregnancy (WHO).",
 viva=["Calcium influx → spastic paralysis of worms",
       "Never treat ocular cysticercosis medically first"],
 src=f"{K} ch.5 (Table 5.1); {W} ch.12"),

dict(name="Pentavalent antimonials (sodium stibogluconate, meglumine antimoniate)", group="More from Khopkar · Other antiparasitics",
 cls="Pentavalent antimony (SbV) compounds; antileishmanial",
 moa=["Prodrug: SbV reduced to trivalent SbIII inside macrophages and amastigotes",
      "Inhibits trypanothione reductase and parasite glycolysis/fatty acid oxidation → amastigote death; also enhances macrophage killing"],
 uses=["Cutaneous leishmaniasis: intralesional for small, few lesions (Old World — L. tropica, L. major); systemic for multiple, large, facial/joint lesions, lymphatic spread, mucosal or New World species",
       "Mucocutaneous and visceral leishmaniasis (visceral: largely replaced in India by liposomal amphotericin B/miltefosine because of resistance in Bihar)",
       "Post-kala-azar dermal leishmaniasis (older regimens; miltefosine now preferred)"],
 dose=["Systemic: 20 mg SbV/kg/day IV or IM for 20 days (cutaneous) or 28 days (mucosal/visceral)",
       "Intralesional: 0.2–1 mL (100 mg SbV/mL) infiltrated until the lesion blanches, weekly or every 2 weeks for 3–8 sessions (often combined with cryotherapy)",
       "Sodium stibogluconate 100 mg SbV/mL; meglumine antimoniate 85 mg SbV/mL"],
 ae=["Cardiotoxicity: QT prolongation, T-wave changes, arrhythmia — dose and duration related",
     "Pancreatitis (raised amylase/lipase), hepatitis, nephrotoxicity",
     "Myalgia, arthralgia, fatigue, headache; cytopenias",
     "IL: pain, swelling, local reactions"],
 ci=["Heart disease (prolonged QT), significant renal/hepatic disease, pregnancy"],
 ix=["Other QT-prolonging drugs (amiodarone, macrolides, fluoroquinolones, antipsychotics)"],
 mon=["ECG twice weekly (stop if QTc >500 ms), amylase/lipase, LFT, renal function, CBC weekly"],
 preg="Avoid (systemic); prefer local measures or liposomal amphotericin B.",
 viva=["SbV prodrug → SbIII",
       "20 mg SbV/kg/day × 20 days (cutaneous)",
       "ECG monitoring — QT prolongation",
       "Resistance in Bihar → replaced for kala-azar"],
 src=f"{K} ch.5 (Antileishmanial agents — sodium stibogluconate); {W} ch.12"),

dict(name="Pentamidine", group="More from Khopkar · Other antiparasitics",
 cls="Aromatic diamidine; antiprotozoal and anti-Pneumocystis",
 moa=["Interferes with parasite DNA, RNA, phospholipid and protein synthesis (binds kinetoplast DNA)"],
 uses=["Cutaneous leishmaniasis due to L. guyanensis (New World) — drug of choice",
       "Pneumocystis jirovecii pneumonia (treatment and aerosolised prophylaxis when co-trimoxazole cannot be used)",
       "Early-stage African trypanosomiasis (T. b. gambiense); visceral leishmaniasis (second-line, historical)"],
 dose=["Leishmaniasis: 4 mg/kg IM/IV on alternate days for 3–4 doses (L. guyanensis) or longer courses",
       "PCP: 4 mg/kg IV daily for 21 days; prophylaxis 300 mg nebulised monthly"],
 ae=["Hypoglycaemia (pancreatic β-cell toxicity — early), followed later by diabetes mellitus",
     "Hypotension (especially with rapid IV infusion — give slowly lying down), arrhythmias (QT prolongation)",
     "Nephrotoxicity, pancreatitis, leucopenia; sterile abscess at IM sites"],
 ci=["Hypersensitivity; caution in diabetes, heart disease, renal impairment"],
 ix=["Foscarnet (severe hypocalcaemia), nephrotoxic and QT drugs"],
 mon=["Blood glucose, BP during and after infusion, ECG, renal function, CBC"],
 preg="Use only when essential.",
 viva=["Hypoglycaemia then diabetes",
       "Drug of choice for L. guyanensis cutaneous leishmaniasis"],
 src=f"{K} ch.5 (Pentamidine); {W} ch.12"),
]
