# Exam drugs — slot 4 (part B): Topicals VI–XI (keratolytics & emollients, anti-acne, pigmentary, immunomodulators, hair & scalp, miscellaneous)
W = "Wolverton 4e"; K = "Khopkar"
D = [
# ---------------- VI KERATOLYTICS & EMOLLIENTS ----------------
dict(name="Salicylic acid (6% ointment, paint)", group="Topicals · VI Keratolytics & emollients",
 cls="β-hydroxy acid; keratolytic (desmolytic) agent",
 moa=["Dissolves the intercellular cement (desmosomes) between corneocytes, so scale sheds — 'desmolytic' rather than true keratolytic",
      "Lipophilic — penetrates the pilosebaceous unit (comedolytic)",
      "Mild antibacterial/antifungal; enhances penetration of other topicals"],
 uses=["3–6%: psoriasis plaques and scalp, ichthyosis, palmoplantar keratoderma, seborrhoeic dermatitis (shampoo), hyperkeratotic eczema",
       "0.5–2%: acne washes and gels (comedolytic)",
       "Salicylic acid paint/collodion (10–20% with lactic acid): common and plantar warts, corns, calluses",
       "40% plaster: corns, plantar warts",
       "20–30% peels: acne, PIH (see chemical peels)"],
 dose=["6% ointment/cream: once or twice daily to thick scaly areas",
       "Wart paint: soak wart, pare, apply daily to the wart only (protect surrounding skin with petroleum jelly), for up to 12 weeks"],
 ae=["Irritation, peeling, stinging",
     "Salicylism (salicylate toxicity) with use over large areas, high concentrations, broken skin, children, renal impairment: nausea, tinnitus, hyperventilation, confusion, metabolic acidosis",
     "Ulceration of normal skin around warts"],
 ci=["Children under 2 years; large areas (over about 20% BSA) in children",
     "Diabetics and peripheral vascular disease (wart paints on feet — ulceration risk)",
     "Aspirin allergy (relative); renal impairment"],
 ix=["Methotrexate, sulfonylureas, warfarin — absorbed salicylate can increase their effects"],
 preg="Small areas acceptable; avoid large-area or high-concentration use.",
 viva=["Desmolytic — dissolves the cement between cells",
       "Salicylism in children treated over large areas",
       "Avoid wart paints on diabetic feet"],
 src=f"{W} ch.55 (Agents used for hyperkeratosis); {K} ch.27 (Moisturizers and keratolytic agents)"),

dict(name="Coal tar + Salicylic acid", group="Topicals · VI Keratolytics & emollients",
 cls="Combination: tar (antiproliferative, antipruritic) + salicylic acid (keratolytic)",
 moa=["Coal tar activates the aryl hydrocarbon receptor → normalises keratinocyte differentiation, reduces proliferation (antimitotic), anti-inflammatory, antipruritic; also photosensitises (UVA)",
      "Salicylic acid removes scale and helps tar penetrate"],
 uses=["Chronic plaque psoriasis (body and scalp), palmoplantar psoriasis",
       "Seborrhoeic dermatitis and dandruff (shampoo), lichen simplex chronicus, chronic eczema",
       "Goeckerman regimen: crude coal tar followed by UVB"],
 dose=["Ointment/lotion: apply at night, wash off in the morning; shampoo 2–3 times weekly",
       "Crude coal tar 1–5% or liquor carbonis detergens (LCD) 5–20%"],
 ae=["Odour, staining of skin, hair and clothes",
     "Tar folliculitis (tar acne), irritation, contact dermatitis",
     "Phototoxicity ('tar smarts' — burning on sun exposure)",
     "Carcinogenicity in occupational exposure; risk from therapeutic use is not proven"],
 ci=["Acute, pustular or erythrodermic psoriasis; infected or broken skin",
     "Face, flexures, genitals (relative); pregnancy (relative)"],
 preg="Avoid (theoretical carcinogen/mutagen).",
 viva=["Tar = AhR ligand",
       "Goeckerman regimen: tar + UVB",
       "Tar folliculitis and 'tar smarts'"],
 src=f"{W} ch.57 (tar) and ch.55; {K} ch.28"),

dict(name="Urea (10% cream; urea + lactic acid)", group="Topicals · VI Keratolytics & emollients",
 cls="Humectant (low concentration) and keratolytic (high concentration)",
 moa=["At 10% or less: humectant — draws water into the stratum corneum (natural moisturising factor component)",
      "At 20–40%: keratolytic — breaks hydrogen bonds in keratin, dissolves scale",
      "40% (under occlusion): softens and dissolves dystrophic nail plate (chemical nail avulsion)",
      "Lactic acid (α-hydroxy acid) adds humectant and keratolytic action; the combination is better for thick scaling"],
 uses=["10%: xerosis, atopic dermatitis (dry skin), mild ichthyosis, elderly dry skin",
       "Urea + lactic acid (e.g. urea 10–12% + lactic acid 10%): ichthyosis vulgaris, X-linked and lamellar ichthyosis, keratosis pilaris, palmoplantar keratoderma, cracked heels",
       "20–40%: hyperkeratosis of soles, calluses",
       "40% paste: onychomycosis/nail psoriasis nail avulsion (before topical antifungal)",
       "Enhances penetration of topical steroids and antifungals"],
 dose=["Apply once or twice daily, ideally after bathing on damp skin"],
 ae=["Stinging or burning, especially on inflamed or fissured skin and in young children",
     "Irritation of face and mucosa"],
 ci=["Acutely inflamed or broken skin; infants (stinging) — use with caution"],
 preg="Safe.",
 viva=["Concentration determines action: humectant (≤10%) vs keratolytic (20–40%) vs nail avulsion (40%)",
       "Stings on eczematous skin"],
 src=f"{W} ch.55; {K} ch.27"),

dict(name="Glycolic acid (cream, lotion, peel)", group="Topicals · VI Keratolytics & emollients",
 cls="α-hydroxy acid (AHA) — smallest AHA (from sugar cane)",
 moa=["Reduces corneocyte cohesion (loosens the stratum corneum) → exfoliation",
      "At higher concentrations: dermal effects — increases collagen and glycosaminoglycan production",
      "Disperses melanin and speeds removal of pigmented keratinocytes"],
 uses=["Creams/lotions 6–12% (home use): xerosis, ichthyosis, keratosis pilaris, photoageing, acne (comedonal), melasma and PIH (adjunct), dull skin",
       "Chemical peels 20–70% (superficial peels, office use): acne, melasma, PIH, photoageing, superficial scars",
       "Also in the anti-acne list (glycolic acid cream)"],
 dose=["Creams: once daily at night, starting with lower strength; sunscreen during the day",
       "Peels: start 20–35% for 2–3 min, increase strength and time every 2–4 weeks; neutralise with sodium bicarbonate solution or water"],
 ae=["Stinging, redness, dryness, peeling",
     "Photosensitivity — use sunscreen",
     "Peels: frosting/burns if left too long, PIH (dark skin), herpes reactivation"],
 ci=["Active infection, open wounds, inflamed eczema/rosacea; recent isotretinoin (peels — relative)"],
 preg="Low-strength creams and superficial peels are considered safe.",
 viva=["Smallest AHA — penetrates best",
       "Glycolic acid peels are time-dependent — must be neutralised",
       "Increases sun sensitivity"],
 src=f"{W} ch.52 (α-Hydroxy acids) and ch.53 (Chemical peels); {K} ch.31"),

dict(name="Ammonium lactate 12% lotion", group="Topicals · VI Keratolytics & emollients",
 cls="α-hydroxy acid (lactic acid neutralised with ammonium hydroxide)",
 moa=["Humectant (lactic acid is part of natural moisturising factor) and mild keratolytic (reduces corneocyte cohesion)",
      "Buffered (pH about 4.5–5.5) → less stinging than plain lactic acid"],
 uses=["Xerosis, ichthyosis vulgaris (FDA approved), keratosis pilaris, cracked heels, palmoplantar hyperkeratosis"],
 dose=["Apply twice daily, rub in thoroughly"],
 ae=["Stinging and burning on fissured or inflamed skin; erythema",
     "Photosensitivity — sun protection advised"],
 ci=["Hypersensitivity; face (relative); broken skin"],
 preg="Safe.",
 viva=["Buffered lactic acid — approved for ichthyosis vulgaris and xerosis"],
 src=f"{W} ch.52 and ch.55; {K} ch.27"),

dict(name="Moisturisers & emollients (Aquasoft, Physiogel-type, ceramide creams)", group="Topicals · VI Keratolytics & emollients",
 cls="Barrier repair agents: occlusives, humectants, emollients and physiological lipids",
 moa=["Occlusives (petrolatum, mineral oil, dimethicone, lanolin) form a film that reduces transepidermal water loss (TEWL); petrolatum is the most effective",
      "Humectants (glycerin, urea, lactic acid, hyaluronic acid, propylene glycol) draw water into the stratum corneum",
      "Emollients (fatty esters, plant oils, ceramides) fill gaps between corneocytes → smooth, soft skin",
      "Physiological lipid mixtures (ceramides : cholesterol : free fatty acids in about 3:1:1 ratio) repair the lamellar barrier in atopic skin (low ceramides)",
      "Physiogel AI-type creams add palmitoylethanolamide (PEA) — an anti-inflammatory/antipruritic lipid",
      "Aquasoft (glycerin–paraffin based cream) is a humectant–occlusive moisturiser commonly used in India"],
 uses=["Atopic dermatitis (cornerstone of treatment; proactive use reduces flares and steroid need)",
       "Ichthyoses, xerosis, asteatotic eczema in the elderly, hand eczema, psoriasis (adjunct)",
       "Barrier recovery with retinoid/isotretinoin therapy, after procedures",
       "Infant skin care (early emollient use may lower AD risk in high-risk infants — conflicting data)"],
 dose=["Apply liberally and often (at least twice daily), within 3 min after bathing ('soak and seal')",
       "Adults may need 250–500 g per week for widespread disease; children 150–250 g per week",
       "Apply in the direction of hair growth (avoid folliculitis); apply 15–30 min apart from topical steroid"],
 ae=["Folliculitis (occlusive ointments), acneiform eruption on face",
     "Stinging (urea, lactic acid, propylene glycol)",
     "Contact allergy to fragrance, lanolin, preservatives (parabens, methylisothiazolinone)",
     "Fire risk: paraffin-soaked clothing/dressings near flames"],
 ci=["Known allergy to an ingredient"],
 preg="Safe.",
 viva=["Occlusive vs humectant vs emollient — give examples",
       "Ceramide : cholesterol : FFA = 3:1:1",
       "Soak-and-seal within 3 min of bathing",
       "Paraffin-based emollients are a fire hazard"],
 src=f"{W} ch.57 (Miscellaneous topical agents — moisturisers); {K} ch.27 (Moisturizers)",
 note="Aquasoft and Physiogel are brand names; the post explains the ingredient types they represent."),

# ---------------- VII ANTI-ACNE ----------------
dict(name="Tretinoin 0.025% (and 0.05%, 0.1%)", group="Topicals · VII Anti-acne — Retinoids",
 cls="First-generation topical retinoid (all-trans retinoic acid)",
 moa=["Binds all three nuclear RAR receptors (α, β, γ) → normalises follicular keratinisation (comedolytic; prevents microcomedones)",
      "Increases cell turnover; anti-inflammatory (reduces TLR-2 expression)",
      "Increases dermal collagen and disperses melanin (photoageing, pigmentation)"],
 uses=["Acne vulgaris (comedonal and inflammatory) — first-line with BPO; maintenance after control",
       "Photoageing (fine wrinkles, mottled pigmentation), melasma (in triple combination), PIH",
       "Flat warts, keratosis pilaris, molluscum (adjunct), striae (early)"],
 dose=["Pea-sized amount for the whole face at night, on dry skin, 20–30 min after washing",
       "Start with 0.025% cream on alternate nights, increase as tolerated",
       "Photolabile and oxidised by BPO — apply at night and separately from BPO (micronised/microsphere forms are more stable)"],
 ae=["Retinoid dermatitis (redness, peeling, burning) in the first 2–4 weeks",
     "Initial flare of acne ('purge'), photosensitivity (thinned stratum corneum)",
     "Hypo- or hyperpigmentation (dark skin)"],
 ci=["Pregnancy (avoid as a precaution), eczema, sunburn, rosacea (relative)"],
 ix=["BPO inactivates it (if applied together); other irritants (abrasive soaps, astringents, peels) increase irritation"],
 preg="Avoid in pregnancy (minimal absorption, but retinoid class — not recommended); azelaic acid is a safer alternative.",
 viva=["Binds RAR-α, β, γ (adapalene and tazarotene are RAR-β/γ selective)",
       "Photolabile and oxidised by BPO — apply at night",
       "Expect irritation and early flare — counsel patients"],
 src=f"{W} ch.46 (Topical retinoids); {K} ch.24"),

dict(name="Adapalene gel (0.1%, 0.3%)", group="Topicals · VII Anti-acne — Retinoids",
 cls="Third-generation (polyaromatic) topical retinoid — naphthoic acid derivative",
 moa=["Selective for RAR-β and RAR-γ → comedolytic, normalises keratinisation",
      "Strong anti-inflammatory action (inhibits neutrophil lipoxygenase, AP-1, TLR-2)"],
 uses=["Acne vulgaris — first-line (0.1% gel, available OTC in the USA; 0.3% for more severe)",
       "Fixed combinations: adapalene 0.1%/0.3% + BPO 2.5%; adapalene + clindamycin",
       "Maintenance after oral therapy or isotretinoin; PIH, keratosis pilaris, Darier disease (off-label)"],
 dose=["Pea-sized amount once daily at night (can be applied in the morning — chemically stable)"],
 ae=["Dryness, redness, stinging — less irritating than tretinoin or tazarotene",
     "Photosensitivity (mild)"],
 ci=["Eczema, sunburn; pregnancy (precaution)"],
 ix=["Stable with BPO and in light — can be combined in one product"],
 preg="Avoid in pregnancy (precaution).",
 viva=["Most tolerable topical retinoid",
       "Light-stable and BPO-stable — combined in one gel",
       "RAR-β/γ selective"],
 src=f"{W} ch.46; {K} ch.24"),

dict(name="Tazarotene 0.1% (gel, cream)", group="Topicals · VII Anti-acne — Retinoids",
 cls="Third-generation acetylenic retinoid (prodrug of tazarotenic acid)",
 moa=["Tazarotenic acid binds RAR-β and RAR-γ",
      "Normalises keratinocyte differentiation and proliferation, reduces inflammatory markers (psoriasis); induces tazarotene-induced genes (TIG1–3)",
      "Comedolytic in acne"],
 uses=["Plaque psoriasis (0.05%/0.1%) — often with a topical steroid to reduce irritation",
       "Acne vulgaris (0.1%; foam 0.1%; 0.045% lotion)",
       "Photoageing, nail psoriasis (off-label), congenital ichthyoses, keratosis pilaris"],
 dose=["Thin layer once daily in the evening to lesions only (avoid surrounding skin in psoriasis)",
       "Short-contact therapy (wash off after 2–5 min, increasing) reduces irritation"],
 ae=["Irritation (most irritating topical retinoid): burning, redness, peeling",
     "Photosensitivity"],
 ci=["Pregnancy (contraindicated — old FDA category X); women must have a negative pregnancy test and use contraception",
     "Eczematous or sunburnt skin"],
 preg="Contraindicated in pregnancy (old FDA category X).",
 viva=["Only topical retinoid that is pregnancy category X",
       "Used for both psoriasis and acne",
       "Most irritating — combine with a steroid or use short contact"],
 src=f"{W} ch.46; {K} ch.24"),

dict(name="Benzoyl peroxide (2.5–5%)", group="Topicals · VII Anti-acne — Others",
 cls="Oxidising agent; bactericidal, keratolytic",
 moa=["Releases free oxygen radicals inside the follicle → kills C. acnes (bactericidal)",
      "Bacteria cannot develop resistance (non-specific oxidation)",
      "Mild comedolytic and anti-inflammatory effects"],
 uses=["Acne vulgaris — in nearly every regimen; combine with topical/oral antibiotics to prevent resistance",
       "Pitted keratolysis, folliculitis, decolonisation (washes)"],
 dose=["2.5–5% gel once or twice daily (2.5% is as effective as 10% with less irritation)",
       "Washes 4–10%: short-contact for chest/back",
       "Fixed combinations: BPO + clindamycin, BPO + adapalene"],
 ae=["Dryness, peeling, redness, burning",
     "Bleaches hair, clothes, towels and bed linen",
     "Allergic contact dermatitis (about 1%)"],
 ci=["Known allergy; acutely inflamed skin"],
 ix=["Oxidises tretinoin (apply at different times) — adapalene is stable",
     "Combined use with dapsone gel can cause temporary orange-brown skin discolouration"],
 preg="Safe (minimal absorption).",
 viva=["No antibiotic resistance — the reason it is combined with antibiotics",
       "2.5% works as well as higher strengths with less irritation",
       "Bleaches fabrics — counsel patients"],
 src=f"{W} ch.41 (BPO) and ch.46; {K} ch.18"),

dict(name="Azelaic acid 20% cream", group="Topicals · VII Anti-acne — Others",
 cls="Naturally occurring saturated dicarboxylic acid (from Malassezia furfur)",
 moa=["Antibacterial against C. acnes and staphylococci; normalises keratinisation (comedolytic)",
      "Competitive inhibitor of tyrosinase and toxic to abnormal (hyperactive) melanocytes → treats hyperpigmentation without affecting normal skin",
      "Anti-inflammatory and anti-oxidant (reduces reactive oxygen species, KLK5/cathelicidin in rosacea)"],
 uses=["Acne vulgaris (mild–moderate), especially with PIH",
       "Papulopustular rosacea (15% gel — approved)",
       "Melasma, PIH, lentigo maligna (historic)",
       "Safe option in pregnancy"],
 dose=["Twice daily; results by 4–8 weeks (acne), 2–3 months (melasma)"],
 ae=["Transient burning, stinging, itching (common at start)",
     "Rarely hypopigmentation in dark skin (watch)"],
 ci=["Hypersensitivity (propylene glycol in gel)"],
 preg="Safe in pregnancy and breastfeeding (old FDA category B).",
 viva=["Tyrosinase inhibitor that acts only on hyperactive melanocytes",
       "Acne + rosacea + melasma in one drug",
       "Pregnancy-safe acne treatment"],
 src=f"{W} ch.57 (azelaic acid); {K} ch.26 (Demelanizing agents)"),

# ---------------- VIII PIGMENTARY / DEPIGMENTING ----------------
dict(name="Hydroquinone 2% (and 4%)", group="Topicals · VIII Pigmentary / depigmenting",
 cls="Phenolic tyrosinase inhibitor (hydroxyphenol); gold-standard depigmenting agent",
 moa=["Competitive substrate inhibitor of tyrosinase → less melanin",
      "Also generates reactive oxygen species that damage melanosomes and melanocytes (cytotoxic)",
      "Unstable — oxidises to brown (do not use if the cream turns brown)"],
 uses=["Melasma (first-line, alone 2–4% or in triple combination), PIH, solar lentigines, ephelides",
       "Monobenzone (monobenzyl ether of hydroquinone) is different — causes permanent depigmentation (used for universal vitiligo)"],
 dose=["Apply at night to pigmented areas only; with strict daytime broad-spectrum sunscreen",
       "Use for 3–4 months, then take a break (cycling) or switch to non-hydroquinone maintenance (azelaic acid, kojic acid, niacinamide)",
       "2% available OTC in some countries; 4% prescription"],
 ae=["Irritant and allergic contact dermatitis",
     "Transient hypopigmentation, 'halo' effect around treated areas, confetti-like depigmentation",
     "Exogenous ochronosis (blue-black pigmentation, caviar-like papules) — especially with long-term use, high concentrations and in dark skin (common in Africa with unregulated products)",
     "Nail discolouration"],
 ci=["Pregnancy and breastfeeding (avoid; significant absorption 35–45%)",
     "Hypersensitivity; sunburnt or inflamed skin"],
 ix=["Benzoyl peroxide and hydrogen peroxide: transient dark staining"],
 preg="Avoid in pregnancy (old FDA category C; high absorption).",
 viva=["Tyrosinase inhibitor + melanocytotoxic",
       "Exogenous ochronosis with prolonged use",
       "Monobenzone (not hydroquinone) for permanent depigmentation",
       "Banned in cosmetics in the EU; prescription-only in many countries"],
 src=f"{K} ch.26 (Demelanizing agents); {W} ch.57"),

dict(name="Kojic acid + Arbutin + Glycolic acid cream", group="Topicals · VIII Pigmentary / depigmenting",
 cls="Non-hydroquinone combination depigmenting cream (cosmeceutical)",
 moa=["Kojic acid (fungal metabolite, 1–4%): chelates copper at the tyrosinase active site → inhibits tyrosinase; antioxidant",
      "Arbutin (glycosylated hydroquinone from bearberry, 1–3%): competitive tyrosinase inhibitor with less melanocytotoxicity than hydroquinone",
      "Glycolic acid: exfoliates pigmented keratinocytes and enhances penetration"],
 uses=["Melasma (maintenance or hydroquinone-intolerant patients), PIH, mild lentigines",
       "Maintenance after triple combination cream"],
 dose=["Once daily at night (or twice daily) with daytime sunscreen; results over 8–12 weeks"],
 ae=["Irritation, contact dermatitis (kojic acid is a sensitiser)",
     "Photosensitivity (glycolic acid)",
     "Kojic acid is unstable — oxidises in air and light"],
 ci=["Hypersensitivity; inflamed skin"],
 preg="Limited data; generally considered low risk (arbutin releases small amounts of hydroquinone — use caution).",
 viva=["Kojic acid chelates copper of tyrosinase",
       "Arbutin = natural hydroquinone glycoside",
       "Useful hydroquinone-free maintenance"],
 src=f"{K} ch.26 and ch.29 (Cosmeceuticals); {W} ch.57"),

dict(name="Triple combination cream (Fluocinolone + Hydroquinone + Tretinoin)", group="Topicals · VIII Pigmentary / depigmenting",
 cls="Fixed combination: tyrosinase inhibitor + retinoid + low-potency steroid (modified Kligman formula)",
 moa=["Hydroquinone 4%: inhibits tyrosinase",
      "Tretinoin 0.05%: increases keratinocyte turnover (removes pigment), helps hydroquinone penetrate, prevents hydroquinone oxidation",
      "Fluocinolone acetonide 0.01%: reduces irritation from the other two and has an anti-melanogenic effect (reduces cell metabolism)",
      "Original Kligman–Willis formula (1975): hydroquinone 5% + tretinoin 0.1% + dexamethasone 0.1%"],
 uses=["Moderate–severe melasma — short-term (approved for up to 8 weeks)",
       "Also listed under 'steroid combinations' in the exam list"],
 dose=["Once nightly, pea-sized amount to pigmented areas, for up to 8 weeks, with strict daytime sunscreen",
       "Then switch to maintenance: twice-weekly TCC or non-steroid depigmenting agents (azelaic, kojic acid, niacinamide)"],
 ae=["Irritation, erythema, peeling, burning",
     "Steroid side effects with long-term use: atrophy, telangiectasia, rosacea-like eruption, acne, topical steroid dependence/TSDF — a common problem in India because of OTC misuse as 'fairness cream'",
     "Hydroquinone: exogenous ochronosis, confetti hypopigmentation"],
 ci=["Pregnancy and breastfeeding",
     "Long-term (more than 8 weeks continuous) or whole-face use as a fairness cream",
     "Rosacea, acne, perioral dermatitis, broken skin"],
 preg="Contraindicated (tretinoin, hydroquinone).",
 viva=["Kligman's original vs modified triple combination — know both",
       "Limit to 8 weeks; maintenance with non-steroid agents",
       "Steroid misuse in fairness creams → topical steroid-damaged face (TSDF)"],
 src=f"{K} ch.26 (Demelanizing agents); {W} ch.45 (steroid misuse) and ch.46"),

dict(name="Methoxsalen topical solution (topical PUVA)", merge_into="Methoxsalen (8-MOP, oral)", form_label="Topical form", group="Topicals · VIII Pigmentary / depigmenting",
 cls="Psoralen (8-methoxypsoralen) for topical photochemotherapy",
 moa=["Applied psoralen is activated by UVA/sunlight → DNA cross-linking, T-cell apoptosis",
      "In vitiligo: stimulates melanocyte proliferation, migration from hair follicle reservoirs, and melanogenesis"],
 uses=["Localised vitiligo (under 20% BSA), including children over about 5 years (oral PUVA not suitable)",
       "Localised palmoplantar psoriasis and hand/foot eczema (soak or paint PUVA)",
       "Alopecia areata (limited)"],
 dose=["Commercial 1% lotion must be diluted (usually to 0.1% or lower, e.g. 1:10 with alcohol/acetone; Wolverton uses even lower 0.001–0.005% for bath/soak)",
       "Apply to patches only, 15–30 min before exposure to UVA or morning sunlight",
       "Start with 1–2 min of sun/low UVA, increase gradually; 2–3 times a week, never on consecutive days",
       "Wash the area after exposure and protect from further sun for the day"],
 ae=["Phototoxic reaction: severe erythema, blistering (common if undiluted or overexposed)",
     "Hyperpigmentation of surrounding skin (perilesional 'halo' or patchy darkening)",
     "Contact dermatitis",
     "Less systemic risk than oral PUVA (no nausea, eye protection less critical, but avoid getting it near eyes)"],
 ci=["Photosensitive disorders (lupus, porphyria, XP), children under 5",
     "Pregnancy (relative)"],
 preg="Avoid.",
 viva=["Always dilute — the 1% lotion causes blistering",
       "Suitable for limited vitiligo and children",
       "Never treat on consecutive days"],
 src=f"{W} ch.23 (PUVA — topical psoralen); {K} (Psoralens, PUVA and phototherapy)"),

dict(name="Decapeptide lotion (e.g. Melbild/Melgain)", group="Topicals · VIII Pigmentary / depigmenting",
 cls="Synthetic decapeptide (repigmenting agent) — a bFGF-related peptide",
 moa=["Mimics a part of basic fibroblast growth factor (bFGF), a natural mitogen for melanocytes",
      "Stimulates melanocyte proliferation and migration, and melanogenesis",
      "Used to support repigmentation (not depigmentation)"],
 uses=["Stable vitiligo (localised and generalised) — adjunct to phototherapy, topical steroids or tacrolimus",
       "Children and face (steroid-sparing)"],
 dose=["Apply once daily to patches; many protocols advise sun exposure (morning) or NB-UVB after application",
       "Response takes 3–6 months"],
 ae=["Mild itching, burning, redness; generally very well tolerated"],
 ci=["Hypersensitivity"],
 preg="Insufficient data; low absorption.",
 viva=["A repigmenting peptide, not a depigmenting agent — classified here with pigmentary agents",
       "bFGF-mimicking decapeptide → melanocyte proliferation",
       "Evidence is modest (Indian studies)"],
 src=f"{K} (Topical immunomodulators — basic fibroblast growth factor decapeptide)"),

# ---------------- IX IMMUNOMODULATORS ----------------
dict(name="Tacrolimus ointment (0.03%, 0.1%)", group="Topicals · IX Immunomodulators",
 cls="Topical calcineurin inhibitor (TCI); macrolide from Streptomyces tsukubaensis",
 moa=["Binds FKBP-12 inside T cells; the complex inhibits calcineurin → NFAT not dephosphorylated → less IL-2, IL-4 and other cytokines",
      "Also reduces mast-cell and basophil mediator release, and Langerhans cell function",
      "Does not cause skin atrophy (no effect on collagen synthesis)"],
 uses=["Atopic dermatitis (moderate–severe; approved) — face, eyelids, flexures; proactive twice-weekly maintenance",
       "Vitiligo (face and neck — good response), seborrhoeic dermatitis, intertriginous/facial psoriasis",
       "Oral and genital lichen planus, cutaneous lupus (facial), steroid-induced rosacea/perioral dermatitis (steroid withdrawal)",
       "Lichen sclerosus (second line), morphoea, chronic actinic dermatitis"],
 dose=["0.03%: children 2–15 years (and adults); 0.1%: adults (16 years and older)",
       "Twice daily until clear, then twice weekly as maintenance",
       "Off-label use under 2 years is common with 0.03%"],
 ae=["Burning, stinging, warmth at application site in the first week (most common; improves)",
     "Alcohol intolerance (facial flushing after drinking)",
     "Skin infections: folliculitis, herpes simplex/eczema herpeticum, molluscum, warts",
     "Boxed warning (FDA 2006) about theoretical malignancy (lymphoma, skin cancer) — long-term studies have not shown a clear increase"],
 ci=["Immunosuppressed patients, Netherton syndrome (high absorption), active infection at site, malignant/pre-malignant skin lesions",
     "Children under 2 (label)"],
 ix=["Systemic CYP3A4 inhibitors — minimal relevance (low absorption) except with large areas or barrier defects"],
 preg="Minimal absorption; may be used on limited areas if needed.",
 viva=["Calcineurin inhibitor — no atrophy, so ideal for face and eyelids",
       "0.03% for 2–15 years, 0.1% for adults",
       "Burning sensation and alcohol flushing",
       "Boxed warning — theoretical malignancy"],
 src=f"{W} ch.48 (Topical calcineurin inhibitors); {K} ch.23 (Topical immunomodulators)"),

dict(name="Crisaborole 2% ointment", group="Topicals · IX Immunomodulators",
 cls="Topical phosphodiesterase-4 (PDE4) inhibitor (boron-containing benzoxaborole)",
 moa=["Inhibits PDE4 → increases intracellular cAMP → reduces TNF-α, IL-12, IL-23 and other cytokines",
      "Small molecule with boron atom → good skin penetration; rapidly metabolised to inactive forms when absorbed"],
 uses=["Mild–moderate atopic dermatitis in patients aged 3 months and older (approved)",
       "Off-label: seborrhoeic dermatitis, psoriasis (intertriginous), vitiligo (limited)"],
 dose=["Thin layer twice daily to affected areas"],
 ae=["Application-site burning or stinging (about 4%)",
     "Contact urticaria (rare)"],
 ci=["Hypersensitivity"],
 preg="Minimal absorption; limited data.",
 viva=["Non-steroidal, PDE4 → ↑cAMP",
       "Approved from 3 months of age",
       "Burning at application is the main complaint"],
 src=f"{W} ch.18 (PDE4 inhibitors — crisaborole); {K} edition predates it"),

dict(name="Imiquimod 5% cream", group="Topicals · IX Immunomodulators",
 cls="Imidazoquinoline immune response modifier; Toll-like receptor 7 (TLR7) agonist",
 moa=["Activates TLR7 (and TLR8) on dendritic cells and macrophages → release of IFN-α, TNF-α, IL-12",
      "Boosts innate and Th1 cell-mediated immunity → clears virus-infected and tumour cells; also directly pro-apoptotic"],
 uses=["Approved: external anogenital warts, actinic keratosis, superficial basal cell carcinoma",
       "Off-label: molluscum (not effective in trials in children), common warts, Bowen disease, lentigo maligna, extramammary Paget disease, keloid (post-excision), cutaneous metastases"],
 dose=["Anogenital warts: 3 times a week at bedtime (e.g. Mon/Wed/Fri), wash off after 6–10 h, up to 16 weeks",
       "Superficial BCC: 5 times a week for 6 weeks",
       "Actinic keratosis: twice a week for 16 weeks (5%); 3.75% daily for two 2-week cycles",
       "Sachets — use one sachet per application; wash hands"],
 ae=["Local inflammation (erythema, erosion, crusting, oedema) — often needed for efficacy; rest days if severe",
     "Flu-like symptoms (fever, myalgia, fatigue) with large areas",
     "Hypo- or hyperpigmentation; induction or worsening of psoriasis, vitiligo-like depigmentation",
     "Weakens condoms and diaphragms"],
 ci=["Hypersensitivity; internal (urethral, intravaginal, cervical, rectal) warts",
     "Caution: autoimmune disease, psoriasis, immunosuppression, broken skin"],
 preg="Limited data — avoid in pregnancy (old FDA category C); use cryotherapy for warts in pregnancy.",
 viva=["TLR7 agonist → IFN-α",
       "Warts: 3 times weekly; sBCC: 5 times weekly × 6 weeks",
       "Inflammation = sign it is working",
       "Damages latex condoms"],
 src=f"{W} ch.43 (Topical antivirals — imiquimod) and ch.47; {K} ch.23"),

dict(name="Tofacitinib 2% ointment", merge_into="Tofacitinib", form_label="Topical form", group="Topicals · IX Immunomodulators",
 cls="Topical Janus kinase (JAK1/3) inhibitor",
 moa=["Blocks JAK-STAT signalling of cytokines (IL-2, IL-4, IL-13, IL-15, IFN-γ) in skin",
      "In vitiligo: reduces IFN-γ–CXCL10 signalling that recruits cytotoxic T cells; in AA: blocks the IFN-γ/IL-15 axis"],
 uses=["Off-label/compounded in India: vitiligo (face), alopecia areata (limited areas), atopic dermatitis, plaque psoriasis (trials)",
       "Note: ruxolitinib 1.5% cream is the approved topical JAK inhibitor (vitiligo and atopic dermatitis, USA)"],
 dose=["Twice daily to limited areas (studies used up to about 10–20% BSA); combine with NB-UVB or sun exposure for vitiligo"],
 ae=["Local irritation, acne, folliculitis",
     "Theoretical systemic JAK effects with large-area use (labs if used extensively)"],
 ci=["Large body areas; active skin infection; pregnancy"],
 preg="Avoid.",
 viva=["Topical JAK inhibitors — newer, best results on facial vitiligo",
       "Ruxolitinib cream is the approved one; tofacitinib topical is mostly compounded/trial use"],
 src=f"{W} ch.18 (JAK inhibitors — tofacitinib 2% ointment, compounded)"),

# ---------------- X HAIR & SCALP ----------------
dict(name="Minoxidil 5% solution", group="Topicals · X Hair & scalp agents",
 cls="Piperidinopyrimidine derivative; potassium-channel opener (originally an oral antihypertensive)",
 moa=["Prodrug — converted in the hair follicle by sulfotransferase (SULT1A1) to minoxidil sulfate (active)",
      "Opens ATP-sensitive potassium channels → vasodilation and increased follicle blood flow",
      "Prolongs anagen, shortens telogen, enlarges miniaturised follicles; stimulates VEGF and dermal papilla cells",
      "Low follicular sulfotransferase activity predicts poor response"],
 uses=["Androgenetic alopecia — men (5%) and women (2% solution or 5% foam once daily)",
       "Alopecia areata (adjunct), chemotherapy-induced alopecia (to shorten duration), eyebrow/beard hypotrichosis (off-label)",
       "Oral low-dose minoxidil (0.25–5 mg/day) — in the Derma Desk 2nd-line ladder"],
 dose=["Men: 1 mL of 5% solution twice daily to dry scalp (affected area), leave at least 4 h; or 5% foam twice daily",
       "Women: 2% solution 1 mL twice daily or 5% foam once daily",
       "Shedding in the first 2–8 weeks is expected (telogen release); judge at 6–12 months; must continue — benefit lost in 3–4 months after stopping"],
 ae=["Scalp irritation, itching, scaling, contact dermatitis (often due to propylene glycol — foam is PG-free)",
     "Hypertrichosis of the face/forehead (especially women; from drips or hand transfer)",
     "Initial shedding; rarely headache, dizziness, palpitations, hypotension (systemic absorption)"],
 ci=["Hypersensitivity; broken or inflamed scalp",
     "Pregnancy and breastfeeding; caution in cardiovascular disease"],
 preg="Avoid in pregnancy (fetal hypertrichosis/malformations reported with systemic exposure) and breastfeeding.",
 viva=["Prodrug activated by follicular sulfotransferase",
       "Initial shedding is a sign of response, not failure",
       "Must be used indefinitely",
       "Propylene glycol causes most contact dermatitis — switch to foam"],
 src=f"{W} ch.57 (Miscellaneous topical agents — minoxidil); {K} ch.28"),

dict(name="Zinc pyrithione shampoo (1–2%)", group="Topicals · X Hair & scalp agents",
 cls="Organometallic antifungal/antibacterial (zinc complex of pyrithione)",
 moa=["Pyrithione disrupts fungal membrane transport and causes copper influx → damages iron–sulfur proteins in Malassezia",
      "Also antibacterial and mildly keratolytic/antiproliferative (cytostatic to keratinocytes)"],
 uses=["Dandruff and seborrhoeic dermatitis of scalp (common OTC shampoos)",
       "Pityriasis versicolor (as body wash), scalp psoriasis (mild, adjunct)"],
 dose=["Lather onto wet scalp, leave 3–5 min, rinse; 2–3 times weekly, then weekly"],
 ae=["Scalp irritation; rare contact dermatitis",
     "Banned in cosmetics in the EU since 2022 (reproductive toxicity classification) — still used elsewhere"],
 ci=["Hypersensitivity; broken scalp"],
 preg="Considered safe for short-contact shampoo use (but see EU regulatory status).",
 viva=["Most common anti-dandruff agent worldwide",
       "Acts via copper influx toxic to Malassezia"],
 src=f"{W} ch.51 (Therapeutic shampoos); {K} ch.28"),

dict(name="Selenium sulfide shampoo (1–2.5%)", group="Topicals · X Hair & scalp agents",
 cls="Inorganic sulfide; cytostatic and antifungal",
 moa=["Cytostatic — reduces epidermal (keratinocyte) turnover, so less scale",
      "Antifungal against Malassezia (sporicidal)"],
 uses=["Pityriasis versicolor (2.5% as a body lotion/shampoo)",
       "Seborrhoeic dermatitis and dandruff",
       "Tinea capitis (adjunct, 2.5% twice weekly — reduces spore shedding and transmission)"],
 dose=["Pityriasis versicolor: apply 2.5% to affected skin for 10 min daily for 7 days (or overnight once weekly), then monthly for prevention",
       "Scalp: leave 2–3 min, rinse; twice weekly for 2 weeks, then weekly"],
 ae=["Irritation (avoid broken skin, genitals), unpleasant smell",
     "Oily scalp, hair discolouration (orange tinge on grey/dyed hair), hair loss (rare)",
     "Absorption from broken skin can be toxic"],
 ci=["Broken or inflamed skin; genital area"],
 preg="Avoid large-area use in pregnancy.",
 viva=["Cytostatic + antifungal",
       "Used in tinea capitis to reduce spore shedding (adjunct to oral therapy)"],
 src=f"{W} ch.51; {K} ch.19 and ch.28"),

# ---------------- XI MISCELLANEOUS ----------------
dict(name="Calamine lotion", group="Topicals · XI Miscellaneous",
 cls="Shake lotion (zinc oxide with a small amount of ferric oxide) — soothing, drying, mildly astringent",
 moa=["Zinc oxide/calamine powder suspended in water: water evaporates → cooling, antipruritic effect",
      "Powder remains on the skin → drying and protective; mildly astringent and antiseptic",
      "Ferric oxide gives the pink colour"],
 uses=["Acute itchy rashes: varicella, insect bites, miliaria rubra, sunburn, urticaria (symptomatic), mild contact dermatitis",
       "Weeping lesions (drying)"],
 dose=["Shake well; dab on 2–4 times daily; allow to dry"],
 ae=["Dryness with prolonged use; caking on hairy skin",
     "Phenol-containing versions — avoid in infants and pregnancy"],
 ci=["Very dry or chronic lichenified eczema (too drying)"],
 preg="Safe (plain calamine).",
 viva=["Classic example of a shake lotion (powder + liquid)",
       "Cooling by evaporation; drying for weeping lesions"],
 src=f"{K} ch.28 (Miscellaneous topical agents); {W} ch.57"),

dict(name="Sunscreens (avobenzone, oxybenzone, tinted sunscreens)", group="Topicals · XI Miscellaneous",
 cls="Ultraviolet filters: organic (chemical) absorbers and inorganic (physical/mineral) blockers",
 moa=["Organic filters absorb UV energy and release it as heat",
      "Avobenzone (butyl methoxydibenzoylmethane): the main UVA1 filter (320–400 nm, peak 357 nm); photo-unstable — needs stabilisers (octocrylene, bemotrizinol)",
      "Oxybenzone (benzophenone-3): absorbs UVB and UVA2 (broad, up to about 350 nm); the most common photoallergen; concerns about hormone effects and coral reefs",
      "Inorganic filters (zinc oxide, titanium dioxide) reflect, scatter and absorb UVB and UVA; zinc oxide covers UVA1 better",
      "Tinted sunscreens contain iron oxides → block visible light (blue light), which worsens melasma and PIH in skin types IV–VI"],
 uses=["Prevention of sunburn, photoageing, actinic keratoses, SCC (proven), melanoma and BCC (supportive data)",
       "Photodermatoses (PLE, lupus, porphyrias, chronic actinic dermatitis, XP)",
       "Melasma, PIH, vitiligo (prevent burning and contrast), patients on photosensitising drugs or after procedures"],
 dose=["Broad spectrum, SPF 30 or more (SPF 50+ for photosensitive), UVA rating PA+++ or higher; tinted for melasma",
       "Amount: 2 mg/cm² (about ½ teaspoon for face and neck; ~30 mL — a 'shot glass' — for the whole adult body); most people apply only a quarter to half of this",
       "Apply 15–30 min before going out; reapply every 2 hours and after swimming or sweating",
       "SPF = ratio of MED with sunscreen to MED without (UVB); SPF 15 blocks ~93%, SPF 30 ~97%, SPF 50 ~98% of UVB",
       "UVA protection measures: PPD/PA rating, critical wavelength ≥370 nm"],
 ae=["Irritant dermatitis (stinging, especially around eyes)",
     "Allergic and photoallergic contact dermatitis (oxybenzone, octocrylene, PABA)",
     "Acne/comedones with oily formulations; white cast with inorganic filters",
     "Possible lower vitamin D synthesis (rarely clinically significant)"],
 ci=["Known allergy to a filter; infants under 6 months — prefer shade and clothing; mineral sunscreen on small areas if needed"],
 preg="Safe; mineral sunscreens preferred by some in pregnancy.",
 viva=["Avobenzone = UVA1 filter but photo-unstable",
       "Oxybenzone = commonest photoallergen",
       "Iron oxide (tinted) protects against visible light — melasma",
       "SPF measures UVB; PA/PPD measures UVA; 2 mg/cm²"],
 src=f"{W} ch.50 (Sunscreens); {K} ch.25"),

dict(name="Lignocaine + Prilocaine (EMLA cream/gel)", group="Topicals · XI Miscellaneous",
 cls="Eutectic mixture of local anaesthetics (lidocaine 2.5% + prilocaine 2.5%)",
 moa=["The two amides mixed in equal amounts have a melting point below room temperature (eutectic) → a liquid oil that penetrates intact skin",
      "Blocks voltage-gated sodium channels in dermal nerve endings → surface anaesthesia"],
 uses=["Topical anaesthesia before venepuncture, IV cannulation, laser treatments, curettage of molluscum, wart removal, superficial biopsies, split-skin grafts, microneedling, leg ulcer debridement",
       "Genital mucosa (shorter application time: 5–10 min)"],
 dose=["Apply a thick layer (1–2 g per 10 cm²) under occlusion (film dressing) for 60 min (depth about 3 mm); 120 min for deeper anaesthesia (about 5 mm)",
       "Infant limits: 0–3 months — max 1 g over 10 cm² for 1 h; 3–12 months — max 2 g over 20 cm²; larger limits in older children by weight",
       "Wipe off before the procedure"],
 ae=["Blanching then redness at application site (vasoconstriction followed by vasodilation)",
     "Methaemoglobinaemia — the most serious adverse effect (prilocaine metabolite o-toluidine oxidises haemoglobin); risk in infants under 3 months, large areas, G6PD deficiency, with other oxidising drugs",
     "Purpura, contact urticaria, irritant reactions",
     "Eye injury if applied near eyes (corneal abrasion)"],
 ci=["Congenital or idiopathic methaemoglobinaemia",
     "Infants under 12 months on methaemoglobin-inducing drugs; premature infants (under 37 weeks)",
     "Amide anaesthetic allergy; open wounds (except leg ulcers per protocol); near eyes or middle ear"],
 ix=["Methaemoglobin-inducing drugs: dapsone, sulfonamides, nitrates (nitroglycerin), paracetamol (high dose), phenytoin, antimalarials (primaquine, chloroquine)",
     "Class I antiarrhythmics: additive toxicity"],
 mon=["In infants or large areas: watch for cyanosis (grey-blue colour with normal oxygen); treat methaemoglobinaemia with methylene blue (avoid in G6PD deficiency)"],
 preg="Safe in pregnancy (old FDA category B).",
 viva=["Eutectic = mixture melts below room temperature → penetrates intact skin",
       "60 min under occlusion",
       "Methaemoglobinaemia due to prilocaine (worse with dapsone)"],
 src=f"{W} ch.58 (Local anesthetics — EMLA, methemoglobinemia); {K} (Miscellaneous agents)"),
]
