# Exam drugs — slot 2: Oral VI–XI (immunosuppressants, systemic steroids, antiandrogens, antihistamines, methoxsalen, miscellaneous incl. STI kits)
W = "Wolverton 4e"; K = "Khopkar"
D = [
# ---------------- VI IMMUNOSUPPRESSANTS ----------------
dict(name="Methotrexate", group="Oral · VI Immunosuppressants",
 cls="Folic acid antagonist (antimetabolite); immunomodulator",
 moa=["Competitively inhibits dihydrofolate reductase (DHFR) → less tetrahydrofolate → less purine and thymidine synthesis → inhibits DNA synthesis in rapidly dividing cells (S-phase specific)",
      "At low weekly doses the main effect is anti-inflammatory: polyglutamated MTX inhibits AICAR transformylase → adenosine builds up and acts as an anti-inflammatory signal",
      "Reduces T-cell activation and keratinocyte proliferation"],
 pk=["Oral absorption is variable and saturable at higher doses; subcutaneous route gives more reliable levels (useful above 15–20 mg/week)",
     "About 50% protein bound (displaced by NSAIDs, sulfonamides, salicylates)",
     "Stored in cells as polyglutamates; excreted mainly unchanged by the kidneys — reduce dose in renal impairment"],
 uses=["Psoriasis (plaque, erythrodermic, pustular, psoriatic arthritis) — approved",
       "Atopic dermatitis, chronic urticaria (refractory), alopecia areata",
       "Immunobullous disease (bullous pemphigoid, pemphigus as steroid-sparing)",
       "Connective tissue disease: dermatomyositis, morphoea and systemic sclerosis skin, cutaneous lupus",
       "Sarcoidosis, pityriasis rubra pilaris, pityriasis lichenoides, lymphomatoid papulosis, Mycosis fungoides (early), vasculitis, pyoderma gangrenosum"],
 dose=["Once weekly — never daily (daily dosing errors cause fatal toxicity)",
       "Psoriasis: start 7.5–15 mg/week (test dose of 2.5–5 mg optional, especially in elderly or renal impairment), increase by 2.5–5 mg to 15–25 mg/week; maximum usually 25–30 mg/week",
       "Children: 0.2–0.7 mg/kg/week",
       "Folic acid 1–5 mg daily (except MTX day) or 5 mg weekly reduces GI and liver side effects and cytopenias",
       "Weekly oral, subcutaneous or IM routes; tablets 2.5, 7.5, 10 mg"],
 ae=["GI: nausea, anorexia, stomatitis, oral ulcers",
     "Bone marrow suppression — pancytopenia is the main cause of death (risk: renal failure, elderly, interacting drugs, no folate, dosing errors)",
     "Hepatotoxicity: raised enzymes, fibrosis and cirrhosis with long-term use (risk: alcohol, obesity, diabetes, fatty liver, hepatitis B/C)",
     "Pulmonary: acute hypersensitivity pneumonitis (idiosyncratic) and chronic fibrosis",
     "Skin: alopecia, ulceration of psoriatic plaques (early sign of overdose), photo-recall, epidermal necrosis",
     "Teratogenic and abortifacient; reversible oligospermia",
     "Infections; lymphoma (EBV-related, may regress on stopping)"],
 ci=["Absolute: pregnancy and breastfeeding; significant liver disease or alcoholism; severe renal impairment; bone marrow failure; active serious infection",
     "Relative: hepatitis B/C, obesity, diabetes, fatty liver, unreliable patient, immunodeficiency, recent live vaccine"],
 ix=["Trimethoprim–sulfamethoxazole (co-trimoxazole): additive antifolate → severe pancytopenia (most important)",
     "NSAIDs, salicylates, penicillins, probenecid, PPIs: reduce renal clearance or displace MTX",
     "Dapsone and other antifolates; retinoids and alcohol (liver); leflunomide",
     "Phenytoin, sulfonylureas, tetracyclines displace MTX from albumin"],
 mon=["Baseline: CBC, LFT, renal function, hepatitis B/C, HIV, chest X-ray, pregnancy test, TB screening (IGRA) where relevant",
      "CBC and LFT weekly–2-weekly for the first month, then every 1–3 months; renal function every 3–6 months",
      "Liver fibrosis: non-invasive tests (e.g. transient elastography/FibroScan, procollagen III peptide) — liver biopsy only if these suggest fibrosis",
      "Traditionally biopsy was considered after a cumulative dose of 3.5–4 g in high-risk-free patients (Wolverton reviews this older approach)"],
 preg="Absolute contraindication (old FDA category X). Stop 3 months before conception (women; also commonly advised for men). Avoid in breastfeeding.",
 viva=["Weekly dosing — check the patient is not taking it daily",
       "Co-trimoxazole is the most dangerous interaction",
       "Antidote for overdose: leucovorin (folinic acid) — bypasses DHFR; give as early as possible (covered in slot 3)",
       "Painful ulceration of psoriatic plaques can be the first sign of toxicity",
       "Liver monitoring has moved from routine biopsy to non-invasive tests"],
 src=f"{W} ch.14 (Methotrexate); {K} (Non-steroidal immunosuppressive drugs)"),

dict(name="Cyclosporine", group="Oral · VI Immunosuppressants",
 cls="Calcineurin inhibitor (cyclic peptide from the fungus Tolypocladium inflatum)",
 moa=["Binds cyclophilin inside T cells; the complex inhibits calcineurin",
      "Calcineurin cannot dephosphorylate NFAT, so NFAT does not enter the nucleus → less IL-2 and other cytokines → T-cell activation blocked",
      "Also inhibits mast-cell and keratinocyte activation"],
 pk=["Microemulsion form (Neoral and generics) has more reliable absorption than the old form (Sandimmune) — do not switch between brands casually",
     "Metabolised by CYP3A4; excreted in bile",
     "Grapefruit juice raises levels"],
 uses=["Severe psoriasis — rapid control ('crisis' drug), erythrodermic and generalised pustular psoriasis",
       "Severe atopic dermatitis (approved in Europe)",
       "Chronic urticaria (refractory to antihistamines)",
       "SJS/TEN (early use may reduce mortality; first line in the Derma Desk SJS ladder)",
       "Pyoderma gangrenosum, Behçet disease, lichen planus, chronic actinic dermatitis, prurigo nodularis, immunobullous diseases (adjunct)"],
 dose=["Psoriasis/atopic dermatitis: 2.5–5 mg/kg/day in 2 divided doses (Wolverton favours starting at the higher end for rapid control, then tapering)",
       "Taper by 0.5–1 mg/kg every 2–4 weeks once controlled",
       "Short courses (intermittent therapy, 12–16 weeks) are preferred; continuous use generally limited to 1–2 years",
       "Capsules 25, 50, 100 mg; oral solution 100 mg/mL"],
 ae=["Nephrotoxicity — the most important; dose- and duration-dependent; early functional (vasoconstriction) then irreversible interstitial fibrosis",
     "Hypertension (about a quarter of psoriasis patients)",
     "Hypertrichosis, gingival hyperplasia, sebaceous hyperplasia, follicular keratosis",
     "Tremor, headache, paraesthesia; hyperkalaemia, hypomagnesaemia, hyperuricaemia, hyperlipidaemia",
     "Increased skin cancer (especially after previous PUVA) and lymphoma; infections"],
 ci=["Uncontrolled hypertension, abnormal renal function",
     "Malignancy (except non-melanoma skin cancer, with caution); high cumulative PUVA (above about 200 treatments)",
     "Concurrent phototherapy; active serious infection; live vaccines"],
 ix=["CYP3A4 inhibitors raise levels (nephrotoxicity): azoles (ketoconazole, itraconazole), macrolides (erythromycin, clarithromycin), diltiazem, verapamil, grapefruit",
     "CYP3A4 inducers lower levels (rejection/flare): rifampicin, phenytoin, carbamazepine, phenobarbital, St John's wort",
     "Additive nephrotoxicity: NSAIDs, aminoglycosides",
     "Statins (myopathy), potassium-sparing diuretics (hyperkalaemia)"],
 mon=["Blood pressure and serum creatinine twice at baseline, then every 2 weeks for 1–2 months, then monthly",
      "If creatinine rises more than 25–30% above baseline (on two readings), reduce dose by 25–50%; stop if it stays high",
      "Also: K⁺, Mg²⁺, uric acid, lipids, LFT, CBC, urine",
      "Trough levels are not needed routinely in dermatology"],
 preg="Not teratogenic in humans (old FDA category C); has been used in transplant pregnancies, but prematurity and low birth weight are reported. Avoid breastfeeding.",
 viva=["Calcineurin–NFAT–IL-2 pathway",
       "Most important side effects: nephrotoxicity and hypertension",
       "Creatinine rule: more than 25–30% above baseline → reduce dose",
       "Microemulsion form has better absorption",
       "Avoid with PUVA history and with phototherapy (skin cancer)"],
 src=f"{W} ch.17 (Cyclosporine); {K} (Non-steroidal immunosuppressive drugs)",
 note="Wolverton notes that recent guidelines use a 25% creatinine threshold while the traditional dermatology threshold is 30% — both are mentioned."),

dict(name="Azathioprine", group="Oral · VI Immunosuppressants",
 cls="Purine analogue (antimetabolite); prodrug of 6-mercaptopurine (6-MP)",
 moa=["Converted non-enzymatically to 6-MP, then to 6-thioguanine nucleotides (6-TGN)",
      "6-TGN are incorporated into DNA and inhibit purine synthesis → T and B lymphocytes (which rely on de novo purine synthesis) are suppressed"],
 pk=["Well absorbed; 6-MP is broken down by three enzymes: TPMT (thiopurine methyltransferase), xanthine oxidase and HGPRT (which makes active 6-TGN)",
     "Low TPMT activity → more 6-TGN → severe myelosuppression",
     "Allopurinol (xanthine oxidase inhibitor) greatly increases toxicity"],
 uses=["Immunobullous diseases: pemphigus (steroid-sparing; paired with steroids as first line in the Derma Desk ladder), bullous pemphigoid",
       "Chronic actinic dermatitis, airborne contact dermatitis (Parthenium — weekly pulse), atopic dermatitis",
       "Dermatomyositis, cutaneous lupus, vasculitis, Behçet disease, pyoderma gangrenosum"],
 dose=["Dose by TPMT activity (Wolverton): under 6.3 U/mL → do not use; 6.3–15 U/mL → 1 mg/kg/day; 15.1–26.4 U/mL (normal) → up to 2–2.5 mg/kg/day",
       "Without TPMT testing: start 50 mg/day and increase slowly with close CBC checks",
       "Usual 1–3 mg/kg/day; takes 6–8 weeks for full effect",
       "Parthenium dermatitis (Indian practice): weekly pulse of 300 mg once a week (as in the Derma Desk ladder)",
       "Tablets 50 mg"],
 ae=["Myelosuppression (leucopenia, thrombocytopenia, macrocytosis) — acute (low TPMT) or chronic",
     "GI: nausea, vomiting (commonest reason to stop); take with food or in divided doses",
     "Hypersensitivity syndrome (fever, rash, shock) in the first weeks",
     "Hepatotoxicity, pancreatitis",
     "Infections; non-melanoma skin cancer (especially SCC) and lymphoma with long-term use"],
 ci=["TPMT activity absent/very low",
     "Pregnancy (relative — see below), active serious infection, malignancy",
     "Previous treatment with alkylating agents (cyclophosphamide, chlorambucil) — higher malignancy risk"],
 ix=["Allopurinol/febuxostat: block xanthine oxidase → severe toxicity — avoid, or reduce azathioprine to 25% of dose",
     "ACE inhibitors, co-trimoxazole: added myelosuppression",
     "Warfarin effect reduced",
     "Sulfasalazine and mesalazine inhibit TPMT"],
 mon=["Baseline: TPMT, CBC, LFT, renal function, hepatitis B/C, HIV, pregnancy test",
      "CBC every 2 weeks for 2 months, then every 1–3 months; LFT every 1–3 months",
      "Annual skin examination for skin cancer; sun protection"],
 preg="Old FDA category D, but widely used in pregnancy in transplant and inflammatory bowel disease patients with acceptable outcomes; decide case by case. Low levels in breast milk.",
 viva=["TPMT testing before starting — key exam point",
       "Allopurinol interaction (xanthine oxidase)",
       "Slow onset (6–8 weeks), so start steroids alongside",
       "Long-term risk of SCC and lymphoma"],
 src=f"{W} ch.15 (Azathioprine), Box 15.4; {K} (Non-steroidal immunosuppressive drugs)"),

dict(name="Mycophenolate mofetil (MMF)", group="Oral · VI Immunosuppressants",
 cls="Inosine monophosphate dehydrogenase (IMPDH) inhibitor; prodrug of mycophenolic acid",
 moa=["Mycophenolic acid reversibly inhibits IMPDH → blocks de novo guanine nucleotide synthesis",
      "Lymphocytes depend on the de novo pathway (other cells can use the salvage pathway), so the effect is fairly selective for T and B cells",
      "Also reduces antibody production and adhesion molecule expression"],
 pk=["Rapidly converted to mycophenolic acid; glucuronidated in the liver; enterohepatic recirculation",
     "Enteric-coated mycophenolate sodium (720 mg ≈ 1 g MMF) has fewer GI effects"],
 uses=["Immunobullous diseases: pemphigus vulgaris (second line with rituximab in the Derma Desk ladder), bullous pemphigoid, mucous membrane pemphigoid",
       "Dermatomyositis, cutaneous lupus, systemic sclerosis (skin and lung), vasculitis",
       "Atopic dermatitis, psoriasis (modest), pyoderma gangrenosum, lichen planus"],
 dose=["Adults: 1–1.5 g twice daily (2–3 g/day); start at 500 mg twice daily and increase over 2–4 weeks",
       "Children: about 600 mg/m² twice daily",
       "Tablets 250 and 500 mg; mycophenolate sodium 180 and 360 mg"],
 ae=["GI (the commonest): nausea, diarrhoea, abdominal cramps",
     "Myelosuppression (leucopenia, anaemia), opportunistic infections (CMV, herpes zoster)",
     "Progressive multifocal leukoencephalopathy (rare); lymphoma and skin cancer risk",
     "Teratogenic"],
 ci=["Pregnancy; hypersensitivity",
     "Active serious infection; caution in peptic ulcer disease and HGPRT deficiency (Lesch–Nyhan, Kelley–Seegmiller)"],
 ix=["Antacids, cholestyramine, PPIs, iron: reduce absorption",
     "Acyclovir/valacyclovir: both levels rise (compete for tubular secretion)",
     "Azathioprine: do not combine (double myelosuppression)",
     "Lowers oral contraceptive levels; rifampicin lowers MMF"],
 mon=["CBC weekly for the first month, every 2 weeks for 2 months, then monthly",
      "LFT and renal function periodically; pregnancy tests"],
 preg="Contraindicated (old FDA category D; embryopathy including ear, facial and limb defects). Women need two forms of contraception during treatment and for 6 weeks after; men should use condoms during and for 90 days after.",
 viva=["IMPDH inhibitor — lymphocyte-selective because of dependence on de novo purine synthesis",
       "GI side effects commonest; enteric-coated sodium salt helps",
       "Steroid-sparing agent in pemphigus"],
 src=f"{W} ch.16 (Mycophenolates); {K} (Non-steroidal immunosuppressive drugs)"),

dict(name="Thalidomide", group="Oral · VI Immunosuppressants",
 cls="Glutamic acid derivative; immunomodulatory drug (IMiD)",
 moa=["Binds cereblon (part of an E3 ubiquitin ligase), changing which proteins are degraded",
      "Reduces TNF-α production (by speeding TNF mRNA breakdown); shifts Th1 responses",
      "Anti-angiogenic (explains teratogenicity — limb defects) and sedative"],
 pk=["Slowly absorbed; half-life about 5–7 h",
     "Broken down mainly by non-enzymatic hydrolysis — few CYP interactions"],
 uses=["Erythema nodosum leprosum (ENL) — drug of choice for severe/recurrent ENL",
       "Cutaneous lupus (refractory discoid/subacute), Behçet disease and aphthous ulcers (especially HIV)",
       "Prurigo nodularis, actinic prurigo, Jessner lymphocytic infiltrate, sarcoidosis, graft-versus-host disease",
       "Multiple myeloma (oncology)"],
 dose=["ENL: 100–400 mg/day at bedtime (start 100 mg; higher doses split), taper to the lowest effective dose (e.g. 50–100 mg) once controlled",
       "Lupus, prurigo, aphthae: 50–100 mg/day at night",
       "Capsules 50, 100 mg"],
 ae=["Teratogenic — phocomelia and other limb, ear, heart, GI defects even after a single dose in early pregnancy (days 20–36 after conception)",
     "Peripheral neuropathy (sensory, often irreversible; dose- and duration-related)",
     "Sedation, dizziness, constipation, oedema",
     "Venous thromboembolism (especially with steroids or chemotherapy)",
     "Rash, bradycardia, neutropenia, hypothyroidism"],
 ci=["Pregnancy and women unable to use reliable contraception",
     "Existing peripheral neuropathy; breastfeeding"],
 ix=["CNS depressants (alcohol, sedatives): more sedation",
     "Drugs causing neuropathy (dapsone, metronidazole, isoniazid): more neuropathy",
     "Drugs raising clot risk (oral contraceptives, steroids)"],
 mon=["Pregnancy tests before, weekly in the first month, then monthly",
      "Baseline and periodic nerve conduction studies or clinical sensory examination",
      "Watch for signs of thrombosis"],
 preg="Absolute contraindication (old FDA category X). Women: two contraceptive methods from 4 weeks before until 4 weeks after. Men must use condoms (drug is present in semen) during treatment and for 4 weeks after. Restricted-distribution programme in many countries.",
 viva=["Drug of choice for severe ENL",
       "Teratogenicity — phocomelia; sensitive period days 20–36 after conception",
       "Peripheral neuropathy — monitor",
       "Mechanism: cereblon binding, TNF-α reduction, anti-angiogenesis"],
 src=f"{W} ch.40 (Miscellaneous systemic drugs); {K} (Miscellaneous agents)"),

dict(name="Tofacitinib", group="Oral · VI Immunosuppressants",
 cls="Janus kinase (JAK) inhibitor — mainly JAK1 and JAK3 (pan-JAK at higher doses)",
 moa=["Blocks JAK enzymes that pass on signals from cytokine receptors",
      "So STAT proteins are not activated, and responses to IL-2, IL-4, IL-6, IL-7, IL-15, IL-21 and interferons are reduced",
      "Dampens T-cell, B-cell and NK-cell function"],
 pk=["Well absorbed; half-life about 3 h (twice daily or once-daily extended release)",
     "Metabolised by CYP3A4 (70%) and kidneys (30%)"],
 uses=["Approved: rheumatoid arthritis, psoriatic arthritis, ulcerative colitis",
       "Off-label in dermatology: alopecia areata, vitiligo (with phototherapy), refractory dermatomyositis, atopic dermatitis, sarcoidosis, lichen planopilaris, psoriasis",
       "In the Derma Desk ladders it is a later-line option (e.g. alopecia areata, vitiligo)"],
 dose=["5 mg twice daily (or 11 mg extended release once daily); 10 mg twice daily used in some trials and off-label for alopecia areata",
       "Reduce to 5 mg once daily with strong CYP3A4 inhibitors or moderate–severe renal/hepatic impairment"],
 ae=["Infections: upper respiratory, herpes zoster (notable risk), TB reactivation, opportunistic infections",
     "Boxed warnings (ORAL Surveillance study, patients over 50 with cardiovascular risk): major cardiac events, thrombosis (DVT/PE), malignancy (lung cancer, lymphoma), and death",
     "Raised lipids, LFT and creatine kinase; cytopenias (lymphopenia, neutropenia, anaemia)",
     "Acne, headache, GI perforation (rare)"],
 ci=["Active serious infection including TB; severe hepatic impairment",
     "Lymphocytes under 500/mm³, neutrophils under 1000/mm³, Hb under 9 g/dL",
     "Pregnancy; caution if over 50 with cardiovascular risk factors or smokers, history of thrombosis or cancer"],
 ix=["Strong CYP3A4 inhibitors (ketoconazole) → reduce dose; inducers (rifampicin) → avoid",
     "Do not combine with biologics or potent immunosuppressants such as cyclosporine or azathioprine",
     "Live vaccines — avoid; give recombinant zoster vaccine beforehand"],
 mon=["Baseline: CBC, LFT, lipids, renal function, TB screen (IGRA), hepatitis B/C, HIV",
      "CBC and LFT at 4–8 weeks, then every 3 months; lipids at 4–8 weeks",
      "Skin check; cardiovascular risk review"],
 preg="Avoid (limited data; animal teratogenicity). Stop at least 4 weeks before planned conception. Avoid in breastfeeding.",
 viva=["JAK-STAT pathway — 'cytokine signal blocker'",
       "Herpes zoster risk — consider the recombinant zoster vaccine",
       "Boxed warning from ORAL Surveillance: MACE, thrombosis, malignancy, death",
       "Oral JAK inhibitor; topical 2% ointment is in the topicals slot"],
 src=f"{W} ch.18 (PDE-4 and JAK inhibitors); {K} edition predates JAK inhibitors"),

dict(name="Apremilast", group="Oral · VI Immunosuppressants",
 cls="Phosphodiesterase-4 (PDE4) inhibitor (small molecule)",
 moa=["Inhibits PDE4 → raises intracellular cAMP in immune cells",
      "Higher cAMP lowers pro-inflammatory cytokines (TNF-α, IL-17, IL-23, IFN-γ) and raises anti-inflammatory IL-10",
      "Immunomodulatory rather than immunosuppressive — no lab monitoring needed"],
 pk=["Well absorbed; metabolised by CYP3A4; half-life about 6–9 h"],
 uses=["Approved: moderate–severe plaque psoriasis, psoriatic arthritis, oral ulcers of Behçet disease",
       "Scalp, nail, palmoplantar and genital psoriasis",
       "Off-label: atopic dermatitis, lichen planus, hidradenitis suppurativa, alopecia areata (limited)"],
 dose=["Titration pack over 5 days (10 mg → 20 mg → 30 mg) to reduce GI side effects, then 30 mg twice daily",
       "Severe renal impairment (creatinine clearance under 30 mL/min): 30 mg once daily"],
 ae=["GI: diarrhoea, nausea, vomiting (mostly in the first 2 weeks)",
     "Headache, upper respiratory infection",
     "Weight loss (about 5–10% of body weight in some patients)",
     "Depression and suicidal thoughts (rare) — ask about mood"],
 ci=["Hypersensitivity",
     "Caution in depression or suicidal ideation, low body weight, severe renal impairment"],
 ix=["Strong CYP3A4 inducers (rifampicin, phenobarbital, carbamazepine, phenytoin) lower levels — avoid"],
 mon=["No routine blood tests",
      "Weight and mood at follow-up visits"],
 preg="Limited human data; animal studies showed pregnancy loss at high doses — avoid in pregnancy and breastfeeding.",
 viva=["PDE4 → ↑cAMP → ↓TNF-α, IL-17, IL-23, ↑IL-10",
       "No lab monitoring; no TB screening required",
       "Start with a titration pack to limit GI side effects",
       "Watch weight and depression"],
 src=f"{W} ch.18; {K} edition predates apremilast"),

# ---------------- VII SYSTEMIC CORTICOSTEROIDS ----------------
dict(name="Prednisolone", group="Oral · VII Systemic corticosteroids",
 cls="Intermediate-acting glucocorticoid (biological half-life 12–36 h); reference steroid for oral dosing",
 moa=["Enters cells and binds the cytoplasmic glucocorticoid receptor; the complex enters the nucleus",
      "Genomic effects: switches on anti-inflammatory genes (lipocortin/annexin-1, IκB) and switches off pro-inflammatory genes (NF-κB and AP-1 targets: IL-1, IL-2, TNF-α, COX-2)",
      "Result: fewer circulating lymphocytes, eosinophils and monocytes; less vascular permeability; reduced antibody production with high doses",
      "Non-genomic (rapid) effects with high pulse doses"],
 pk=["Prednisolone is active itself (prednisone needs conversion in the liver to prednisolone)",
     "Well absorbed; bound to transcortin and albumin; metabolised in the liver (enzyme inducers raise clearance)",
     "Equivalence: 5 mg prednisolone = 20 mg hydrocortisone = 4 mg methylprednisolone = 6 mg deflazacort = 0.75 mg dexamethasone = 0.6 mg betamethasone",
     "Glucocorticoid potency 4 (hydrocortisone = 1); mineralocorticoid effect 0.8"],
 uses=["Immunobullous diseases: pemphigus vulgaris (1–1.5 mg/kg/day initially), bullous pemphigoid (0.5–0.75 mg/kg/day if topical not possible)",
       "Connective tissue disease: dermatomyositis (1 mg/kg/day), SLE",
       "Vasculitis, neutrophilic dermatoses (Sweet syndrome, pyoderma gangrenosum)",
       "Short courses: acute severe allergic contact dermatitis, severe urticaria/angioedema (short), DRESS, erythema nodosum leprosum and type 1 lepra reaction",
       "Lichen planus (extensive), sarcoidosis, alopecia areata (selected)"],
 dose=["Short courses: 0.5–1 mg/kg/day for 1–3 weeks, then taper",
       "Give as a single morning dose (mimics normal cortisol rhythm, less HPA suppression); divided doses for severe disease",
       "Alternate-day dosing for maintenance reduces HPA suppression and side effects",
       "Taper slowly once disease is controlled; below physiological dose (about 5–7.5 mg/day) taper more slowly",
       "Courses under 2–3 weeks can usually be stopped without taper"],
 ae=["Metabolic: hyperglycaemia/steroid diabetes, weight gain, Cushingoid features, hyperlipidaemia, hypokalaemia",
     "Bone: osteoporosis and fractures, avascular necrosis of femoral head, growth retardation in children",
     "Eye: posterior subcapsular cataract, glaucoma",
     "GI: peptic ulcer (mainly with NSAIDs), pancreatitis",
     "CNS: insomnia, mood change, psychosis",
     "Infections (TB reactivation, strongyloides hyperinfection, opportunistic); poor wound healing",
     "HPA axis suppression and adrenal crisis on sudden withdrawal",
     "Skin: striae, atrophy, purpura, steroid acne, hirsutism, delayed healing",
     "Hypertension, fluid retention; myopathy (proximal)"],
 ci=["Absolute: systemic fungal infection, herpes simplex keratitis, hypersensitivity",
     "Relative: active TB, uncontrolled diabetes or hypertension, peptic ulcer, osteoporosis, psychosis, recent live vaccines, pregnancy (prefer lowest dose)"],
 ix=["Enzyme inducers (rifampicin, phenytoin, carbamazepine) lower steroid levels — dose may need doubling",
     "CYP3A4 inhibitors (ketoconazole, ritonavir) raise levels",
     "NSAIDs: GI ulcer risk",
     "Diuretics/amphotericin B: hypokalaemia",
     "Live vaccines: avoid with immunosuppressive doses"],
 mon=["Baseline: weight, BP, glucose, lipids, electrolytes, eye exam, TB screen, bone density (if long-term), stool for strongyloides in endemic areas",
      "Follow-up: BP, weight, glucose, electrolytes regularly; eye exam every 6–12 months; bone density annually if long-term",
      "Prevention: calcium + vitamin D, bisphosphonate if long-term (≥3 months, ≥7.5 mg/day), PPI if ulcer risk, deworming (albendazole) in endemic areas"],
 preg="Prednisolone is mostly inactivated by placental 11β-HSD2, so it is the preferred steroid in pregnancy; slight risk of cleft palate with first-trimester use and growth restriction with high doses. Compatible with breastfeeding.",
 viva=["Know the equivalence table",
       "Morning single dose; alternate-day dosing to spare the HPA axis",
       "Prophylaxis for long-term use: calcium, vitamin D, bisphosphonate, PPI if needed, deworming",
       "Prednisone is a prodrug; prednisolone is active (use in liver disease)",
       "Placenta inactivates prednisolone — preferred in pregnancy (dexamethasone and betamethasone cross)"],
 src=f"{W} ch.13 (Systemic corticosteroids); {K} ch.8 (Oral and injectable steroids), Table 8.2"),

dict(name="Deflazacort", group="Oral · VII Systemic corticosteroids",
 cls="Intermediate-acting oxazoline derivative of prednisolone (prodrug)",
 moa=["Converted to its active metabolite (21-desacetyl-deflazacort), which acts on the glucocorticoid receptor like prednisolone"],
 pk=["Rapidly absorbed and activated; half-life of the active metabolite about 1–2 h but biological effect 12–36 h",
     "Equivalence: 6 mg deflazacort ≈ 5 mg prednisolone (ratio about 1.2 : 1)",
     "Little mineralocorticoid effect"],
 uses=["Same indications as prednisolone — used in India as an alternative in children and patients with diabetes or bone loss concerns",
       "Approved in the USA for Duchenne muscular dystrophy"],
 dose=["Usual 0.5–1.2 mg/kg/day as a single morning dose (6 mg replaces 5 mg prednisolone)",
       "Tablets 6, 12, 18, 24, 30 mg"],
 ae=["Same class side effects as prednisolone",
     "It is claimed (in Khopkar and product data) to have fewer effects on bone, glucose and weight, but this advantage is modest and inconsistent",
     "Weight gain and Cushingoid features are still seen"],
 ci=["Same as other systemic steroids"],
 ix=["CYP3A4 inducers lower levels; CYP3A4 inhibitors raise levels"],
 mon=["Same as prednisolone"],
 preg="Limited data; prednisolone is preferred in pregnancy.",
 viva=["6 mg deflazacort = 5 mg prednisolone",
       "Claimed bone- and glucose-sparing, but it still causes the full range of steroid side effects and is more expensive (Khopkar)"],
 src=f"{K} ch.8 (Oral and injectable steroids); not covered in {W}",
 note="Deflazacort is not covered in Wolverton; Khopkar and product data were used."),

dict(name="Betamethasone (oral)", group="Oral · VII Systemic corticosteroids",
 cls="Long-acting fluorinated glucocorticoid (biological half-life 36–54 h)",
 moa=["Glucocorticoid receptor agonist like prednisolone, but much more potent and longer acting",
      "No mineralocorticoid effect"],
 pk=["Equivalence: 0.6 mg betamethasone ≈ 5 mg prednisolone (about 25 times hydrocortisone)",
     "Crosses the placenta (not inactivated by 11β-HSD2) — used to mature fetal lungs"],
 uses=["Oral mini-pulse (OMP): progressive/unstable vitiligo, spreading alopecia areata, extensive lichen planus",
       "General systemic steroid indications (less often than prednisolone)"],
 dose=["OMP (Pasricha regimen): 5 mg betamethasone (or dexamethasone) as a single morning dose on 2 consecutive days per week (adults); children 0.1 mg/kg on the same schedule",
       "Continue OMP for about 3–6 months for vitiligo, then taper",
       "Tablets 0.5 mg (and 1 mg in some brands)"],
 ae=["Same as systemic steroids; with OMP mainly weight gain, acne, insomnia, menstrual disturbance, mild Cushingoid features",
     "Long-acting steroids suppress the HPA axis more than prednisolone if given daily"],
 ci=["As for systemic steroids"],
 ix=["As for prednisolone"],
 mon=["Weight, BP, glucose during OMP"],
 preg="Crosses the placenta (used deliberately for fetal lung maturity); avoid for skin disease in pregnancy.",
 viva=["OMP — pulse dosing on 2 days a week reduces side effects but still stops disease activity",
       "Long-acting: more HPA suppression if given daily",
       "Not inactivated by the placenta (unlike prednisolone)"],
 src=f"{K} ch.8 (Table 8.2, OMP indications); {W} ch.13"),

dict(name="Methylprednisolone (oral)", group="Oral · VII Systemic corticosteroids",
 cls="Intermediate-acting glucocorticoid (biological half-life 12–36 h)",
 moa=["Glucocorticoid receptor agonist; slightly more potent than prednisolone",
      "Minimal mineralocorticoid effect"],
 pk=["Equivalence: 4 mg methylprednisolone ≈ 5 mg prednisolone",
     "Metabolised in the liver (CYP3A4)"],
 uses=["Oral alternative to prednisolone (when less fluid retention is desired)",
       "Oral step-down after IV methylprednisolone pulses",
       "IV pulse use (pemphigus, SJS/TEN, pyoderma gangrenosum) — covered in the injectables slot"],
 dose=["Oral: 4–48 mg/day depending on condition (e.g. 0.8 mg/kg/day ≈ 1 mg/kg prednisolone)",
       "Tablets 4, 8, 16, 32 mg"],
 ae=["Same as systemic steroids; less fluid retention than prednisolone"],
 ci=["As for systemic steroids"],
 ix=["CYP3A4 inhibitors (ketoconazole, itraconazole, macrolides) raise levels; inducers lower them"],
 mon=["As for prednisolone"],
 preg="Partly inactivated by the placenta; prednisolone is usually preferred.",
 viva=["4 mg methylprednisolone = 5 mg prednisolone",
       "Less mineralocorticoid effect than prednisolone",
       "Used for IV pulse therapy (slot 3)"],
 src=f"{W} ch.13; {K} ch.8"),

# ---------------- VIII ANTIANDROGEN ----------------
dict(name="Finasteride", group="Oral · VIII Antiandrogen",
 cls="5α-reductase inhibitor (type II isoenzyme selective)",
 moa=["Inhibits type II 5α-reductase (found in hair follicles, prostate), blocking conversion of testosterone to the more potent dihydrotestosterone (DHT)",
      "Lowers serum DHT by about 70% and scalp DHT by about 60%",
      "Reverses miniaturisation of androgen-sensitive scalp follicles"],
 pk=["Well absorbed; metabolised in the liver (CYP3A4); half-life 5–6 h, but enzyme inhibition lasts longer"],
 uses=["Male androgenetic alopecia (vertex and mid-scalp) — approved at 1 mg",
       "Female pattern hair loss in post-menopausal women (off-label, higher doses 2.5–5 mg)",
       "Hirsutism (off-label, with contraception), frontal fibrosing alopecia (off-label)",
       "Benign prostatic hyperplasia (5 mg)"],
 dose=["Male AGA: 1 mg once daily; results take 3–6 months, assess at 12 months",
       "Must be continued — benefit is lost within about 12 months of stopping",
       "Topical finasteride 0.25% solution is available"],
 ae=["Sexual: decreased libido, erectile and ejaculatory dysfunction (about 1–2%; usually reversible)",
     "Gynaecomastia, breast tenderness",
     "Depression; 'post-finasteride syndrome' (persistent symptoms after stopping) is reported but unproven",
     "Lowers PSA by about 50% — double the measured PSA when screening for prostate cancer"],
 ci=["Women of childbearing potential (unless strict contraception) and pregnancy — risk of feminising a male fetus",
     "Pregnant women should not handle crushed or broken tablets",
     "Children"],
 ix=["No important interactions"],
 mon=["None routinely; record baseline PSA in men over 40–50"],
 preg="Contraindicated in pregnancy (old FDA category X) — causes hypospadias/ambiguous genitalia in male fetuses. Men on finasteride need no contraception (semen levels are negligible).",
 viva=["Type II 5α-reductase inhibitor; dutasteride blocks types I and II",
       "1 mg for hair; 5 mg for prostate",
       "PSA is halved — double it",
       "Pregnant women should not handle broken tablets"],
 src=f"{W} ch.34 (Antiandrogens and androgen inhibitors); {K} (Miscellaneous agents)"),

dict(name="Dutasteride", group="Oral · VIII Antiandrogen",
 cls="Dual 5α-reductase inhibitor (types I and II)",
 moa=["Inhibits both type I (sebaceous glands, skin) and type II (hair follicle, prostate) 5α-reductase",
      "Lowers serum DHT by more than 90% — more than finasteride"],
 pk=["Very long half-life (about 5 weeks); effect persists for months after stopping",
     "Metabolised by CYP3A4"],
 uses=["Male androgenetic alopecia (approved in Korea/Japan at 0.5 mg; off-label elsewhere) — slightly more effective than finasteride",
       "Female pattern hair loss in post-menopausal women (off-label)",
       "Mesotherapy (intradermal dutasteride) for AGA",
       "Benign prostatic hyperplasia"],
 dose=["0.5 mg once daily (some use 0.5 mg 2–3 times a week); soft capsules should not be opened"],
 ae=["Sexual side effects (similar to or slightly more than finasteride)",
     "Gynaecomastia, breast tenderness",
     "PSA lowered by about 50%"],
 ci=["Women of childbearing potential and pregnancy; children",
     "Men should not donate blood for 6 months after the last dose (long half-life)"],
 ix=["Strong CYP3A4 inhibitors (ritonavir, ketoconazole) raise levels"],
 mon=["Baseline PSA in older men"],
 preg="Contraindicated (old FDA category X). Pregnant women should not handle leaking capsules.",
 viva=["Blocks both isoenzymes — more DHT suppression than finasteride",
       "Very long half-life — no blood donation for 6 months after stopping"],
 src=f"{W} ch.34; {K} (Miscellaneous agents)"),

# ---------------- IX ANTIHISTAMINES ----------------
dict(name="Hydroxyzine", group="Oral · IX Antihistaminics",
 cls="First-generation (sedating) H1 antihistamine; piperazine class",
 moa=["Inverse agonist at H1 receptors (stabilises the inactive form)",
      "Crosses the blood–brain barrier → sedation and anxiolysis",
      "Also anticholinergic, antiserotonergic and mild antiemetic effects"],
 pk=["Well absorbed; onset 15–30 min; metabolised in the liver to cetirizine (active metabolite)",
     "Half-life about 20 h in adults (shorter in children, longer in elderly)"],
 uses=["Pruritus of atopic dermatitis and other itchy dermatoses — night-time sedation helps",
       "Urticaria (usually as a night-time add-on to a non-sedating antihistamine)",
       "Anxiety; pre-procedure sedation"],
 dose=["Adults: 10–25 mg at night, up to 25 mg three to four times daily (max 100 mg/day; lower in elderly)",
       "Children: about 1–2 mg/kg/day in divided doses (syrup 10 mg/5 mL)"],
 ae=["Sedation, impaired driving and school performance, next-day hangover",
     "Anticholinergic: dry mouth, urinary retention, constipation, blurred vision, confusion in elderly",
     "QT prolongation at high doses (caution)",
     "Paradoxical excitation in children"],
 ci=["Prolonged QT; early pregnancy",
     "Caution: glaucoma, prostatic hypertrophy, elderly, hepatic impairment, porphyria"],
 ix=["Alcohol and CNS depressants (additive sedation)",
     "Other QT-prolonging drugs; other anticholinergics"],
 mon=["None"],
 preg="Avoid in early pregnancy (EMA advice); cetirizine/loratadine preferred. Avoid in breastfeeding.",
 viva=["First-generation, crosses BBB",
       "Its metabolite is cetirizine",
       "Useful at night for itch-related sleep loss, but sedation lowers daytime performance",
       "Guidelines recommend second-generation antihistamines as first line for urticaria"],
 src=f"{W} ch.32 (Antihistamines); {K} (Antihistamines and mast cell stabilizers)"),

dict(name="Cetirizine", group="Oral · IX Antihistaminics",
 cls="Second-generation H1 antihistamine (piperazine; carboxylic acid metabolite of hydroxyzine)",
 moa=["Selective peripheral H1 inverse agonist",
      "Some anti-inflammatory effect: reduces eosinophil migration and late-phase reactions"],
 pk=["Rapid onset (within 1 h); half-life about 8–10 h; once daily",
     "Excreted mostly unchanged in urine — halve the dose in renal impairment",
     "Levocetirizine is the active R-enantiomer (5 mg = 10 mg cetirizine)"],
 uses=["Chronic spontaneous and inducible urticaria (first line)",
       "Allergic rhinitis, atopic dermatitis itch (limited), insect bite reactions, mastocytosis"],
 dose=["Adults: 10 mg once daily; in urticaria may be increased up to 4 times (40 mg/day) per guidelines",
       "Children 6 months–2 years: 2.5 mg daily; 2–6 years: 2.5 mg twice daily or 5 mg daily; over 6 years: 10 mg daily"],
 ae=["Mild sedation (more than fexofenadine and loratadine; about 10%)",
     "Headache, dry mouth, fatigue"],
 ci=["Severe renal impairment (creatinine clearance under 10 mL/min)",
     "Hypersensitivity to hydroxyzine or piperazines"],
 ix=["Alcohol and CNS depressants (mild additive effect)"],
 mon=["None"],
 preg="One of the preferred antihistamines in pregnancy (with loratadine); compatible with breastfeeding (watch infant drowsiness).",
 viva=["Metabolite of hydroxyzine",
       "Renally excreted — adjust in kidney disease",
       "Most sedating of the second-generation group",
       "Updosing up to 4 times in urticaria"],
 src=f"{W} ch.32; {K} (Antihistamines)"),

dict(name="Fexofenadine", group="Oral · IX Antihistaminics",
 cls="Second-generation H1 antihistamine (active metabolite of terfenadine)",
 moa=["Selective peripheral H1 inverse agonist; a P-glycoprotein substrate, so it is pumped out of the brain — truly non-sedating"],
 pk=["Onset 1–2 h; half-life about 14 h",
     "Excreted mostly unchanged in faeces and urine; little liver metabolism, so no QT problems (unlike its parent terfenadine)",
     "Fruit juices (grapefruit, orange, apple) reduce absorption via OATP — take with water"],
 uses=["Chronic urticaria, allergic rhinitis",
       "Preferred in pilots, drivers and people needing no sedation"],
 dose=["Adults: 120–180 mg once daily; urticaria may be updosed up to 360–720 mg/day (Wolverton mentions 180–360 mg)",
       "Children 6–11 years: 30 mg twice daily"],
 ae=["Headache; generally very well tolerated", "No significant sedation even at high doses"],
 ci=["Hypersensitivity"],
 ix=["Antacids with aluminium/magnesium and fruit juices reduce absorption",
     "Erythromycin and ketoconazole raise levels (not clinically important)"],
 mon=["None"],
 preg="Less data than cetirizine or loratadine; use those first in pregnancy.",
 viva=["Least sedating antihistamine (P-gp efflux)",
       "Metabolite of terfenadine, but without its QT toxicity",
       "Avoid fruit juice at the time of dosing"],
 src=f"{W} ch.32; {K} (Antihistamines)"),

dict(name="Loratadine", group="Oral · IX Antihistaminics",
 cls="Second-generation H1 antihistamine (tricyclic, piperidine)",
 moa=["Selective peripheral H1 inverse agonist; poor CNS penetration"],
 pk=["Prodrug; metabolised in the liver (CYP3A4, 2D6) to desloratadine (active, longer acting)",
     "Half-life (with metabolite) about 27 h; once daily"],
 uses=["Urticaria, allergic rhinitis, itch"],
 dose=["Adults: 10 mg once daily (updosing to 40 mg in urticaria)",
       "Children 2–12 years: 5 mg daily (under 30 kg), 10 mg (over 30 kg)",
       "Liver impairment: 10 mg on alternate days"],
 ae=["Headache, fatigue, dry mouth; minimal sedation at standard dose"],
 ci=["Hypersensitivity; caution in severe liver disease"],
 ix=["CYP3A4 inhibitors (ketoconazole, erythromycin, cimetidine) raise levels without important QT effects"],
 mon=["None"],
 preg="Preferred antihistamine in pregnancy (with cetirizine); compatible with breastfeeding.",
 viva=["Prodrug of desloratadine",
       "Safe in pregnancy (most data)",
       "Non-sedating at standard dose"],
 src=f"{W} ch.32; {K} (Antihistamines)"),

# ---------------- X PHOTOCHEMOTHERAPY ----------------
dict(name="Methoxsalen (8-MOP, oral)", group="Oral · X Photochemotherapy",
 cls="Psoralen (furocoumarin) photosensitiser; used with UVA (PUVA)",
 moa=["Intercalates between DNA base pairs; after UVA exposure it forms monofunctional adducts and then cross-links between DNA strands",
      "Result: inhibits DNA synthesis and keratinocyte proliferation; apoptosis of activated T cells; immunosuppression",
      "In vitiligo: stimulates melanocyte proliferation and migration and melanogenesis"],
 pk=["Absorption variable; peak photosensitivity at about 1–2 h (liquid capsules about 1 h, crystalline about 2 h); lasts about 8 h",
     "Large first-pass metabolism; food slows absorption"],
 uses=["Psoriasis (plaque, palmoplantar, erythrodermic in selected cases)",
       "Vitiligo (generalised), mycosis fungoides (early stage), chronic hand eczema, atopic dermatitis",
       "Lichen planus, polymorphous light eruption (prophylactic hardening), urticaria pigmentosa, generalised granuloma annulare, morphoea"],
 dose=["0.4–0.6 mg/kg orally, 1–2 h before UVA exposure (10 mg tablets/capsules)",
       "Treatments 2–3 times a week, never on consecutive days (phototoxic reaction peaks at 48–72 h)",
       "UVA dose started by skin type or minimal phototoxic dose (MPD), increased gradually",
       "5-MOP (bergapten) 1.2 mg/kg is an alternative with less nausea and phototoxicity"],
 ae=["Nausea (most common), dizziness, headache",
     "Phototoxic reaction (erythema, blistering, pain); PUVA itch; PUVA lentigines",
     "Long-term: photoageing, non-melanoma skin cancer (especially SCC, dose-dependent, highest in genitals of men — shield them), melanoma (late)",
     "Cataract — eye protection with UVA-blocking glasses for 12–24 h after the dose",
     "Hepatotoxicity (rare)"],
 ci=["Absolute: pregnancy (relative in many texts), lupus erythematosus, xeroderma pigmentosum, porphyria and other photosensitive disorders, melanoma history, children under 10–12 years",
     "Relative: previous arsenic or ionising radiation, non-melanoma skin cancer, cataract, liver disease, immunosuppression (cyclosporine), heavy sun damage"],
 ix=["Other photosensitising drugs (tetracyclines, thiazides, fluoroquinolones, phenothiazines) increase phototoxicity",
     "Cyclosporine: much higher skin cancer risk",
     "Phenytoin and other enzyme inducers lower psoralen levels"],
 mon=["Baseline eye exam, ANA, LFT (if indicated); yearly eye and skin examination",
      "Record cumulative UVA dose and number of treatments (risk of SCC rises above about 200 treatments)"],
 preg="Avoid (old FDA category C); no clear teratogenicity seen, but use NB-UVB instead.",
 viva=["DNA cross-linking after UVA activation",
       "Dose 0.6 mg/kg, 2 h before UVA",
       "Never on consecutive days — phototoxicity peaks at 48–72 h",
       "Eye protection for 24 h; shield male genitalia",
       "Main long-term risk: SCC"],
 src=f"{W} ch.23 (PUVA photochemotherapy); {K} (Psoralens, PUVA and phototherapy)"),

# ---------------- XI MISCELLANEOUS ----------------
dict(name="Nicotinamide (niacinamide, oral)", group="Oral · XI Miscellaneous",
 cls="Amide form of vitamin B3",
 moa=["Precursor of NAD⁺ — restores cellular energy after UV damage, improving DNA repair",
      "Prevents UV-induced immunosuppression",
      "Anti-inflammatory: inhibits neutrophil chemotaxis, mast-cell degranulation and PARP; reduces sebum"],
 pk=["Well absorbed; does not cause flushing (unlike nicotinic acid/niacin)"],
 uses=["Chemoprevention of non-melanoma skin cancer in high-risk patients (ONTRAC trial: 23% fewer new cancers)",
       "Bullous pemphigoid (with tetracycline/doxycycline)",
       "Acne and rosacea (oral and topical), pellagra",
       "Other neutrophilic or inflammatory dermatoses: linear IgA, dermatitis herpetiformis (adjunct), granuloma annulare, necrobiosis lipoidica"],
 dose=["Skin cancer chemoprevention: 500 mg twice daily",
       "Bullous pemphigoid: 500 mg three times daily (up to 2 g/day) with doxycycline/tetracycline",
       "Pellagra: 100 mg every 6 h until symptoms resolve, then maintenance"],
 ae=["Generally very safe: mild GI upset, headache",
     "At very high doses (above 3 g/day): hepatotoxicity"],
 ci=["Hypersensitivity; caution in liver disease at high doses"],
 ix=["Carbamazepine and primidone levels may rise"],
 mon=["None at usual doses"],
 preg="Safe at dietary/standard supplement doses.",
 viva=["Nicotinamide does not cause flushing — nicotinic acid does",
       "ONTRAC trial: 500 mg twice daily reduces new skin cancers",
       "Nicotinamide + tetracycline for bullous pemphigoid"],
 src=f"{W} ch.40 (Miscellaneous systemic drugs); {K} (Vitamins and trace elements)"),

dict(name="Zinc acetate (oral zinc)", group="Oral · XI Miscellaneous",
 cls="Trace element supplement (zinc salt)",
 moa=["Zinc is a cofactor for over 300 enzymes — needed for epithelial repair, immune function and wound healing",
      "Anti-inflammatory: inhibits neutrophil chemotaxis and TNF-α; reduces sebum and C. acnes inflammation",
      "Immunomodulatory — boosts cell-mediated immunity (used in warts and leishmaniasis)"],
 pk=["Absorbed in the small intestine; food (phytates), iron and calcium reduce absorption",
     "Zinc acetate and gluconate are better tolerated than zinc sulfate"],
 uses=["Acrodermatitis enteropathica (inherited — lifelong) and acquired zinc deficiency",
       "Acne (modest benefit), hidradenitis suppurativa (adjunct), rosacea",
       "Viral warts (immunomodulation), alopecia areata (in deficiency), leg ulcers in deficient patients",
       "Wilson disease (zinc acetate approved — blocks copper absorption)"],
 dose=["Acrodermatitis enteropathica: 1–3 mg/kg/day of elemental zinc",
       "Adults (acne/warts): about 10 mg/kg/day zinc sulfate (up to 600 mg/day) in divided doses, or 30–90 mg elemental zinc/day",
       "Wilson disease: zinc acetate 50 mg elemental zinc three times daily",
       "Check how much elemental zinc a tablet gives: zinc acetate ≈ 30%, zinc sulfate ≈ 23%, zinc gluconate ≈ 14%"],
 ae=["Nausea, epigastric pain, metallic taste (take with food if needed)",
     "Long-term high doses: copper deficiency → anaemia, neutropenia, neuropathy",
     "Lowers HDL"],
 ci=["Hypersensitivity; caution in copper deficiency"],
 ix=["Reduces absorption of tetracyclines, fluoroquinolones and dolutegravir — separate by at least 2 h",
     "Iron and calcium compete for absorption",
     "Penicillamine absorption reduced"],
 mon=["Serum zinc and alkaline phosphatase (zinc-dependent) in deficiency; copper level and CBC on long courses"],
 preg="Safe at recommended doses.",
 viva=["Acrodermatitis enteropathica — SLC39A4 (ZIP4) mutation; triad of periorificial and acral dermatitis, alopecia and diarrhoea; responds dramatically to zinc",
       "Chronic high-dose zinc causes copper deficiency",
       "Separate zinc from tetracyclines and dolutegravir"],
 src=f"{W} ch.40 (zinc sulfate); {K} (Vitamins and trace elements)"),

dict(name="Colchicine", group="Oral · XI Miscellaneous",
 cls="Alkaloid from Colchicum autumnale; anti-mitotic, anti-inflammatory",
 moa=["Binds tubulin and prevents microtubule polymerisation",
      "This blocks neutrophil migration, adhesion and degranulation, and inflammasome (NLRP3) activation",
      "Also an anti-mitotic (metaphase arrest) at higher concentrations"],
 pk=["Absorbed in the gut; enterohepatic circulation; metabolised by CYP3A4 and pumped out by P-gp",
     "Narrow therapeutic index"],
 uses=["Behçet disease (mucocutaneous ulcers, erythema nodosum)",
       "Leukocytoclastic vasculitis (chronic cutaneous), urticarial vasculitis",
       "Recurrent aphthous stomatitis, Sweet syndrome, erythema nodosum leprosum (adjunct)",
       "Dermatitis herpetiformis, epidermolysis bullosa acquisita, linear IgA, palmoplantar pustulosis",
       "Familial Mediterranean fever, gout"],
 dose=["0.5–0.6 mg once to three times daily (usually 0.5 mg twice daily; Wolverton lists 0.6 mg twice daily)",
       "Reduce dose in renal/hepatic impairment or the elderly"],
 ae=["GI (the commonest, dose-limiting): diarrhoea, nausea, abdominal pain — start low",
     "Myelosuppression, myopathy and neuropathy (especially with renal impairment or interacting drugs)",
     "Overdose is often fatal (above 0.8 mg/kg): multiorgan failure, alopecia in survivors",
     "Reversible azoospermia"],
 ci=["Severe renal or hepatic impairment",
     "Combination with strong CYP3A4 or P-gp inhibitors in patients with renal or hepatic impairment"],
 ix=["Clarithromycin, erythromycin, ketoconazole, itraconazole, ritonavir, cyclosporine, verapamil, diltiazem: raise colchicine levels → fatal toxicity reported",
     "Statins and fibrates: myopathy"],
 mon=["CBC, renal function, LFT and CK periodically on long-term use"],
 preg="Can be continued in pregnancy for familial Mediterranean fever (old FDA category C); generally avoid for skin disease. Compatible with breastfeeding.",
 viva=["Microtubule inhibitor → neutrophil inhibitor",
       "Main use: Behçet and cutaneous vasculitis",
       "Diarrhoea is the dose-limiting side effect",
       "Clarithromycin/cyclosporine interaction can be fatal"],
 src=f"{W} ch.40; {K} (Miscellaneous agents)"),

dict(name="Propranolol", group="Oral · XI Miscellaneous",
 cls="Non-selective β-adrenergic blocker",
 moa=["In infantile haemangioma: early vasoconstriction (lighter colour, softer within days), then inhibition of angiogenic signals (VEGF, bFGF) and induction of apoptosis of endothelial cells",
      "Also blocks the renin–angiotensin system in haemangioma tissue"],
 pk=["Well absorbed; large first-pass metabolism; lipophilic (crosses BBB); half-life 3–6 h",
     "Hypoglycaemia risk: blocks glycogenolysis and masks its warning signs"],
 uses=["Infantile haemangioma — first-line systemic therapy: ulcerated, function-threatening (eye, airway, ear), disfiguring (face, nose, lip), segmental (PHACE), or multiple with liver involvement",
       "Best started early (proliferative phase, ideally before 5 months of age)",
       "Off-label: performance anxiety, rosacea flushing, essential tremor"],
 dose=["Infantile haemangioma: start 0.5–1 mg/kg/day in 2–3 divided doses, increase over 1–2 weeks to 2–3 mg/kg/day (Wolverton: 1–3 mg/kg/day divided twice or three times daily)",
       "Give with or just after feeds (avoid hypoglycaemia); stop during illness or poor feeding",
       "Continue for at least 6 months (often until 12 months of age), then taper",
       "Oral solution 20 mg/5 mL or 40 mg/5 mL; in India often prepared from tablets"],
 ae=["Hypoglycaemia (especially with poor feeding or vomiting) — the most important in infants",
     "Bradycardia, hypotension",
     "Bronchospasm/wheeze",
     "Sleep disturbance, cold hands and feet, GI upset",
     "Rebound growth of haemangioma after stopping"],
 ci=["Cardiogenic shock, sinus bradycardia, heart block above first degree, heart failure",
     "Bronchial asthma or bronchospasm, hypoglycaemia tendency",
     "Premature infants under 5 weeks corrected age, weight under 2 kg (caution)",
     "PHACE syndrome with significant brain vessel abnormalities — careful assessment before starting (stroke risk)"],
 ix=["Other antihypertensives and calcium-channel blockers (verapamil — bradycardia)",
     "Insulin and oral hypoglycaemics (masking of hypoglycaemia)",
     "CYP2D6 inhibitors raise levels"],
 mon=["Baseline: history and examination of heart and lungs, heart rate and BP; ECG if bradycardia or family history of arrhythmia",
      "Heart rate and BP 1–2 h after the first dose and after each dose increase",
      "Counsel parents on hypoglycaemia signs"],
 preg="Used in pregnancy for maternal indications (may cause fetal growth restriction and neonatal bradycardia/hypoglycaemia). Compatible with breastfeeding.",
 viva=["First-line systemic treatment for problematic infantile haemangioma",
       "Give with feeds — hypoglycaemia is the main risk",
       "Check heart rate and BP after starting and after dose increases",
       "Screen for PHACE syndrome in large segmental facial haemangiomas"],
 src=f"{W} ch.70 (Dermatologic drug therapy in children), ; {K} (Miscellaneous agents)"),

dict(name="Pregabalin + Nortriptyline", group="Oral · XI Miscellaneous",
 cls="Fixed-dose combination: gabapentinoid (pregabalin) + tricyclic antidepressant (nortriptyline)",
 moa=["Pregabalin binds the α2δ subunit of voltage-gated calcium channels in nerve endings → less release of glutamate, substance P and noradrenaline → reduces neuropathic pain and neuropathic itch",
      "Nortriptyline (secondary-amine TCA, metabolite of amitriptyline) blocks reuptake of noradrenaline (and serotonin) → strengthens descending pain-inhibiting pathways; fewer anticholinergic effects than amitriptyline",
      "The two act at different points, so lower doses of each can be used"],
 pk=["Pregabalin: well absorbed, not metabolised, excreted by kidneys — reduce in renal impairment; no CYP interactions",
     "Nortriptyline: metabolised by CYP2D6; long half-life (about 30 h)"],
 uses=["Post-herpetic neuralgia (PHN)",
       "Neuropathic itch: brachioradial pruritus, notalgia paraesthetica, post-zoster itch, scalp dysaesthesia",
       "Leprosy neuritis-related neuropathic pain, diabetic neuropathy",
       "Pregabalin alone: uraemic pruritus, chronic prurigo, burning mouth (adjunct)"],
 dose=["Common Indian FDC: pregabalin 75 mg + nortriptyline 10 mg, one tablet at bedtime; may increase to twice daily",
       "Pregabalin alone: start 75 mg twice daily (or 75 mg at night), up to 150–300 mg/day (max 600 mg/day); halve in renal impairment",
       "Start low and go slow in the elderly; taper slowly when stopping"],
 ae=["Pregabalin: dizziness, drowsiness, weight gain, peripheral oedema, blurred vision; misuse and dependence potential; withdrawal on abrupt stop",
     "Nortriptyline: dry mouth, constipation, urinary retention, postural hypotension, sedation",
     "Nortriptyline: arrhythmias and QT prolongation; overdose is dangerous (cardiotoxic)",
     "Suicidal thoughts (antidepressant class warning)"],
 ci=["Recent myocardial infarction, heart block or arrhythmia (TCA)",
     "Use of MAO inhibitors within 14 days",
     "Narrow-angle glaucoma, urinary retention, severe liver disease",
     "Caution: elderly (falls), renal impairment, history of substance misuse, suicidal risk"],
 ix=["Other CNS depressants (alcohol, opioids, benzodiazepines): more sedation and respiratory depression",
     "SSRIs, tramadol, linezolid with TCA: serotonin syndrome",
     "CYP2D6 inhibitors (fluoxetine, paroxetine, terbinafine) raise nortriptyline levels",
     "Other QT-prolonging and anticholinergic drugs"],
 mon=["ECG before starting in patients over 40–50 or with cardiac history",
      "Renal function for pregabalin dosing; mood and suicidal ideation; weight"],
 preg="Avoid in pregnancy unless clearly needed (possible malformation signal with pregabalin; TCA neonatal withdrawal). Avoid in breastfeeding.",
 viva=["Pregabalin: α2δ calcium-channel ligand",
       "Nortriptyline: fewer anticholinergic effects than amitriptyline",
       "Terbinafine (CYP2D6 inhibitor) raises nortriptyline levels",
       "Used for PHN and neuropathic itch"],
 src=f"{W} ch.35 (Psychotropic agents) and ch.39 (Drugs for the skinternist; pregabalin); {K} (Miscellaneous agents)"),

dict(name="STI kits (NACO colour-coded kits)", group="Oral · XI Miscellaneous",
 cls="Pre-packed syndromic treatment kits supplied free under the National AIDS Control Programme (NACO) — 7 colour-coded kits",
 moa=["Syndromic case management: treats all the common organisms that cause a given syndrome at the first visit, without waiting for lab tests",
      "Each kit is a single complete course, which improves adherence; partners get the same kit"],
 pk=["See each component drug (azithromycin, cefixime, secnidazole, fluconazole, benzathine penicillin, doxycycline, acyclovir, metronidazole)"],
 uses=["Kit 1 — Grey: urethral discharge, anorectal discharge, cervicitis → azithromycin 1 g single dose + cefixime 400 mg single dose",
       "Kit 2 — Green: vaginal discharge (vaginitis: trichomonas, bacterial vaginosis, candida) → secnidazole 2 g single dose + fluconazole 150 mg single dose",
       "Kit 3 — White: genital ulcer disease, non-herpetic (syphilis, chancroid) → benzathine penicillin 2.4 MU IM single dose (with sterile water and syringe) + azithromycin 1 g single dose",
       "Kit 4 — Blue: genital ulcer disease, non-herpetic, for penicillin allergy → doxycycline 100 mg twice daily × 15 days + azithromycin 1 g single dose",
       "Kit 5 — Red: genital ulcer disease, herpetic → acyclovir 400 mg three times daily × 7 days",
       "Kit 6 — Yellow: lower abdominal pain (PID) → cefixime 400 mg single dose + metronidazole 400 mg twice daily × 14 days + doxycycline 100 mg twice daily × 14 days",
       "Kit 7 — Black: inguinal bubo (LGV, chancroid) → doxycycline 100 mg twice daily × 21 days + azithromycin 1 g single dose"],
 dose=["Given as the full kit to the patient, with an identical kit (or appropriate treatment) for each partner",
       "Pregnancy: avoid doxycycline kits (blue, black, yellow) — use erythromycin/azithromycin alternatives as per NACO; secnidazole avoided in the first trimester"],
 ae=["As for the individual drugs: GI upset (azithromycin, metronidazole, doxycycline), disulfiram-like reaction (metronidazole/secnidazole with alcohol), Jarisch–Herxheimer reaction and anaphylaxis risk (benzathine penicillin), photosensitivity (doxycycline)"],
 ci=["Kit 3 (white): penicillin allergy → use kit 4 (blue)",
     "Doxycycline kits in pregnancy, breastfeeding and children under 8",
     "Avoid alcohol with kits containing metronidazole or secnidazole"],
 ix=["See component drugs"],
 mon=["Follow-up at 7 days (14 days for ulcers and PID) to check response",
      "Offer HIV and syphilis testing, condoms, partner notification and counselling (the '4 Cs': compliance, counselling, condoms, contact tracing)"],
 preg="Adjust in pregnancy (no doxycycline); syphilis in pregnancy → benzathine penicillin (desensitise if allergic).",
 viva=["Know each colour and its contents — a favourite viva question",
       "Grey = urethral discharge; Green = vaginal discharge; White = non-herpetic ulcer; Blue = non-herpetic ulcer with penicillin allergy; Red = herpetic ulcer; Yellow = lower abdominal pain; Black = bubo",
       "Syndromic approach — treat the patient and partner at the first visit",
       "4 Cs of STI management"],
 src="NACO National Guidelines on Prevention, Management and Control of RTI including STI (colour-coded kits); not covered in Wolverton or Khopkar",
 note="The kit contents follow NACO's standard 7-kit scheme. The exam list names 5 colours (white, green, blue, yellow, black), but all 7 are included because grey and red are commonly asked too. Please check against the latest NACO technical guidelines in case your hospital supply differs."),
]
