# Viva slot V1 (part A): bacterial infections, leprosy, cutaneous TB, viral infections
DYP = "DYP Survival Guide for PG Dermatology Exam"; IA = "IADVL Textbook of Dermatology 5e"
D = [
dict(case="Impetigo", src=f"{DYP} (Bacterial infections); {IA} ch.15",
 qa=[
 ("What is impetigo and what are its types?", ["Contagious superficial (subcorneal) bacterial infection of the epidermis, commonest in children", "Non-bullous impetigo (impetigo contagiosa, ~70%): S. aureus (most), Streptococcus pyogenes; honey-coloured crusts", "Bullous impetigo: S. aureus phage group II (type 71) producing exfoliative toxins A and B that cleave desmoglein 1", "Ecthyma is the deeper (ulcerative) form"]),
 ("Why are the crusts honey-coloured?", ["Dried serum from ruptured thin-roofed vesicopustules"]),
 ("Where is the split in bullous impetigo and why?", ["Subcorneal/granular layer — exfoliative toxin cleaves desmoglein 1 (same target as pemphigus foliaceus and SSSS)"]),
 ("Differential diagnosis?", ["Non-bullous: eczema herpeticum/herpes simplex, impetiginised eczema, tinea faciei, scabies with pyoderma, pemphigus foliaceus, seborrhoeic dermatitis", "Bullous: bullous insect bite, chronic bullous disease of childhood, bullous pemphigoid, thermal burn, bullous fixed drug eruption, SSSS, bullous erythema multiforme"]),
 ("What is primary vs secondary impetigo (impetiginisation)?", ["Primary — on normal skin; secondary — on pre-existing dermatoses (eczema, scabies, pediculosis, insect bites, varicella)"]),
 ("Does impetigo scar?", ["No — it is superficial; may leave temporary hypo/hyperpigmentation; ecthyma scars"]),
 ("Complications?", ["Post-streptococcal glomerulonephritis (nephritogenic strains — not prevented by antibiotics); rheumatic fever is not associated with skin infection", "Cellulitis, lymphangitis, SSSS, sepsis, guttate psoriasis, scarlet fever"]),
 ("How will you investigate?", ["Usually clinical; Gram stain (Gram-positive cocci in clusters/chains) and pus culture with sensitivity in recurrent/extensive cases or suspected MRSA", "Urine for haematuria/proteinuria if streptococcal (PSGN watch)"]),
 ("Treatment of localised impetigo?", ["Remove crusts with soaks; topical mupirocin 2% or fusidic acid 2% three times daily for 5–7 days (ozenoxacin 1% twice daily for 5 days, retapamulin)"]),
 ("Treatment of extensive impetigo or bullous impetigo?", ["Oral antibiotics for 7 days: cloxacillin/flucloxacillin, cephalexin/cefadroxil, amoxicillin–clavulanate; macrolide or clindamycin in penicillin allergy; co-trimoxazole/doxycycline for MRSA (age >8 for doxycycline)"]),
 ("What is 'impetigo of Bockhart'?", ["Superficial staphylococcal folliculitis — small follicular pustules (not true impetigo)"]),
 ("How will you prevent recurrence?", ["Treat the underlying dermatosis, nasal carriage (mupirocin 5 days), hygiene, separate towels, exclude from school until 24–48 h after starting antibiotics or lesions crusted"]),
 ],
 spot=["Honey-coloured crusts on face around nose/mouth in a child", "Flaccid bullae with a hypopyon sign — bullous impetigo"]),

dict(case="Folliculitis", src=f"{DYP} (Bacterial infections — folliculitis, infundibular folliculitis, LMDF); {IA} ch.15",
 qa=[
 ("Define folliculitis.", ["Inflammation of the hair follicle (histologically inflammatory cells in the wall and ostium) producing a follicular papule or pustule; superficial (infundibulum) or deep (whole follicle)"]),
 ("Classify folliculitis.", ["Infective: bacterial (S. aureus — superficial/Bockhart, sycosis barbae; Gram-negative folliculitis in acne on long-term antibiotics; Pseudomonas hot-tub folliculitis), fungal (Malassezia, dermatophyte — Majocchi), viral (herpetic, molluscum), parasitic (Demodex)", "Non-infective: eosinophilic pustular folliculitis (Ofuji, HIV-associated), perforating folliculitis, acne keloidalis nuchae, pseudofolliculitis barbae, folliculitis decalvans, drug-induced (steroids, EGFR inhibitors), occupational (oil/tar)"]),
 ("What is sycosis barbae and how is it different from tinea barbae and pseudofolliculitis barbae?", ["Sycosis barbae: deep staphylococcal folliculitis of the beard, chronic, upper lip involved", "Tinea barbae: zoophilic dermatophyte, kerion-like boggy plaques, hairs easily pluckable, usually spares upper lip", "Pseudofolliculitis barbae: ingrown curly hairs after close shaving; not infective"]),
 ("What is hot-tub folliculitis?", ["Pseudomonas aeruginosa folliculitis 8–48 h after contaminated hot tub/swimming pool; pruritic follicular papulopustules on trunk under swimwear; self-limiting; ciprofloxacin if severe"]),
 ("What is Gram-negative folliculitis?", ["Pustules around nose/chin in acne patients on long-term tetracyclines (Klebsiella, Enterobacter, Proteus); treat with isotretinoin"]),
 ("What is follicular triad and tetrad?", ["Triad: acne conglobata, hidradenitis suppurativa, dissecting cellulitis of scalp", "Tetrad: triad + pilonidal sinus"]),
 ("Investigations?", ["Gram stain and culture of pustule; KOH for fungal; Demodex mount; biopsy for non-infective types; check for nasal carriage, diabetes in recurrent cases"]),
 ("Treatment?", ["Antiseptic washes (chlorhexidine/BPO), topical mupirocin/fusidic acid; oral cloxacillin/cephalexin for extensive; treat carriage", "Avoid occlusion, shaving with clean blade or stop shaving; specific therapy for non-bacterial types (e.g. indomethacin for eosinophilic pustular folliculitis, antifungal for Malassezia)"]),
 ("What is infundibular folliculitis?", ["Disseminate and recurrent infundibulofolliculitis — skin-coloured follicular papules on trunk in dark-skinned young men; non-infective; treated with isotretinoin, emollients, keratolytics"]),
 ("What is LMDF?", ["Lupus miliaris disseminatus faciei — reddish-brown papules on central face incl. eyelids; caseating granulomas; now considered granulomatous rosacea variant/separate entity; heals with pitted scars; doxycycline, isotretinoin, dapsone"]),
 ],
 spot=["Follicular pustules with central hair — folliculitis; tender nodule — furuncle"]),

dict(case="Furuncle and carbuncle", src=f"{DYP} (Bacterial infections — furuncle, carbuncle, recurrent furunculosis); {IA} ch.15",
 qa=[
 ("Define furuncle and carbuncle.", ["Furuncle (boil): acute deep necrotising infection of a hair follicle by S. aureus with perifollicular abscess, central necrotic core", "Carbuncle: confluent furuncles involving several adjacent follicles with multiple draining points (sieve-like), deeper, on nape/back/thighs, with fever and malaise"]),
 ("Risk factors?", ["Nasal/perineal carriage of S. aureus, diabetes, obesity, poor hygiene, friction and sweating, immunodeficiency (HIV, steroids), atopic dermatitis, iron deficiency, PVL-producing community MRSA, chronic granulomatous disease/hyper-IgE (recurrent)"]),
 ("Sites of predilection?", ["Hair-bearing areas exposed to friction: neck, face, axillae, buttocks, thighs; not on palms/soles (no follicles)"]),
 ("Why is a furuncle on the central face dangerous?", ["Danger triangle — spread via angular and ophthalmic veins to cavernous sinus (cavernous sinus thrombosis); avoid squeezing"]),
 ("Investigations in recurrent furunculosis?", ["Pus culture/sensitivity (MRSA, PVL), nasal/perineal/axillary swabs of patient and family, blood sugar, CBC, HIV, immunoglobulins/neutrophil function if childhood onset"]),
 ("Treatment?", ["Warm compresses; incision and drainage when fluctuant (main treatment for abscess)", "Antibiotics if large, multiple, cellulitis, fever, immunocompromised, central face: cloxacillin, cephalexin, amoxicillin–clavulanate; MRSA: co-trimoxazole, doxycycline, clindamycin, linezolid"]),
 ("Management of recurrent furunculosis (decolonisation)?", ["Nasal mupirocin twice daily × 5 days (monthly for some months), chlorhexidine 4% body washes, bleach baths, wash linen/towels hot, treat family carriers", "Long-term low-dose clindamycin 150 mg/day × 3 months, or rifampicin 600 mg/day × 10 days with another antistaphylococcal agent, or vitamin C (neutrophil function)"]),
 ("What is bacterial interference therapy?", ["Deliberate colonisation of nares with a non-virulent S. aureus strain (502A) to prevent recolonisation by virulent strains — historical"]),
 ("What is botryomycosis?", ["Chronic suppurative granulomatous bacterial infection (usually S. aureus) forming grains — mimics mycetoma/actinomycosis"]),
 ],
 spot=["Painful red nodule with central pus point on the buttock — furuncle"]),

dict(case="Ecthyma", src=f"{DYP} (Bacterial infections — ecthyma); {IA} ch.15",
 qa=[
 ("What is ecthyma?", ["Ulcerative pyoderma extending into the dermis, caused by Streptococcus pyogenes (± S. aureus); 'deep impetigo'", "Heals with scarring"]),
 ("Clinical features?", ["Vesicopustule on legs of children/elderly → thick adherent grey-yellow/brown-black crust; removal shows punched-out saucer-shaped ulcer with raised indurated margin; regional lymphadenopathy common; 0.5–3 cm"]),
 ("Predisposing factors?", ["Poor hygiene, malnutrition, insect bites/scabies, minor trauma, warm humid climate, diabetes, neglected excoriations, soldiers/travellers"]),
 ("Differential diagnosis?", ["Ecthyma gangrenosum (Pseudomonas, neutropenic), cutaneous anthrax, leishmaniasis, insect bite reaction, pyoderma gangrenosum, vasculitic ulcer, sporotrichosis, Buruli ulcer, tungiasis"]),
 ("What is ecthyma gangrenosum?", ["Pseudomonas aeruginosa septicaemia in immunocompromised/neutropenic patients — painless red macules → haemorrhagic bullae → necrotic ulcer with black eschar, anogenital/axillary; needs IV antipseudomonal therapy"]),
 ("Treatment?", ["Soaks to remove crust, topical mupirocin, oral penicillin/cloxacillin/cephalexin or macrolide for 10 days; treat underlying scabies/insect bites"]),
 ],
 spot=["Punched-out ulcer with adherent crust on shin — ecthyma"]),

dict(case="Erysipelas and cellulitis", src=f"{DYP} (Bacterial infections — erysipelas, cellulitis); {IA} ch.15",
 qa=[
 ("Difference between erysipelas and cellulitis?", ["Erysipelas: superficial dermis and lymphatics; raised, sharply demarcated, bright red, shiny plaque; mainly Streptococcus pyogenes; face and legs", "Cellulitis: deeper dermis and subcutis; ill-defined margins, not raised; S. pyogenes and S. aureus"]),
 ("What is Milian's ear sign?", ["Ear involvement in erysipelas (dermis) — cellulitis spares the pinna because it lacks subcutaneous tissue"]),
 ("Predisposing factors?", ["Breach of skin (tinea pedis/toe-web intertrigo — commonest portal), lymphoedema, venous insufficiency, obesity, diabetes, previous episodes, saphenous vein harvest, alcohol"]),
 ("Differential diagnosis?", ["Deep vein thrombosis, stasis dermatitis (often bilateral — 'red legs' are rarely bilateral cellulitis), contact dermatitis, gout, necrotising fasciitis, erythema nodosum, panniculitis, herpes zoster (early), Wells syndrome, insect bite"]),
 ("Red flags for necrotising fasciitis?", ["Pain out of proportion, rapid spread, woody induration, dusky/violaceous skin, bullae, crepitus, anaesthesia of skin, systemic toxicity, raised CK/LRINEC score — urgent surgical debridement"]),
 ("Investigations?", ["Usually clinical; CBC, CRP, blood culture if systemic, ASO/anti-DNase B, swab of portal of entry; Doppler to exclude DVT; imaging if abscess/necrotising infection suspected"]),
 ("Treatment?", ["Elevation, rest, analgesia, treat tinea pedis", "Oral penicillin V/amoxicillin (erysipelas) or cloxacillin/cephalexin (cellulitis) for 5–10 days; IV benzylpenicillin/ceftriaxone/cefazolin if severe; clindamycin or macrolide in allergy; add MRSA cover if purulent"]),
 ("How to prevent recurrent cellulitis?", ["Treat toe-web intertrigo and lymphoedema (compression); prophylactic penicillin V 250 mg twice daily or benzathine penicillin every 3–4 weeks for ≥2 episodes/year"]),
 ("Complications?", ["Lymphoedema (and vicious cycle of recurrence), abscess, necrotising fasciitis, septicaemia, glomerulonephritis, cavernous sinus thrombosis (facial)"]),
 ],
 spot=["Sharply demarcated, raised, shiny red plaque on face crossing to ear — erysipelas"]),

dict(case="Pitted keratolysis", src=f"{DYP} (Bacterial infections — pitted keratolysis); {IA} ch.15",
 qa=[
 ("What is pitted keratolysis and what causes it?", ["Superficial infection of the stratum corneum of soles (keratoma plantare sulcatum, ringed keratolysis)", "Kytococcus sedentarius (main), Dermatophilus congolensis, Corynebacterium, Actinomyces — produce keratin-degrading proteases"]),
 ("Clinical features?", ["Multiple 1–7 mm crateriform pits, coalescing into furrows, on pressure-bearing areas of soles (heel, ball, toe pads); worse when wet", "Hyperhidrosis and malodour (sulfur compounds — thiols, thioesters) are characteristic; sliminess; asymptomatic or sore"]),
 ("Predisposing factors?", ["Hyperhidrosis, occlusive footwear (soldiers, athletes, farmers), hot humid climate, barefoot walking in wet conditions"]),
 ("Diagnosis?", ["Clinical; dermoscopy shows pits with visible walls; Wood's lamp — coral-red fluorescence may be seen (corynebacteria)", "Histopathology: pits in stratum corneum with Gram-positive coccobacilli/filaments on PAS/Gram stain"]),
 ("Differential diagnosis?", ["Tinea pedis, plantar warts, punctate palmoplantar keratoderma, basal cell naevus syndrome pits, arsenical keratoses, callosities"]),
 ("Treatment and prevention?", ["Topical erythromycin/clindamycin/fusidic acid/mupirocin, benzoyl peroxide wash, topical azoles; treat hyperhidrosis (aluminium chloride, iontophoresis, botulinum toxin)", "Prevention: dry feet, absorbent cotton socks changed often, breathable shoes, antiperspirants"]),
 ],
 spot=["Crater-like pits on the sole with foul smell — pitted keratolysis"]),

dict(case="Erythrasma", src=f"{DYP} (Bacterial infections — erythrasma); {IA} ch.15",
 qa=[
 ("Causative organism?", ["Corynebacterium minutissimum (Gram-positive diphtheroid)"]),
 ("How does it present?", ["Well-defined reddish-brown, finely scaly, slightly wrinkled patches in groins, axillae, submammary folds; interdigital (4th web space) maceration — commonest form", "Usually asymptomatic or mild itch; generalised form in diabetics"]),
 ("Associations?", ["Diabetes mellitus (screen), obesity, hyperhidrosis, warm humid climate, poor hygiene, elderly, immunosuppression; may coexist with tinea/candida"]),
 ("Wood's lamp finding?", ["Coral-red fluorescence due to porphyrin (coproporphyrin III) — may be absent if recently washed"]),
 ("Differential diagnosis?", ["Tinea cruris (active scaly border, central clearing), intertriginous candidiasis (satellite pustules), inverse psoriasis, seborrhoeic dermatitis, pityriasis versicolor"]),
 ("Treatment?", ["Topical erythromycin, clindamycin, fusidic acid or azoles (miconazole, clotrimazole — also cover fungi) for 2 weeks; benzoyl peroxide wash", "Oral erythromycin 250 mg four times daily × 14 days or clarithromycin 1 g single dose for extensive disease"]),
 ("Other corynebacterial infections?", ["Pitted keratolysis, trichomycosis axillaris (yellow/red/black concretions on axillary hair — C. tenuis)"]),
 ],
 spot=["Brown patch in the groin with coral-red fluorescence on Wood's lamp — erythrasma"]),

dict(case="Hansen's disease (leprosy)", src=f"{DYP} (Long case — Hansen's disease); {IA} ch.138–149; NLEP 2025 revised regimen",
 qa=[
 ("What are the cardinal signs (WHO diagnostic criteria)?", ["At least one of: (1) definite loss of sensation in a pale (hypopigmented) or reddish skin patch; (2) thickened or enlarged peripheral nerve with loss of sensation and/or weakness of muscles supplied by it; (3) presence of acid-fast bacilli in slit-skin smear"]),
 ("Classify leprosy.", ["Ridley–Jopling (immunological spectrum): TT, BT, BB, BL, LL, plus indeterminate and pure neuritic", "Indian (IAL 1981): indeterminate, tuberculoid, borderline, lepromatous, pure neuritic", "WHO operational: PB vs MB", "NLEP revised (2025): PB = 1–5 lesions, no nerve involvement, smear negative; MB = >5 lesions, OR any nerve involvement, OR smear positive"]),
 ("Describe slit-skin smear technique and indices.", ["Pinch skin to blanch, 5 mm long 2–3 mm deep slit with No.15 blade, turn blade 90° and scrape, smear in circular manner, heat-fix, Ziehl–Neelsen (5% sulfuric acid decolourisation)", "Sites: ear lobes, eyebrows/forehead, chin, buttocks, active lesions (standard 4–6 sites)", "Bacteriological index (BI, Ridley logarithmic scale 0–6+), morphological index (% solid-staining bacilli — viability)"]),
 ("Histopathology across the spectrum?", ["TT: epithelioid granulomas reaching epidermis, Langhans cells, nerve destruction, AFB nil", "BT: granulomas with clear subepidermal zone may be absent, few bacilli", "BB: epithelioid cells without giant cells, moderate bacilli", "BL: lymphocytes and foamy macrophages", "LL: Grenz zone, foamy (Virchow/lepra) cells, globi, plenty of bacilli"]),
 ("Which nerves are thickened and how do you examine them?", ["Greater auricular, supraorbital, ulnar (most commonly), radial cutaneous, median, common peroneal (lateral popliteal), posterior tibial, sural, superficial peroneal", "Palpate for thickening, tenderness, consistency, nodularity, abscess; compare both sides; voluntary muscle testing and sensory testing (monofilament)"]),
 ("Differential diagnosis of a hypopigmented patch?", ["Pityriasis alba, pityriasis versicolor, nevus depigmentosus/anaemicus, vitiligo (early), post-inflammatory hypopigmentation, hypopigmented mycosis fungoides, sarcoidosis, PKDL — sensory loss distinguishes leprosy"]),
 ("Causes of thickened nerves other than leprosy?", ["Hereditary motor sensory neuropathies (CMT type 1, Dejerine–Sottas, Refsum), neurofibromatosis, amyloidosis, acromegaly, primary amyloidosis, CIDP, sarcoidosis, nerve tumours"]),
 ("What is MDT now (India)?", ["Since 1 April 2025 NLEP uses 3 drugs for both PB (6 months) and MB (12 months): adult rifampicin 600 mg + clofazimine 300 mg monthly supervised, clofazimine 50 mg + dapsone 100 mg daily; child 10–14 y: R 450, C 150 monthly, C 50 alternate days, D 50 daily; <10 y: R 10 mg/kg, C 100 mg monthly + 50 mg twice weekly, D 2 mg/kg"]),
 ("Lepra reactions — types and treatment?", ["Type 1 (reversal, cell-mediated, BT/BB/BL): existing lesions inflamed, new lesions, neuritis — prednisolone 40 mg/day tapered over 12–20 weeks", "Type 2 (ENL, immune complex, BL/LL): crops of tender nodules, fever, neuritis, iritis, orchitis — NSAIDs (mild), prednisolone, thalidomide (drug of choice for recurrent), clofazimine 300 mg/day max 12 weeks", "Lucio phenomenon (diffuse LL, Mexico) — necrotising vasculitis"]),
 ("Management of neuritis and disability?", ["Prednisolone for neuritis (silent neuritis too), splinting, physiotherapy; WHO disability grading 0/1/2; reconstructive surgery after 1 year of stable nerve function"]),
 ("Prevention of trophic ulcers — '4 S'?", ["See (inspect daily), Soak, Scrape (callus), Smear (oil); MCR footwear; treat ulcers with rest, debridement, dressings"]),
 ("Recent advances?", ["NLEP 3-drug regimen and revised classification (2025), single-dose rifampicin PEP for contacts, Mw/MIP vaccine, PCR/serology (anti-PGL-1), rifampicin resistance testing (rpoB), leprosy notification from all sectors"]),
 ],
 spot=["Hypopigmented anaesthetic patch with thickened nerve — leprosy", "Leonine facies, madarosis — lepromatous leprosy"]),

dict(case="Cutaneous tuberculosis", src=f"{DYP} (Cutaneous tuberculosis); {IA} ch.16; NTEP",
 qa=[
 ("Classify cutaneous tuberculosis.", ["Exogenous: tuberculous chancre (primary inoculation, non-immune), tuberculosis verrucosa cutis (TBVC — immune host)", "Endogenous: scrofuloderma (contiguous from lymph node/bone), orificial TB (autoinoculation, advanced disease), lupus vulgaris (haematogenous/lymphatic, high immunity), acute miliary TB, tuberculous gumma/metastatic abscess", "Tuberculids (hypersensitivity): papulonecrotic tuberculid, lichen scrofulosorum, erythema induratum of Bazin; (nodular tuberculid)"]),
 ("Describe lupus vulgaris.", ["Commonest form in India; slowly progressive reddish-brown plaque with peripheral activity and central scarring (sometimes atrophic), on face in West and buttocks/extremities in India", "Apple-jelly nodules on diascopy; 'probe sign' (soft tissue — probe sinks)", "Complications: scarring, deformity, SCC (lupus carcinoma)"]),
 ("What is seen on diascopy?", ["Apple-jelly nodules — yellow-brown translucent granulomas"]),
 ("Describe TBVC and its differentials.", ["Warty verrucous plaque on hands/feet/buttocks (children) — 'prosector's wart'", "DDx: verruca vulgaris, chromoblastomycosis, M. marinum, sporotrichosis, hypertrophic LP, verrucous epidermal naevus, blastomycosis, iododerma/bromoderma"]),
 ("What is scrofuloderma?", ["Cold abscess from underlying lymph node/bone breaks down forming undermined ulcers and sinuses with cord-like scars (neck most common)"]),
 ("Investigations?", ["Biopsy: tuberculoid granulomas ± caseation (caseation prominent in scrofuloderma, absent/minimal in LV); ZN stain (paucibacillary); culture; GeneXpert/CBNAAT (rifampicin resistance), PCR", "Mantoux strongly positive, IGRA, chest X-ray, search for systemic focus (lymph nodes, lungs, bones), HIV test", "Therapeutic trial — response in 4–6 weeks"]),
 ("Treatment?", ["India NTEP daily regimen: 2 months HRZE + 4 months HRE (weight-band FDCs); extend if slow response; DR-TB as per programme", "Surgery for residual scarring, plastic repair of deformities"]),
 ("What are tuberculids?", ["Hypersensitivity reactions to TB elsewhere; bacilli not demonstrable but PCR may be positive; respond to ATT — papulonecrotic tuberculid, lichen scrofulosorum (lichenoid follicular papules in children), erythema induratum (nodular vasculitis on calves of women)"]),
 ("Historical importance?", ["Finsen won the Nobel Prize (1903) for UV light therapy of lupus vulgaris; lupus vulgaris = 'wolf' — eats away tissue"]),
 ],
 spot=["Plaque with apple-jelly nodules on diascopy — lupus vulgaris"]),

dict(case="Herpes simplex", src=f"{DYP} (Herpes simplex virus); {IA} ch.20 and ch.131",
 qa=[
 ("Types of HSV and sites?", ["HSV-1: mainly orolabial (now an increasing cause of genital herpes); HSV-2: mainly genital", "Both are alpha-herpesviruses, latent in sensory ganglia (trigeminal, sacral)"]),
 ("Define primary, non-primary first episode and recurrent infection.", ["Primary: first infection in a person without antibodies to either type", "Non-primary first episode: first infection with one type in a person with antibodies to the other", "Recurrent: reactivation of latent virus"]),
 ("Clinical features of primary herpetic gingivostomatitis and genital herpes?", ["Children: fever, painful oral vesicles/erosions, gingivitis, lymphadenopathy", "Genital primary: grouped painful vesicles → erosions, inguinal lymphadenopathy, fever, dysuria, urinary retention, aseptic meningitis; lasts 2–3 weeks"]),
 ("What is asymptomatic shedding?", ["Virus shedding from mucosa without lesions — major source of transmission; reduced by suppressive therapy and condoms"]),
 ("Complications/variants?", ["Eczema herpeticum (Kaposi varicelliform eruption — punched-out erosions on atopic skin), herpetic whitlow, herpes gladiatorum (wrestlers), keratitis, encephalitis (temporal lobe), neonatal herpes, erythema multiforme (HSV-associated), chronic ulcers in HIV, hepatitis"]),
 ("Differential diagnosis of genital herpes?", ["Chancroid, primary syphilis, fixed drug eruption, Behçet ulcers, trauma, candidal balanitis, herpes zoster, erythema multiforme"]),
 ("Investigations?", ["Tzanck smear: multinucleated giant cells (moulding, margination, multinucleation — 3 Ms) — cannot differentiate HSV from VZV", "PCR (most sensitive, test of choice), viral culture, DFA; type-specific serology (gG-based) for unrecognised infection"]),
 ("Treatment?", ["First episode: acyclovir 400 mg three times daily × 7–10 days (or valacyclovir 1 g twice daily, famciclovir 250 mg three times daily)", "Recurrent: episodic short courses started at prodrome", "Suppressive therapy for ≥6 recurrences/year: acyclovir 400 mg twice daily or valacyclovir 500 mg–1 g daily", "Eczema herpeticum/severe: IV acyclovir 5–10 mg/kg 8-hourly; acyclovir-resistant: foscarnet/cidofovir"]),
 ("Herpes in pregnancy?", ["Primary infection in third trimester carries highest neonatal risk (30–50%) — caesarean section if lesions at labour; suppressive acyclovir from 36 weeks"]),
 ],
 spot=["Grouped vesicles on an erythematous base on the lip — herpes labialis"]),

dict(case="Molluscum contagiosum", src=f"{DYP} (Molluscum contagiosum); {IA} ch.20",
 qa=[
 ("Why is this molluscum?", ["Multiple discrete pearly, dome-shaped, skin-coloured umbilicated papules 2–5 mm; curd-like material expressible on squeezing; often in children on trunk/face/flexures, genital in adults (STI)"]),
 ("Causative agent?", ["Molluscum contagiosum virus — poxvirus (largest DNA virus family), types MCV1–4 (MCV1 commonest; MCV2 in adults/HIV)"]),
 ("Why the umbilication?", ["Central crater from the keratin-filled pore through which molluscum bodies are discharged"]),
 ("Histopathology?", ["Cup-shaped (lobulated) endophytic hyperplasia with large eosinophilic intracytoplasmic inclusions — Henderson–Patterson (molluscum) bodies, becoming basophilic towards the surface"]),
 ("Differential diagnosis?", ["Warts, milia, juvenile xanthogranuloma, keratoacanthoma, BCC; in HIV — cryptococcosis, histoplasmosis, penicilliosis (talaromycosis) — biopsy"]),
 ("Is treatment necessary?", ["Self-limiting in immunocompetent children (6–18 months) — treatment optional; treat to reduce spread, symptoms, cosmetic reasons, genital lesions (STI) and in immunocompromised"]),
 ("Treatment options?", ["Curettage/expression, cryotherapy, cantharidin 0.7%, potassium hydroxide 5–10%, podophyllotoxin (adults), tretinoin, TCA, salicylic acid", "HIV: ART (immune reconstitution), cidofovir topical"]),
 ("Complications?", ["Molluscum dermatitis (eczema around lesions), secondary infection, BOTE sign (beginning of the end — inflammation before resolution), scarring, giant mollusca in HIV, eyelid lesions with conjunctivitis"]),
 ],
 spot=["Pearly umbilicated papules — molluscum contagiosum"]),

dict(case="Chickenpox (varicella)", src=f"{DYP} (Chicken pox); {IA} ch.20–21",
 qa=[
 ("Why is it chickenpox?", ["Fever followed by crops of itchy lesions in different stages (macule → papule → vesicle 'dew drop on rose petal' → pustule → crust), centripetal distribution (trunk > face/limbs), mucosal involvement, scalp involvement"]),
 ("Causative agent and transmission?", ["Varicella-zoster virus (HHV-3) — airborne/droplet and vesicle fluid; infectious from 1–2 days before rash until all lesions crust; incubation 10–21 days"]),
 ("Difference from smallpox?", ["Smallpox: lesions in same stage, centrifugal, deep-seated, palms/soles involved, severe prodrome — eradicated 1980"]),
 ("Differential diagnosis?", ["Disseminated herpes simplex/zoster, hand-foot-and-mouth disease, PLEVA (Mucha–Habermann), insect bite reactions, rickettsial pox, eczema herpeticum, impetigo, drug eruptions"]),
 ("Tzanck smear findings?", ["Multinucleated giant cells and intranuclear inclusions (Cowdry type A) — same as HSV"]),
 ("Complications?", ["Secondary bacterial infection (commonest), scarring, pneumonia (adults, smokers, pregnancy), encephalitis/cerebellar ataxia, Reye syndrome (aspirin), hepatitis, purpura fulminans, congenital varicella syndrome (first 20 weeks), neonatal varicella (maternal rash 5 days before to 2 days after delivery)"]),
 ("Management?", ["Children: symptomatic (calamine, antihistamines, paracetamol — avoid aspirin); acyclovir 20 mg/kg four times daily × 5 days in adolescents/adults, secondary cases in households, chronic skin/lung disease", "Immunocompromised/pregnant/pneumonia: IV acyclovir 10 mg/kg 8-hourly", "Post-exposure: vaccine within 3–5 days, VZIG within 10 days for high-risk"]),
 ("Vaccines available?", ["Live attenuated varicella vaccine (Oka strain) 2 doses (12–15 months and 4–6 years); MMRV; zoster vaccines (recombinant Shingrix) for adults"]),
 ("Diseases caused by poxviruses (as asked in DYP)?", ["Smallpox, mpox (monkeypox), cowpox, vaccinia, molluscum contagiosum, orf, milker's nodule — chickenpox is NOT a poxvirus (it is a herpesvirus)"]),
 ],
 spot=["Polymorphic crops of vesicles ('dew drop on rose petal') — varicella"]),

dict(case="Warts (verruca)", src=f"{DYP} (Anogenital warts; topical agents — 5-FU, bleomycin); {IA} ch.20",
 qa=[
 ("What are warts and what causes them?", ["Benign epidermal proliferations caused by human papillomavirus (HPV — DNA virus, >200 types) infecting basal keratinocytes through microabrasions"]),
 ("Clinical types and HPV types?", ["Verruca vulgaris (HPV 2, 4, 27, 57), plantar/myrmecia (HPV 1), plane/flat warts (HPV 3, 10), filiform/digitate (face), periungual, mosaic warts, butcher's warts (HPV 7)", "Anogenital: HPV 6, 11 (low risk); 16, 18 (high risk)", "Epidermodysplasia verruciformis: HPV 5, 8"]),
 ("Why is it a wart and not a corn?", ["Paring a wart shows black dots (thrombosed capillaries) and interruption of skin lines; corn has a central translucent core, painful on direct pressure, skin lines preserved; lateral squeeze painful in wart"]),
 ("Histopathology?", ["Hyperkeratosis, papillomatosis, acanthosis, parakeratosis over papillae ('church spire'), koilocytes (vacuolated cells with perinuclear halo), large keratohyaline granules, inward-pointing rete ridges"]),
 ("Treatment options?", ["Destructive: salicylic acid 15–26% paint, cryotherapy, electrocautery, laser, TCA, cantharidin, curettage", "Antiproliferative: 5-FU, bleomycin intralesional (1 U/mL), podophyllotoxin (genital), retinoids (plane warts)", "Immunotherapy: imiquimod, intralesional MMR/Candida antigen/PPD/Mw vaccine, DPCP/SADBE, cimetidine, zinc, HPV vaccine (off-label)"]),
 ("What is Koebner phenomenon in warts?", ["Pseudo-Koebner — linear warts along scratch marks due to autoinoculation (also seen in molluscum)"]),
 ("Warts in special situations?", ["Children: many regress spontaneously (2/3 in 2 years) — gentle treatments", "Immunocompromised/transplant: extensive, recalcitrant, risk of SCC", "Pregnancy: cryotherapy/TCA; avoid podophyllin"]),
 ("Prevention?", ["HPV vaccine (quadrivalent/9-valent) prevents anogenital warts; avoid sharing footwear, cover warts in pools"]),
 ],
 spot=["Rough hyperkeratotic papule with black dots — verruca vulgaris"]),

dict(case="Herpes zoster", src=f"{DYP} (Herpes simplex virus chapter — herpes zoster); {IA} ch.20",
 qa=[
 ("Pathogenesis?", ["Reactivation of latent VZV in dorsal root/cranial nerve ganglia after childhood varicella, triggered by age-related decline in cell-mediated immunity, immunosuppression, stress, trauma; virus travels down the sensory nerve to skin"]),
 ("Clinical features?", ["Prodrome of pain/tingling, then unilateral grouped vesicles on erythematous base in a dermatomal distribution not crossing the midline (thoracic commonest, then ophthalmic division of trigeminal); regional lymphadenopathy"]),
 ("Signs to remember?", ["Hutchinson's sign: vesicles on tip/side of nose (nasociliary branch) → high risk of ocular involvement", "Ramsay Hunt syndrome: facial nerve palsy + vesicles in ear/palate + vertigo/tinnitus (geniculate ganglion)"]),
 ("Complications?", ["Post-herpetic neuralgia (pain >90 days; risk ↑ with age), ocular (keratitis, uveitis, acute retinal necrosis), motor paresis, meningoencephalitis, myelitis, stroke (vasculopathy), secondary infection, scarring, disseminated zoster (>20 lesions outside dermatome) in immunocompromised", "Dermatological: post-zoster granulomas/Wolf isotopic response, pigmentary change, herpes gangrenosum"]),
 ("Diagnosis?", ["Clinical; Tzanck (giant cells), PCR of vesicle fluid (test of choice), DFA, culture"]),
 ("Treatment?", ["Start within 72 h (later if new vesicles/immunocompromised/ocular): acyclovir 800 mg five times daily × 7 days, valacyclovir 1 g three times daily, famciclovir 500 mg three times daily", "IV acyclovir 10 mg/kg 8-hourly for disseminated/immunocompromised", "Analgesia; ophthalmology review for HZO"]),
 ("Treatment of post-herpetic neuralgia?", ["Pregabalin/gabapentin, tricyclics (amitriptyline/nortriptyline), topical lidocaine 5% patch, capsaicin 8% patch, tramadol/opioids, nerve blocks"]),
 ("Prevention?", ["Recombinant zoster vaccine (Shingrix, 2 doses) for adults ≥50 years and immunocompromised ≥18; live vaccine (Zostavax) discontinued in many countries"]),
 ("Zoster as a marker?", ["Multidermatomal/recurrent/disseminated zoster in a young person — screen for HIV and malignancy"]),
 ],
 spot=["Unilateral dermatomal grouped vesicles — herpes zoster"]),
]
