# Viva slot V1 (part B): fungal infections, infestations
DYP = "DYP Survival Guide for PG Dermatology Exam"; IA = "IADVL Textbook of Dermatology 5e"
D = [
dict(case="Mycetoma (Madura foot)", src=f"{DYP} (Mycetoma); {IA} ch.19 (Deep fungal infections)",
 qa=[
 ("Define mycetoma.", ["Chronic, localised, granulomatous infection of skin, subcutis and bone caused by fungi (eumycetoma) or aerobic actinomycetes (actinomycetoma), characterised by the triad of tumefaction, multiple draining sinuses and discharge of grains"]),
 ("Who described it and what is the mycetoma belt?", ["Gill described it in Madura (Madurai) in 1842 (hence Madura foot); Carter named it mycetoma", "Mycetoma belt: between latitudes 15°S and 30°N — Sudan, Mexico, India, Venezuela, Senegal"]),
 ("Common agents in India?", ["Actinomycetoma (commoner in India): Nocardia brasiliensis, Actinomadura madurae, A. pelletieri, Streptomyces somaliensis", "Eumycetoma: Madurella mycetomatis (black grains), Pseudallescheria boydii/Scedosporium (white grains)"]),
 ("Grain colour and causative organism?", ["Black: Madurella (eumycetoma)", "White/yellow: Nocardia, Actinomadura madurae, Scedosporium", "Red: Actinomadura pelletieri", "Yellow-brown: Streptomyces somaliensis"]),
 ("Differences between actinomycetoma and eumycetoma?", ["Actinomycetoma: faster progression, more inflammatory, earlier bone involvement (many small lytic lesions), grains small (filaments <1 µm), responds to antibiotics", "Eumycetoma: slow, well-defined, fewer large cavities, grains with hyphae 2–5 µm, needs antifungals ± surgery"]),
 ("Why is mycetoma painless and why does it become painful?", ["Painless due to slow progression and possible anaesthetic effect of nerve involvement; pain appears with secondary bacterial infection or bone invasion"]),
 ("Investigations?", ["Grain examination (KOH, Gram — actinomycetes Gram-positive), culture (Sabouraud's for fungi; LJ/blood agar for actinomycetes)", "Deep biopsy (wedge, not punch) — grains with Splendore–Hoeppli phenomenon", "X-ray (periosteal reaction, cavities, 'sunray'), USG (bright hyperreflective echoes from grains), MRI 'dot-in-circle sign' (grains in granuloma), FNAC, PCR/sequencing"]),
 ("Treatment of actinomycetoma?", ["Welsh regimen: amikacin 15 mg/kg/day in cycles (3 weeks) with co-trimoxazole; modified Welsh with rifampicin", "Damle's regimen (India): intensive phase penicillin + gentamicin + co-trimoxazole, then maintenance doxycycline + co-trimoxazole", "Two-step: co-trimoxazole + dapsone (± rifampicin, doxycycline) for months"]),
 ("Treatment of eumycetoma?", ["Itraconazole 400 mg/day (or voriconazole/posaconazole) for 9–12 months to shrink the lesion, followed by surgical excision with wide margins, then continue antifungal; ketoconazole no longer used (hepatotoxicity)"]),
 ("Why is surgery under local anaesthesia avoided?", ["Infiltration may spread grains along tissue planes and cause recurrence; regional/general anaesthesia and bloodless field with tourniquet preferred"]),
 ("Indications of amputation?", ["Advanced bony involvement with non-response to medical therapy, secondary infection threatening life"]),
 ],
 spot=["Swollen foot with multiple sinuses discharging grains — mycetoma"]),

dict(case="Sporotrichosis", src=f"{DYP} (Other deep fungal infections — sporotrichosis); {IA} ch.19",
 qa=[
 ("Causative agent?", ["Sporothrix schenckii complex (S. schenckii, S. brasiliensis, S. globosa — commonest in India) — thermally dimorphic fungus (mould at 25 °C, yeast at 37 °C)"]),
 ("Mode of infection and risk groups?", ["Traumatic inoculation from plants, thorns, sphagnum moss, wood splinters, hay (gardeners, farmers, florists — 'rose gardener's disease'); zoonotic from cats (S. brasiliensis)", "Common in sub-Himalayan India (Himachal, north-east), Kangra"]),
 ("Clinical types?", ["Lymphocutaneous (commonest, ~75%): nodule/ulcer at inoculation site with nodules along lymphatics (sporotrichoid spread)", "Fixed cutaneous: single plaque/verrucous lesion (face, in endemic areas with prior sensitisation)", "Disseminated/extracutaneous (osteoarticular, pulmonary) in immunocompromised"]),
 ("Differential diagnosis of sporotrichoid spread?", ["Mycobacterium marinum (fish tank granuloma — the closest mimic), nocardiosis, leishmaniasis, tularaemia, cat-scratch disease, blastomycosis, mycobacterial infections, sporotrichoid pyogenic infections"]),
 ("Investigations?", ["Biopsy: suppurative granulomatous inflammation; organisms rare — cigar-shaped yeasts; asteroid bodies (Splendore–Hoeppli reaction around yeast)", "Culture on Sabouraud's at 25 °C (moist, cream → black colonies); conversion to yeast at 37 °C", "Sporotrichin skin test; PCR"]),
 ("What are asteroid bodies and where else are they seen?", ["Eosinophilic radiating material around fungal cells — Splendore–Hoeppli phenomenon (antigen–antibody deposition)", "Also seen in sarcoidosis (in giant cells — different), botryomycosis, mycetoma, schistosomiasis, zygomycosis"]),
 ("Treatment?", ["Itraconazole 200 mg/day until 2–4 weeks after lesions resolve (usually 3–6 months) — drug of choice", "Saturated solution of potassium iodide (SSKI) — cheap alternative (1 mL three times daily increasing to 4–6 mL three times daily)", "Terbinafine 500 mg twice daily; local heat (fungus cannot grow above 39 °C) in pregnancy; amphotericin B for disseminated disease"]),
 ],
 spot=["Ulcerated nodule on finger with nodules along the lymphatics of the forearm — lymphocutaneous sporotrichosis"]),

dict(case="Chromoblastomycosis", src=f"{DYP} (Other deep fungal infections — chromoblastomycosis); {IA} ch.19",
 qa=[
 ("What is chromoblastomycosis and its agents?", ["Chronic subcutaneous mycosis by dematiaceous (pigmented) fungi after traumatic inoculation", "Fonsecaea pedrosoi (commonest), F. compacta, Phialophora verrucosa, Cladophialophora carrionii, Rhinocladiella aquaspersa"]),
 ("What are dematiaceous fungi?", ["Fungi with melanin in their cell walls (brown/black) — also cause phaeohyphomycosis and black-grain eumycetoma"]),
 ("Clinical features?", ["Slowly growing verrucous, cauliflower-like or plaque lesions on the lower limb of barefoot rural workers; 'black dots' on surface (transepidermal elimination of fungi) — best site for KOH", "Types: nodular, tumorous, verrucous, plaque, cicatricial; lymphoedema/elephantiasis, secondary infection, SCC (rare)"]),
 ("What are muriform (sclerotic/Medlar) bodies?", ["Thick-walled, brown, multiseptate (septate in two planes) fungal cells resembling copper pennies — diagnostic on KOH and histopathology"]),
 ("Histopathology?", ["Pseudoepitheliomatous hyperplasia, suppurative granulomas (microabscesses) with sclerotic bodies, transepidermal elimination"]),
 ("Differential diagnosis of verrucous plaques (DYP favourite)?", ["TBVC, verrucous LV, sporotrichosis (fixed), mycetoma, blastomycosis, leishmaniasis, verrucous carcinoma, hypertrophic LP, iododerma, M. marinum, PEH over pyogenic infection"]),
 ("Treatment?", ["Small lesions: surgical excision (wide), cryotherapy, local heat, laser", "Systemic: itraconazole 200–400 mg/day for 6–12 months or longer; terbinafine 500 mg/day; flucytosine combination; posaconazole", "Combination of systemic antifungal with cryotherapy improves cure"]),
 ("In which deep mycoses is koebnerisation/autoinoculation seen?", ["Chromoblastomycosis (satellite lesions from scratching), sporotrichosis, blastomycosis"]),
 ],
 spot=["Warty cauliflower plaque on the foot of a farmer with black dots — chromoblastomycosis"]),

dict(case="Tinea corporis / cruris / faciei", src=f"{DYP} (Superficial fungal infection); {IA} ch.18; ECTODERM/IADVL consensus on dermatophytosis",
 qa=[
 ("What are dermatophytes?", ["Keratinophilic fungi of genera Trichophyton, Microsporum and Epidermophyton that infect keratin (skin, hair, nails); anthropophilic, zoophilic, geophilic"]),
 ("Clinical features of tinea corporis/cruris?", ["Annular/arcuate plaques with active scaly papulovesicular border and central clearing, itchy; cruris on groins/inner thighs sparing scrotum (unlike candida)", "Indian epidemic: extensive, multiple, concentric (tinea pseudoimbricata), steroid-modified (tinea incognito) lesions, chronic and recurrent"]),
 ("What is the current Indian dermatophytosis scenario?", ["Since ~2014 an epidemic of chronic, recurrent, extensive and treatment-resistant tinea driven by Trichophyton indotineae (formerly T. mentagrophytes genotype VIII), misuse of steroid–antifungal combinations, poor adherence and squalene epoxidase mutations (terbinafine resistance)"]),
 ("Investigations?", ["KOH mount (10–20%): branching septate hyphae; culture on Sabouraud dextrose agar with chloramphenicol and cycloheximide (DTM); dermoscopy; MALDI-TOF/sequencing and antifungal susceptibility testing in resistant cases"]),
 ("Differential diagnosis of annular lesions?", ["Nummular eczema, psoriasis, pityriasis rosea (herald patch), seborrhoeic dermatitis, granuloma annulare (no scale), erythema annulare centrifugum (trailing scale), SCLE, leprosy (anaesthetic), annular lichen planus, Hansen's BT"]),
 ("What is tinea incognito?", ["Tinea modified by topical steroids — less scaling, ill-defined border, pustules, extensive spread, Majocchi granuloma"]),
 ("What is Majocchi granuloma?", ["Deep perifollicular dermatophyte infection (often T. rubrum) after steroid use or shaving legs; nodules/pustules — needs systemic antifungals"]),
 ("What is tinea imbricata?", ["Trichophyton concentricum infection — concentric rings of scale ('tokelau'), Pacific islands; Indian 'pseudoimbricata' pattern due to steroid misuse"]),
 ("Treatment (Indian practice)?", ["Topical azole/allylamine (luliconazole, sertaconazole, amorolfine, terbinafine) — continue 2 weeks after clearance", "Systemic for extensive/recurrent: itraconazole 200 mg/day for 4–8 weeks (preferred now in India), terbinafine 250–500 mg/day, griseofulvin, fluconazole; combinations in recalcitrant cases", "General: stop steroids, treat family, loose cotton clothes, wash and dry clothing, avoid sharing"]),
 ],
 spot=["Annular scaly plaque with active border and central clearing — tinea corporis"]),

dict(case="Tinea capitis", src=f"{DYP} (Superficial fungal infection — tinea capitis); {IA} ch.18; {'Wolverton 4e'} Table 10.5",
 qa=[
 ("Types of hair invasion?", ["Ectothrix: arthroconidia outside the shaft, destroy cuticle (Microsporum canis, M. audouinii, T. mentagrophytes, T. verrucosum)", "Endothrix: arthroconidia inside the shaft, cuticle intact (T. tonsurans, T. violaceum, T. soudanense) — black-dot", "Favus: hyphae and air spaces in shaft (T. schoenleinii)"]),
 ("Clinical types?", ["Non-inflammatory: grey patch (ectothrix, scaly patches with broken hairs), black dot (endothrix), seborrhoeic/diffuse scaling type", "Inflammatory: kerion (boggy, pustular, suppurative plaque with lymphadenopathy — can scar), agminate folliculitis", "Favus: yellow cup-shaped crusts (scutula), mousy odour, scarring alopecia"]),
 ("Which fungi fluoresce under Wood's lamp?", ["Green fluorescence: Microsporum canis, M. audouinii, M. ferrugineum, M. distortum; favus (T. schoenleinii) — dull blue-green", "Non-fluorescent: T. tonsurans, T. violaceum, T. soudanense (endothrix)"]),
 ("Differential diagnosis?", ["Seborrhoeic dermatitis, psoriasis, alopecia areata, trichotillomania, pityriasis amiantacea, impetigo, pyoderma/bacterial folliculitis (kerion), lupus/LPP, discoid lupus"]),
 ("Investigations?", ["KOH of plucked hairs/scales (spores and hyphae), Wood's lamp, trichoscopy (comma hairs, corkscrew hairs, Morse-code hairs, zigzag hairs), culture"]),
 ("Treatment?", ["Systemic therapy is always needed (topicals do not penetrate the follicle)", "Griseofulvin microsize 20–25 mg/kg/day for 6–8 weeks (drug of choice for Microsporum)", "Terbinafine weight-based (10–20 kg 62.5 mg; 20–40 kg 125 mg; >40 kg 250 mg) for 2–4 weeks (T. tonsurans; 8–12 weeks for M. canis)", "Itraconazole 5 mg/kg/day; fluconazole 6 mg/kg/day", "Adjuncts: 2% ketoconazole or 2.5% selenium sulfide shampoo for patient and family (reduce spore shedding); kerion — add short oral steroid if severe; no surgical drainage"]),
 ("Why is tinea capitis rare after puberty?", ["Sebum fatty acids (fungistatic) increase at puberty"]),
 ],
 spot=["Scaly patch of broken hairs in a child with green fluorescence — grey patch tinea capitis (Microsporum)"]),

dict(case="Tinea pedis & onychomycosis", src=f"{DYP} (Superficial fungal infection — tinea pedis, tinea unguium); {IA} ch.18 and ch.58",
 qa=[
 ("Types of tinea pedis?", ["Interdigital (commonest, 4th web space — maceration, fissuring)", "Moccasin/chronic hyperkeratotic (T. rubrum — diffuse plantar scaling)", "Vesiculobullous (T. mentagrophytes — instep)", "Acute ulcerative (with Gram-negative superinfection)"]),
 ("What is 'two feet–one hand' syndrome?", ["Bilateral tinea pedis with unilateral tinea manuum (usually dominant/scratching hand) — T. rubrum"]),
 ("What is an id (dermatophytid) reaction?", ["Sterile vesicular eruption on palms/fingers as an allergic reaction to an active fungal infection elsewhere (often inflammatory tinea pedis); KOH-negative; clears when infection is treated"]),
 ("Clinical types of onychomycosis?", ["Distal and lateral subungual (commonest), superficial white (T. mentagrophytes/moulds), proximal subungual (T. rubrum — suspect HIV), endonyx, total dystrophic, candidal (paronychia, onycholysis), mixed"]),
 ("Differential diagnosis of onychomycosis?", ["Nail psoriasis (pits, oil-drop), lichen planus (pterygium), trauma/onycholysis, yellow nail syndrome, pachyonychia, eczema nail changes, subungual tumours, onychogryphosis"]),
 ("Investigations?", ["KOH with nail clippings from proximal edge of onycholysis, culture (dermatophyte vs non-dermatophyte mould — repeat culture), nail clipping histopathology with PAS (most sensitive), dermoscopy (jagged proximal edge, spikes, longitudinal striae), PCR"]),
 ("Treatment of onychomycosis?", ["Topical (≤50% nail, no matrix): amorolfine 5% lacquer weekly, ciclopirox 8% daily, efinaconazole/tavaborole", "Systemic: terbinafine 250 mg/day — 6 weeks fingernails, 12 weeks toenails (drug of choice for dermatophytes); itraconazole pulse 200 mg twice daily 1 week/month (2 pulses fingers, 3 toes) — also covers Candida/moulds; fluconazole weekly", "Adjuncts: chemical (40% urea) or surgical avulsion, debridement, lasers; combination improves cure"]),
 ("Prevention of tinea pedis?", ["Dry toe webs, absorbent socks, antifungal powder, open/breathable footwear, avoid barefoot in communal showers, treat household members"]),
 ],
 spot=["Thickened yellow crumbling toenails with subungual debris — distal lateral subungual onychomycosis"]),

dict(case="Pityriasis versicolor", src=f"{DYP} (Superficial fungal infection — tinea versicolor); {IA} ch.18",
 qa=[
 ("Causative organism?", ["Malassezia globosa (mainly), M. furfur, M. sympodialis — lipophilic yeasts of normal flora that convert to mycelial form"]),
 ("Predisposing factors?", ["Hot humid climate, sweating, oily skin (adolescents/young adults), oily applications, pregnancy, Cushing/steroids, immunosuppression, malnutrition, genetic predisposition"]),
 ("Clinical features?", ["Hypo- or hyperpigmented (or erythematous) round/oval macules with fine branny scale on upper trunk, neck, upper arms; 'evoked scale' (Besnier's sign/scratch sign) on stretching or scratching"]),
 ("Why hypopigmentation?", ["Azelaic acid (dicarboxylic acid) produced by Malassezia inhibits tyrosinase; also pityriacitrin/malassezin effects and screening of UV"]),
 ("Investigations?", ["KOH: short hyphae and round yeasts — 'spaghetti and meatballs'", "Wood's lamp: yellow-orange/golden fluorescence (not always)", "Scotch tape test, dermoscopy"]),
 ("Differential diagnosis?", ["Vitiligo (no scale, chalky white), pityriasis alba, post-inflammatory hypopigmentation, leprosy (anaesthetic), seborrhoeic dermatitis, pityriasis rosea, confluent and reticulated papillomatosis, erythrasma, nevus depigmentosus"]),
 ("Treatment?", ["Topical: ketoconazole 2% shampoo as body wash (5 min daily for 3 days), selenium sulfide 2.5%, zinc pyrithione, azole creams, terbinafine solution", "Systemic for extensive/recurrent: fluconazole 300 mg weekly × 2 (or 400 mg single), itraconazole 200 mg/day for 5–7 days (oral terbinafine and griseofulvin are ineffective)", "Prophylaxis: monthly shampoo/itraconazole 400 mg once monthly in hot months", "Pigment takes months to return — explain to patient"]),
 ],
 spot=["Fine scaly hypopigmented macules on the upper back — pityriasis versicolor"]),

dict(case="Cutaneous candidiasis / intertrigo", src=f"{DYP} (Superficial fungal infection — candidiasis); {IA} ch.18",
 qa=[
 ("Causative organism?", ["Candida albicans (commonest), C. tropicalis, C. parapsilosis, C. glabrata, C. krusei; emerging C. auris (multidrug-resistant)"]),
 ("Predisposing factors?", ["Moisture/occlusion (obesity, skin folds, diapers), diabetes, pregnancy, broad-spectrum antibiotics, steroids, immunosuppression (HIV), infancy and old age, dentures, iron deficiency, endocrinopathies"]),
 ("Clinical forms?", ["Intertrigo: moist beefy-red plaques with peripheral scaling and satellite papulopustules in folds", "Oral thrush, angular cheilitis, vulvovaginitis, balanoposthitis, napkin candidiasis, chronic paronychia, onychomycosis, erosio interdigitalis blastomycetica (3rd web space of hand), chronic mucocutaneous candidiasis"]),
 ("How to differentiate from tinea cruris?", ["Candida: involves scrotum, beefy red, satellite pustules, no central clearing; tinea cruris spares scrotum, active scaly border with central clearing"]),
 ("Investigations?", ["KOH: budding yeast with pseudohyphae; Gram stain; culture on Sabouraud's (creamy colonies), germ tube test (C. albicans), CHROMagar species ID", "Blood sugar, HIV in recurrent/extensive cases"]),
 ("What is chronic mucocutaneous candidiasis?", ["Persistent candida of skin, nails and mucosa from defective IL-17 immunity — AIRE mutation (APECED: hypoparathyroidism, Addison disease), STAT1 gain-of-function, STAT3 (hyper-IgE)"]),
 ("Treatment?", ["Keep area dry; topical azoles (clotrimazole, miconazole), nystatin, ciclopirox; drying agents/barrier pastes", "Systemic: fluconazole 150 mg weekly or 50–100 mg daily × 2 weeks; itraconazole for resistant species (C. krusei is resistant to fluconazole)", "Treat predisposing causes (weight loss, glycaemic control)"]),
 ],
 spot=["Beefy red moist plaque in the inframammary fold with satellite pustules — candidal intertrigo"]),

dict(case="Pediculosis", src=f"{DYP} (Pediculosis); {IA} ch.22",
 qa=[
 ("Types of lice affecting humans?", ["Pediculus humanus capitis (head louse), Pediculus humanus corporis (body louse), Phthirus pubis (crab/pubic louse)"]),
 ("Life cycle of the head louse?", ["Eggs (nits) cemented to hair shaft near scalp, hatch in 7–10 days into nymphs, mature in 9–12 days; adult female lays ~5–10 eggs/day and lives ~30 days; obligate blood feeders, die within 1–2 days off host"]),
 ("Clinical features of pediculosis capitis?", ["Itching (occipital and post-auricular), nits on hair, live lice, excoriations, secondary impetigo, occipital lymphadenopathy, 'plica polonica' (matted hair) in neglected cases"]),
 ("Nits vs pseudonits?", ["Nits are firmly cemented and cannot be slid along the hair; pseudonits (hair casts, dandruff, hair spray, piedra) move freely along the shaft"]),
 ("Head louse vs body louse?", ["Body louse lives in clothing seams, lays eggs on fibres, causes vagabond's disease (hyperpigmented lichenified skin in neglected/homeless), transmits epidemic typhus (Rickettsia prowazekii), trench fever (Bartonella quintana), relapsing fever (Borrelia recurrentis)", "Head louse is not an important disease vector"]),
 ("What is maculae caeruleae?", ["Slate-blue macules on thighs/trunk at sites of pubic louse feeding (altered haemoglobin from louse saliva)"]),
 ("Treatment of head lice?", ["Permethrin 1% creme rinse 10 min, repeat on day 9–10; malathion 0.5%; ivermectin 0.5% lotion; spinosad 0.9%; dimeticone 4% (physical, no resistance); benzyl alcohol 5%", "Oral ivermectin 200–400 µg/kg on days 1 and 8 for resistance", "Wet combing with fine-tooth comb; treat contacts; wash bedding/combs in hot water"]),
 ("Treatment of phthiriasis palpebrarum?", ["Petrolatum applied twice daily for 10 days (smothers lice), mechanical removal, oral ivermectin; pubic lice — evaluate for other STIs, treat partner"]),
 ("What is pediculicide resistance?", ["Knockdown resistance (kdr) — sodium channel mutations reducing permethrin/pyrethrin efficacy; suspect if live lice persist after correct use"]),
 ],
 spot=["Nits firmly attached to hair shafts with occipital excoriations — pediculosis capitis"]),

dict(case="Scabies", src=f"{DYP} (Scabies); {IA} ch.22; {'Wolverton 4e'} ch.12 and ch.44",
 qa=[
 ("Define scabies and describe the mite.", ["Contagious infestation by Sarcoptes scabiei var. hominis; oval, flattened mite ~0.4 mm (female), 4 pairs of legs, transmitted by prolonged skin-to-skin contact"]),
 ("Life cycle?", ["Fertilised female burrows in stratum corneum (2–3 mm/day), lays 2–3 eggs/day for 4–6 weeks; eggs hatch in 3–4 days; larvae → nymphs → adults in 10–14 days; usually 10–15 mites per patient (millions in crusted scabies)"]),
 ("Why is itching worse at night and delayed in first infestation?", ["Type IV hypersensitivity to mite and its products develops in 3–6 weeks in first infestation (1–3 days in re-infestation); warmth at night increases mite activity and itch perception"]),
 ("Clinical features and sites?", ["Nocturnal pruritus, family members affected, burrows (pathognomonic — grey serpiginous lines), papules, vesicles, nodules (male genitalia, axillae)", "Sites: finger webs, flexor wrists, elbows, axillary folds, areola, umbilicus, buttocks, genitalia (circle of Hebra); face and scalp spared in adults but involved in infants (also palms/soles)"]),
 ("Types of scabies?", ["Classic, nodular, crusted (Norwegian — hyperkeratotic, thousands of mites, in immunocompromised/neurological/elderly; highly contagious), bullous (mimics pemphigoid), scabies incognito (steroid-treated), animal scabies (no burrows, exposed sites, self-limiting)"]),
 ("Diagnosis?", ["Clinical (IACS 2020 criteria), burrow ink test, skin scraping with mineral oil/KOH (mite, eggs, scybala — faecal pellets), dermoscopy 'delta wing jet with contrail' sign, adhesive tape test, biopsy"]),
 ("Differential diagnosis?", ["Infants: atopic dermatitis, infantile acropustulosis, papular urticaria", "Adults: insect bites, dermatitis herpetiformis, prurigo, contact dermatitis, HIV pruritus; elderly: asteatotic eczema, bullous pemphigoid"]),
 ("Treatment?", ["Permethrin 5% cream neck down (whole body in infants/elderly) for 8–14 h, repeat after 7 days — first line (safe from 2 months, in pregnancy)", "Oral ivermectin 200 µg/kg repeated after 7–14 days (not <15 kg/pregnancy)", "Alternatives: benzyl benzoate 25%, precipitated sulphur 5–10% (infants, pregnancy), crotamiton", "Crusted: oral ivermectin on days 1, 2, 8, 9, 15 (± 22, 29) with topical permethrin and keratolytics", "Treat all close contacts simultaneously; launder clothes/bedding; antihistamines; post-scabetic itch lasts 2–4 weeks"]),
 ("Complications?", ["Secondary impetigo, cellulitis, post-streptococcal glomerulonephritis (and possibly rheumatic heart disease in endemic communities), eczematisation, nodular scabies, lymphangitis"]),
 ],
 spot=["Papules and burrows in finger webs with nocturnal itch in family members — scabies"]),
]
