# Viva slot V2 (part A): sexually transmitted infections + first eczemas
DYP = "DYP Survival Guide for PG Dermatology Exam"; IA = "IADVL Textbook of Dermatology 5e"
D = [
dict(case="Anogenital warts", src=f"{DYP} (Long case — Anogenital warts); {IA} ch.131",
 qa=[
 ("What are anogenital warts and their HPV types?", ["Benign epithelial proliferations of anogenital skin/mucosa caused by HPV — mainly low-risk types 6 and 11 (~90%); high-risk 16, 18, 31, 33 cause intraepithelial neoplasia and carcinoma"]),
 ("Clinical types?", ["Condylomata acuminata (cauliflower/acuminate), papular (dome-shaped, keratinised skin), keratotic, flat/macular (mucosal — visible with acetowhitening), giant condyloma of Buschke–Löwenstein (verrucous carcinoma), intraepithelial neoplasia (bowenoid papulosis, Bowen disease)"]),
 ("How are they transmitted? Significance in a child?", ["Sexual contact (most), perinatal (maternal), autoinoculation/heteroinoculation from hand warts, fomites (rare)", "In children consider sexual abuse, especially >3 years — sensitive evaluation"]),
 ("Condyloma acuminata vs condyloma lata?", ["Lata (secondary syphilis): flat-topped, moist, broad-based, grey-white, highly infectious, dark-ground positive, generalised lymphadenopathy", "Acuminata: pink, dry, papillomatous, narrow base (paper can be passed under it), DGI negative"]),
 ("Differential diagnosis?", ["Pearly penile papules, Fordyce spots, vestibular papillae, molluscum, seborrhoeic keratosis, skin tags, condyloma lata, bowenoid papulosis, lichen planus, scabies nodules, SCC"]),
 ("Histopathology?", ["Acanthosis, papillomatosis, koilocytes (perinuclear halo with raisinoid nuclei) in upper layers, parakeratosis"]),
 ("What is the acetowhite test?", ["3–5% acetic acid for 3–5 min turns HPV-infected epithelium white — helps identify subclinical lesions, but non-specific"]),
 ("Treatment of external genital warts?", ["Patient-applied: podophyllotoxin 0.5% solution/0.15% cream (3 days on, 4 off, up to 4 cycles), imiquimod 5% cream thrice weekly up to 16 weeks, sinecatechins 15% ointment three times daily up to 16 weeks", "Provider-administered: cryotherapy (preferred in pregnancy), TCA 80–90%, podophyllin 10–25% (wash off in 1–4 h), electrocautery, surgical excision, CO2 laser", "Special situations: intralesional interferon, 5-FU, cidofovir, immunotherapy"]),
 ("Warts in pregnancy?", ["Grow rapidly and may bleed/obstruct labour; podophyllin, podophyllotoxin and imiquimod avoided; cryotherapy/TCA/excision; caesarean only for obstruction or bleeding; risk of juvenile laryngeal papillomatosis in baby"]),
 ("Is a vaccine available?", ["Yes — quadrivalent (6, 11, 16, 18) and 9-valent HPV vaccines prevent anogenital warts; bivalent (16, 18) does not prevent warts"]),
 ],
 spot=["Cauliflower-like papillomatous growths on the prepuce — condylomata acuminata"]),

dict(case="Chancroid", src=f"{DYP} (Long case — Chancroid); {IA} ch.128; NACO STI guidelines",
 qa=[
 ("Synonyms and causative organism?", ["Soft chancre, soft sore, ulcus molle", "Haemophilus ducreyi — Gram-negative coccobacillus, arranged in 'school of fish'/'railroad track' chains"]),
 ("Incubation period and why more common in men?", ["3–7 days (short)", "More common in men (male:female up to 10:1) — women may be asymptomatic carriers; sex workers act as reservoir; uncircumcised men at higher risk"]),
 ("Describe the classical ulcer.", ["Multiple painful, soft (non-indurated), ragged undermined ulcers with grey-yellow necrotic purulent base that bleeds easily, surrounded by erythema; kissing ulcers from autoinoculation"]),
 ("What is chancroidal bubo?", ["Painful, tender, unilateral inguinal lymphadenitis in ~50% that may suppurate and rupture with a single opening (unlike LGV)"]),
 ("Clinical variants?", ["Dwarf, giant, follicular, papular (ulcus molle elevatum), transient, phagedenic, serpiginous, mixed chancre (with syphilis)"]),
 ("Differential diagnosis?", ["Primary syphilis (painless indurated), genital herpes (grouped vesicles), donovanosis (beefy red painless), LGV (transient ulcer), traumatic ulcer, Behçet, FDE"]),
 ("Investigations?", ["Gram stain of ulcer edge (school of fish), culture on enriched GC agar/Mueller–Hinton with haemin and vancomycin (difficult; transport quickly), multiplex PCR (most sensitive), biopsy (three zones: superficial necrosis, middle vascular zone with endothelial proliferation, deep plasma cell/lymphocyte infiltrate)", "Always test for syphilis (DGI, VDRL/TPHA) and HIV"]),
 ("Treatment?", ["Azithromycin 1 g single dose, or ceftriaxone 250 mg IM single dose, or ciprofloxacin 500 mg twice daily × 3 days, or erythromycin 500 mg three times daily × 7 days", "NACO syndromic kit for genital ulcer disease (non-herpetic) — white kit (benzathine penicillin + azithromycin) covers chancroid and syphilis", "Fluctuant bubo: needle aspiration through healthy skin (not incision)"]),
 ("Follow-up?", ["Review at 3–7 days — symptoms improve in 3 days and ulcers heal in 1–2 weeks; treat partners within 10 days; re-test HIV/syphilis at 3 months"]),
 ("Does chancroid increase HIV risk?", ["Yes — genital ulcer disease increases both acquisition and transmission of HIV several-fold"]),
 ],
 spot=["Multiple painful ragged undermined ulcers with unilateral fluctuant bubo — chancroid"]),

dict(case="Genital ulcer disease", src=f"{DYP} (Long case — Genital ulcer/syphilis); {IA} ch.125–126; NACO STI guidelines",
 qa=[
 ("Causes of genital ulcer disease?", ["Infective STI: syphilis, chancroid, genital herpes, LGV, donovanosis", "Non-STI: trauma, FDE, Behçet disease, aphthae, erythema multiforme/SJS, pyoderma, scabies, carcinoma (SCC), tuberculosis, pemphigus, Lipschütz ulcer (EBV in young girls)"]),
 ("Describe the primary chancre of syphilis.", ["Single, painless, indurated (button-like) clean-based ulcer with raised edge, appears 9–90 days (average 21) after exposure; bilateral rubbery non-tender inguinal lymphadenopathy"]),
 ("Why is the incubation period of syphilis long?", ["T. pallidum has a very slow division time (~30–33 hours) and inoculum size determines the time to chancre"]),
 ("Named terms DYP likes to ask?", ["Dory-flop sign: indurated chancre flips over when prepuce is retracted", "Chancre redux: relapse of chancre at original site; pseudochancre redux: gumma at site of old chancre", "Syphilis d'emblée: secondary syphilis without primary (transfusion)", "Balanitis of Follmann: syphilitic balanitis", "Condom chancre: chancre on prepuce distal to the coronal sulcus", "Phagedenic chancre: necrotic chancre with secondary infection"]),
 ("Features of secondary syphilis?", ["6–12 weeks after chancre: non-itchy symmetrical maculopapular rash including palms and soles (copper-coloured), Biett's collarette, mucous patches/snail-track ulcers, condyloma lata, split papules, moth-eaten alopecia, generalised lymphadenopathy, constitutional symptoms; corymbose, annular (face), lichenoid, follicular, nodular variants, lues maligna"]),
 ("Investigations for syphilis?", ["Dark-ground microscopy (primary/secondary moist lesions — not oral lesions due to commensal treponemes), direct fluorescent antibody, PCR", "Non-treponemal: VDRL/RPR (quantitative, for monitoring; prozone phenomenon; biological false positives)", "Treponemal: TPHA/TPPA, FTA-ABS, CLIA/EIA (remain positive for life); reverse algorithm", "CSF VDRL (only test used on CSF) in suspected neurosyphilis"]),
 ("Treatment of syphilis?", ["Early (primary, secondary, early latent): benzathine penicillin G 2.4 MU IM single dose", "Late latent/unknown duration, tertiary (non-neuro): 2.4 MU weekly × 3", "Neurosyphilis: aqueous crystalline penicillin G 18–24 MU/day IV × 10–14 days", "Penicillin allergy: doxycycline 100 mg twice daily × 14 days (28 days for late); pregnancy — desensitise and give penicillin", "Jarisch–Herxheimer reaction may occur in first 24 h"]),
 ("Syndromic management (NACO)?", ["Genital ulcer non-herpetic: white kit (kit 3 — benzathine penicillin 2.4 MU + azithromycin 1 g) or blue kit (kit 4 — doxycycline 100 mg twice daily × 15 days + azithromycin 1 g) if penicillin-allergic", "Herpetic ulcer: red kit (kit 5 — acyclovir 400 mg three times daily × 7 days)", "Plus counselling, condoms, partner management, HIV/syphilis testing"]),
 ("Follow-up after treatment?", ["Quantitative VDRL/RPR at 3, 6, 12 (24) months — four-fold (two dilution) fall indicates adequate response; serofast state possible"]),
 ],
 spot=["Single painless indurated clean ulcer with bilateral rubbery nodes — primary chancre"]),

dict(case="Gonorrhoea / urethral discharge", src=f"{DYP} (Long case — Gonorrhoea); {IA} ch.132; NACO; CDC 2021",
 qa=[
 ("What is gonorrhoea and its organism?", ["STI caused by Neisseria gonorrhoeae — Gram-negative intracellular kidney/bean-shaped diplococci; infects columnar/transitional epithelium (urethra, endocervix, rectum, pharynx, conjunctiva)"]),
 ("Why does gonorrhoea not cause vaginitis in adult women?", ["Adult vagina has stratified squamous epithelium (oestrogen) resistant to gonococci; prepubertal girls (thin columnar-like epithelium) get vulvovaginitis"]),
 ("Clinical features in men?", ["Incubation 2–5 days; profuse purulent urethral discharge, dysuria, meatal oedema; complications: epididymitis, prostatitis, periurethral abscess, Tysonian/Littre gland abscess, urethral stricture"]),
 ("Gonococcal vs non-gonococcal urethritis?", ["Gonococcal: short incubation, profuse purulent discharge, Gram-negative intracellular diplococci", "NGU: longer incubation (1–3 weeks), scanty mucoid discharge, pus cells ≥2/oil immersion field without diplococci — Chlamydia trachomatis (D–K), Mycoplasma genitalium, Ureaplasma, Trichomonas"]),
 ("What is disseminated gonococcal infection?", ["Arthritis–dermatitis syndrome: fever, migratory polyarthralgia, tenosynovitis and few acral haemorrhagic pustules on erythematous base; or purulent monoarthritis; risk with menstruation, pregnancy, late complement (C5–C9) deficiency, SLE"]),
 ("Investigations?", ["Gram stain of urethral smear (sensitivity >95% in symptomatic men; poor in women), culture on Thayer–Martin/modified New York City medium (antibiotic sensitivity), NAAT/PCR (most sensitive, multiple sites incl. pharynx and rectum)", "Screen for chlamydia, syphilis, HIV, hepatitis B/C"]),
 ("Treatment?", ["CDC 2020/2021: ceftriaxone 500 mg IM single dose (1 g if ≥150 kg); add doxycycline 100 mg twice daily × 7 days if chlamydia not excluded", "NACO syndromic: grey kit (kit 1) — cefixime 400 mg + azithromycin 1 g single dose for urethral discharge/cervicitis", "Treat partners; abstain for 7 days; test of cure for pharyngeal infection"]),
 ("Why high-dose ceftriaxone?", ["Rising MICs and ceftriaxone-resistant strains; pharyngeal infection needs higher levels; azithromycin resistance makes dual therapy less reliable"]),
 ("Ophthalmia neonatorum — prevention and treatment?", ["Prophylaxis at birth: 0.5% erythromycin or 1% tetracycline eye ointment (silver nitrate 1% — Credé method, historical)", "Treatment: ceftriaxone 25–50 mg/kg IM single dose (max 125 mg) and saline irrigation"]),
 ],
 spot=["Profuse purulent urethral discharge with Gram-negative intracellular diplococci — gonococcal urethritis"]),

dict(case="Lymphogranuloma venereum", src=f"{DYP} (Long case — Lymphogranuloma venereum); {IA} ch.130",
 qa=[
 ("What is LGV?", ["Systemic STI of lymphatic tissue caused by invasive Chlamydia trachomatis serovars L1, L2 (L2b — proctitis outbreaks in MSM), L3"]),
 ("Stages of LGV?", ["Primary (3–30 days): transient painless papule/ulcer/herpetiform lesion, often unnoticed; urethritis/cervicitis", "Secondary (inguinal syndrome, 2–6 weeks): painful unilateral inguinal lymphadenitis (bubo) with periadenitis, multiple sinuses ('watering-can'); groove sign; constitutional symptoms; or anorectal syndrome (proctocolitis)", "Tertiary: chronic lymphoedema (esthiomene of vulva, saxophone penis), rectal strictures, fistulae, lymphorrhoids, perianal condylomas"]),
 ("What is the groove sign?", ["Enlarged inguinal and femoral nodes separated by the inguinal (Poupart's) ligament — seen in ~10–20%; highly suggestive of LGV"]),
 ("What is esthiomene?", ["Chronic elephantiasis with ulceration of the vulva (and perineum) in late LGV in women (from Greek 'eating away')"]),
 ("Bubo of LGV vs chancroid?", ["LGV: initially painful matted nodes, periadenitis, multiple sinuses, groove sign, primary lesion healed", "Chancroid: unilocular suppurative bubo with single opening, painful ulcers still present"]),
 ("What is bubonulus?", ["Painful nodule/abscess along the dorsal lymphatic of the penis (lymphangitis) that may rupture"]),
 ("Investigations?", ["NAAT/PCR for C. trachomatis with LGV-specific genotyping (most sensitive) from ulcer, rectal swab or bubo aspirate", "Serology (complement fixation ≥1:64, micro-IF), culture (McCoy cells — difficult); Frei test historical", "Screen for HIV, syphilis, hepatitis"]),
 ("Differential diagnosis?", ["Chancroid, syphilis, herpes, donovanosis (pseudobubo — subcutaneous granulomas, not true nodes), tuberculous/pyogenic lymphadenitis, lymphoma, cat-scratch disease, filariasis, Crohn disease (anorectal)"]),
 ("Treatment?", ["Doxycycline 100 mg twice daily × 21 days (drug of choice); erythromycin 500 mg four times daily × 21 days in pregnancy; azithromycin 1 g weekly × 3 weeks", "NACO black kit (kit 7) for inguinal bubo — doxycycline × 21 days + azithromycin 1 g", "Aspirate fluctuant nodes through healthy skin; surgery for strictures/elephantiasis; treat partners (contacts within 60 days)"]),
 ],
 spot=["Unilateral matted inguinal nodes with groove sign — LGV"]),

dict(case="Asteatotic eczema", src=f"{DYP} (Asteatotic eczema); {IA} ch.24",
 qa=[
 ("Synonyms and definition?", ["Eczema craquelé, xerotic eczema, winter itch — eczema arising on very dry skin from loss of stratum corneum lipids and water"]),
 ("Clinical features?", ["Dry, scaly skin with fine fissures in a 'crazy paving' / dried river-bed pattern with erythema, mainly shins of elderly, worse in winter; itchy"]),
 ("Predisposing factors?", ["Old age (reduced sebum and natural moisturising factor), low humidity/winter, frequent hot baths and soaps, diuretics, statins, retinoids, hypothyroidism, malnutrition/zinc deficiency, renal failure, malignancy (widespread sudden onset — lymphoma)"]),
 ("Differential diagnosis?", ["Stasis dermatitis, nummular eczema, ichthyosis vulgaris/acquired ichthyosis, contact dermatitis, scabies (elderly), cutaneous T-cell lymphoma"]),
 ("Treatment?", ["Short lukewarm baths, soap substitutes, liberal emollients immediately after bathing (petrolatum, urea, lactic acid), humidify room", "Mild–moderate topical steroid ointment for inflamed areas for 1–2 weeks; treat itch; stop offending drugs"]),
 ("When should you suspect an internal cause?", ["Sudden generalised asteatotic eczema in an adult — screen for lymphoma, malignancy, hypothyroidism, nutritional deficiency"]),
 ],
 spot=["Crazy-paving dry fissured shins of an elderly person in winter — asteatotic eczema"]),
]
